Fix guess  IP from Agent
glpi-project/glpi pull request #10115
Opened 2021-12-14 16:04 UTC by stonebuzz

Actually, GLPI try to get all addresses from computer to request a remote inventory / status

from a standard inventory GLPI return three addresses (or more depending of inventory) (```NetworkPortLocal``` are excluded)
```https://192.168.1.24:62354/status``` (by ipv4)
```https://2a01:e0a:87c:4ea0:f178:597:e709:8aea:62354/status``` (by ipv6)
```https://Desktop:62354/status``` (by name)

Only IPV4 work

This PR Restrict addresses to get only IPV4 compliant

Perhaps we could save the IP used by the agent during the ```PROLOG``` (into ```Agent``` object)

As discuss with @g-bougard 

When agent contact GLPI save into ```glpi_agents``` table two new informations

- IP ```$_SERVER['REMOTE_ADDR']``` use by agent to contact GLPI (store as binary with ```inet_pton```)
- Protocol : ```http``` by default , ```https``` if plugin ```ssl``` is active agent side 

When user request ```/status```, ```/now``` (or other from plugins)
GLPI use this IP and make only one call.

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

2021-12-15 05:47 UTC, trasher approved these changes

2021-12-15 05:48 UTC, trasher commented
please run `vendor/bin/phpcbf install/migrations/update_9.5.x_to_10.0.0/native_inventory.php src/Agent.php`

2021-12-15 07:41 UTC, trasher requested changes

2021-12-15 07:41 UTC, trasher commented on src/Agent.php
> +            if ($ip_binary = inet_pton($_SERVER['REMOTE_ADDR'])) {
As discussed, we cannot rely on that; it will be wrong in czse of uploading an XML file, or if there are proxies between agent and glpi.

2021-12-15 10:37 UTC, closed without merging

2022-01-28 08:54 UTC, g-bougard commented
Would it be possible to resurrect this PR but updating guessAddress adding the know agent ip and not changing requestAgent ?