Disable header detection
glpi-project/glpi pull request #10207
Opened 2021-12-23 07:57 UTC by trasher

- Disable agent detection
- make path replacements unconditional,
-  fix variable name

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

2021-12-23 07:57 UTC, trasher commented
Following https://github.com/glpi-project/glpi/pull/10080

2021-12-23 12:03 UTC, g-bougard requested changes
Error handling and related tests still must be updated.

2021-12-24 16:39 UTC, g-bougard commented
Please, can you first wait ##10225 to be merged so you can remove the error handling support from this PR ? Indeed as my comment tells you, I think error handling update should not be included in this PR as this is not fully related to the subject and you're clearly missing some cases.

2022-01-05 10:11 UTC, cedric-anne approved these changes

2022-01-06 11:59 UTC, closed without merging