timeline_actions hook must load hooks of plugins
glpi-project/glpi pull request #10319
Opened 2022-01-13 11:16 UTC by btry

This fix ensure that hook.php from the plugin is loaded.

Fixes a feature of Formcreator.

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

2022-01-13 11:21 UTC, cconard96 approved these changes
Tested changes with Screenshot plugin. No breaks there.

2022-01-13 11:23 UTC, cedric-anne approved these changes

2022-01-13 11:25 UTC, cedric-anne requested changes
IMHO, `Plugin::doHook(Hooks::TIMELINE_ACTIONS, [... ]);` should be called once, not for each plugin that register the hook. Inddeed, the `doHook` method itself will loop on each plugin.

2022-01-13 12:44 UTC, orthagh approved these changes

2022-01-13 12:46 UTC, btry commented on src/CommonITILObject.php
> -        if (isset($PLUGIN_HOOKS[Hooks::TIMELINE_ACTIONS])) {
if and foreach are already in the doHook method.

2022-01-13 13:34 UTC, cconard96 approved these changes

2022-01-17 06:50 UTC, trasher approved these changes

2022-01-17 10:39 UTC, merged