Fix entity switcher when using a non-recursive profile
glpi-project/glpi pull request #10418
Opened 2022-01-23 17:05 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #10043 

Entity switcher was showing child entities even when using a profile assigned non-recursively because no checks for `is_recursive` were done.

2022-01-24 07:57 UTC, orthagh approved these changes

2022-01-24 12:31 UTC, trasher approved these changes

2022-01-24 12:43 UTC, cedric-anne approved these changes

2022-01-24 12:44 UTC, cedric-anne requested changes
See comment in #10043. Maybe cache key must be adapted.

2022-01-25 12:55 UTC, trasher commented
Cache issue is not related to the initial problem this PR tries to address, am I wrong?

2022-01-28 00:48 UTC, cconard96 commented
> Cache issue is not related to the initial problem this PR tries to address, am I wrong?

I don't understand what the issue with the cache would be and I cannot seem to find any further issues on my end.

2022-01-28 07:25 UTC, cedric-anne approved these changes

2022-01-28 07:25 UTC, merged