Improve SNMP credentials form
glpi-project/glpi pull request #10420
Opened 2022-01-23 19:59 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #10150

- Show only relevant fields based on the selected SNMP version.
- Added required marker to snmpversion field (Checked server-side. Client-side validates OK for empty choice; not a big deal).
- Added check that the username field is set if using v3.
- Added ability to specify additional attributes on form fields. Used in this PR to add a data attribute to each field to specify which SNMP version they are used for.
- Removed redundant card headers for SNMP versions.

2022-01-24 14:08 UTC, g-bougard requested changes
There's a little issue.

2022-01-24 14:10 UTC, cconard96 commented on src/SNMPCredential.php
> +    }
Fixed. Surprised my IDE didn't complain.

2022-01-24 14:11 UTC, g-bougard approved these changes

2022-01-24 14:20 UTC, orthagh approved these changes

2022-01-25 07:47 UTC, cedric-anne approved these changes

2022-01-25 07:47 UTC, merged