Fix TicketValidation
glpi-project/glpi pull request #10587
Opened 2022-02-09 08:18 UTC by tsmr

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #none 

![image](https://user-images.githubusercontent.com/13178158/153154109-4d4a4948-f94b-4a39-bfe9-4a44362ebc26.png)

2022-02-09 08:26 UTC, orthagh approved these changes

2022-02-14 08:41 UTC, cedric-anne requested changes

2022-02-14 08:41 UTC, cedric-anne commented on src/CommonITILValidation.php
> +            'display'             => false,
I guess `false` should be used instead of `$params['display']` on lines 1426 and 1435.

2022-02-14 08:41 UTC, cedric-anne commented on templates/components/itilobject/fields/global_validation.html.twig
> +            'display': true,
Output should be passed to the `fields.field` macro.
```suggestion
            'display': false,
```

2022-02-15 13:01 UTC, cedric-anne approved these changes

2022-02-21 07:46 UTC, trasher approved these changes

2022-02-21 11:29 UTC, orthagh approved these changes

2022-02-21 11:46 UTC, merged