Check required libsodium constant as version check
glpi-project/glpi pull request #10750
Opened 2022-02-22 13:05 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Added new requirements check for existence of the "SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES" constant. The PHP extension only defines this is it exists from the libsodium package and just directly assigns its value from the one provided by the library.
The compatibility library used does define this constant using a hard-coded value but only for PHP 7.2 and lower it seems.

Also, given that PHP is compiled by default with the sodium extension, it is most likely that users will be running the extension and will be reliant on the libsodium library version.

2022-02-22 13:12 UTC, cedric-anne requested changes
Could you quickly add a unit test for this new class ? There are already some for other `Glpi\System\Requirement` classes.

2022-02-22 13:12 UTC, cedric-anne commented on src/System/RequirementsManager.php
> +        $requirements[] = new ExtensionConstant(
Should be moved before the `// Below requirements are optionals` comment (probably after the `zlib` extension check).

2022-02-23 10:28 UTC, cedric-anne approved these changes

2022-02-23 10:29 UTC, cedric-anne commented
@cconard96
Did you identify something that you would consider as a bug in the polyfill library ? In this case, maybe it should be reported there.

2022-02-23 12:54 UTC, orthagh approved these changes

2022-02-23 13:09 UTC, cconard96 commented
> @cconard96 Did you identify something that you would consider as a bug in the polyfill library ? In this case, maybe it should be reported there.

I didn't find anything that would be considered a bug on their end. They are only concerned with polyfilling the extension and not the library. If you have PHP 7.2 or higher, you should already have the extension. In this case, you are required to have the correct version of libsodium. On Linux, it should be up to the package maintainers to ensure the correct version of libsodium is listed as a dependency for "php-sodium" and/or "php".

2022-02-24 08:51 UTC, trasher approved these changes

2022-02-24 08:51 UTC, merged