Fix navigation menu z-index
glpi-project/glpi pull request #10767
Opened 2022-02-23 17:54 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #10592

Set z-index higher so that is can show over other elements when in "mobile" mode.

2022-02-23 20:03 UTC, orthagh requested changes

2022-02-23 20:03 UTC, orthagh commented on css/includes/components/_global-menu.scss
> +    z-index: 2000;
You should use bootstrap variable for z-indexes : https://getbootstrap.com/docs/5.0/layout/z-index/

Test to be sure, but i think we need fixed or sticky var

2022-02-24 07:59 UTC, orthagh approved these changes

2022-02-24 08:07 UTC, cedric-anne approved these changes

2022-02-24 08:07 UTC, merged