fix: content translation
glpi-project/glpi pull request #10843
Opened 2022-03-03 09:53 UTC by Rom1-B

The content of the followups and tasks was not translated, although a translation exists.

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !23516

_I am doing another PR for master_

2022-03-03 10:33 UTC, orthagh approved these changes

2022-03-04 09:58 UTC, cedric-anne requested changes
You should add a `DropdownTranslation::isDropdownTranslationActive()` check.

2022-03-04 10:58 UTC, trasher approved these changes

2022-03-04 12:10 UTC, cedric-anne approved these changes

2022-03-04 12:11 UTC, merged