Fix removal of saved NetworkPort input
glpi-project/glpi pull request #10857
Opened 2022-03-04 00:32 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #8980

NetworkPort's prepareInputForUpdate was calling `NetworkPort::splitInputForElements` which was removing all non-fields that didn't start with an underscore. This meant that the `update` input was being removed and later in the update method, it was failing that check which would have cleared the saved input.

This fix I propose sets the `_update` property in `CommonDBTM::update` just before `prepareInputForUpdate` is called while leaving the original `update` property. Then afterwards, the `update` property is removed. This should fix the reported issue without to much risk in causing a break in compatibility.

2022-03-04 09:20 UTC, trasher reviewed
Looks good to me. What about adding a test?

2022-03-04 09:26 UTC, cedric-anne requested changes
I do not understand why current code is done like this.

1. The whole following block should be placed before `$this->prepareInputForUpdate($this->input)`, to be consistent with the behaviour existing in `add()` method.
```php
         if (isset($this->input['update'])) {
            $this->input['_update'] = $this->input['update'];
            unset($this->input['update']);
         }
```
I would even be more relevant to have it before call to plugin hooks, but it would introduce a BC break (I found only one impacted plugin [ see `plugin_projectbridge_pre_contract_update` ], but I do not have all existing plugins on my machine would).
Note: It would require to update `CommonITILTask::prepareInputForUpdate()`, `Config::prepareInputForUpdate()` and `CommonITILSolution::prepareInputForUpdate()`.

2. I do not get why a local variable is not used here (i.e. defining `$save_input = isset($this->input['update']);` and reuse it to determine wether input have to be saved/cleared).

I guess we should use solution 2 for now, and maybe solution 1 on the long term.

Also, I am not in favor to do it on 9.5 branch, as bug is far from being really critical. If you want to fix 9.5, just add the `update` case in `NetwrkPort::splitInputForElements()`.

2022-03-04 10:06 UTC, cconard96 commented
It was only done like this to prevent BC like the one you found. I can re-do it for GLPI 10 instead and just move the block entirely before the plugin hook call.

2022-03-04 10:09 UTC, cedric-anne commented
> I do not understand why current code is done like this.

I was talking about the existing code, not yours.

2022-03-04 10:15 UTC, cedric-anne commented
> I can re-do it for GLPI 10 instead and just move the block entirely before the plugin hook call.

1. On 9.5 branch, you can just add the `update` case in `NetworkPort::splitInputForElements()`.

2. On master branch, I guess you can apply the solution 1, as `plugin_projectbridge_pre_contract_update` function is anyway broken on every language except in French.

2022-03-04 10:56 UTC, cconard96 commented
Not security related, so I just changed the base to `master` branch.

2022-03-07 11:00 UTC, cedric-anne approved these changes

2022-03-07 11:40 UTC, orthagh approved these changes

2022-03-07 13:13 UTC, trasher approved these changes

2022-03-07 13:13 UTC, merged