Fix actors added by rule on Ticket update
glpi-project/glpi pull request #10852
Opened 2022-03-03 14:08 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #10564

2022-03-04 09:21 UTC, trasher commented
I guess this would need a test

2022-03-04 09:41 UTC, cedric-anne reviewed
It seems related to #10739.

2022-03-14 08:19 UTC, cedric-anne requested changes
Unless I am wrong, it will not handle groups and suppliers.

2022-03-24 07:59 UTC, cedric-anne approved these changes

2022-03-24 07:59 UTC, cedric-anne commented on src/CommonITILObject.php
> +                    $first_item = reset($this->input[$input_field_name]);
Could you please add a comment in code to explain what are expected formats ? I had to read twice to be able to understand.

2022-03-24 07:59 UTC, cedric-anne commented on src/CommonITILObject.php
> +                        $input_ids = isset($this->input[$input_field_name]) ? array_values($this->input[$input_field_name]) : [];
`isset` check is done on line 8150.
```suggestion
                        $input_ids = array_values($this->input[$input_field_name]);
```

2022-03-24 07:59 UTC, cedric-anne commented on src/CommonITILObject.php
> +                if (isset($this->input[$input_field_name]) && count($this->input[$input_field_name])) {
```suggestion
                if (isset($this->input[$input_field_name]) && is_array($this->input[$input_field_name]) && count($this->input[$input_field_name])) {
```

2022-03-24 07:59 UTC, cedric-anne commented on src/CommonITILObject.php
> +                        $input_ids = isset($this->input[$input_field_name]) ? array_column($this->input[$input_field_name], $existing['itemtype']::getForeignKeyField()) : [];
```suggestion
                        $input_ids = array_column($this->input[$input_field_name], $existing['itemtype']::getForeignKeyField());
```

2022-03-24 09:54 UTC, trasher approved these changes

2022-03-24 11:25 UTC, cedric-anne approved these changes

2022-03-24 11:26 UTC, merged