feat(cable): add template managment
glpi-project/glpi pull request #11059
Opened 2022-03-21 10:57 UTC by stonebuzz

Add ```template``` to ```Cables```

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

2022-05-02 07:16 UTC, cedric-anne requested changes
To be able to use templates, in GLPI 10.0, `Clonable` trait must be added to `Cable` class, and clore relations must be defined.
```Uncaught Exception Error: Call to undefined method Cable::clone() in /var/www/glpi/src/CommonDBTM.php at line 1221```

2022-05-03 11:10 UTC, cedric-anne approved these changes

2022-05-03 11:41 UTC, trasher approved these changes

2022-05-03 11:58 UTC, orthagh approved these changes

2022-05-03 11:58 UTC, merged