Fix FA6 compatibility
glpi-project/glpi pull request #11125
Opened 2022-03-28 14:09 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #11123

Readdressing what I started in #11098 since the issue wasn't fully fixed.
This PR fixes all character codes changed between Font Awesome 5 and 6. It also removes the use of `font-family` and `font-weight` and replaces them with the new `font: var(--fa-font-solid);` syntax.
Finally, this PR fixes a small alignment issue with the icons in the timeline statistics view where the icon was not centered in the circle.

2022-03-28 14:10 UTC, cedric-anne approved these changes

2022-03-28 14:49 UTC, orthagh approved these changes

2022-03-29 06:52 UTC, trasher requested changes
Please fix cs

2022-03-30 07:19 UTC, trasher approved these changes

2022-03-30 07:19 UTC, merged