Cable management improvements
glpi-project/glpi pull request #11186
Opened 2022-04-05 10:40 UTC by cedric-anne

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #10720

2022-04-05 12:49 UTC, stonebuzz commented
1. Make it possible to add multiple sockets for an asset
Ok for this improvment.

IMHO :
you have to hide the "connected to" part which is useless for bulk creation
 
![image](https://user-images.githubusercontent.com/7335054/161754250-07c14b07-922b-4a50-a13a-33f647e3ebf7.png)

```From```, ```To```, ```Prefix``` and ```Suffix``` are fine.

But ```Position``` must be incremented

![image](https://user-images.githubusercontent.com/7335054/161754476-9e0ec098-1f90-4d8f-a082-51221d089b67.png)


2. Split up the network port form, because it is confusing when using passive devices

Agree with that (This indicates that the link is made to the asset and possibly to the network port (if available))
but be careful :

when ```itemtype``` /  ```items_id``` is changed the 'Network Port' label disappears

![image](https://user-images.githubusercontent.com/7335054/161754996-2ae1faea-54f4-4680-8139-92bfabd0a642.png)

3. Make it easier to add/edit connected cables to a socket 

After adding a socket to a cable, i have an error from socket form (previously linked)

![image](https://user-images.githubusercontent.com/7335054/161755903-c1e2890c-5612-4082-8136-858cdeeb4c11.png)

4. Remove "wiring_side" from Socket and put it to Cable

Some customers want to finely manage sockets (rear and front)

That's why we want to keep the information of the wiring side in the socket (it is placed in front or rear)

![image](https://user-images.githubusercontent.com/7335054/161756669-7362b370-7dc3-4f23-8d01-8164db6c450e.png)

 Perhaps we can also have this information in the ```Cable``` in addition to the ```Socket``` 

Such as the ```position``` of the ```NetworkPort``` and the associated ```Socket``` (when a ```Socket``` is created, if a ```NetworkPort``` is defined , ```Socket``` take the same ```position```  )

2022-04-21 08:27 UTC, cedric-anne commented
ping @rbrannath

2022-04-25 16:31 UTC, rbrannath commented
Done some work:

- position is increment in bulk mode (add several sockets)
- position is hidden in bulk mode
- network port is hidden in bulk mode
- restored wiring_side in sockets
- fixed disappearing network port label

2022-05-02 07:23 UTC, rbrannath commented
> ping @rbrannath

@cedric-anne, can you help me with the failed checks? I am unaware of the concept of changing database tables between versions.

2022-05-02 07:53 UTC, cedric-anne commented
> > ping @rbrannath
> 
> @cedric-anne, can you help me with the failed checks? I am unaware of the concept of changing database tables between versions.

Hi,

First, could you use the rebase feature of Git to have a clean pull request (i.e. only containing your commits/changes) ? You can do it using `git pull --rebase git@github.com:glpi-project/glpi.git main` command.

2022-05-03 04:53 UTC, rbrannath commented
@cedric-anne this should be fine now

2022-05-12 09:33 UTC, stonebuzz commented
@rbrannath have you see my changes requests ?

Best regards

2022-05-16 01:58 UTC, KongNan commented
The pr is still in draft status though  :(   Sorry to comment here, but of all the pr's in 10.1, this is the one I'm most concerned about, and I've even thought about skipping the 10.0 stable release and updating to it directly...  Hope it's still progressing 👍

2022-05-16 06:51 UTC, rbrannath commented
> @rbrannath have you see my changes requests ?
> 
> Best regards

Hi @stonebuzz,

no, I haven't seen it. Where do I have to look?

2022-05-17 06:41 UTC, stonebuzz commented
> > @rbrannath have you see my changes requests ?
> > Best regards
> 
> Hi @stonebuzz,
> 
> no, I haven't seen it. Where do I have to look?

here, in the discussion thread, you will find the requests for changes

![image](https://user-images.githubusercontent.com/7335054/168745686-2c642ffb-5719-494b-8e12-00e947e653c8.png)

2022-05-17 06:50 UTC, stonebuzz requested changes

2022-05-17 06:51 UTC, stonebuzz commented
> > > @rbrannath have you see my changes requests ?
> > > Best regards
> > 
> > 
> > Hi @stonebuzz,
> > no, I haven't seen it. Where do I have to look?
> 
> here, in the discussion thread, you will find the requests for changes
> 
> ![image](https://user-images.githubusercontent.com/7335054/168745686-2c642ffb-5719-494b-8e12-00e947e653c8.png)

Sorry my review was in pending state

2022-05-22 10:55 UTC, KongNan commented
all check passed! congratulations and thanks to rbrannath ✿✪❉✼♡

2022-05-27 12:03 UTC, KongNan commented
It looks like it is now time for 10.0.1 . But after rbrannath's excellent efforts, this pr is still in draft status, which worries me. Even though we may have to wait for 10.1.0 to officially have this feature, I wonder if this pr will be approved/merged as soon as possible, just like the [other pr's in 10.1.0](https://github.com/glpi-project/glpi/milestone/49?closed=1)?

(Sorry for my bad English, and I'm not sure if my statement is appropriate, so please let me know if I'm doing it wrong)

2022-06-07 11:18 UTC, KongNan commented
10.0.1 has already released.  now please consider pay attention to this great feature, so everyone will get benefit ~  @stonebuzz 
(sorry for my English)

2022-06-14 07:56 UTC, stonebuzz requested changes

2022-06-14 07:56 UTC, stonebuzz commented on src/Socket.php
> +            $frontCable = $DB->request(array_merge($criteria, $where(2, $ID)))->current();
```$rearCable``` and ```$frontCable``` are never used
```global $DB;``` are never called

2022-06-14 07:56 UTC, stonebuzz commented on templates/pages/assets/socket.html.twig
> +      ) }}
```Position``` and ```NetworkPort``` field are duplicated from creater form

![image](https://user-images.githubusercontent.com/7335054/173523751-bcd8029f-9907-4862-a9ef-5e09c5510071.png)

After creation we have a blank page


```shell
[2022-06-14 09:28:49] glpiphplog.WARNING: Test logger  
[2022-06-14 09:28:49] glpiphplog.WARNING: Test logger  
[2022-06-14 09:49:51] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to a member function request() on null in /home/stanislas/Teclib/dev/GLPI/cable_management/src/Socket.php at line 301
  Backtrace :
  src/CommonGLPI.php:655                             Glpi\Socket->showForm()
  ajax/common.tabs.php:107                           CommonGLPI::displayStandardTab()
```
![image](https://user-images.githubusercontent.com/7335054/173523941-85af54c5-ee01-490a-9df4-5ceda773181b.png)

2022-06-14 07:56 UTC, stonebuzz commented on templates/pages/assets/socket.html.twig
> +	{% if params["several"] is defined %}
```several``` form does not seem to work

![image](https://user-images.githubusercontent.com/7335054/173524281-a1d8dc02-0204-4386-8c84-63b6faa108e4.png)

![image](https://user-images.githubusercontent.com/7335054/173524324-d1584733-2bca-4d9e-8526-d79e15bf44ee.png)

2022-06-14 09:00 UTC, stonebuzz commented
@rbrannath can you try this PR -> https://github.com/glpi-project/glpi/pull/11893

This PR allows you to add multiple sockets from one item

2022-07-02 13:03 UTC, KongNan commented
dear @rbrannath <https://github.com/rbrannath> , could you please have a
look at stonebuzz's message? He/she replied your 11186, and make another
two #11893 <https://github.com/glpi-project/glpi/pull/11893> and #11895
<https://github.com/glpi-project/glpi/pull/11895>. Hope I can have a
PatchPanel with all of them in the coming 10.1.0 :D


Stanislas ***@***.***> 于2022年6月14日周二 17:42写道：

> @rbrannath <https://github.com/rbrannath> can you try this PR -> #11895
> <https://github.com/glpi-project/glpi/pull/11895>
>
> This PR allows you to link Socket to Location (to represent socket
> outlets)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/glpi-project/glpi/pull/11186#issuecomment-1154957107>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABGRJR6B6I6ZZNZDA25XER3VPBHXJANCNFSM5SSKAHNA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-08-02 17:56 UTC, rbrannath commented
> @rbrannath can you try this PR -> #11893
> 
> This PR allows you to add multiple sockets from one item

@stonebuzz, sorry for the late reply, I was busy at work and then on vacation.
I tested it and I will write my results and thoughts inside that PR

2022-09-13 10:33 UTC, cedric-anne commented
I close this PR as it seems stale and replaced by #11893  and #11895. Feel free to reopen your own PR.

2022-09-13 10:33 UTC, closed without merging