Fix approval request handling in Change creation form
glpi-project/glpi pull request #11276
Opened 2022-04-13 07:54 UTC by cedric-anne

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

1. Approval request field was displayed even when user has no right to create an approval request.
2. User dropdown was not correctly filtered on `Change` form.
3. Approval requests were not created on `Change` creation.

Unless for point 1, bugs were already present in GLPI 9.5.

2022-04-13 09:20 UTC, cconard96 requested changes

2022-04-13 09:20 UTC, cconard96 commented on templates/components/itilobject/fields/global_validation.html.twig
> +            call('TicketValidation::dropdownValidator', [{
```suggestion
            call('CommonITILValidation::dropdownValidator', [{
```

2022-04-13 11:24 UTC, cedric-anne commented on templates/components/itilobject/fields/global_validation.html.twig
> +            }|merge(required)]),
```suggestion
            validation.dropdownValidator({
               'name': 'users_id_validate',
               'entity': item.fields['entities_id'],
               'right': validation_right,
               'users_id_validate': params['users_id_validate'],
               'display': false,
               'disabled': (not canupdate),
            }|merge(required)),
```

2022-04-13 11:24 UTC, cedric-anne commented on templates/components/itilobject/fields/global_validation.html.twig
> +            }|merge(required)]),
```suggestion
            validation.dropdownValidator({
               'name': 'users_id_validate',
               'entity': item.fields['entities_id'],
               'right': validation_right,
               'users_id_validate': params['users_id_validate'],
               'display': false,
               'disabled': (not canupdate),
            }|merge(required)),
```

2022-04-19 07:56 UTC, orthagh approved these changes

2022-04-19 07:59 UTC, trasher approved these changes

2022-04-19 08:58 UTC, cconard96 approved these changes

2022-04-19 09:03 UTC, merged