feat(knowbase): standard search
glpi-project/glpi pull request #11323
Opened 2022-04-20 13:53 UTC by Rom1-B

Modification of the 2ᵉ tab (Browse) to standardize :
- search by criteria
- switch between tree view (default) and classic view

The 1st tab is not modified
The 3ᵉ tab (Manage) is removed to be replaced by a toogle to display unpublished articles.

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !23445

2022-05-10 14:11 UTC, cedric-anne requested changes
As browsing now uses the `Search` class, it could be useful to populate some default display preferences.

2022-05-11 13:42 UTC, cedric-anne commented on src/KnowbaseItem.php
> +                'value'         => null,
These `null` values are not working. Indeed, if I create a KB entry that has a profile as a target, I will not see it into "Published" results.

2022-05-12 11:29 UTC, cedric-anne approved these changes

2022-05-17 13:01 UTC, orthagh commented
As seen together, the toggle for showing not published article should be on by default.
I missed it completly

2022-05-25 12:23 UTC, cedric-anne approved these changes

2022-05-25 12:28 UTC, trasher approved these changes

2022-05-25 12:28 UTC, merged