feat(DCbreadcrumb): add capability to display location (and use it om Cable)
glpi-project/glpi pull request #11480
Opened 2022-05-04 09:07 UTC by stonebuzz

Add capability to display location from ```DCBreadcrumb```

(and use it from ```Cable``` object)

Before : 
![image](https://user-images.githubusercontent.com/7335054/166652445-3170e091-a5c7-478c-993b-1180f6631c9e.png)

After : 
![image](https://user-images.githubusercontent.com/7335054/166652433-ca58cdba-80b3-4bc0-a8ed-e40e081314f7.png)

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

2022-05-04 09:09 UTC, orthagh commented
Did you test with very long location name ?
if not, maybe some text-overflow classes should be added

2022-05-04 09:21 UTC, stonebuzz commented
> text-overflow

(without change for the moment)

![image](https://user-images.githubusercontent.com/7335054/166654667-59c2e676-1ca3-4871-94d9-80a49a9351c3.png)

2022-05-04 09:35 UTC, stonebuzz commented
> Did you test with very long location name ? if not, maybe some text-overflow classes should be added

Maybe better with ```text-truncate```

![image](https://user-images.githubusercontent.com/7335054/166656625-ab791169-d5f5-4aae-97ca-a12c13a41113.png)

2022-05-04 09:48 UTC, btry commented
Hi

Interesting feature. After viewing the rendering, I got an idea. The breadcrumb consumes 2 lines very fast, without the need of long strings. Then why not show the locations in the 2nd line directly, horizontally aligned with the matching breadcrumb item ?

Something like that : 
```preformatted 
General > Datacenter > Server room > Rack
          Marseille >  Marseille >   Marseille

```

2022-05-04 11:43 UTC, cconard96 commented
Realistically, how often is a rack going to have a different location than its server room or a server room with a different location than its datacenter?

I think some optimization can be done with that. If a breadcrumb item has the same location as the one before it, there shouldn't be a need to display the location again. If a breadcrumb item in in a child location of the item before it, only the difference in the complete name needs shown. If a breadcrumb item has no location, the badge can be hidden too so it appears that the location is inherited.
If there is some weird case where the location of two breadcrumb items are not in the same hierarchy, then the full location can be shown I guess.

I'm not sure how complicated that would be to implement though.

2022-05-04 11:51 UTC, stonebuzz commented
> Hi
> 
> Interesting feature. After viewing the rendering, I got an idea. The breadcrumb consumes 2 lines very fast, without the need of long strings. Then why not show the locations in the 2nd line directly, horizontally aligned with the matching breadcrumb item ?
> 
> Something like that :
> 
> ```
> General > Datacenter > Server room > Rack
>           Marseille >  Marseille >   Marseille
> ```
> 
> or
> 
> ```
> General > Datacenter > Server room > Rack
>           Marseille  > Marseille   > Marseille
> ```

new version 

![image](https://user-images.githubusercontent.com/7335054/166675762-73232c50-a7a5-4316-9a1d-fdc8ff142cbe.png)

2022-05-04 12:53 UTC, orthagh commented
How the breadcrumb behaves when there is no location for an item ?

2022-05-04 13:51 UTC, stonebuzz commented
> Realistically, how often is a rack going to have a different location than its server room or a server room with a different location than its datacenter?
> 
> I think some optimization can be done with that. If a breadcrumb item has the same location as the one before it, there shouldn't be a need to display the location again. If a breadcrumb item in in a child location of the item before it, only the difference in the complete name needs shown. If a breadcrumb item has no location, the badge can be hidden too so it appears that the location is inherited. If there is some weird case where the location of two breadcrumb items are not in the same hierarchy, then the full location can be shown I guess.
> 
> I'm not sure how complicated that would be to implement though.

@cconard96 

Some examples:

GLPI location tree

![image](https://user-images.githubusercontent.com/7335054/166693950-10aab559-028f-4dbe-b05e-a1fd9d509f28.png)

Datacenter -> ```A```
DCRoom -> ```A > A1```
Rack -> ```B > B1```

Breadcrumb

![image](https://user-images.githubusercontent.com/7335054/166693862-516d971f-a0c2-4ea6-999d-82bf9e698b3b.png)



Datacenter -> ```A```
DCRoom -> ```A```
Rack -> ```A1```

Breadcrumb 

![image](https://user-images.githubusercontent.com/7335054/166694400-a8b49c8d-56a6-4d81-aca5-ca61b977c898.png)

2022-05-04 13:52 UTC, stonebuzz commented
> How the breadcrumb behaves when there is no location for an item ?

![image](https://user-images.githubusercontent.com/7335054/166695732-f0c81994-68e3-4f34-9c02-06e3dffb52c2.png)

2022-05-04 14:11 UTC, stonebuzz commented
> It may be good to prepend child locations with "> " to differentiate them from completely separate locations.

Like this

![image](https://user-images.githubusercontent.com/7335054/166699570-7ea4d26b-9c4f-4056-bf51-6b083f9f2cd2.png)

2022-05-10 12:47 UTC, orthagh commented on src/Features/DCBreadcrumb.php
> +    private function getItemLocation($itemtype, $items_id)
a suggestion here, this method seems not related to DCBreadcrumb class and doesn't require any `$this`.
I suggest to move it to Location class as private method.
Like `Location::getForItem(CommonDBTM $item)`  (avoid itemtype, items_id parameter when you the item initialy)

2022-05-10 12:51 UTC, orthagh commented on templates/layout/parts/dcbreadcrumbs.html.twig
> +</div>
```suggestion
</div>

```

2022-05-10 12:52 UTC, orthagh commented on src/Features/DCBreadcrumb.php
> +    public function cleanLocationInforamtions(&$breadcrumb)
a dockblock could help

2022-05-10 15:06 UTC, stonebuzz commented on src/Location.php
> +    public static function getItemLocation(CommonDBTM $item)
done

2022-05-11 06:24 UTC, orthagh commented on src/Location.php
> +     * @return Location if succeed else false
```suggestion
     * @return Location|false
```

2022-05-11 06:24 UTC, orthagh approved these changes

2022-05-11 08:34 UTC, trasher commented
Please fix tests ;)

2022-05-12 07:02 UTC, stonebuzz commented
Ex (from Computer side ) with small location name

![image](https://user-images.githubusercontent.com/7335054/168010650-e4ea1a65-0725-41f3-8555-c03683002389.png)

With long location name

![image](https://user-images.githubusercontent.com/7335054/168010954-e9ffa78b-7832-4a75-85ff-9caab82dc214.png)

2022-05-12 08:10 UTC, orthagh commented on templates/layout/parts/dcbreadcrumbs.html.twig
> +            <span class='p-0 float-left badge bg-blue-lt d-inline-block text-truncate' data-toggle='tooltip' title='{{ breadcrumb_item['location']['name'] }}' style='max-width: 100px;'>
```suggestion
            <span class='p-0 float-left badge bg-blue-lt d-inline-block text-truncate' data-bs-toggle='tooltip' title='{{ breadcrumb_item['location']['name'] }}' style='max-width: 100px;'>
```

2022-05-12 09:11 UTC, orthagh approved these changes

2022-05-12 10:11 UTC, cedric-anne commented on src/Features/DCBreadcrumb.php
> +    public function cleanLocationInformations(&$breadcrumb)
1. Your return the updated array, so no need to use a reference.
2. Method should be private as it is used only here.
```suggestion
    private function cleanLocationInformations(array $breadcrumb)
```

2022-05-12 12:15 UTC, cedric-anne requested changes
Functionnaly, it seems OK, but technically, it is not OK for me. Indeed, you changed existing public methods signature, and, even if they does not seems to be used in plugins, it is preferable to avoid such changes.

I will adapt the code and fix tests.

2022-05-18 09:05 UTC, cedric-anne approved these changes

2022-05-18 11:48 UTC, orthagh approved these changes

2022-05-18 12:33 UTC, merged