feat(ui): add new shortcut to show entity list
glpi-project/glpi pull request #11487
Opened 2022-05-05 05:53 UTC by stonebuzz

new shortcut to open entity form

```ctrl + alt + e````

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !23907

2022-05-05 05:54 UTC, trasher approved these changes

2022-05-05 08:27 UTC, orthagh requested changes
One small note, there is some clipping when calling the shortcut
i don't know if it's possible to avoid it 

Not blocking for merge

2022-05-05 08:27 UTC, orthagh commented on templates/layout/parts/profile_selector.html.twig
> +         <div class="mb-3">
```suggestion
         <div class="alert alert-info" role="alert">
```

2022-05-06 06:08 UTC, stonebuzz commented
> One small note, there is some clipping when calling the shortcut i don't know if it's possible to avoid it
> 
> Not blocking for merge

Let me check

2022-05-06 06:15 UTC, orthagh approved these changes

2022-05-06 09:59 UTC, stonebuzz commented
I tried to give focus to the input but without success.

Boostrap implements its own listener t to know when the dropdown is displayed but does not seem to work

```javascript
    $(".dropdown-list-entity").on('shown.bs.dropdown', function(){
        setTimeout(function(){
            $(this).parent().find("input").trigger("focus");
        }, 0);

    });
````

A simple call like this does not seem to work either
```javascript
   $('input[name=entsearchtext]').trigger("focus");
````

If anyone has an idea I'm interested

2022-05-06 12:19 UTC, trasher approved these changes

2022-05-06 12:20 UTC, trasher commented
@stonebuzz you have lint issue ;)

2022-05-09 12:37 UTC, cedric-anne commented on js/fuzzysearch.js
> +
This code should not be here, as it is not related to fuzzy search. Maybe it should be moved into `templates/layout/parts/profile_selector.html.twig`, to be placed at the same place as the HTML code it controls..

2022-05-09 12:38 UTC, cedric-anne commented
I pushed 2 commits:
1. I moved translation logic into view.
2. I added a stylesheet rule to prevent wrapping of `<kbd>` shortcuts.

But I was not able to use the feature on Chrome:
![image](https://user-images.githubusercontent.com/33253653/167411289-3d43244f-eeff-44d4-b576-d04292b4913b.png)

2022-05-09 12:58 UTC, cedric-anne commented
> But I was not able to use the feature on Chrome: ![image](https://user-images.githubusercontent.com/33253653/167411289-3d43244f-eeff-44d4-b576-d04292b4913b.png)

Fixed.

2022-05-09 13:11 UTC, AdrienClairembault commented on templates/layout/parts/profile_selector.html.twig
> +               {{ __('Click on the %s icon to load the entity and its sub-entities')|format(recursive_icon)|raw }}
It was discussed with myself and @orthagh 

The 'see' label is misleading, clicking on the icon does not show you any entities, it load them.
The actual button to see the sub entities is on the left side.

2022-05-09 13:11 UTC, AdrienClairembault commented on templates/layout/parts/profile_selector.html.twig
> +               {{ __('Click on the %s icon to load the entity and its sub-entities')|format(recursive_icon)|raw }}
![image](https://user-images.githubusercontent.com/42734840/167417138-2b9c182f-66d0-43e3-9446-bfa35eaaaad8.png)

2022-05-09 14:05 UTC, orthagh commented
for the last, probably fixed by #11521

2022-05-09 14:29 UTC, AdrienClairembault approved these changes

2022-05-10 07:08 UTC, merged