Add more control over Marketplace availability
glpi-project/glpi pull request #11650
Opened 2022-05-21 01:35 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Add new constant `GLPI_MARKETPLACE_ENABLE` to configure the availability of the Marketplace.
- 0 = Completely disabled
- 1 = CLI access only
- 2 = Web access only
- 3 = CLI and Web access allowed (Default)

As with other configuration options defined by constants, this can be overridden by package maintainers (`inc/downstream.php`) or GLPI administrators (`config/local_define.php`).
See: https://glpi-install.readthedocs.io/en/latest/install/index.html#files-and-directories-locations

2022-05-25 10:48 UTC, cedric-anne requested changes
Please add summary PHPDoc for new constants and methods.

Except this, it is OK for me.

2022-05-25 10:48 UTC, cedric-anne commented on src/Marketplace/Controller.php
> +    public static function isCLIAllowed()
```suggestion
    public static function isCLIAllowed(): bool
```

2022-05-25 10:48 UTC, cedric-anne commented on src/Marketplace/Controller.php
> +    public static function isWebAllowed()
```suggestion
    public static function isWebAllowed(): bool
```

2022-05-25 11:28 UTC, cedric-anne approved these changes

2022-06-09 07:20 UTC, cedric-anne commented on front/marketplace.download.php
> +   Html::displayRightError();
```suggestion
    Html::displayRightError();
```

2022-06-09 07:21 UTC, orthagh approved these changes

2022-06-09 07:25 UTC, trasher approved these changes

2022-06-09 07:54 UTC, merged