[GLPI 10 Bugfixes] Fix Requester Count Display
glpi-project/glpi pull request #11673
Opened 2022-05-24 08:10 UTC by tsmr

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #11672

2022-05-24 12:10 UTC, orthagh requested changes
I agree with the miss of the previous feature.
But maybe you can factorize the call of assign/requester information in a single ajax file and just change the title/parameter/etc.

Having a new file for requester doing the same for assign is little too much

2022-05-25 08:15 UTC, trasher commented on templates/components/itilobject/actors/field.html.twig
> +               var already_element = $(
Variable name is strange.
```suggestion
               var existing_element = $(
```

2022-05-25 08:15 UTC, trasher commented
And also, you have CS fails to fix. Appart of that, sounds correct to me that me.

2022-05-25 08:16 UTC, trasher requested changes
See previous comments

2022-05-25 11:59 UTC, trasher approved these changes

2022-05-25 12:01 UTC, orthagh requested changes
Last thing, rename ticketinformation.php to actorinformation.php

Functional review ok

2022-05-25 12:53 UTC, orthagh approved these changes

2022-05-31 11:50 UTC, merged