feat(inventory): get tag from related agent for NetDiscovery
glpi-project/glpi pull request #11948
Opened 2022-06-20 14:39 UTC by stonebuzz

If ```TAG``` not available  (ie netDiscovery)
Try to find related ```TAG``` Agent with ```deviceID``` 

and make it available from ```Rule``` engine

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

2022-06-20 14:51 UTC, g-bougard requested changes
Comment is breaking my head :-P
one line can be moved into `if` block.

2022-06-20 14:51 UTC, g-bougard commented on src/Inventory/Asset/MainAsset.php
> +        if (!isset($input['tag'])) {
```suggestion
        // for discovery mode, try to get TAG from agent by its deviceid
        if (!isset($input['tag'])) {
            $agent = new Agent();
```

2022-06-20 15:13 UTC, stonebuzz commented on src/Inventory/Asset/MainAsset.php
> +        //form discovery mode try to get related agent TAG by it's deviceid
Done 
(it was always at ```false``` on my side, but it's a plugin bug see ->  https://github.com/glpi-project/glpi-inventory-plugin/pull/135)

2022-06-20 15:15 UTC, stonebuzz commented on src/Inventory/Asset/MainAsset.php
> +        if (!isset($input['tag'])) {
XD, done

2022-06-20 15:31 UTC, g-bougard commented on src/Inventory/Asset/MainAsset.php
> +        //form discovery mode try to get related agent TAG by it's deviceid
I guess netinventory case could be also concerned.

2022-06-21 07:05 UTC, cedric-anne commented on src/Inventory/Asset/MainAsset.php
> +        if (!isset($input['tag']) && $this->is_discovery === true ) {
```suggestion
        if (!isset($input['tag']) && $this->is_discovery === true) {
```

2022-06-21 07:08 UTC, stonebuzz commented on src/Inventory/Asset/MainAsset.php
> +        //form discovery mode try to get related agent TAG by it's deviceid
Maybe in other PR ?

2022-06-27 06:33 UTC, trasher approved these changes

2022-06-27 13:45 UTC, closed without merging