Fix handling of pasted images and uploaded files
glpi-project/glpi pull request #12281
Opened 2022-07-22 15:23 UTC by cedric-anne

fixes #12276

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #12276

Name of field that contains uploaded files can be:
 - `filename`, if richtext editor is initialized using `enable_fileupload: true` (file uploader can be used to attach documents),
 - same as richtext editor name, if richtext editor is initialized using `enable_fileupload: false` (file uploader is hidden, and is used only when pasting images).

See https://github.com/glpi-project/glpi/blob/e91180444200389eb6612fe9834488632c9eb39d/src/Html.php#L5726-L5738

IMHO, both feature should be technically separated, as it is corresponding to 2 distinct features (pasting images in rich text VS attaching documents to an item), but it cannot be changed in a bugfix version.

So this PR fixes multiple issues.

1. Handling of pasted images in KnowbaseItem `answer` was broken. Indeed, editor is initialized using `enable_fileupload: true`, so `CommonDBTM::addFiles()` have to be call using `name=filename` (which is the default value).
2. In `CommonITILObject` and `CommonITILTask`, `CommonDBTM::addFiles()` was called twice. First time using default `name` parameter value (i.e. `content`), and then using explicitely `name=content` parameter. So it result in two identical calls, and second one can be dropped.
3. In `ITILFollowup` and `ITILSolution`, editor is initialized using `enable_fileupload: true`, so uploaded files are handled by call to `CommonDBTM::addFiles()` using default `name` parameter value. Second call using `name=content` was useless.
4. In `CommonITILObject`, the `solution` field was handled. This field is not anymore handled (i.e. it does not create an `ITILSolution`), so code i dead and can be removed.
5. In `CommonITILValidation`, as there can be 2 content fields, I updated forms to handle separately richtext and documents (using `enable_fileupload: false`). It makes the logic more robust and prevent any issue if both `comment_submission` and `comment_validation` are present in input (in a plugin request or in an API request).
6. The JS code that is used to call the uploader when an image is pasted from TinyMCE was working only due to fallback to any uploader present in form. I encountered a case where, having 2 uploaders in same form, my file was uploaded twice. I fixed logic by adding a `data-uploader-name` property that make DOM selection easier. I keep a fallback to prevent BC-break.
7. I removed the `_donotadddocs` handlming that seemed obsolete.

2022-08-02 11:56 UTC, AdrienClairembault requested changes
Pasting two images still doesn't work, the first one is remplaced by the second.
For some reasons it worked when I tested last week, not really sure why...

2022-08-02 11:59 UTC, AdrienClairembault commented
Also, it breaks images submitted in forms (formcreator)

2022-08-02 12:03 UTC, cedric-anne commented
> Pasting two images still doesn't work, the first one is replaced by the second. For some reasons it worked when I tested last week, not really sure why...

This was not known and addressed by this PR, so it should probably be fixed in another PR, as this one is already huge.

2022-08-02 12:09 UTC, cedric-anne commented
> Also, it breaks images submitted in forms (formcreator)

It probably means that formcreator is not sending images in the right input key. The right key prefix to use is `_filename` (the default one). Using this key prefix should work in any GLPI 10.0 version (i.e. with or without current fix). As there is no stable release for GLPI 10.0 yet, I guess we can consider it will not break production environments. Thus, a new version of formcreator will probably be released before GLPI 10.0.3.

2022-08-02 13:34 UTC, AdrienClairembault approved these changes

2022-08-08 14:02 UTC, trasher approved these changes

2022-08-08 14:11 UTC, merged