fix(ticket): empty service levels
glpi-project/glpi pull request #12317
Opened 2022-07-27 13:17 UTC by Rom1-B

If the template hides all the fields in "Service Levels", the area was visible in the ticket, but empty and therefore useless.

![image](https://user-images.githubusercontent.com/8530352/181256378-d046838a-e05f-43a5-96c1-1cf32d99dbbb.png)

![image](https://user-images.githubusercontent.com/8530352/181256133-2be6fe15-4020-4193-a981-cc99571f3af9.png)

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !24541

2022-07-29 10:25 UTC, cedric-anne commented on templates/components/itilobject/service_levels.html.twig
> +      /$('#service-levels-heading').closest('.accordion-item').hide();
```suggestion
      $('#service-levels-heading').closest('.accordion-item').hide();
```

2022-07-29 10:32 UTC, cedric-anne reviewed
I do not really like the idea of adding a container to DOM then hiding it with JS code, but I do not have a better solution except by changing the template structure.

2022-07-29 10:32 UTC, cedric-anne approved these changes

2022-07-29 10:58 UTC, cconard96 approved these changes

2022-08-29 14:02 UTC, orthagh requested changes
Alternative proposal:

```patch
diff --git a/templates/components/itilobject/fields_panel.html.twig b/templates/components/itilobject/fields_panel.html.twig
index 757afea78d..00f8739785 100644
--- a/templates/components/itilobject/fields_panel.html.twig
+++ b/templates/components/itilobject/fields_panel.html.twig
@@ -293,26 +293,32 @@
    {% endif %}
 
    {% if item.getType() == 'Ticket' %}
-      {% set nb_la = (item.fields['slas_id_tto'] > 0 ? 1 : 0) + (item.fields['slas_id_ttr'] > 0 ? 1 : 0) + (item.fields['olas_id_tto'] > 0 ? 1 : 0) + (item.fields['olas_id_ttr'] > 0 ? 1 : 0) %}
-      {% set servicelevels_show = headers_states['service-levels'] is defined and headers_states['service-levels'] == "true" ? true : false %}
-      <div class="accordion-item">
-         <h2 class="accordion-header" id="service-levels-heading" title="{{ _n('Service level', 'Service levels', get_plural_number()) }}" data-bs-toggle="tooltip">
-            <button class="accordion-button {{ servicelevels_show ? "" : "collapsed" }}" type="button" data-bs-toggle="collapse" data-bs-target="#service-levels" aria-expanded="true" aria-controls="service-levels">
-               <i class="ti ti-alarm me-1"></i>
-               <span class="item-title">
-                    {{ _n('Service level', 'Service levels', get_plural_number()) }}
-               </span>
-               {% if nb_la > 0 %}
-                  <span class="badge bg-secondary ms-2">{{ nb_la }}</span>
-               {% endif %}
-            </button>
-         </h2>
-         <div id="service-levels" class="accordion-collapse collapse {{ servicelevels_show ? "show" : "" }}" aria-labelledby="service-levels-heading">
-            <div class="accordion-body row m-0 mt-n2">
-               {{ include('components/itilobject/service_levels.html.twig') }}
+        {% set la_content %}
+            {{ include('components/itilobject/service_levels.html.twig') }}
+        {% endset %}
+
+        {% if la_content|trim|length > 0 %}
+            {% set nb_la = (item.fields['slas_id_tto'] > 0 ? 1 : 0) + (item.fields['slas_id_ttr'] > 0 ? 1 : 0) + (item.fields['olas_id_tto'] > 0 ? 1 : 0) + (item.fields['olas_id_ttr'] > 0 ? 1 : 0) %}
+            {% set servicelevels_show = headers_states['service-levels'] is defined and headers_states['service-levels'] == "true" ? true : false %}
+            <div class="accordion-item">
+                <h2 class="accordion-header" id="service-levels-heading" title="{{ _n('Service level', 'Service levels', get_plural_number()) }}" data-bs-toggle="tooltip">
+                    <button class="accordion-button {{ servicelevels_show ? "" : "collapsed" }}" type="button" data-bs-toggle="collapse" data-bs-target="#service-levels" aria-expanded="true" aria-controls="service-levels">
+                    <i class="ti ti-alarm me-1"></i>
+                    <span class="item-title">
+                            {{ _n('Service level', 'Service levels', get_plural_number()) }}
+                    </span>
+                    {% if nb_la > 0 %}
+                        <span class="badge bg-secondary ms-2">{{ nb_la }}</span>
+                    {% endif %}
+                    </button>
+                </h2>
+                <div id="service-levels" class="accordion-collapse collapse {{ servicelevels_show ? "show" : "" }}" aria-labelledby="service-levels-heading">
+                    <div class="accordion-body row m-0 mt-n2">
+                        {{ la_content }}
+                    </div>
+                </div>
             </div>
-         </div>
-      </div>
+        {% endif %}
    {% endif %}
 
    {% if item.getType() in ['Problem', 'Change'] %}
```

2022-08-30 07:22 UTC, orthagh approved these changes

2022-08-30 07:32 UTC, trasher approved these changes

2022-08-30 09:44 UTC, cconard96 approved these changes

2022-09-01 07:11 UTC, cedric-anne approved these changes

2022-09-01 07:11 UTC, merged