API: decode html
glpi-project/glpi pull request #12323
Opened 2022-07-28 13:34 UTC by AdrienClairembault

One issue with our API is that results are returned with encoded HTML:

![image](https://user-images.githubusercontent.com/42734840/181511596-6c1165ee-c58b-43d7-a05c-a0017166e636.png)

![image](https://user-images.githubusercontent.com/42734840/181512526-58e989ab-75e2-4de1-9b3a-6a28d2e281c9.png)

It happens because we store HTML encoded data in the database (bad practice), but I don't see us changing that soon because of how much work would be involved.

What we can do now is decode the data before sending it in the API response.

Regarding the impact on existing code that use the API, I expect most code would already be decoding the content.
In this case, decoding a second time shouldn't break anything.

Is there some use case we should be worried about breaking with this change ?

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !24579

2022-07-28 14:15 UTC, cconard96 commented
I don't agree with decoding every field in the response, at least not now given that it has always been encoded.

What if they were passing the encoded values as-is to another system that accepts encoded content only? Security-wise, I don't know how this could affect clients. On fields we expect to have rich-text, we sanitize the content to try an remove harmful content but how would a plain text field value like a name of "<script>alert()</script>" affect the client if it was sent as that instead of encoded? If the value was given as a response on its own later, then you could run into XSS through MIME sniffing (Client assumes the correct content type based on the content instead of the Content-Type header).

It sounds safer to put the responsibility on the API client/script to handle the encoded properties properly based on their needs.
I am not even sure it would be good to send decoded content in the new API (#12221) but if it was determined to be OK, that would be a better place to introduce the change where we could have more control over API versioning and handling individual response properties.

2022-07-29 08:59 UTC, cedric-anne commented
I agree, it may result in security issue in API clients.

To prevent introducing a BC-break in a non major version, we could add a `X-Glpi-Sanitized-Content` boolean header in 10.x version, having `true` as default value. If client pass `X-Glpi-Sanitized-Content: false`, in this case, we could return an unsanitized value.

2022-07-29 10:41 UTC, cconard96 commented
Another possibility is a header that lets the client specify which fields they want to be unsanitized like:
`X-Glpi-Unsanitized-Fields: name, content`

2022-07-29 11:02 UTC, cedric-anne commented
> Another possibility is a header that lets the client specify which fields they want to be unsanitized like: `X-Glpi-Unsanitized-Fields: name, content`

In most cases, the escaping logic is global to an application. So having to declare all fields that should be returned in their original value (the unsanitized one) may be a pain for developper.

2022-08-01 07:11 UTC, AdrienClairembault commented
> I agree, it may result in security issue in API clients.
> 
> To prevent introducing a BC-break in a non major version, we could add a `X-Glpi-Sanitized-Content` boolean header in 10.x version, having `true` as default value. If client pass `X-Glpi-Sanitized-Content: false`, in this case, we could return an unsanitized value.

I like this option, I think I'll add it to the pull request

2022-08-01 08:21 UTC, cedric-anne commented
You should also add some tests using special chars to validate current behaviour. The fact that you were able to change encoding handling without having any failure in tests is a not very reassuring.

2022-08-01 09:26 UTC, cedric-anne approved these changes

2022-08-02 11:34 UTC, trasher approved these changes

2022-08-02 21:16 UTC, cconard96 commented
I cannot test this at the moment. The API authenticates me but doesn't load my profiles or entities into the session. I do not think it is related to this PR, but I haven't found the cause.

2022-08-04 13:37 UTC, AdrienClairembault commented
I've added another commit to handle the API success message on item creation:

![image](https://user-images.githubusercontent.com/42734840/182860659-8fad7209-f246-4946-8b16-90bdda8c658b.png)

![image](https://user-images.githubusercontent.com/42734840/182860768-afc608c1-3b41-4e10-a560-f61e9b8c1365.png)

2022-08-09 09:51 UTC, cedric-anne requested changes

2022-08-09 09:51 UTC, cedric-anne commented on src/Api/API.php
> +                fn ($f) => is_string($f) ? html_entity_decode($f) : $f,
We should only revert sanitization process.
```suggestion
                fn ($f) => is_string($f) ? Sanitizer::decodeHtmlSpecialChars($f) : $f,
```

2022-08-09 09:51 UTC, cedric-anne commented on src/Api/API.php
> +                    fn ($f) => is_string($f) ? html_entity_decode($f) : $f,
```suggestion
                    fn ($f) => is_string($f) ? Sanitizer::decodeHtmlSpecialChars($f) : $f,
```

2022-08-09 09:51 UTC, cedric-anne commented on src/Api/API.php
> +                        $message = html_entity_decode($message);
```suggestion
                        $message = Sanitizer::decodeHtmlSpecialChars($message);
```

2022-08-09 10:55 UTC, cedric-anne approved these changes

2022-08-16 09:55 UTC, orthagh approved these changes

2022-08-16 13:25 UTC, merged