Fix default recipients for assign group in ticket notification
glpi-project/glpi pull request #12388
Opened 2022-08-05 03:03 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Change default recipient for the "New group in assignees" ticket notification from "Group in charge of the hardware" to "Group in charge of the ticket". This matches up with the other notifications related to new actors.

2022-08-05 11:06 UTC, cedric-anne commented
Tests are failing because you did not add a migration to fix existing data.

It is dangerous to touch existing data, but in this case, unless I am wrong, `ITEM_TECH_IN_CHARGE` and `ITEM_TECH_GROUP_IN_CHARGE` are not working, as `users_id_tech` and `groups_id_tech` fields are not existing for ITIL objects. So, for this notification, "Group in charge of the hardware" target should be replaced (or dropped if "Group in charge of the ticket" already exists).

And the, for all ITIL notifications, these targets should probably removed from proposed targets, and dropped from existing data.

2022-08-08 07:51 UTC, cedric-anne requested changes

2022-08-08 07:51 UTC, cedric-anne commented on install/migrations/update_10.0.2_to_10.0.3/notifications.php
> +        'event'    => 'assign_group',
Migration should parse all notifications related to ITIL objects, as it should also remove `Notification::ITEM_TECH_IN_CHARGE` and `Notification::ITEM_USER` targets.
```suggestion
```

2022-08-08 07:51 UTC, cedric-anne commented on install/migrations/update_10.0.2_to_10.0.3/notifications.php
> +    $removed_item_group = false;
`Notification::ASSIGN_GROUP` target should probably be added even if there is already another target (e.g. `Requester`), but only if `Notification::ASSIGN_GROUP` is not already part of targets.

See also next suggestions.

```suggestion
    $removed_item_group = false;
    $found_assigned_group = false;
```

2022-08-08 07:51 UTC, cedric-anne commented on install/migrations/update_10.0.2_to_10.0.3/notifications.php
> +        }
```suggestion
        }
        if ((int) $target['items_id'] === Notification::ASSIGN_GROUP) {
            $found_assigned_group = true;
        }
```

2022-08-08 07:51 UTC, cedric-anne commented on install/migrations/update_10.0.2_to_10.0.3/notifications.php
> +    if (count($targets) === 0) {
```suggestion
    if ($notification['event'] === 'assign_group' && $removed_item_group && !$found_assigned_group) {
```

2022-08-08 07:51 UTC, cedric-anne commented on install/migrations/update_10.0.2_to_10.0.3/notifications.php
> +        if ((int) $target['items_id'] === Notification::ITEM_TECH_GROUP_IN_CHARGE) {
```suggestion
        if (
            (int) $target['items_id'] === Notification::ITEM_TECH_GROUP_IN_CHARGE
            || (int) $target['items_id'] === Notification::ITEM_TECH_IN_CHARGE
            || (int) $target['items_id'] === Notification::ITEM_USER
        ) {
```

2022-08-08 07:51 UTC, cedric-anne commented on install/migrations/update_10.0.2_to_10.0.3/notifications.php
> +            unset($targets[$target_id]);
```suggestion
            if ((int) $target['items_id'] === Notification::ITEM_TECH_GROUP_IN_CHARGE) {
                $removed_item_group = true;
            };
```

2022-09-02 09:53 UTC, cedric-anne commented on install/migrations/update_10.0.2_to_10.0.3/notifications.php
> +        }
```suggestion
    foreach ($targets as $target_id => $items_id) {
        if (
            $items_id === Notification::ITEM_TECH_GROUP_IN_CHARGE
            || $items_id === Notification::ITEM_TECH_IN_CHARGE
            || $items_id === Notification::ITEM_USER
        ) {
            $DB->deleteOrDie('glpi_notificationtargets', [
                'id' => $target['id'],
            ]);
            if ($items_id === Notification::ITEM_TECH_GROUP_IN_CHARGE) {
                $removed_item_group = true;
            }
        }
        if ($items_id === Notification::ASSIGN_GROUP) {
            $found_assigned_group = true;
        }
```

2022-09-02 10:41 UTC, cedric-anne approved these changes

2022-09-06 07:44 UTC, trasher approved these changes

2022-09-07 14:56 UTC, orthagh approved these changes

2022-09-07 14:59 UTC, merged