Do not present deleted actors to BR for Tickets
glpi-project/glpi pull request #12422
Opened 2022-08-10 10:52 UTC by VladoTTX

Currently BR receive also actors from $this->fields not accounting deleted actors on $input["_actors"]
Present new values instead (without deleted actors), utilizing "_deleted" keys which come from transformActorsInput()

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #11671

2022-08-10 12:08 UTC, cedric-anne approved these changes

2022-08-10 12:11 UTC, cedric-anne requested changes

2022-08-10 12:11 UTC, cedric-anne commented on src/Ticket.php
> +                $removed = is_array($input[$input_key . "_deleted"]) ? array_column($input[$input_key . "_deleted"], "items_id") : [];
```suggestion
                $deleted_key = $input_key . '_deleted';
                $deleted_actors = array_key_existst($deleted_key, $input) && is_array($input[$deleted_key]) ? array_column($input[$deleted_key], 'items_id') : [];
```

2022-08-10 12:11 UTC, cedric-anne commented on src/Ticket.php
> +                        if(!in_array($actor[$field],$removed)){
```suggestion
                        if (!in_array($actor[$field], $deleted_actors)) {
```

2022-08-22 05:21 UTC, VladoTTX reviewed
Thanks for the update!
You have a typo on line 1150 should be array_key_exists

2022-08-22 06:10 UTC, trasher commented on src/Ticket.php
> +                $deleted_actors = array_key_existst($deleted_key, $input) && is_array($input[$deleted_key]) ? array_column($input[$deleted_key], 'items_id') : [];
```suggestion
                $deleted_actors = array_key_exists($deleted_key, $input) && is_array($input[$deleted_key]) ? array_column($input[$deleted_key], 'items_id') : [];
```

2022-08-22 06:17 UTC, trasher commented on src/Ticket.php
> +                           $tocleanafterrules[$input_key][] = $actor[$field];
```suggestion
                            $input[$input_key][]             = $actor[$field];
                            $tocleanafterrules[$input_key][] = $actor[$field];
```

2022-08-22 07:27 UTC, trasher approved these changes

2022-08-22 07:42 UTC, orthagh approved these changes

2022-08-22 07:44 UTC, merged