fix(notification): fix image size from notification
glpi-project/glpi pull request #12459
Opened 2022-08-22 08:32 UTC by stonebuzz

When the user copies/pastes the image from richtext and changes its size (smaller)

on display, the size is reworked by GLPI to match the size of the text area -> perfect

But when GLPI generates the notification, it takes into account the ```width``` and ```height``` in the ```img``` DOM

This PR allow GLPI to handle image size.

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !24145

2022-08-22 08:46 UTC, trasher approved these changes

2022-09-01 07:45 UTC, cedric-anne requested changes
I think resizing was wanted here, to ensure that image is sent using the size defined in rich text, to have a rendering similar in both browser and mail contexts.
There is probably something wrong in width/height handling.

2022-09-05 07:21 UTC, stonebuzz commented
Currently : 

With this image
![image](https://user-images.githubusercontent.com/7335054/188391264-8c6645ec-b983-4a25-838b-20ac7d0f3fc8.png)


- Paste image (GLPI resize it to match rich text size)
![image](https://user-images.githubusercontent.com/7335054/188391108-5ab1a33f-ec8b-4bdf-9124-f5d82b870fe0.png)

- Manually resize the image and save 
![image](https://user-images.githubusercontent.com/7335054/188391119-bd187a56-6a19-42ac-8468-09c18a818338.png)

- GLPI display like this
![image](https://user-images.githubusercontent.com/7335054/188391130-1de97c39-92d3-4eb9-88d8-0fc197b88da2.png)

- And like this when editing the follow-up
![image](https://user-images.githubusercontent.com/7335054/188391148-914852ac-c2d4-43d6-96b8-a9ca3f006f00.png)

2022-09-05 07:45 UTC, cedric-anne commented
IMHO, the display size in timeline is not correct.

2022-09-05 09:49 UTC, stonebuzz commented
Now, ```img``` from ```timeline``` or ```richtext``` use ```user``` size if exist 
![image](https://user-images.githubusercontent.com/7335054/188420540-5754ffc8-391c-4d37-84f9-cd713facc601.png)
![image](https://user-images.githubusercontent.com/7335054/188420596-5ce298c2-9534-4d38-a289-2f7baa0fff3c.png)

```PhotoSwipe``` gallery continues to use the real size of the image
![image](https://user-images.githubusercontent.com/7335054/188420861-da8f4c7c-c274-4917-ab55-77d3751c19ee.png)

```NotificationEventMailing``` continues to use ```user``` size if exist

2022-09-05 12:47 UTC, trasher approved these changes

2022-09-05 12:48 UTC, trasher commented on src/RichText/RichText.php
> +
```suggestion
```

2022-09-07 09:05 UTC, cedric-anne requested changes
Initial problem is that the HTML tag may contain only `height` or `width` but not both. In that case, for the undefined dimension, `Document::getImage()` uses a default value for `mail` context. IMHO, if `height` or `width` is defined, but not both, we should compute the other dimension using same ratio, and used default values only if both are not defined.

2022-09-07 10:43 UTC, cedric-anne requested changes

2022-09-07 10:43 UTC, cedric-anne commented on src/RichText/RichText.php
> +                            'user_h' => $height,//use from timeline
`thumbnail` prefix will be easier to understand. No need to comment it.
```suggestion
                            'w'   => $imgsize[0],
                            'h'   => $imgsize[1],
                            'thumbnail_w' => $width,
                            'thumbnail_h' => $height,
```

2022-09-07 10:43 UTC, cedric-anne commented on src/RichText/RichText.php
> +            $out .= "<img src='{$img['thumbnail_src']}' itemprop='thumbnail' loading='lazy' width='{$img['user_w']}' height='{$img['user_h']}' >";
Values were not required before this PR, so missing values have to be handled.
```suggestion
            $width_attr = isset($img['thumbnail_w']) ? "width='{$img['thumbnail_w']}'" : "";
            $height_attr = isset($img['thumbnail_h']) ? "height='{$img['thumbnail_h']}'" : "";
            $out .= "<img src='{$img['thumbnail_src']}' itemprop='thumbnail' loading='lazy' {$width_attr} {$height_attr}>";
```

2022-09-07 10:48 UTC, cedric-anne commented
> Initial problem is that the HTML tag may contain only `height` or `width` but not both. In that case, for the undefined dimension, `Document::getImage()` uses a default value for `mail` context. IMHO, if `height` or `width` is defined, but not both, we should compute the other dimension using same ratio, and used default values only if both are not defined.

I am not really sure to understand this piece of code. I guess it is quiet obsolete and could probably be simplified (it should not be a problem anymore to send images in real size in emails in 2022), but it is another topic.

So this PR is OK for me.

2022-09-07 10:48 UTC, cedric-anne approved these changes

2022-09-07 12:42 UTC, trasher approved these changes

2022-09-07 15:37 UTC, orthagh approved these changes

2022-09-07 18:46 UTC, cconard96 approved these changes

2022-09-08 06:12 UTC, merged