Fix missing self service ticket form defaults
glpi-project/glpi pull request #12473
Opened 2022-08-23 18:49 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #12427

When a ticket template is used in the self-service ticket creation form, multiple options are not set properly from the default values.
This PR fixes that and also changes how the `entities_id` is referenced within the template to match the regular ITIL Object form.

2022-08-24 04:48 UTC, trasher approved these changes

2022-08-24 09:00 UTC, btry approved these changes

2022-08-25 09:03 UTC, orthagh reviewed
Nothing to say on the entity part.
But for the default value part, maybe we can factorize this part in a dedicated method.
We have the same code repeated in all showFormXXX methods (Commonitilobjet::showForm, same for Ticket and now the helpdesk form)

2022-08-29 12:19 UTC, orthagh approved these changes

2022-08-29 12:20 UTC, orthagh commented
the @cedric-anne opinion should be better before merge.
Seems ok when reading the changes, but i may miss something

2022-09-01 07:20 UTC, cedric-anne requested changes

2022-09-01 07:20 UTC, cedric-anne commented on templates/components/itilobject/selfservice.html.twig
> +                        'entities_id': entities_id,
Line 250 should be updated too, I guess.

2022-09-02 13:32 UTC, cedric-anne commented on templates/components/itilobject/selfservice.html.twig
> +                        'entities_id': entities_id,
In fact, modification was not required, as variable is defined from `'entities_id' => $options['entities_id'],` but now the source of value is more clear.

2022-09-02 13:33 UTC, cedric-anne approved these changes

2022-09-02 13:52 UTC, merged