fix(inventory): update network port metrics
glpi-project/glpi pull request #12528
Opened 2022-08-31 08:12 UTC by stonebuzz

Actually ```NetworkPortMetric``` are never update / added after first import of ```NetworkPort```

This PR fix this

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #12483

2022-08-31 08:28 UTC, g-bougard approved these changes

2022-08-31 11:51 UTC, stonebuzz commented
refactor code: now it uses ```portUpdated``` from ```InventoryNetworkPort``` trait

2022-08-31 12:03 UTC, trasher approved these changes

2022-08-31 12:43 UTC, g-bougard approved these changes

2022-09-01 06:14 UTC, orthagh approved these changes

2022-09-01 06:16 UTC, cedric-anne commented on src/Inventory/Asset/NetworkPort.php
> +        ) {
You can use a shorter notation here.
```suggestion
        if (isset($input['ifinbytes'], $input['ifoutbytes'], $input['ifinerrors'], $input['ifouterrors'])) {
```

2022-09-01 06:22 UTC, cedric-anne requested changes
You should also test behaviour for `ifinerrors` and `ifouterrors` fields.

2022-09-01 06:22 UTC, cedric-anne commented on tests/functionnal/Glpi/Inventory/Assets/NetworkPort.php
> +        ->isTrue();
This part seems useless on update.
```suggestion
```

2022-09-01 06:22 UTC, cedric-anne commented on tests/functionnal/Glpi/Inventory/Assets/NetworkPort.php
> +        ->isTrue();
```suggestion
```

2022-09-01 06:22 UTC, cedric-anne commented on tests/functionnal/Glpi/Inventory/Assets/NetworkPort.php
> +        //now we have two metrics, one for yesterday and one for today
```suggestion
        //we still have two metrics, but today metrics are updated
```

2022-09-01 11:48 UTC, stonebuzz commented on tests/functionnal/Glpi/Inventory/Assets/NetworkPort.php
> +        //now we have two metrics, one for yesterday and one for today
done

2022-09-01 11:53 UTC, stonebuzz commented on tests/functionnal/Glpi/Inventory/Assets/NetworkPort.php
> +        ->isTrue();
done

2022-09-01 11:53 UTC, stonebuzz commented on tests/functionnal/Glpi/Inventory/Assets/NetworkPort.php
> +        ->isTrue();
done

2022-09-01 12:48 UTC, cedric-anne approved these changes

2022-09-01 12:49 UTC, merged