Feature/inventory envs
glpi-project/glpi pull request #12625
Opened 2022-09-12 12:16 UTC by trasher

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

2022-09-13 06:18 UTC, orthagh commented on src/Item_Environment.php
> +            ],
```suggestion
```
You don't have any `user` entry in `columns` key

2022-09-13 06:22 UTC, orthagh commented on src/Item_Environment.php
> +        return "ti ti-bolt";
```suggestion
        return "ti ti-terminal-2";
```

2022-09-13 06:23 UTC, orthagh requested changes
Maybe also `Phone` could have the new tab

2022-09-13 06:23 UTC, orthagh commented on src/Computer.php
> +        ->addStandardTab('Item_Environment', $ong, $options)
```suggestion
         ->addStandardTab('Item_Environment', $ong, $options)
```

2022-09-13 06:34 UTC, trasher commented
> Maybe also `Phone` could have the new tab

Tab is already present
![image](https://user-images.githubusercontent.com/224733/189827401-09187657-5134-4a5b-bd1c-5208051f7c63.png)

2022-09-13 07:46 UTC, orthagh commented
Okay, i did the comment a little too quick, in my mind it was also to add the clone relation and the purge of sub envs if needed

2022-09-13 08:02 UTC, trasher commented
> Okay, i did the comment a little too quick, in my mind it was also to add the clone relation and the purge of sub envs if needed

It's also done. There are 3 `Item_Environment` ocurrences in Computer.php and also 3 in Phone.php

2022-09-13 08:31 UTC, orthagh approved these changes

2022-09-21 13:12 UTC, cedric-anne approved these changes

2022-09-21 13:12 UTC, cedric-anne commented on src/Inventory/Asset/Environment.php
> +class Environment extends InventoryAsset
```suggestion
final class Environment extends InventoryAsset
```

2022-09-21 13:12 UTC, cedric-anne commented on src/Inventory/Asset/Environment.php
> +           // Delete Item_Process in DB
```suggestion
           // Delete Item_Environment in DB
```

2022-09-21 13:12 UTC, cedric-anne commented on src/Item_Environment.php
> +class Item_Environment extends CommonDBChild
```suggestion
final class Item_Environment extends CommonDBChild
```

2022-09-21 13:49 UTC, merged