Feat/logs viewer
glpi-project/glpi pull request #12636
Opened 2022-09-13 07:40 UTC by orthagh

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

2022-09-14 16:25 UTC, cconard96 requested changes

2022-09-14 16:25 UTC, cconard96 commented on templates/pages/admin/log_viewer.html.twig
> +                    <input type="text" value="" class="form-control form-control-sm" id="filter_logs_input"
```suggestion
                    <input type="text" value="" class="form-control form-control-sm" id="filter-logs-input"
```

2022-09-14 16:25 UTC, cconard96 commented on templates/pages/admin/log_viewer.html.twig
> +                {% set limitdropdown = include('components/dropdown/limit.html.twig', {
This dropdown currently redirects to an invalid page `/front/glpilist_limit=5` when changed. No `href` is set and it isn't in a tab, so the default behavior doesn't work. Also, I'm not sure the fluid_search check is needed as the page doesn't initialize a fluid search view.

2022-09-14 16:25 UTC, cconard96 commented on src/LogViewer.php
> +        if (!file_exists($filepath)) {
```suggestion
        if (is_dir($filepath) || !file_exists($filepath)) {
```
An invalid log name would make this code try reading from the log directory.

2022-09-15 07:55 UTC, orthagh commented
> Some remarks about the UX:

all should be fixed (or get around)

2022-09-15 11:00 UTC, orthagh commented
You're right, it should be fixed

2022-09-15 11:07 UTC, cconard96 approved these changes

2022-09-20 07:22 UTC, trasher commented
Maybe some tests may be added on new  LogViewer class

2022-09-20 13:48 UTC, orthagh commented
> Maybe some tests may be added on new LogViewer class

Done, and also class has been "un-staticked" (as much as possible)

2022-09-21 06:04 UTC, trasher commented
Seems correct :+1: 

Would it be possible to add the last modification date in logs files view? And maybe order files by that date, so non accessed files are not displayed first.

2022-09-21 06:45 UTC, trasher commented
Maybe log file size may be of interest also; and why not the ability for super admins to empty them?

2022-09-21 12:58 UTC, cconard96 requested changes

2022-09-21 12:58 UTC, cconard96 commented on templates/pages/admin/logs_list.html.twig
> +                                'label': __("sort by filename")
```suggestion
                                'label': __("Sort by filename")
```

2022-09-21 12:58 UTC, cconard96 commented on templates/pages/admin/logs_list.html.twig
> +                                'label': __("sort by size")
```suggestion
                                'label': __("Sort by size")
```

2022-09-21 12:58 UTC, cconard96 commented on templates/pages/admin/logs_list.html.twig
> +                                'label': __("sort by date")
```suggestion
                                'label': __("Sort by date")
```

2022-09-21 13:21 UTC, trasher approved these changes

2022-09-21 13:33 UTC, cconard96 approved these changes

2022-09-26 12:40 UTC, cedric-anne approved these changes

2022-09-26 12:51 UTC, merged