feat(ticket): remove pending status from follow-up/task
glpi-project/glpi pull request #12684
Opened 2022-09-19 09:57 UTC by Rom1-B

Before GLPI 10.0, we could define the status of the ticket when adding a follow-up or a task.

![image](https://user-images.githubusercontent.com/8530352/190991463-fca3222a-4555-4854-98ba-6055ebb3a708.png)

Since, GLPI 10.0 it is more automatic, and we can only add the status "pending" not remove it, for that it is necessary to do it by updating the ticket header.

This PR activates the toggle if the ticket is already pending, and if you deactivate it, the ticket becomes assigned or new (if there is no technician)

![image](https://user-images.githubusercontent.com/8530352/190993284-4454b8a2-e4ca-47fa-a245-741a82ae61eb.png)

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !24936

2022-09-19 13:50 UTC, orthagh commented on src/CommonITILTask.php
> +        } elseif ($this->input['_job']->fields["status"] == CommonITILObject::WAITING) {
I think all this part should be factorized as it's almost the same as Followup

2022-09-21 06:13 UTC, trasher approved these changes

2022-09-22 06:47 UTC, orthagh requested changes

2022-09-22 06:47 UTC, orthagh commented on src/CommonDBTM.php
> +
good for the factorisation but not in commonDBTM please.
As said in GLPI mattermost channel today, a trait could be the way

2022-09-23 08:05 UTC, trasher approved these changes

2022-09-23 09:35 UTC, orthagh approved these changes

2022-09-23 09:39 UTC, cedric-anne commented on src/Features/ParentStatus.php
> +    public function updateParentStatus(): void
Changes made to `$this->input` seems to be used only in this new method. Passing values in parameters would make static code analysis easier for IDEs and code analysis tools.

```suggestion
    public function updateParentStatus(CommonITILObject $parentitem, array $input): void
```

2022-09-23 11:08 UTC, trasher approved these changes

2022-09-23 12:13 UTC, cedric-anne commented on src/Features/ParentStatus.php
> +        $parentitem = $this->input['_job'];
```suggestion
```

2022-09-23 12:13 UTC, cedric-anne commented on src/Features/ParentStatus.php
> +            $input["_job"]->update($update);
```suggestion
            $parentitem->update($update);
```

2022-09-23 12:13 UTC, cedric-anne commented on src/Features/ParentStatus.php
> +              || ($input["_job"]->fields["status"] == CommonITILObject::ASSIGNED)
```suggestion
            && $parentitem->isStatusExists(CommonITILObject::PLANNED)
            && (($parentitem->fields["status"] == CommonITILObject::INCOMING)
              || ($parentitem->fields["status"] == CommonITILObject::ASSIGNED)
```

2022-09-26 07:13 UTC, cedric-anne approved these changes

2022-09-26 07:14 UTC, merged