Twig itemdevice
glpi-project/glpi pull request #12735
Opened 2022-09-22 13:10 UTC by stonebuzz

Use twig for ```Item_Device``` (usefull for locked field)

remove useless ```fields``` from ```getSpecificities``` already handle by ```generic_show_form``` 

- ```locations_id```
- ```states_id```
- ```otherserial```
- ```serial```
- ```users_id```
- ```groups_id```.

Example : 

Simcard before :
![image](https://user-images.githubusercontent.com/7335054/191750598-5ce2e655-f05a-4aad-aaf8-6768f207b3d4.png)

Simcard after :
![image](https://user-images.githubusercontent.com/7335054/191750625-bf6b3003-7f8a-44e3-bcd1-4de26eb97384.png)

Item_DeviceMemory before :  
![image](https://user-images.githubusercontent.com/7335054/191750764-c6ed7f5b-c40e-41fd-9c39-890fd4116d2e.png)

Item_DeviceMemory after :  
![image](https://user-images.githubusercontent.com/7335054/191750871-f51fb127-e547-4048-942f-a2b1118e0744.png)

Note : 
The known fields of GLPI are displayed before those of the class.  
The order of the fields is therefore not the same.
I don't know if it is possible to do anything

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

2022-09-22 13:19 UTC, cedric-anne requested changes
`getSpecificities` is used in many places, inclunding in the logic that build seearch options, you cannot remove fields from there.

2022-09-22 13:27 UTC, stonebuzz commented
> `getSpecificities` is used in many places, inclunding in the logic that build seearch options, you cannot remove fields from there.

agree with you

2022-09-23 05:20 UTC, trasher approved these changes

2022-09-23 06:44 UTC, orthagh approved these changes

2022-09-23 07:56 UTC, stonebuzz commented
sorry for that last commit 
Trying to get order as closest to the original
So i need drop generic_show_form to take control

2022-09-23 08:24 UTC, trasher approved these changes

2022-09-27 09:01 UTC, stonebuzz commented on templates/components/form/item_device.html.twig
> +{% endif %}
done

2022-09-27 09:01 UTC, stonebuzz commented on templates/components/form/item_device.html.twig
> +               {% block more_fields %}
done

2022-09-27 09:02 UTC, stonebuzz commented on templates/components/form/item_device.html.twig
> +{% set no_header = true %}
done

2022-09-27 09:02 UTC, stonebuzz commented on templates/components/form/item_device.html.twig
> +{% set item_has_pictures = item.hasItemtypeOrModelPictures() %}
done

2022-09-27 09:04 UTC, stonebuzz commented on templates/components/form/item_device.html.twig
> +                  ) }}
indeed

2022-09-27 09:05 UTC, stonebuzz commented on templates/components/form/item_device.html.twig
> +                        withtemplate,
done

2022-09-27 09:05 UTC, stonebuzz commented on templates/components/form/item_device.html.twig
> +                     ) }}
Exist in ```glpi_items_devicesimcards``

2022-09-27 09:06 UTC, stonebuzz commented on templates/components/form/item_device.html.twig
> +{% endif %}
done

2022-09-27 09:08 UTC, stonebuzz commented on templates/components/form/item_device.html.twig
> +{% if params['formfooter'] is null or params['formfooter'] == true %}
agree formfooter and date not needed here

2022-09-27 10:25 UTC, cedric-anne approved these changes

2022-09-27 10:53 UTC, merged