Twig computerantivirus
glpi-project/glpi pull request #12783
Opened 2022-09-27 15:02 UTC by stonebuzz

Use ```twig``` template for ```ComputerVirtualMachine```

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

2022-09-28 07:04 UTC, trasher commented on src/ComputerVirtualMachine.php
> +    public function showFormv1($ID, array $options = [])
Should not this one be removed?

2022-09-28 07:15 UTC, stonebuzz commented on src/ComputerVirtualMachine.php
> +    public function showFormv1($ID, array $options = [])
indeed =)

2022-09-28 07:18 UTC, trasher approved these changes

2022-09-28 13:49 UTC, cedric-anne requested changes

2022-09-28 13:49 UTC, cedric-anne commented on src/ComputerVirtualMachine.php
> +     * Display form for antivirus
```suggestion
     * Display form
```

2022-09-28 13:49 UTC, cedric-anne commented on src/ComputerVirtualMachine.php
> +     * @param integer $ID      id of the antivirus
```suggestion
     * @param integer $ID
```

2022-09-28 13:49 UTC, cedric-anne commented on templates/components/form/computervirtualmachine.html.twig
> +                     _n('Virtualization system', 'Virtualization systems', get_plural_number()),
```suggestion
                     'VirtualMachineType'|itemtype_name,
```

2022-09-28 13:49 UTC, cedric-anne commented on templates/components/form/computervirtualmachine.html.twig
> +                     _n('Virtualization model', 'Virtualization models', get_plural_number()),
```suggestion
                     'VirtualMachineSystem'|itemtype_name,
```

2022-09-28 13:49 UTC, cedric-anne commented on templates/components/form/computervirtualmachine.html.twig
> +                     _n('State of the virtual machine', 'States of the virtual machine', get_plural_number()),
```suggestion
                     'VirtualMachineState'|itemtype_name,
```

2022-09-29 09:20 UTC, cedric-anne commented on templates/components/form/computervirtualmachine.html.twig
> +                     item,
```suggestion
                     item.fields['name'],
```

2022-09-29 09:21 UTC, cedric-anne approved these changes

2022-09-30 06:09 UTC, merged