Improve image pasting from MS Word
glpi-project/glpi pull request #12862
Opened 2022-10-04 01:24 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #12849

When pasting an image from MS Word or LibreOffice Writer, the images were being inserted with one of two formats for their source attributes (Seemed random which it was):
1. A `file://` URI pointing to the image in a temporary directory
2. A `blob:` URI that seemed to point to a broken image

Local file access is not allowed in at least Chrome and Firefox for security reasons. However, the raw clipboard data has 3 different data sources (plain text, HTML, and RTF). TinyMCE only uses HTML or plain text but the RTF source has the binary image contents in hexadecimal. We can extract that data and replace the broken image sources.

I don't know if this fix would cause issues with other copy-paste cases that worked previously but I've not found any issues yet.
There is still an error printed in the browser console as it tries to initially access the local file. I haven't found a way to replace the `src` value earlier to prevent that error.

2022-10-18 09:13 UTC, cedric-anne commented on js/fileupload.js
> +                const local_file_blob_pattern = `^blob:${CFG_GLPI.url_base}/[0-9A-F]{8}-[0-9A-F]{4}-4[0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}`;
This kind of URL is produced by `URL.createObjectURL(file)` (line 95).

I think the only way to reproduce presence of this kind of URLs is to copy the data I just pasted and paste it again in the editor. I propose to not handle this case in this PR, as it a specific case that will not be a problem anymore in another fix I am working on in order to handle #12961.

2022-10-18 09:13 UTC, cedric-anne commented on js/fileupload.js
> +            if (last_paste_content !== null) {
```suggestion
            if (last_paste_content !== null && last_paste_content.types.includes('text/rtf')) {
```

2022-10-18 09:56 UTC, cedric-anne commented
> There is still an error printed in the browser console as it tries to initially access the local file.

I think it is caused by the creation of a `DocumentFragment` based on `event.content`. Maybe it is possible to add `loading="lazy"` to `<img>` tag in `event.content` before converting it to a fragment.

2022-10-19 07:29 UTC, cconard96 commented on js/fileupload.js
> +                    src = image.attr('data-rtf-src');
I don't know what I did differently the first time, but it is working properly now.

2022-10-19 07:32 UTC, cconard96 commented
> > There is still an error printed in the browser console as it tries to initially access the local file.
> 
> I think it is caused by the creation of a `DocumentFragment` based on `event.content`. Maybe it is possible to add `loading="lazy"` to `<img>` tag in `event.content` before converting it to a fragment.

This isn't an issue anymore since it was changed to update the `src` attribute directly.

2022-10-21 07:22 UTC, cedric-anne commented on js/fileupload.js
> +                const local_file_blob_pattern = `^blob:${CFG_GLPI.url_base}/[0-9A-F]{8}-[0-9A-F]{4}-4[0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}`;
While working on #13016, I dig a little bit on this. This is really an edge case.

As far as I understand, blob URLs are produced by TinyMCE. Technically, they are valid as long as they are used in the same browser session. So the only way to have this kind of issues is to copy an image pointing to a blob from a browser A and try to use it in a browser B.

I was able to reproduce the issue by:
 - starting to write a ticket description containing a pasted image on Chrome,
 - copying the content before it was submitted,
 - pasting it a new ticket form in Firefox.

Complexing the code to handle an unlikely case is something I do not favor.

2022-10-27 08:56 UTC, cedric-anne commented on js/fileupload.js
> +                if (src.match(file_pattern) !== null) {
To handle any tool that would not provide corresponding RTF content.
```suggestion
                if (src.match(file_pattern) !== null && base64_img_contents.length > 0) {
```

2022-10-27 08:56 UTC, cedric-anne approved these changes

2022-10-27 13:07 UTC, trasher approved these changes

2022-11-02 13:27 UTC, orthagh approved these changes

2022-11-02 14:06 UTC, cedric-anne requested changes

2022-11-02 14:06 UTC, cedric-anne commented on js/fileupload.js
> +        });
```suggestion
```

2022-11-02 14:11 UTC, cedric-anne approved these changes

2022-11-02 14:51 UTC, merged