fix(inventory): save agent port if needed (service mode)
glpi-project/glpi pull request #12895
Opened 2022-10-06 14:53 UTC by stonebuzz

Save agent port, if possible and if it run as service mode.

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

2022-10-06 15:08 UTC, g-bougard approved these changes

2022-10-07 04:27 UTC, trasher commented on src/Inventory/Inventory.php
> +            'deviceid'  => $this->raw_data->deviceid,
Alignment changes are not needed :)

2022-10-07 04:30 UTC, trasher requested changes
Some changes seems coming from another PR. Maybe rebase this one to take care of latest merged changes on inventory

2022-10-07 04:30 UTC, trasher commented on tests/functionnal/Glpi/Inventory/Inventory.php
> +            'last_boot' => null,
```suggestion
```

2022-10-07 04:30 UTC, trasher commented on tests/functionnal/Glpi/Inventory/Inventory.php
> +            'last_boot' => null,
```suggestion
```

2022-10-07 04:30 UTC, trasher commented on tests/functionnal/Glpi/Inventory/Inventory.php
> +            'last_boot' => null,
```suggestion
```

2022-10-07 06:11 UTC, stonebuzz commented on src/Inventory/Inventory.php
> +            'deviceid'  => $this->raw_data->deviceid,
done =)

2022-10-07 06:11 UTC, stonebuzz commented on tests/functionnal/Glpi/Inventory/Inventory.php
> +            'last_boot' => null,
revert

2022-10-07 06:11 UTC, stonebuzz commented on tests/functionnal/Glpi/Inventory/Inventory.php
> +            'last_boot' => null,
reverted

2022-10-07 06:12 UTC, stonebuzz commented on tests/functionnal/Glpi/Inventory/Inventory.php
> +            'last_boot' => null,
revert

2022-10-07 06:35 UTC, cedric-anne approved these changes

2022-10-07 06:35 UTC, cedric-anne commented on src/Agent.php
> +        if (isset($metadata['port']) && !is_null($metadata['port'])) {
`isset(null)` returns `false`, no need to do the second check.
```suggestion
        if (isset($metadata['port'])) {
```

2022-10-07 07:49 UTC, orthagh approved these changes

2022-10-07 12:35 UTC, trasher approved these changes

2022-10-07 12:35 UTC, merged