fix(ui): fix the display of the icon
glpi-project/glpi pull request #13050
Opened 2022-10-24 07:13 UTC by stonebuzz

Fix the display of the icon

Before : 
![image](https://user-images.githubusercontent.com/7335054/197468314-96610938-d5fc-4c29-872a-f0f985af99fc.png)

After : 
![image](https://user-images.githubusercontent.com/7335054/197468329-dbd5b709-dc25-474d-adf0-a07267acc3c4.png)

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

2022-10-24 07:18 UTC, trasher approved these changes

2022-10-24 09:10 UTC, cedric-anne commented
The best solution would be to have an icon in each dropdown option.

2022-10-24 10:17 UTC, stonebuzz commented
> The best solution would be to have an icon in each dropdown option.

![image](https://user-images.githubusercontent.com/7335054/197504132-e4aaf017-b64a-4b5a-a31f-eeeba24c7678.png)

2022-10-25 08:06 UTC, orthagh approved these changes

2022-10-25 08:21 UTC, cedric-anne requested changes

2022-10-25 08:21 UTC, cedric-anne commented on src/Dropdown.php
> +                        return $(img+'&nbsp'+label);
```suggestion
                        return $(img+'&nbsp;'+label);
```

2022-10-25 08:47 UTC, cedric-anne requested changes

2022-10-25 08:47 UTC, cedric-anne commented on src/Dropdown.php
> +                    formatFormIcon{$rand} = function(icon) {
Will prevent function to be declared in global scope.
```suggestion
                    const formatFormIcon = function(icon) {
```

2022-10-25 08:47 UTC, cedric-anne commented on src/Dropdown.php
> +                        if (!icon.id) {
`'0'` string is not skipped for now.
```suggestion
                        if (!icon.id || icon.id == '0') {
```

2022-10-25 08:47 UTC, cedric-anne commented on src/Dropdown.php
> +                        templateResult: formatFormIcon{$rand}
```suggestion
                        templateSelection: formatFormIcon,
                        templateResult: formatFormIcon
```

2022-10-25 09:31 UTC, cedric-anne approved these changes

2022-10-25 09:32 UTC, merged