feat(crontask): clean unset queued notifications
glpi-project/glpi pull request #13096
Opened 2022-10-28 07:04 UTC by Rom1-B

Added a job to trash browser notifications not sent for X days.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !25082

replace https://github.com/glpi-project/glpi/pull/13070

2022-11-09 17:45 UTC, cedric-anne requested changes

2022-11-09 17:45 UTC, cedric-anne commented on src/QueuedNotification.php
> +            case 'queuednotificationcleanunset':
1. "unset" had a typo, and "stale" is probably more appropriate.
2. "ajax" term should be added to be precise enough.
```suggestion
            case 'queuednotificationcleanstaleajax':
```

2022-11-09 17:45 UTC, cedric-anne commented on src/QueuedNotification.php
> +                return ['description' => __('Clean unsent notification queue'),
```suggestion
                return ['description' => __('Clean stale queued browser notifications'),
```

2022-11-09 17:45 UTC, cedric-anne commented on src/QueuedNotification.php
> +       // Expire mails in queue
```suggestion
        // Stale ajax notifications in queue
```

2022-11-09 17:45 UTC, cedric-anne commented on src/QueuedNotification.php
> +            $send_time = date("U") - $secs;
Should be computed on MySQL server side, to prevent timezone offset issues.

2022-11-09 17:45 UTC, cedric-anne commented on install/empty_data.php
> +                'param' => null,
Should this param have a default value?

2022-11-10 07:53 UTC, cedric-anne commented
We often have complains about this, so maybe it should be activated by default. In this case, to ensure that administrator is aware of this cleaning, we could:
 - move the parameter in browser notifications config form (/front/notificationajaxsetting.form.php), using, with a "Validity period of notifications" label and a tooltip to explain that notifications are not sent if the validity period expires and that cleaning is made by the cron task;
 - add a where clause to exclude stale notifications in `NotificationAjax::getMyNotifications()`.

2022-11-10 12:25 UTC, cedric-anne requested changes

2022-11-10 12:25 UTC, cedric-anne commented on install/migrations/update_10.0.x_to_10.1.0/queued_notification.php
> +
```suggestion

$current_config = Config::getConfigurationValues('core');
```

2022-11-10 12:25 UTC, cedric-anne commented on src/NotificationAjaxSetting.php
> +                __('Expired notifications will be trashed by the crontask'),
```suggestion
                __('Notifications older than the selected value will not be displayed. Expired notifications will be deleted by the %s crontask.'),
```

2022-11-10 12:25 UTC, cedric-anne commented on src/NotificationAjaxSetting.php
> +                ['value' => $CFG_GLPI["notifications_ajax_expiration_delay"]]
```suggestion
                [
                    'toadd' => [0 => __('Unlimited')],
                    'value' => $CFG_GLPI["notifications_ajax_expiration_delay"],
                ]
```

2022-11-10 13:17 UTC, cedric-anne approved these changes
OK for me.

The only question is, what should be the default validity period on update ? @orthagh

2022-11-10 13:18 UTC, orthagh commented
30 days should be reasonable.

2022-11-10 13:23 UTC, cedric-anne commented on install/migrations/update_10.0.x_to_10.1.0/queued_notification.php
> +        'notifications_ajax_expiration_delay' => '7'
```suggestion
        'notifications_ajax_expiration_delay' => '30'
```

2022-11-10 14:00 UTC, trasher approved these changes

2022-11-10 14:33 UTC, merged

2024-05-15 08:50 UTC, thobou-gly commented
Hi,
1st, thank you for implementing this feature, your work will be much appreciated, at least by me !
Any insight when 10.1 will be released so we all can enjoy it ?
Any way to vote this feature to be implemented sooner ?