show-socket-name-instead-of-socket-ID-in-Assets->computer-Table
glpi-project/glpi pull request #13189
Opened 2022-11-03 15:23 UTC by vijaidjearam

It would be meaningfull to show socket name instead socket ID in the Assets -> Computer Table

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

2022-11-04 07:36 UTC, stonebuzz requested changes
Can you change ```datatype``` of this ```searchoption``` to ```itemlink```

2022-11-04 09:59 UTC, vijaidjearam commented
@stonebuzz  Changing the `datatype` of this `searchoption` to `itemlink`  doesnt make any change , only _socket ID_ is displayed in the table.

2022-11-07 15:48 UTC, vijaidjearam reviewed
@stonebuzz As you have requested changed the  `datatype `of this `searchoption` to `itemlink`

@stonebuzz  i have accidentally removed the request for @trasher and @cedric-anne , could you please do the needfull.

2022-11-08 10:21 UTC, stonebuzz commented
> @stonebuzz Changing the `datatype` of this `searchoption` to `itemlink` doesnt make any change , only _socket ID_ is displayed in the table.

Column value is now an ```a href```et allow user to go to ```Socket```object

2022-11-08 10:21 UTC, stonebuzz approved these changes

2022-11-08 12:50 UTC, trasher approved these changes

2022-11-09 11:26 UTC, cedric-anne approved these changes

2022-11-09 11:26 UTC, merged