Fix missing value in password fields
glpi-project/glpi pull request #13246
Opened 2022-11-08 20:09 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | Ref https://forum.glpi-project.org/viewtopic.php?id=285362

Password fields from the form field twig template were not having their value set. This broke the display of the simcard PIN/PUK fields for example.

2022-11-08 21:00 UTC, orthagh approved these changes

2022-11-09 05:23 UTC, trasher commented
I wonder if setting this value will not cause issues with some real password fields.

2022-11-09 09:43 UTC, cedric-anne requested changes
Adding the existing value in DOM may is not correct from a security point of view.

The solution for this problem is probably to use same kind of logic as we already do for some password fields, like the `passwd` field of `MailCollector`, i.e., adding a checkbox to ask if password should be cleared, and redefine the value only if password field is not empty.

2022-11-09 10:35 UTC, cconard96 commented
> Adding the existing value in DOM may is not correct from a security point of view.
> 
> The solution for this problem is probably to use same kind of logic as we already do for some password fields, like the `passwd` field of `MailCollector`, i.e., adding a checkbox to ask if password should be cleared, and redefine the value only if password field is not empty.

These fields shouldn't be treated like passwords at all then.
Another type of field should be used for secrets that need to be seen and not write-only.

2022-11-09 10:36 UTC, cedric-anne commented
> > Adding the existing value in DOM may is not correct from a security point of view.
> > The solution for this problem is probably to use same kind of logic as we already do for some password fields, like the `passwd` field of `MailCollector`, i.e., adding a checkbox to ask if password should be cleared, and redefine the value only if password field is not empty.
> 
> These fields shouldn't be treated like passwords at all then. Another type of field should be used for secrets that need to be seen and not write-only.

So, in this case, we should probably use a `<input type="text">` field.

2022-11-09 10:38 UTC, cconard96 commented
Alternatively, any password/secret that doesn't intend to have its value shown should just not pass the value to that password field macro.

2022-11-09 13:14 UTC, trasher commented
> Alternatively, any password/secret that doesn't intend to have its value shown should just not pass the value to that password field macro.

Yes, but it's difficult to be sure it's the case. I thunk using another type of field for non password is the best way to go (no surprise).

2022-11-10 09:33 UTC, cedric-anne commented
It is probable that same issue is present in all usage of `passwordField` macro.

To handle it in a secure way, I think we should handle the `disclose` feature directly in the `passwordField` macro, by adding a `is_disclosable` boolean option (default to `false`). The `value` attribute would be defined only for disclosable fields, so we would not expose this value in DOM if user is not supposed to be able to read it.

To handle non disclosable fields, we should probably add a `clearable` option (default to `!is_disclosable`), that will add a `<input type="checkbox" name="_blank_{{ name }}" />`, and check all usages of this macro to ensure that password is cleared only when this field is set to 1.

2022-11-15 08:14 UTC, trasher approved these changes

2022-11-15 08:18 UTC, cedric-anne commented on templates/components/form/fields_macros.html.twig
> +      {%  set label = label ~ btn_group %}
```suggestion
      {% set label = label ~ btn_group %}
```

2022-11-15 08:32 UTC, cedric-anne requested changes

2022-11-15 08:32 UTC, cedric-anne commented on templates/components/form/fields_macros.html.twig
> +      &nbsp;<i class="fa fa-paste pointer disclose" onclick="copyToClipboard('{{ options.id }}')"></i>
`showField`, `hideField` and `copyToClipboard` are declared in `templates/components/form/item_device.html.twig` and will not be accessible in some contexts. The should be moved in `common.js` file.

2022-11-15 10:24 UTC, cedric-anne approved these changes

2022-11-15 13:44 UTC, merged

2023-01-17 07:42 UTC, efgiese commented
Can you please check the patch again?
With my installation (upgrade from 9.5.6 to 10.0.5), the points are now displayed, but the display or copying of the PIN/PUK does not work.

2023-01-17 07:44 UTC, cedric-anne commented
@efgiese This patch will be part of the 10.0.6 version that should be released soon.

2023-01-17 08:16 UTC, efgiese commented
I've applied the patch manually but it doesn't seem to work entirely.

2023-01-17 08:18 UTC, trasher commented
Use provided nightly builds