Fix RedirectList from CommonDBChild class
glpi-project/glpi pull request #13243
Opened 2022-11-08 17:29 UTC by tsmr

Fix RedirectList from CommonDBChild class

When use 
![image](https://user-images.githubusercontent.com/13178158/200633947-45fcf202-9269-4592-89d4-52b06521f196.png)
 from 
CommonDBChild class, we are redirected to non existant pages

Examples : /front/apiclient.php, /front/computerantivirus.php

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

2022-11-08 21:05 UTC, orthagh approved these changes

2022-11-09 05:26 UTC, trasher requested changes

2022-11-09 05:26 UTC, trasher commented on src/CommonGLPI.php
> +                $glpilisturl = $parent::getFormURL(true) . "?id=" . $parent->fields['id'];
```suggestion
                $glpilisturl = $parent::getFormURLWithID($parent->fields['id'], true);
```

2022-11-09 10:58 UTC, cedric-anne approved these changes

2022-11-09 13:14 UTC, trasher approved these changes

2022-11-09 13:14 UTC, merged