feat(knowbase): add entity on articles
glpi-project/glpi pull request #13526
Opened 2022-12-05 14:22 UTC by Rom1-B

Addition of the entity on the articles of the KB, to have a partitioning like with the other objects of GLPI.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !25522 + !24105

2022-12-06 10:00 UTC, AdrienClairembault commented
Aren't entities for articles already defined in the "criteria" tab ?

2022-12-06 10:30 UTC, Rom1-B commented
> Aren't entities for articles already defined in the "criteria" tab ?

Yes, for distribution, but until now, the article did not belong to any entity, so an admin had access to all existing articles, even if his profile is limited to a single sub-entity.

2022-12-06 10:37 UTC, cconard96 commented
So, basically the article itself will have a default or management entity that can then be shared with other entities?

It will only be editable from its own entity, but viewable in any it is shared with?

2022-12-06 15:11 UTC, Rom1-B commented
The goal is that the entities on the items work as elsewhere (e.g. computers).

If the item is in a sub-entity, it is only visible in this entity and its children.

In the targets by entities, only the entity of the article and its children are proposed.

If the article is in a root entity, this is exactly how it works now.

2022-12-12 09:14 UTC, cedric-anne requested changes

2022-12-12 09:14 UTC, cedric-anne commented on install/migrations/update_10.0.x_to_10.1.0/knowbaseitem.php
> +        "int {$default_key_sign} NOT NULL DEFAULT '0'",
You can use the corresponding format helper.
```suggestion
        'fkey',
```

2022-12-12 09:14 UTC, cedric-anne commented on install/migrations/update_10.0.x_to_10.1.0/knowbaseitem.php
> +            'value' => 0,
No need to define it as it is already defined by `fkey` type.
```suggestion
```

2022-12-12 09:14 UTC, cedric-anne commented on install/migrations/update_10.0.x_to_10.1.0/knowbaseitem.php
> +            'value' => 1,
`value` is for field default value. If you want to update existing value, you have to use `update` option.

```suggestion
            'update' => 1,
```

2022-12-12 09:14 UTC, cedric-anne commented on install/migrations/update_10.0.x_to_10.1.0/knowbaseitem.php
> +        "tinyint NOT NULL DEFAULT '0'",
You can use the corresponding format helper.
```suggestion
        'bool',
```

2022-12-12 09:14 UTC, cedric-anne commented on install/migrations/update_10.0.x_to_10.1.0/knowbaseitem.php
> +$fkey_to_add = 'is_recursive';
This is not a fkey, variable name should be changed.
```suggestion
$field_to_add = 'is_recursive';
```

2022-12-12 09:14 UTC, cedric-anne commented on src/CommonDBVisible.php
> +            'is_recursive'  => $this->fields['is_recursive'],
`getShowVisibilityDropdownParams()` is also used on plugins. New parameters should only be added if there is a corresponding field.

2022-12-12 10:10 UTC, cedric-anne approved these changes

2022-12-12 10:35 UTC, trasher approved these changes

2022-12-14 13:44 UTC, orthagh approved these changes

2022-12-14 13:54 UTC, merged