Hide locked fields for deleted relation
glpi-project/glpi pull request #13527
Opened 2022-12-05 16:37 UTC by AdrienClairembault

From the "Locks" tab of a monitor, I can see the computer locked fields AND the locked fields of items linked to the computer:

![image](https://user-images.githubusercontent.com/42734840/205690747-c53c09a5-dea5-4706-8a34-5d6fe250aa3e.png)

@stonebuzz tell me that this is done on purpose (to make it easier to browse all locked fields from the parent computer) so no issues at this point.

However, the linked fields are still shown even if the relation is deleted:

![image](https://user-images.githubusercontent.com/42734840/205691602-d3b7ad74-ff2b-4caa-a3ee-a2dc77fc5cb2.png)

They should be hidden in the case (the fields are irrelevant because the items are no longer linked).

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !25474

2022-12-06 07:24 UTC, stonebuzz requested changes
This filter could be generalized and used by

- the first ```if``` statement -> ```instanceof CommonDBConnexity```

For ```Item_Devicexxx```,```NetworkPort```, ```NetworkName```, ```IPAddress```, ```Antivirus```, ```VirtualMachine```, ```Software``` ...

- the second ```elsif``` statement -> ```$CFG_GLPI['directconnect_types']```

For ```Monitor```, ```Peripheral```, ```Phone```, ```Printer```

- the last ```elseif``` statement -> ```isField($itemtype) && isField($items_id)```

For ```DatabaseInstance```

if I'm not mistaken, all these objects have the ```is_deleted``` field but it could be checked with

```php
if ($lockable_object->isField('is_deleted')) {

}
```

2022-12-06 11:32 UTC, AdrienClairembault commented
DatabaseInstance done in [94110ff](https://github.com/glpi-project/glpi/pull/13527/commits/94110ffdcd9031416b07cb0e73897ec127bc4b51).

Before:

![image](https://user-images.githubusercontent.com/42734840/205900617-87072901-7bb8-4ebc-9b84-06d304af9e8f.png)

The DB is deleted but its locked fields are still displayed AND it's missing from the second table that indicate deleted items.

After:

![image](https://user-images.githubusercontent.com/42734840/205900508-202e04d3-21c5-47a8-8149-696209c3eb9c.png)

2022-12-06 13:09 UTC, stonebuzz approved these changes

2022-12-12 08:59 UTC, cedric-anne approved these changes

2022-12-12 13:19 UTC, trasher approved these changes

2022-12-12 13:20 UTC, merged