fix(cleansoftware): some versions were not deleted
glpi-project/glpi pull request #13661
Opened 2022-12-21 13:35 UTC by Rom1-B

In some cases, an uninstalled software version was not deleted, because the link between the item and this version remained in the trash bin.

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !25983

2022-12-21 13:45 UTC, trasher approved these changes

2022-12-23 09:45 UTC, trasher requested changes
Looking at what codes currently do, this seems wrong. Other method are not looking for a `is_deleted = 1` nor `is_dynamic = 1`.

I wonderr if the issue is not in Software relations cleaning rather than is current cron.

2022-12-29 14:10 UTC, AdrienClairembault commented
For relations, doesn't `is_deleted = 1` + `is_dynamic = 1` indicate a lock ?
I think that if you delete the row, the data will be recreated on the next inventory.

2023-01-03 09:25 UTC, cedric-anne commented on src/CleanSoftwareCron.php
> +        ]);
With this, you will delete rows that are not necessary related to softwares that will be deleted on next line.

Updating criteria in `getVersionsWithNoInstallationCriteria` to exclude deleted `Item_SoftwareVersion` is a better solution.

2023-01-04 15:53 UTC, cedric-anne approved these changes

2023-01-05 06:09 UTC, trasher approved these changes

2023-01-05 07:27 UTC, orthagh approved these changes

2023-01-05 08:08 UTC, merged