Twig template for projects' tasks
glpi-project/glpi pull request #13729
Opened 2023-01-03 15:20 UTC by AdrienClairembault

Viewing projects' tasks from the "Your planning" widget of the  "Personal view" tab of the home page is broken:

![image](https://user-images.githubusercontent.com/42734840/210385996-a07abc17-78bf-48f1-b683-981b1dbf0c5a.png)

It seems to be outdated table based html that isn't really responsive and can't deal with the smaller available width.

I've migrated it to twig to fix the issue.

After fix:

![image](https://user-images.githubusercontent.com/42734840/210386272-942bc9ee-a115-4dd3-abc1-adba5c1d0a82.png)

And here the before/after from the project task main tab:

![image](https://user-images.githubusercontent.com/42734840/210386490-5fec2266-13a5-44cb-97de-cec30cae96a8.png)

![image](https://user-images.githubusercontent.com/42734840/210386522-522976be-9b34-41eb-ac78-2a76eba95ff0.png)

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !26056

2023-01-05 13:40 UTC, cedric-anne requested changes

2023-01-05 13:40 UTC, cedric-anne commented on src/ProjectTask.php
> +            $duration = ProjectTask_Ticket::getTicketsTotalActionTime($this->getID());
Should be placed after next line, to save a useless DB query if check does not pass.

2023-01-05 13:40 UTC, cedric-anne commented on src/ProjectTask.php
> +            );
Should be formatted on template side using `|formatted_duration(false)` filter. Filter will have to be updated to get an optional `bool $display_seconds = true` parameter.

2023-01-05 13:40 UTC, cedric-anne commented on src/ProjectTask.php
> +            'safe_content'             => RichText::getSafeHtml($this->fields["content"], true),
This should not be needed. Indeed, `|safe_html|escape` filters are already applied by textarea field macro.

```suggestion
            'content'             => $this->fields["content"],
```

2023-01-05 13:40 UTC, cedric-anne commented on templates/pages/tools/project_task.html.twig
> +        _n('Project task template', 'Project task templates', 1),
```suggestion
        'ProjectTaskTemplate'|itemtype_name,
```

2023-01-05 13:40 UTC, cedric-anne commented on templates/pages/tools/project_task.html.twig
> +                $('textarea[name=comment]').val(data.comments);
Selectors are not precise enough, `name` and `comment` are common field names. You should either find a way to trigger the form.
Maybe something like:
```js
function projecttasktemplate_update(value) {
    const form = $(this).closest('form');
```
and then:
```js
form.find('input[name=name]').val(data.name);
```

2023-01-05 13:40 UTC, cedric-anne commented on templates/pages/tools/project_task.html.twig
> +        $("input[name=auto_percent_done]").on('change', function() {
Selectors based on random ID would be safer here.

2023-01-05 13:40 UTC, cedric-anne commented on templates/pages/tools/project_task.html.twig
> +        $('select[name=is_milestone]').on('change', function() {
Same here.

2023-01-06 07:28 UTC, cedric-anne approved these changes

2023-01-06 08:04 UTC, orthagh approved these changes

2023-01-06 08:08 UTC, merged