feat(marketplace): add GLPI URL for checkpluginsupdate notif
glpi-project/glpi pull request #13751
Opened 2023-01-05 14:24 UTC by flegastelois

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | N/A

2023-01-05 14:47 UTC, cedric-anne commented on install/empty_data.php
> +##lang.glpi.url## :##glpi.url##',
```suggestion
##lang.glpi.url## : ##glpi.url##',
```

2023-01-05 14:47 UTC, cedric-anne commented on src/Marketplace/NotificationTargetController.php
> +                                                        '/front/marketplace.php');
```suggestion
        $this->data['##glpi.url##'] = $this->formatURL(
            NotificationTarget::GLPI_USER,
            '/front/marketplace.php'
        );
```

2023-01-05 14:47 UTC, cedric-anne commented on src/Marketplace/NotificationTargetController.php
> +            'glpi.url'           => __('URL of the application')
```suggestion
            'glpi.url'           => __('URL of the application'),
```

2023-01-05 14:50 UTC, trasher approved these changes

2023-01-05 15:06 UTC, cedric-anne requested changes
There is already something that should be available globally: https://github.com/glpi-project/glpi/blob/d14f99ea0a807cb4be585a24cd39a2bbc7bb8952/src/NotificationTarget.php#L1333-L1336

I will try to investigate to see why it does not work.

2023-01-05 15:21 UTC, flegastelois commented
> 



> There is already something that should be available globally:
> 
> https://github.com/glpi-project/glpi/blob/d14f99ea0a807cb4be585a24cd39a2bbc7bb8952/src/NotificationTarget.php#L1333-L1336
> 
> I will try to investigate to see why it does not work.

This is also what I had seen, but the "glpi.url" tag is not visible in the list of those available in the template.

2023-01-18 15:18 UTC, cedric-anne requested changes

2023-01-18 15:18 UTC, cedric-anne commented on src/Marketplace/NotificationTargetController.php
> +            'glpi.url'           => __('URL of the application'),
```suggestion
            'marketplace.url'    => __('URL of GLPI marketplace'),
```

2023-01-18 15:18 UTC, cedric-anne commented on src/Marketplace/NotificationTargetController.php
> +        $this->data['##glpi.url##'] = $this->formatURL(
```suggestion
        $this->data['##marketplace.url##'] = $this->formatURL(
```

2023-01-18 15:18 UTC, cedric-anne commented on src/Marketplace/NotificationTargetController.php
> +            NotificationTarget::GLPI_USER,
Not sure of this one, but all calls to `formatUrl` are using the same value
```suggestion
            $options['additionnaloption']['usertype'],
```

2023-01-18 15:18 UTC, cedric-anne commented on install/empty_data.php
> +##lang.glpi.url## : ##glpi.url##',
```suggestion
##lang.marketplace.url## : ##marketplace.url##',
```

2023-01-18 15:18 UTC, cedric-anne commented on install/empty_data.php
> +&lt;p&gt;##lang.glpi.url## : &lt;a title="##lang.glpi.url##" href="##glpi.url##" target="_blank" rel="noopener"&gt;##glpi.url##&lt;/a&gt;&lt;/p&gt;'
```suggestion
&lt;p&gt;##lang.marketplace.url## : &lt;a title="##lang.marketplace.url##" href="##marketplace.url##" target="_blank" rel="noopener"&gt;##marketplace.url##&lt;/a&gt;&lt;/p&gt;'
```

2023-01-18 15:31 UTC, flegastelois commented
Linked to https://github.com/glpi-project/glpi/pull/13830

2023-01-18 15:33 UTC, orthagh approved these changes

2023-01-19 06:56 UTC, trasher approved these changes

2023-01-19 06:56 UTC, merged