Added software license item recipients
glpi-project/glpi pull request #13789
Opened 2023-01-12 23:38 UTC by zombigiraffe

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #13774

2023-01-13 00:20 UTC, cconard96 approved these changes

2023-01-13 10:28 UTC, cedric-anne requested changes
To be able to send notifications to technician/group in charge, we have to send separate notifications for each licence. Indeed, the default logic expects `target_object` property to be unique `CommonDBTM` object (see `NotificationTarget::addUserByField()`).

Splitting notification has been done recently for `Domain` and `Certificate` classe to be able to handle these targets, see #11068.

2023-01-20 00:12 UTC, cconard96 requested changes

2023-01-20 00:12 UTC, cconard96 commented on src/NotificationTargetSoftwareLicense.php
> +            Toolbox::deprecated('Using "entities_id" option in NotificationSoftwareLicense is deprecated.');
```suggestion
            Toolbox::deprecated('Using "entities_id" option in NotificationTargetSoftwareLicense is deprecated.');
```

2023-01-20 07:43 UTC, cedric-anne commented
I changed target branch from 10.0/bugfixes to main.

2023-02-08 10:33 UTC, cedric-anne commented
@orthagh 

We talked yesterday about the same change for `Cartridge`/`Consumable` alerts. You said that having distinct notifications could result in sending way too much notifications. Do you consider the issue will be the same for expired `SoftwareLicence` alerts?

2023-02-08 13:26 UTC, orthagh commented
I don't know particulary for this itemtype, but this fact is we should change (at least not in bugfixes) how much notifications we push for one event.
But as this seems to be asked frequently, we may change it main and if possible maybe permits to choose the behavior (grouped or one send per item)

2023-02-08 17:37 UTC, cedric-anne commented
> if possible maybe permits to choose the behavior (grouped or one send per item)

If we group items, we have to keep in mind that we have to prevent sending to someone a notification about an item he is not supposed to be notified. So we have to only group items from same entity, with same tech in charge, same froup in charge, and probably more.

2023-04-11 20:16 UTC, cedric-anne commented
I am closing this topic because it is a too complex topic that requires additional functional and technical specifications that we do not have time to do at the moment.

2023-04-11 20:16 UTC, closed without merging