feat(databaseinstance): add info from computer
glpi-project/glpi pull request #13795
Opened 2023-01-13 10:49 UTC by stonebuzz

Add some infos

Before : 
![image](https://user-images.githubusercontent.com/7335054/212302144-4d8dd248-d652-4cf9-8d51-f991002aad12.png)

After : 
![image](https://user-images.githubusercontent.com/7335054/212302170-0070f00b-f44a-4741-ab64-225db62a7ad4.png)

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

2023-01-13 11:30 UTC, orthagh approved these changes

2023-01-13 11:37 UTC, cedric-anne requested changes

2023-01-13 11:37 UTC, cedric-anne commented on src/DatabaseInstance.php
> +                echo "<td>" . $databasetype->fields['name'] . "</td>";
```suggestion
                $databasetype_name = '';
                if ($item->fields['databaseinstancetypes_id'] > 0 && $databasetype->getFromDB($item->fields['databaseinstancetypes_id']) {
                    $databasetype_name = $databasetype->fields['name'];
                }
                echo "<td>" . $databasetype_name . "</td>";
```

2023-01-13 11:37 UTC, cedric-anne commented on src/DatabaseInstance.php
> +                echo "<td>" . $manufacturer->fields['name'] . "</td>";
```suggestion
                $manufacturer_name = '';
                if ($item->fields['manufacturers_id'] > 0 && $manufacturer->getFromDB($item->fields['manufacturers_id'])) {
                    $manufacturer_name = $manufacturer->fields['name'];
                }
                echo "<td>" . $manufacturer_name . "</td>";
```

2023-01-13 15:27 UTC, cedric-anne approved these changes

2023-01-14 07:17 UTC, trasher approved these changes

2023-01-14 07:17 UTC, merged