Fix knowbase browse view in some locales
glpi-project/glpi pull request #13800
Opened 2023-01-13 21:29 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #13799

2023-01-14 07:08 UTC, trasher approved these changes

2023-01-16 07:04 UTC, cedric-anne requested changes
Same issue exists on `Glpi\Features\TreeBrowse` class.

2023-01-16 12:49 UTC, cedric-anne commented on src/Features/TreeBrowse.php
> +        $loading_txt = addslashes(__s('Loading...'));
`addslashes` is not needed anymore.
```suggestion
        $loading_txt = __s('Loading...');
```

2023-01-16 12:49 UTC, cedric-anne commented on src/Html.php
> +                    //trigger_error(sprintf('Debug tab "%s"(%s) display callable is invalid.', $tab_info['title'] ?? '', $tab_id), E_USER_WARNING);
```suggestion
                    trigger_error(sprintf('Debug tab "%s"(%s) display callable is invalid.', $tab_info['title'] ?? '', $tab_id), E_USER_WARNING);
```

2023-01-16 12:49 UTC, cedric-anne commented on src/Knowbase.php
> +        $loading_txt = addslashes(__s('Loading...'));
```suggestion
        $loading_txt = __s('Loading...');
```

2023-01-16 12:53 UTC, cedric-anne approved these changes

2023-01-16 13:22 UTC, merged