Do not expose FS path on front.
glpi-project/glpi pull request #13834
Opened 2023-01-19 08:41 UTC by trasher

Fix some typos.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #12785

2023-01-19 08:42 UTC, trasher commented
This PR introduces new strings to translate, I'm not sure it should be part of 10.0.6.

2023-01-19 08:44 UTC, orthagh approved these changes

2023-01-19 09:14 UTC, cedric-anne requested changes

2023-01-19 09:14 UTC, cedric-anne commented on src/Document.php
> +                    );
```suggestion
                    trigger_error(
                        sprintf(
                            __('Failed to delete the file %s'),
                            GLPI_DOC_DIR . "/" . $this->fields["filepath"]
                        ),
                        E_USER_WARNING
                    );
```

2023-01-19 09:14 UTC, cedric-anne commented on src/Document.php
> +            );
```suggestion
            trigger_error(
                sprintf(__('File %s not found.'), $fullpath),
                E_USER_WARNING
            );
```

2023-01-19 09:14 UTC, cedric-anne commented on src/Document.php
> +                );
```suggestion
                trigger_error(
                    sprintf(
                        __('Failed to delete the file %1$s (%2$s)'),
                        $input['current_filename'],
                        GLPI_DOC_DIR . "/" . $input['current_filepath']
                    ),
                    E_USER_WARNING
                );
```

2023-01-19 09:14 UTC, cedric-anne commented on src/Document.php
> +            );
```suggestion
            trigger_error(
                sprintf(__('File %s not found.'), $fullpath),
                E_USER_WARNING
            );
```

2023-01-19 09:14 UTC, cedric-anne commented on src/Document.php
> +                );
```suggestion
                trigger_error(
                    sprintf(
                        __('Failed to delete the file %1$s (%2$s)'),
                        $input['current_filename'],
                        GLPI_DOC_DIR . "/" . $input['current_filepath']
                    ),
                    E_USER_WARNING
                );
```

2023-01-19 09:14 UTC, cedric-anne commented on src/Document.php
> +                );
```suggestion
                trigger_error(
                    sprintf(
                        __('Failed to delete the file %1$s (%2$s)'),
                        $input['current_filename'],
                        GLPI_DOC_DIR . "/" . $input['current_filepath']
                    ),
                    E_USER_WARNING
                );
```

2023-01-19 09:14 UTC, cedric-anne commented on src/Document.php
> +            );
```suggestion
            trigger_error(
                sprintf(
                    __("The directory %s doesn't exist."),
                    GLPI_DOC_DIR
                ),
                E_USER_WARNING
            );
```

2023-01-19 09:14 UTC, cedric-anne commented on src/Document.php
> +            );
```suggestion
            trigger_error(
                sprintf(
                    __('Failed to create the directory %s. Verify that you have the correct permission'),
                    GLPI_DOC_DIR . "/" . $subdir
                ),
                E_USER_WARNING
            );
```

2023-01-19 09:15 UTC, cedric-anne commented
> This PR introduces new strings to translate, I'm not sure it should be part of 10.0.6.

These messages are here from a very long time, so it could wait to be fixed in 10.0.7.

2023-01-19 09:48 UTC, cedric-anne reviewed
We should not translate error messages in `trigger_error` calls, to be sure to have untranslated error log.

2023-01-19 09:48 UTC, cedric-anne commented on src/Document.php
>                              __('Failed to delete the file %s'),
```suggestion
                            'Failed to delete the file %s',
```

2023-01-19 09:48 UTC, cedric-anne commented on src/Document.php
>                  sprintf(__('File %s not found.'), $fullpath),
```suggestion
                sprintf('File %s not found.', $fullpath),
```

2023-01-19 09:48 UTC, cedric-anne commented on src/Document.php
>                          __('Failed to delete the file %1$s (%2$s)'),
```suggestion
                        'Failed to delete the file %1$s (%2$s)',
```

2023-01-19 09:48 UTC, cedric-anne commented on src/Document.php
>                  sprintf(__('File %s not found.'), $fullpath),
```suggestion
                sprintf('File %s not found.', $fullpath),
```

2023-01-19 09:48 UTC, cedric-anne commented on src/Document.php
>                          __('Failed to delete the file %1$s (%2$s)'),
```suggestion
                        'Failed to delete the file %1$s (%2$s)',
```

2023-01-19 09:48 UTC, cedric-anne commented on src/Document.php
>                          __('Failed to delete the file %1$s (%2$s)'),
```suggestion
                        'Failed to delete the file %1$s (%2$s)',
```

2023-01-19 09:48 UTC, cedric-anne commented on src/Document.php
>                      __("The directory %s doesn't exist."),
```suggestion
                    "The directory %s doesn't exist.",
```

2023-01-19 09:48 UTC, cedric-anne commented on src/Document.php
>                      __('Failed to create the directory %s. Verify that you have the correct permission'),
```suggestion
                    'Failed to create the directory %s.',
```

2023-01-20 12:52 UTC, cedric-anne approved these changes

2023-01-20 13:01 UTC, merged