fix(FAQ): visibility as documented (before GLPI 10.1)
glpi-project/glpi pull request #13890
Opened 2023-01-26 10:43 UTC by Rom1-B

Fix for `bugfix` only as discussed in https://github.com/glpi-project/glpi/pull/13455

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !25313

2023-01-26 10:54 UTC, AdrienClairembault requested changes
Looks good to me but I'd like to see some additional unit tests on this to ensure it doesn't break again (visibility and the recent issue on categories).

You can look at tests added here (https://github.com/glpi-project/glpi/pull/12922/files#diff-9c345c4cc3f12a0e4643b10935087375017c0c2ae71d850b06cf5c5e8845fd0d), I guess the FAQ part is too lightweight.

2023-01-26 10:54 UTC, AdrienClairembault commented on src/KnowbaseItem.php
> +        if ($params['knowbaseitemcategories_id'] !== KnowbaseItemCategory::SEEALL) {
I suppose this part is related to the issue we saw yesterday with categories ?

2023-01-26 11:08 UTC, AdrienClairembault approved these changes
After second thoughts, ok to merge without tests as it wont be merged in main.
However, this mean the separate PR for main should include the tests.

2023-01-26 11:29 UTC, cedric-anne approved these changes

2023-01-31 06:27 UTC, trasher approved these changes

2023-01-31 06:27 UTC, merged