feat(invntory): software with special char are poorly reconciled
glpi-project/glpi pull request #13893
Opened 2023-01-26 14:02 UTC by stonebuzz

From ```inventory``` when GLPI compare  software from database and from inventory file.

With ```inventory``` when GLPI compares the software of the database and those of the file of inventory, 

the method allowing to create the key of comparison does not take into account special characters encoded in database (encoded with ```htmlentities```)

From JSON

```json
            {
                "arch": "neutral",
                "folder": "C:\\Program Files\\WindowsApps\\SoundcloudLtd.SoundCloudforWindowsBeta_2.0.0.0_neutral__2xc63xn306dnw",
                "from": "uwp",
                "install_date": "2023-01-13",
                "name": "SoundCloud - Music & Songs",
                "publisher": "SoundCloud Global Limited & Co. KG",
                "system_category": "store",
                "version": "2.0.0.0"
            }
```  

from DB (see ```&#38;``` for ```&```)

```php
Array
  (
      [softid] => 3065
      [name] => SoundCloud - Music &#38; Songs
      [versionid] => 3331
      [version] => 2.0.0.0
      [arch] => neutral
      [entities_id] => 0
      [softwarecategories_id] => store
      [is_recursive] => 0
      [operatingsystems_id] => 0
      [manufacturers_id] => SoundCloud Global Limited &#38; Co. KG
  )
```

Generated comparison key from JSON
```
12a69d811b2a9eb60fbd52dfbe8fdbdc8f7b19ee$$$$2.0.0.0$$$$neutral$$$$SoundCloud Global Limited & Co. KG$$$$0$$$$0$$$$0
```

Generated comparison key from DB
```
e8688186f7ad446305b996140b146d36156b77b2$$$$2.0.0.0$$$$neutral$$$$SoundCloud Global Limited &#38; Co. KG$$$$0$$$$0$$$$0 
```

This Pr fix this

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/glpi-project/glpi-inventory-plugin/issues/296

2023-01-26 14:14 UTC, cedric-anne requested changes

2023-01-26 14:14 UTC, cedric-anne commented on src/Inventory/Asset/Software.php
> +            sha1($DB->escape(Html::entity_decode_deep($val->name))),
```suggestion
            sha1(Sanitizer::sanitize($val->name)),
```

2023-01-26 14:14 UTC, cedric-anne commented on src/Inventory/Asset/Software.php
> +            $DB->escape(Html::entity_decode_deep($val->manufacturers_id)),
```suggestion
            Sanitizer::sanitize($val->manufacturers_id),
```

2023-01-26 14:14 UTC, cedric-anne commented on src/Inventory/Asset/Software.php
> +            sha1($DB->escape(Html::entity_decode_deep($val->name))),
```suggestion
            sha1(Sanitizer::sanitize($val->name)),
```

2023-01-26 14:14 UTC, cedric-anne commented on src/Inventory/Asset/Software.php
> +        global $DB;
```suggestion
```

2023-01-26 14:14 UTC, cedric-anne commented on src/Inventory/Asset/Software.php
> +        global $DB;
```suggestion
```

2023-01-26 14:14 UTC, cedric-anne commented on src/Inventory/Asset/Software.php
> +use Html;
```suggestion
```

2023-01-26 14:21 UTC, cedric-anne commented
@stonebuzz Could you add a test case for this ? W will need to validate that #12451 will not break this specific case.

2023-01-26 14:34 UTC, cedric-anne reviewed
Almost all properties may have special chars.
Maybe it would be more efficient to handle `\stdClass` in `Sanitizer::sanitize()` and then use `$val = Sanitizer::sanitize()` on first line of `get*Key` methods.

2023-02-02 14:15 UTC, cedric-anne approved these changes

2023-02-02 14:20 UTC, orthagh approved these changes

2023-02-02 16:46 UTC, trasher approved these changes

2023-02-02 16:47 UTC, merged