Filtering on end warranty should also allow to search future dates
glpi-project/glpi pull request #14034
Opened 2023-02-08 11:50 UTC by liedekef

Currently it is now possible to select future dates when wanting to see the warranty expiration dates of devices. This change helps to see which devices will need attention in the coming X time then.

2023-02-08 12:32 UTC, cedric-anne requested changes
Thanks for the contribution.

Adding `'maybefuture' => true` to the search option declared in `Infocom::rawSearchOptionsToAdd()` would be a better solution, if it works.  Could you try it?

`Search` class is already way to complex and specific code should not be added anymore.

2023-02-08 13:49 UTC, liedekef commented
I can confirm it works by adding 'maybefuture' => true to the search option declared in Infocom::rawSearchOptionsToAdd() . Do I cancel this PR and create a new one?

2023-02-08 14:10 UTC, cedric-anne commented
> I can confirm it works by adding 'maybefuture' => true to the search option declared in Infocom::rawSearchOptionsToAdd() . Do I cancel this PR and create a new one?

You can just revert the first commit and push a new one on current PR. We will squash them when we will be ready to merge them.

2023-02-08 14:27 UTC, liedekef commented
Change done

2023-02-08 14:27 UTC, cedric-anne commented on src/Search.php
>                              ];
```suggestion
                            ];

```

2023-02-08 14:27 UTC, cedric-anne commented on src/Search.php
> +                     }
```suggestion
                    }
```

2023-02-08 14:27 UTC, cedric-anne approved these changes

2023-02-09 08:14 UTC, trasher approved these changes

2023-02-09 08:15 UTC, merged