add key on level column for CommonTreeDropdowns
glpi-project/glpi pull request #14077
Opened 2023-02-14 12:45 UTC by btry

For itemtypes using commontreedropdown items may show very slowly because of unoptimized SQL queries. 

This may happen with Formcxreator, when a question is designed to show only a subtree of existing items, and when there are a thousands of items in the database.

Adding an index on level columns shows a speed gain of 50%.

internal ref !26669

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #

2023-02-14 13:02 UTC, trasher approved these changes

2023-02-20 08:47 UTC, orthagh approved these changes

2023-02-20 09:16 UTC, cedric-anne requested changes
A check should be added in `DatabaseKeysChecker` to validates that `level` field is always indexed when table refeers to a `CommonTreeDropdown` item.

2023-02-27 13:45 UTC, trasher commented
ping @btry ?

2023-03-08 10:49 UTC, cedric-anne approved these changes

2023-03-08 11:11 UTC, merged