feat(ITIL Template): read-only fields
glpi-project/glpi pull request #14112
Opened 2023-02-17 13:44 UTC by Rom1-B

Allows managing read-only fields via templates

![image](https://user-images.githubusercontent.com/8530352/219667062-f2743556-d0f5-4f6e-8d83-f1a44efc1b0c.png)

![image](https://user-images.githubusercontent.com/8530352/219667487-912ae53c-ff21-4f27-9a0b-0d7a0cc982fa.png)
_It is not obvious on the screenshot, but the opening date field is disabled_

This PR does not handle special cases such as actors, as not requested by the customer

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !25392

2023-02-20 11:50 UTC, cconard96 approved these changes

2023-02-20 13:17 UTC, trasher commented
Tests are failing

2023-02-20 13:47 UTC, trasher commented on src/ITILTemplateReadonlyField.php
> +            echo "<div class='firstbloc'>";
We should use twig templates for new developments; unless there is a reason not to.

2023-02-20 13:58 UTC, cedric-anne requested changes
1. A control logic should probably be added somewhere to ensure that read-only fields are not updatable if someone forces some values when sending form. This should be done only when update is call from UI, as these read-only fields should probably remains updatable by any backend logic. By the way, same kind of control should probably be done also for hidden fields.

2. `disabled` inputs will not be sent in POST request and threfore will not be pssed to rules engine. I do not know if it will be considered as a problem.

2023-03-07 08:42 UTC, trasher commented
> 1. A control logic should probably be added somewhere to ensure that read-only fields are not updatable if someone forces some values when sending form. This should be done only when update is call from UI, as these read-only fields should probably remains updatable by any backend logic. By the way, same kind of control should probably be done also for hidden fields.
> 
>     2. `disabled` inputs will not be sent in POST request and threfore will not be pssed to rules engine. I do not know if it will be considered as a problem.

Are those fixed? I did not pay attention to this comment for the first time, but we should really not send hidden/read-only data from the form (or at least, do not use it, to prevent any user able to manipulate the HTML page to send data).

Also, I guess a few tests may be added.

2023-03-07 08:46 UTC, trasher commented
And ho, for the rules engine, I think we must send the values, or the rules may not be applied correctly... At creation, it must be the ones defined in the template; and the ones already in database in update case (template may have changed since item creation)

2023-03-07 09:05 UTC, Rom1-B commented
If, for example, the user triggers a rule that updates a hidden or read-only field. Should this action be blocked?

IMHO, the template is more about facilitating input than controlling it?
@orthagh @cedric-anne

2023-03-08 13:54 UTC, cedric-anne approved these changes

2023-03-08 13:55 UTC, cedric-anne commented
> If, for example, the user triggers a rule that updates a hidden or read-only field. Should this action be blocked?
> 
> IMHO, the template is more about facilitating input than controlling it? @orthagh @cedric-anne

As discussed in our weekly meeting, ITIL templates are made only to control form displaying.

2023-03-08 13:55 UTC, trasher approved these changes

2023-03-08 13:55 UTC, merged