fix: no rights for personal reminders and RSS feeds
glpi-project/glpi pull request #14125
Opened 2023-02-20 11:20 UTC by Rom1-B

When a profile did not have access to `public reminders`, GLPI replaced the menu with `personal reminders`, so the menu was not removed completely.

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !26786

2023-02-20 11:39 UTC, cedric-anne commented on src/RSSFeed.php
> +            $values[self::PERSONAL] = __('Show personal when no public rights');
Right should not be limited to `show` feature. If user has no right to show its personal feeds, he should also not be able to create, update, delete and purge its own feeds.
In this case, it probably means that, when a feed is created, its visibility should be forced to "public".

2023-02-22 15:35 UTC, cedric-anne requested changes
Remarks made on reminders are also applying on RSS feeds.

2023-02-23 09:33 UTC, cedric-anne reviewed
Seems OK. A test should be added to the new migration method.

2023-02-23 10:53 UTC, trasher approved these changes

2023-02-23 12:46 UTC, orthagh approved these changes

2023-02-23 13:18 UTC, merged