feat(Ruleticket): add Project assign to RuleTicket action
glpi-project/glpi pull request #14227
Opened 2023-03-01 15:44 UTC by stonebuzz

Add capability to assign ```Project``` from ```RuleTicket``` action. 

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !26077

2023-03-02 15:59 UTC, trasher commented on tests/functionnal/SLM.php
> +use CommonITILObject;
Not required?

2023-03-02 15:59 UTC, trasher approved these changes

2023-03-03 06:47 UTC, stonebuzz commented on tests/functionnal/SLM.php
> +use CommonITILObject;
yes, it's a residue, my bad

2023-03-08 11:04 UTC, cedric-anne requested changes

2023-03-08 11:04 UTC, cedric-anne commented on src/RuleTicket.php
> +                            $output["items_id"][Project::getType()][] = $value;
```suggestion
                            if (!array_key_exists("_projects_id", $output)) {
                                $output["_projects_id"] = [];
                            }
                            $output["_projects_id"][] = $value;
```

2023-03-08 11:04 UTC, cedric-anne commented on src/RuleTicket.php
> +                                }
```suggestion
                                if (!array_key_exists("_projects_id", $output) && count($target_projects) > 0) {
                                    $output["_projects_id"] = [];
                                }
```

2023-03-08 11:04 UTC, cedric-anne commented on src/RuleTicket.php
> +                                    $output["projects_id"] = $value['id'];
```suggestion
                                    $output["projects_id"][] = $value['id'];
```

2023-03-08 11:04 UTC, cedric-anne commented on src/RuleTicket.php
> +        $actions['assign_project']['appendto']              = 'items_id';
Not sure it is used.
```suggestion
        $actions['assign_project']['appendto']              = '_projects_id';
```

2023-03-08 11:04 UTC, cedric-anne commented on src/Ticket.php
> +        if ($projects_id) {
```suggestion
        // Add linked projects
        $projects_ids = $this->input['_projects_id'] ?? [];
        foreach ($projects_ids as $projects_id) {
```

2023-03-08 11:04 UTC, cedric-anne commented on src/Ticket.php
> +        if ($projects_id) {
```suggestion
        // Add linked projects
        $projects_ids = $this->input['_projects_id'] ?? [];
        foreach ($projects_ids as $projects_id) {
```

2023-03-08 11:04 UTC, cedric-anne commented on src/RuleTicket.php
> +        $actions['assign_project']['name']                  = _n('Associated element', 'Associated elements', Session::getPluralNumber()) . " : " . Project::getTypeName(1);
```suggestion
        $actions['assign_project']['name']                  = Project::getTypeName(1);
```

2023-03-08 11:08 UTC, stonebuzz commented on src/RuleTicket.php
> +                            $output["_projects_id"] = $action->fields["value"];
fixed

2023-03-08 11:08 UTC, stonebuzz commented on src/RuleTicket.php
> +                            $output["items_id"][Project::getType()][] = $value;
fixed

2023-03-08 11:08 UTC, stonebuzz commented on src/RuleTicket.php
> +                                    $output["projects_id"] = $value['id'];
fixed

2023-03-08 11:09 UTC, stonebuzz commented on src/RuleTicket.php
> +        $actions['assign_project']['appendto']              = 'items_id';
fixed

2023-03-08 11:10 UTC, stonebuzz commented on src/Ticket.php
> +        if ($projects_id) {
fixed

2023-03-08 11:10 UTC, stonebuzz commented on src/Ticket.php
> +        if ($projects_id) {
fixed

2023-03-08 11:10 UTC, stonebuzz commented on src/RuleTicket.php
> +        $actions['assign_project']['name']                  = _n('Associated element', 'Associated elements', Session::getPluralNumber()) . " : " . Project::getTypeName(1);
fixed

2023-03-08 11:52 UTC, cedric-anne approved these changes

2023-03-08 12:31 UTC, merged