Improve form for the "Add new task" massive action
glpi-project/glpi pull request #14238
Opened 2023-03-02 15:58 UTC by AdrienClairembault

Changes summary:
* Improve "Add new task" form in massive actions
* Increase task content textarea size 
* Remove width restriction on massive actions form

###  1) Improve "Add new task" form in massive actions

The 'Add new task" massive action form didn't support all the options from the "original" add task form found in the timeline:

![image](https://user-images.githubusercontent.com/42734840/222472953-cdea56ba-e0f1-4733-9bf4-5ab699ea7fd2.png)

![image](https://user-images.githubusercontent.com/42734840/222473038-d8216ad8-983f-430e-b3a5-8c06198bb907.png)

To improve this, I've exported the HTML code responsible for the "timeline version" of this form in a separate twig file (form_task_main_form.html.twig) which can then be included in the timeline and in massive actions.

This way we use the same form for both endpoints, minus a few special behaviors that must be handled with the template parameters:
* `no_form` as the massive action page already has a form defined with a specific target
* `disable_pending_reasons` to hide the pending reason toggle on the massive actions page as it may lead to accidental changes on the tickets' statuses.

Massive action form after changes:

![image](https://user-images.githubusercontent.com/42734840/222476314-f426160d-0837-4f2d-bfa1-144aca3f1a97.png)

###  2) Increase task content textarea size 

We have a lot of options using the right side which leads to wasted space on the left:

![image](https://user-images.githubusercontent.com/42734840/222478002-3d63dfea-d046-4ac8-ab8a-4aaccb1d955b.png)

I think it look better if we use the same space on both columns:

![image](https://user-images.githubusercontent.com/42734840/222478598-07dd3095-ced6-4264-9d6c-5572c5334184.png)

To do this, I've added a new `editor_height` option to the `textareaField` macro.

This also affect tasks on the timeline:

![image](https://user-images.githubusercontent.com/42734840/222479209-def86b38-0611-4057-a780-10d0afd56ead.png)

![image](https://user-images.githubusercontent.com/42734840/222479357-b1738478-c6a6-44d6-893e-7f8d1e6eace0.png)

###  3) Remove width restriction on massive actions form

It seems the massive action page had a weird 90% width restriction:

![image](https://user-images.githubusercontent.com/42734840/222480170-6961c1db-77cd-4c5a-a99f-a21e61c98ab8.png)

I've removed it as it didn't seem intentional, probably a remnant from the old UI.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !24844 FR75

2023-03-02 16:27 UTC, AdrienClairembault commented
Tests failure can be ignored as it does not seem related to the changes:

![image](https://user-images.githubusercontent.com/42734840/222490350-5715d7e9-1aee-46f5-8a21-f782fd83626e.png)

2023-03-03 14:50 UTC, trasher approved these changes

2023-03-14 11:18 UTC, cedric-anne requested changes
`form_task_main_form.html.twig` expect many variables to be defined, like `formoptions`, `params`, `rand`, `can_read_kb`, `kb_id_toload`, `candedit`, `can_update_kb`, `nokb` and `add_html_form`, but these are not defined by caller template.
Either caller template should pass them explicitely, either `form_task_main_form.html.twig` should define default values explicitely in its beginning, to make maintenance of this template easier.

2023-03-14 11:18 UTC, cedric-anne commented on templates/components/itilobject/timeline/form_task_main_form.html.twig
> +            {{ pending_reasons|raw }}
Should not be printed if `disable_pending_reasons` is `true`.

2023-03-14 11:18 UTC, cedric-anne commented on templates/components/itilobject/timeline/form_task_main_form.html.twig
> +    {% set pending_reasons %}
Should not be computed if `disable_pending_reasons` is `true`.

2023-03-15 12:32 UTC, cedric-anne approved these changes

2023-03-15 14:16 UTC, orthagh approved these changes

2023-03-16 07:00 UTC, merged