Fix max param for CleanSoftware
glpi-project/glpi pull request #14335
Opened 2023-03-20 19:27 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #11962

2023-03-22 08:19 UTC, cedric-anne requested changes
Tests are failing.

2023-03-23 07:37 UTC, cedric-anne approved these changes

2023-03-24 07:36 UTC, trasher approved these changes

2023-03-24 08:37 UTC, AdrienClairembault approved these changes

2023-03-24 09:16 UTC, merged