Fix can_promote in twig
glpi-project/glpi pull request #14475
Opened 2023-04-03 09:16 UTC by Aeto-J

Add "can_promote" test in a if on the creation of the button, for now when can_promote was false it do nothing, with this fix if we set can-promote at false the button on timeline object won't show up

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

2023-04-03 09:18 UTC, cedric-anne commented
@Aeto-J 

Can you explain, from a user point of view, what was the issue here?

2023-04-03 09:22 UTC, cedric-anne requested changes

2023-04-03 09:22 UTC, cedric-anne commented on templates/components/itilobject/timeline/timeline_item_header.html.twig
> +      {% elseif can_promote and get_current_interface() == 'central' and item.getType() is same as 'Ticket' and item.canCreate() and (entry['type'] is same as 'ITILFollowup' or entry['type'] is same
All of these conditions should probably be moved in `can_promote` definition.
```suggestion
      {% elseif can_promote %}
```

2023-04-03 09:23 UTC, cedric-anne commented
> Can you explain, from a user point of view, what was the issue here?

As far as I understand, `can_promote` is set to false when status is closed, but button is still shown.

2023-04-03 09:26 UTC, Aeto-J commented
The button "promote to ticket" ont ask for exemple is displayed even though the can_promote variable is false

2023-04-03 10:39 UTC, Rom1-B commented
`can_promote` is defined in `timeline.html.twig` and is equal to false when the ticket is closed:

```{% set can_promote = (entry['type'] == 'ITILFollowup' or entry['type'] == 'TicketTask') and can_edit_i and not status_closed %}```

In my opinion, you should be able to do promotions regardless of the status of the ticket. I don't think this behavior needs to be changed.

2023-04-04 07:32 UTC, tomolimo commented
> `can_promote` is defined in `timeline.html.twig` and is equal to false when the ticket is closed:
> 
> `{% set can_promote = (entry['type'] == 'ITILFollowup' or entry['type'] == 'TicketTask') and can_edit_i and not status_closed %}`
> 
> In my opinion, you should be able to do promotions regardless of the status of the ticket. I don't think this behavior needs to be changed.

Hello @Rom1-B 
can_promote is also false when can_edit_i is false, and here, that's the point which is important.
Thank you,
Regards,
Tomolimo

2023-04-12 08:39 UTC, trasher commented
Please check #14510

2023-04-12 08:57 UTC, closed without merging