Add 'tag' and 'otherserial' to RuleAsset
glpi-project/glpi pull request #14553
Opened 2023-04-18 14:46 UTC by stonebuzz

Add 'tag' as criteria to ```RuleAsset``` engine

Add 'otherserial' action (```regex_result```) to ```RuleAsset``` engine

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !27588

2023-04-18 15:30 UTC, orthagh approved these changes

2023-04-18 15:55 UTC, trasher approved these changes

2023-04-19 06:13 UTC, cedric-anne requested changes

2023-04-19 06:13 UTC, cedric-anne commented on src/CommonDBTM.php
> +                    $input['tag'] = $agent->fields['tag'];
We used to add a `_`  prefix to "virtual" fields (i.e. fields that are not in DB).

```suggestion
                    $input['_tag'] = $agent->fields['tag'];
```

2023-04-19 06:13 UTC, cedric-anne commented on src/RuleAsset.php
> +        $criterias['tag']['name']            = sprintf('%s > %s', Agent::getTypeName(1), __('Inventory tag'));
```suggestion
        $criterias['_tag']['name']            = sprintf('%s > %s', Agent::getTypeName(1), __('Inventory tag'));
```

2023-04-19 06:13 UTC, cedric-anne commented on tests/functional/Glpi/Inventory/Inventory.php
> +            'criteria'      => 'tag',
```suggestion
            'criteria'      => '_tag',
```

2023-04-19 06:28 UTC, cedric-anne approved these changes

2023-04-19 06:40 UTC, merged