Fix Default Email & actor name For Ticket Email Followup
glpi-project/glpi pull request #14587
Opened 2023-04-25 12:48 UTC by tsmr

Fix display of emails on already created ticket : 

Before : 

![image](https://user-images.githubusercontent.com/13178158/234281049-2317f55e-23ca-44db-b114-87cc2d1d8b17.png)

After : 

![image](https://user-images.githubusercontent.com/13178158/234285173-afdd6c4b-dd35-4e56-ba41-6775d0492514.png)

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

2023-04-25 14:25 UTC, cedric-anne commented on templates/components/itilobject/actors/main.html.twig
> +               title: "{{ actor['title'] }}",
```suggestion
               title: "{{ actor['title']|escape('js') }}",
```

2023-05-05 07:31 UTC, orthagh approved these changes

2023-05-05 07:47 UTC, cedric-anne requested changes
`alternative_email` should not be filled if it is not an alternative email. Indeed, if we store the default email of every actor here, then someone that changes its default email in its preference will still receive emails on its previous address for all tickets created before this address change.

If you want to display the default actor email, then you should probably do it using a `placeholder` attribute.

2023-06-13 14:33 UTC, cedric-anne commented
ping @tsmr

2023-06-14 09:07 UTC, closed without merging