fix: missing category when ticket created from change
glpi-project/glpi pull request #14601
Opened 2023-04-27 12:36 UTC by Rom1-B

When creating a ticket from a change, the category of the original change was not automatically included in the new ticket.

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !27779

2023-04-27 12:48 UTC, cconard96 commented on templates/components/form/link_existing_or_new.html.twig
> +               {% set target_form_path = (target_itemtype|itemtype_form_path ~ "?" ~ source_itemtype|itemtype_foreign_key ~ "=" ~ source_items_id) %}
When creating a ticket from a project task, the foreign key needs the underscore in front. That seems to be the only case, and must have been the first case I migrated. Perhaps the code in the Ticket class should be changed to handle both `projecttasks_id` and `_projecttasks_id` in addition to this change.

2023-05-09 07:43 UTC, cedric-anne requested changes
As discussed IRL, all fields that are copied from initial Tickets must be predefined only on initial load, to ensure that they are not reset when form is reloaded after category change.

2023-05-11 12:31 UTC, orthagh commented on src/CommonITILObject.php
> +            $fields = [
```suggestion
            // copy fields from original ticket, only when fields are not already set by the user (contained in _saved array)
            $fields = [
```

add a comment to clarify the feature, like seen together, it was hard without explanation to find how this works

2023-05-15 06:19 UTC, trasher approved these changes

2023-05-15 06:19 UTC, merged