Force tablename in sql construction to avoid ambiguity if the same fi…
glpi-project/glpi pull request #14678
Opened 2023-05-09 10:39 UTC by kabassanov

…eld is present in the secondary table

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

2023-05-09 10:43 UTC, cconard96 commented on src/CommonDBTM.php
> +                                $tablename.".".$field => $this->getID(),
```suggestion
                                $tablename . "." . $field => $this->getID(),
```

2023-05-09 10:44 UTC, cconard96 commented
Is this a fix for a specific bug you noticed?

2023-05-09 10:47 UTC, kabassanov commented
> Is this a fix for a specific bug you noticed?

Yes it is. There was an error while displaying group form:

[2023-05-09 12:14:58] glpisqllog.ERROR: DBmysql::query() in /usr/share/glpi/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: SELECT COUNT(*) AS cpt FROM `glpi_problemtasks`, `glpi_tasktemplates` WHERE (((`groups_id_tech` = '1234'))) AND `glpi_problemtasks`.`tasktemplates_id` = `glpi_tasktemplates`.`id` AND  NOT (`glpi_tasktemplates`.`entities_id` IN ('
10', '19'))
  Error: Column 'groups_id_tech' in where clause is ambiguous

By the way there are some other pieces of code with the same "Relation based on single foreign key". Probably need to change them also.

2023-05-09 11:51 UTC, cconard96 commented
What group form?

2023-05-09 12:13 UTC, cconard96 commented
Issue occurs on the Group item form when the Child Entities checkbox is checked. Error is triggered during the `canUnrecurs` check.

2023-05-10 06:31 UTC, trasher approved these changes

2023-05-10 06:35 UTC, cedric-anne requested changes
Seems OK, but same change should be done on lines 2553 and 2554.

2023-05-10 10:34 UTC, cconard96 commented
> Why not, but I'm not sure how it works exactly. I supposed that sending the item type would somehow define the table to use... Isn't it true?

No. This is just translated directly to a SQL query.
```php
$or_criteria[] = [
    $itemtype_field => $this->getType(),
    $items_id_field => $this->getID(),
];
```
becomes something like:
OR (`itemtype` = 'Computer' AND `items_id` = 32)

No guesses are made about which table the fields come from.

2023-05-10 12:11 UTC, trasher commented on src/CommonDBTM.php
>                                  $itemtype_field => $this->getType(),
```suggestion
                                $tablename . "." . $itemtype_field => $this->getType(),
```

2023-05-10 13:50 UTC, orthagh approved these changes

2023-06-05 13:07 UTC, cedric-anne approved these changes

2023-06-05 13:12 UTC, orthagh approved these changes

2023-06-05 17:34 UTC, merged