fix(core): display checkbox for allasset view
glpi-project/glpi pull request #14685
Opened 2023-05-10 06:06 UTC by stonebuzz

```checkbox```  from ```allasset (global)``` view is not available because

```item``` from ```allasset (global)``` view is ```null```

This PR handle this case

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #14684

2023-05-10 06:27 UTC, trasher approved these changes

2023-05-10 06:40 UTC, cedric-anne requested changes

2023-05-10 06:40 UTC, cedric-anne commented on templates/components/search/table.html.twig
> +                           {% if item is null or item is instanceof('CommonDBTM') and call(itemtype ~ '::isMassiveActionAllowed', [row['id']])  %}
```suggestion
                           {% if itemtype == 'AllAssets' or (item is instanceof('CommonDBTM') and call(itemtype ~ '::isMassiveActionAllowed', [row['id']]))  %}
```

2023-05-10 06:48 UTC, cedric-anne commented on templates/components/search/table.html.twig
> +                           {% if item is null or item is instanceof('CommonDBTM') and call(itemtype ~ '::isMassiveActionAllowed', [row['id']])  %}
I just saw that itemtype is defined in `row['TYPE']` in global search view.
```suggestion
                           {% set row_itemtype = row['TYPE'] ?? itemtype %}
                           {% if call(row_itemtype ~ '::isMassiveActionAllowed', [row['id']]) %}
```

2023-05-10 06:50 UTC, cedric-anne commented on templates/components/search/table.html.twig
>                                {% set checked = session('glpimassiveactionselected')[itemtype][row['id']] ?? false %}
Not related to initial bug, but this have to be updated too:
```suggestion
                              {% set checked = session('glpimassiveactionselected')[row_itemtype][row['id']] ?? false %}
```

2023-05-10 06:56 UTC, cedric-anne approved these changes

2023-05-10 07:05 UTC, orthagh approved these changes

2023-05-10 12:05 UTC, trasher approved these changes

2023-05-10 12:05 UTC, merged

2023-05-22 15:23 UTC, dzabaljauregui commented
Hello people!
Thank you very much for the fix!
Keep up the good work!
Best regards,
Daniel (from Argentina).