Add "View new tickets" right
glpi-project/glpi pull request #14747
Opened 2023-05-22 11:19 UTC by FragDev

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Added a "View new tickets" right, visible only for central interface profiles.
This right allows to see tickets with "New" status.
Currently we rely on another right (to assign tickets) which is not necessarily very intuitive.

2023-05-24 07:34 UTC, orthagh approved these changes

2023-05-24 08:13 UTC, trasher reviewed
I'm OK with the proposal, baut as discussed in yesterday meeting; it should target main branch.

2023-05-24 08:16 UTC, cedric-anne requested changes

2023-05-24 08:16 UTC, cedric-anne commented on src/Ticket.php
When user has the `READNEWTICKET` right:
- `Ticket::canView()` should return `true`,
- `Ticket::showCentralNewList()` should propbably display list of new tickets.

2023-05-25 07:15 UTC, orthagh commented
Another comment following a discussion I had yesterday with @cedric-anne 
Tests suite should be strongly enhanced to cover all changed methods at least.
At minimum, a test covering Search engine is expected

2023-05-30 12:32 UTC, AdrienClairembault approved these changes

2023-05-31 09:45 UTC, orthagh approved these changes

2023-05-31 11:32 UTC, cedric-anne approved these changes

2023-05-31 11:33 UTC, merged