Confirmation before uninstalling a plugin
glpi-project/glpi pull request #14746
Opened 2023-05-22 11:18 UTC by FragDev

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Added a confirmation modal before uninstalling the plugin.
Both "plugins" and "marketplace" views have been taken into account.

![image](https://github.com/glpi-project/glpi/assets/42278610/93c16e50-e6ca-4935-8546-8d837acca286)

2023-05-22 11:39 UTC, cedric-anne commented on templates/components/plugin_uninstall_modal.html.twig
> +                <h3>{{ _x('uninstall_plugin', 'Are you sure?') }}</h3>
No need to have context here (we rarely use contexts).
```suggestion
                <h3>{{ __('Are you sure?') }}</h3>
```

2023-05-22 11:39 UTC, cedric-anne commented on templates/components/plugin_uninstall_modal.html.twig
> +                <div class="text-muted">{{ _x('uninstall_plugin', 'By uninstalling the plugin you will lose all the data of the plugin.') }}</div>
```suggestion
                <div class="text-muted">{{ __('By uninstalling the plugin you will lose all the data of the plugin.') }}</div>
```

2023-05-22 11:39 UTC, cedric-anne commented on templates/components/plugin_uninstall_modal.html.twig
> +{{ open_btn|raw }}
I do not like the idea of defining the whole button HTML on PHP side, but as both buttons are really different on both marketplace and legacy plugin list, it is OK for me.

I guess we will find time to refactor these views in next major versions, in order to keep only one of them.

2023-05-22 11:41 UTC, cedric-anne commented on templates/components/plugin_uninstall_modal.html.twig
> +                <div class="text-muted">{{ _x('uninstall_plugin', 'By uninstalling the plugin you will lose all the data of the plugin.') }}</div>
Also, the plugin name should be added in this sentence, so the user will be sure that he is not deleting the wrong plugin data.

2023-05-25 08:19 UTC, orthagh requested changes
There's an issue in the former plugin list. 
The plugin name mentioned in the modal take the first installed entry of the list and not the one selected for uninstallation.

Ex, I clicked on uninstall for Gantt plugin:
![image](https://github.com/glpi-project/glpi/assets/418844/009be410-8424-46dd-9f0a-82bd3136f399)

2023-05-25 09:49 UTC, orthagh approved these changes

2023-05-25 12:05 UTC, trasher approved these changes

2023-05-25 14:17 UTC, cedric-anne approved these changes

2023-05-25 14:17 UTC, merged