feat(search): additional default filter
glpi-project/glpi pull request #14789
Opened 2023-05-29 12:00 UTC by Rom1-B

Replace https://github.com/glpi-project/glpi/pull/13977

Addition of default search filters, applied in addition to user filters. This filter can be disabled by the user.

![image](https://github.com/glpi-project/glpi/assets/8530352/34c0a49f-cec4-40f1-84f7-91347caa1b5f)

Settings in dropdowns:

![image](https://github.com/glpi-project/glpi/assets/8530352/f215745d-596d-4c7f-be0e-c51e252b3b12)

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !24956

2023-05-31 09:01 UTC, orthagh requested changes
Another issue : when previewing results, the search is saved in SESSION.
I suggest to remove the entry  (in SESSION) after previewing end.

2023-06-08 09:12 UTC, orthagh commented on install/mysql/glpi-empty.sql
> +  UNIQUE KEY `itemtype` (`itemtype`),
I want to discuss about this unicity key.
I'm not against it, but at least, a message should inform the admin when he tries to add a new filter when another one exists on the same itemtype.

Now, do we want to support only one filter per itemtype ?
Is there any technical issue having multiple ? (UI aside)

2023-06-20 11:41 UTC, orthagh reviewed
Before accepting, I'm still waiting for alert feature when unicity error triggers

2023-06-21 06:16 UTC, orthagh approved these changes

2023-06-30 05:00 UTC, trasher approved these changes

2023-07-03 13:15 UTC, cedric-anne requested changes

2023-07-03 13:15 UTC, cedric-anne commented on src/DefaultFilter.php
> +    public static function getSearchCriteria($itemtype)
```suggestion
    public static function getSearchCriteria(string $itemtype): ?array
```

2023-07-03 13:15 UTC, cedric-anne commented on src/DefaultFilter.php
> +        return [];
It should return `null` when there is nothing to return.
```suggestion
        return null;
```

2023-07-03 13:15 UTC, cedric-anne commented on templates/components/search/controls.html.twig
> +      window.location.replace(url);
Using regex does not seems safe. Using something like the following code would be more resilient to changes in URLs:
```suggestion
      const search_params = new URLSearchParams(window.location.search);
      if (!$(this).is(":checked")) {
          search_params.set('nodefault', '1');
      } else {
          search_params.delete('nodefault');
      }
      window.location.replace('?' + search_params.toString());
```

2023-07-18 09:03 UTC, cedric-anne reviewed
When default filter is enabled, the default criterion seems to be added, additionaly to the current search criteria. It may result in a duplicated default criterion:
![image](https://github.com/glpi-project/glpi/assets/33253653/68cfe899-7e62-443f-8c23-1cd878032f34)

I think this default criterion should not be added when default filters are enabled.

2023-07-19 12:30 UTC, cedric-anne approved these changes

2023-07-19 13:16 UTC, merged