Reload current loggedin user config after its been updated
glpi-project/glpi pull request #14890
Opened 2023-06-09 07:23 UTC by trasher

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

2023-06-09 07:35 UTC, cedric-anne commented on src/User.php
> +    public function cachePreferences()
```suggestion
    final public function loadPreferencesInSession(): void
```

2023-06-09 15:34 UTC, cconard96 requested changes

2023-06-09 15:34 UTC, cconard96 commented on src/Config.php
> +                $user->cachePreferences();
```suggestion
                $user->loadPreferencesInSession();
```

2023-06-09 15:34 UTC, cconard96 commented on src/User.php
> +            $this->cachePreferences();
```suggestion
            $this->loadPreferencesInSession();
```

2023-06-12 06:13 UTC, cedric-anne approved these changes

2023-06-12 06:59 UTC, orthagh approved these changes

2023-06-12 07:01 UTC, merged