fix(approval reminder): exclude solved tickets
glpi-project/glpi pull request #14924
Opened 2023-06-15 07:28 UTC by Rom1-B

Notifications were sent on all tickets with no status filtering (resolved or closed)

Feat: https://github.com/glpi-project/glpi/pull/11623

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !28109

2023-06-15 07:35 UTC, trasher commented
Maybe this need a test

2023-06-15 13:35 UTC, trasher requested changes

2023-06-15 13:35 UTC, trasher commented on tests/functional/CommonITILValidationCron.php
> +        ]);
```suggestion
        $this->boolean(
            $entity->update([
                'id' => 0,
                'approval_reminder_repeat_interval' => 1,
            ])
        )->isTrue();
```

2023-06-15 13:35 UTC, trasher commented on tests/functional/CommonITILValidationCron.php
> +        ]);
```suggestion
        ]);
        $this->integer($ticket_id)->isGreaterThan(0);
```

2023-06-15 13:35 UTC, trasher commented on tests/functional/CommonITILValidationCron.php
> +        ]);
```suggestion
        ]);
        $this->integer($ticket_validation_id)->isGreaterThan(0);
```

2023-06-15 13:35 UTC, trasher commented on tests/functional/CommonITILValidationCron.php
> +        $DB->updateOrDie(
I'm not sure this is a good idea to use that in tests

2023-06-15 13:35 UTC, trasher commented on tests/functional/CommonITILValidationCron.php
> +        ]);
```suggestion
        $this->boolean(
            $ticket->update([
                'id' => $ticket_id,
                'status' => \Ticket::SOLVED,
            ])
        )->isTrue();
```

2023-06-15 13:35 UTC, trasher commented on tests/functional/CommonITILValidationCron.php
> +        $DB->updateOrDie(
I'm not sure this is a good idea to use that in tests

2023-06-15 13:35 UTC, trasher commented on tests/functional/CommonITILValidationCron.php
> +        $ticket_validation->getFromDB($ticket_validation_id);
```suggestion
        $this->boolean($ticket_validation->getFromDB($ticket_validation_id))->isTrue();
```

2023-06-15 13:35 UTC, trasher commented on tests/functional/CommonITILValidationCron.php
> +        ]);
```suggestion
        $this->boolean(
            $ticket->update([
                'id' => $ticket_id,
                'status' => \Ticket::CLOSED,
            ])
        )->isTrue();
```

2023-06-15 13:35 UTC, trasher commented on tests/functional/CommonITILValidationCron.php
> +        $ticket_validation->getFromDB($ticket_validation_id);
```suggestion
        $this->boolean($ticket_validation->getFromDB($ticket_validation_id))->isTrue();
```

2023-06-15 13:35 UTC, trasher commented on tests/functional/CommonITILValidationCron.php
> +        // verify last reminder date is empty
Test does not check date. Either test or comment is wrong

2023-06-15 13:35 UTC, trasher commented on tests/functional/CommonITILValidationCron.php
> +        \CommonITILValidationCron::cronApprovalReminder($crontask);
You should test returned cron status.

2023-06-16 05:21 UTC, trasher commented on tests/functional/CommonITILValidationCron.php
> +        );
```suggestion
        $this->boolean(
            $DB->update(
                \TicketValidation::getTable(),
                [
                    'submission_date' => date('Y-m-d H:i:s', strtotime('-1 day')),
                ],
                [
                    'id' => $ticket_validation_id,
                ]
            )
        )->isTrue();
```

2023-06-16 05:21 UTC, trasher commented on tests/functional/CommonITILValidationCron.php
> +        );
```suggestion
        $this->boolean(
            $DB->update(
                \TicketValidation::getTable(),
                [
                    'last_reminder_date' => null,
                ],
                [
                    'id' => $ticket_validation_id,
                ]
            )
        )->isTrue();
```

2023-06-30 05:08 UTC, trasher approved these changes

2023-07-05 13:02 UTC, cedric-anne commented
Please rebase to ensure tests are made on a most recent version of main branch.

2023-07-18 11:21 UTC, cedric-anne approved these changes

2023-07-18 11:24 UTC, merged