fix(upload): prevent form submit during file upload
glpi-project/glpi pull request #14967
Opened 2023-06-20 13:47 UTC by stonebuzz

If the user sends a file to GLPI and then tries to submit the form, 

The added element may be truncated (especially images) 

Nothing prevents the user from adding the element, even if the file has not been fully uploaded.

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !28447

2023-06-20 14:53 UTC, trasher approved these changes

2023-06-20 19:31 UTC, cedric-anne requested changes

2023-06-20 19:31 UTC, cedric-anne commented on src/Html.php
> +               $(this).closest('form').find('button:submit').prop('disabled', 'disabled');
1. Using `:submit` will also disable `<input type="submit" />` elements (can be used is specific forms).
2. `$().prop()` value parameter should be a boolean, according to documentation.
```suggestion
               $(this).closest('form').find(':submit').prop('disabled', true);
```

2023-06-20 19:31 UTC, cedric-anne commented on src/Html.php
> +               $(this).closest('form').find('button:submit').prop('disabled', '');
```suggestion
               $(this).closest('form').find(':submit').prop('disabled', false);
```

2023-06-20 19:31 UTC, cedric-anne commented on src/Html.php
> +                $(this).closest('form').find('button:submit').prop('disabled', '');
```suggestion
                $(this).closest('form').find(':submit').prop('disabled', false);
```

2023-06-20 19:31 UTC, cedric-anne commented on src/Html.php
> +                $(this).closest('form').find('button:submit').prop('disabled', '');
```suggestion
                $(this).closest('form').find(':submit').prop('disabled', false);
```

2023-06-21 06:42 UTC, cedric-anne approved these changes

2023-06-21 06:57 UTC, merged