Fix "read" right for reservations
glpi-project/glpi pull request #14978
Opened 2023-06-21 14:22 UTC by ccailly

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !28443

Added the ability to view reservations with the `READ` right.
Until now, the `ReservationItem::RESERVEANITEM` right was required to display reservations.
The `READ` right was already present but had no effect.

2023-06-22 08:54 UTC, AdrienClairembault requested changes

2023-06-22 08:54 UTC, AdrienClairembault commented on js/reservations.js
>              selectable: true,
I think we can also disable `selectable` if the user can't add items.

```suggestion
            selectable: my.can_reserve,
```

2023-06-22 14:20 UTC, AdrienClairembault approved these changes

2023-06-22 14:28 UTC, orthagh approved these changes

2023-06-23 06:33 UTC, cedric-anne approved these changes

2023-06-23 06:34 UTC, merged