Add redirection if user lacks rights to view the page upon profile change
glpi-project/glpi pull request #14983
Opened 2023-06-22 08:05 UTC by ccailly

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

When a user changes their profile in GLPI, the current page is reloaded. However, the new active profile does not guarantee that the user has the necessary rights to view the page, which can result in a permissions error. This pull request aims to address this issue by redirecting the user to the homepage if they lack the required rights. If the user has the necessary rights, no changes are made.

2023-06-22 09:13 UTC, AdrienClairembault requested changes
I think you should put this call directly in `Html::displayRightError()`, to cover all possibles entry points (search for `displayRightError` and you will see that it can be called from other places that `Session::checkRight`).

2023-06-22 14:25 UTC, AdrienClairembault approved these changes

2023-06-22 14:29 UTC, orthagh approved these changes

2023-06-23 06:36 UTC, cedric-anne approved these changes

2023-06-23 06:37 UTC, merged