Ticket external ID
glpi-project/glpi pull request #15105
Opened 2023-07-04 10:24 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Add field to tickets meant for tracking the request/incident in an external system.

2023-07-04 12:07 UTC, trasher approved these changes

2023-07-05 12:34 UTC, orthagh requested changes

2023-07-05 12:34 UTC, orthagh commented on templates/components/itilobject/fields_panel.html.twig
> +            {{ fields.textField('externalid', item.fields['externalid'], __('External ID'), field_options) }}
maybe a condition here, as you don't change the schema for changes and problems (fields_pnal twig file is shared between itilobjects)

2023-07-05 14:15 UTC, orthagh approved these changes

2023-07-06 11:29 UTC, cedric-anne commented on templates/components/itilobject/fields_panel.html.twig
> +            {% if item.getType() == 'Ticket' %}
```suggestion
            {% if item.isField('externalid') %}
```

2023-07-11 10:16 UTC, cedric-anne approved these changes

2023-07-17 06:42 UTC, merged