fix dashboard entity recursive param
glpi-project/glpi pull request #15139
Opened 2023-07-06 10:50 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #15137

2023-07-06 10:51 UTC, cedric-anne approved these changes

2023-07-06 11:13 UTC, trasher approved these changes

2023-07-06 11:23 UTC, cedric-anne reviewed
Maybe another solution is to use a unique `json_encode` on all params, to ensure that JS will not be malformed.

```php
$js_params = json_encode([
    'current' => $this->current,
    'cols'      => $this->cols,
    ...
    'is_recursive' => $_SESSION['glpiactive_entity_recursive'] ? 1 : 0
]);
$js = <<<JAVASCRIPT
    $(function () {
        new GLPIDashboard({$js_params});
      });
JAVASCRIPT;
```

2023-07-06 11:57 UTC, cconard96 commented
> Maybe another solution is to use a unique `json_encode` on all params, to ensure that JS will not be malformed.
> 
> ```
> $js_params = json_encode([
>     'current' => $this->current,
>     'cols'      => $this->cols,
>     ...
>     'is_recursive' => $_SESSION['glpiactive_entity_recursive'] ? 1 : 0
> ]);
> $js = <<<JAVASCRIPT
>     $(function () {
>         new GLPIDashboard({$js_params});
>       });
> JAVASCRIPT;
> ```

Doesn't seem possible without some other changes. A null token becomes "null" instead of just null.
Maybe its better to just move this to Twig in a separate PR and leave this as a quick/easy fix that people can apply.

2023-07-06 12:02 UTC, cconard96 commented
Done. I don't know if it broke it in some other cases though.

2023-07-06 12:21 UTC, cedric-anne requested changes

2023-07-06 12:21 UTC, cedric-anne commented on src/Dashboard/Grid.php
> +            'all_cards'     => $cards_json,
```suggestion
            'all_cards'     => $cards,
```

2023-07-06 12:21 UTC, cedric-anne commented on src/Dashboard/Grid.php
> +            'all_widgets'   => $all_widgets_json,
```suggestion
            'all_widgets'   => $all_widgets,
```

2023-07-07 06:04 UTC, cedric-anne approved these changes

2023-07-07 06:05 UTC, merged