fix(core): use non sensitive case to find user
glpi-project/glpi pull request #15178
Opened 2023-07-10 11:42 UTC by stonebuzz

To avoid misunderstandings and data entry errors,
 I suggest modifying the function to find users by their email address by performing a search using lower case letters.

From RFC 5321, section 2.3.11:

    The standard mailbox naming convention is defined to be "local-part@domain"; contemporary usage permits a much broader set of applications than simple "user names". Consequently, and due to a long history of problems when intermediate hosts have attempted to optimize transport by modifying them, the local-part MUST be interpreted and assigned semantics only by the host specified in the domain part of the address.

So yes, the part before the "@" could be case-sensitive, since it is entirely under the control of the host system. In practice though, no widely used mail systems distinguish different addresses based on case.

see : https://stackoverflow.com/questions/9807909/are-email-addresses-case-sensitive

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !28716

2023-07-10 11:55 UTC, cedric-anne requested changes

2023-07-10 11:55 UTC, cedric-anne commented on src/User.php
> +                        'LOWER(' . UserEmail::getTable() . '.email' . ')'  => strtolower($email)
Email addresses can contain unicode chars. We have to use a method that supports multi-byte strings.
```suggestion
                        'LOWER(' . UserEmail::getTable() . '.email' . ')'  => Toolbox::strtolower($email)
```

2023-07-10 19:07 UTC, trasher approved these changes

2023-07-11 06:47 UTC, cedric-anne approved these changes

2023-07-11 08:55 UTC, merged