expired session message
glpi-project/glpi pull request #15236
Opened 2023-07-17 14:13 UTC by Rom1-B

When the session expires and an action is attempted, the error message was too generic.

Before:
![image](https://github.com/glpi-project/glpi/assets/8530352/5bbd5562-56f8-4c11-9cb2-6c17c5d51380)

After:
![image](https://github.com/glpi-project/glpi/assets/8530352/d27a48ea-756e-4e26-ab19-55b974cc10c0)

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !28748

2023-07-17 14:45 UTC, cedric-anne requested changes

2023-07-17 14:45 UTC, cedric-anne commented on src/Session.php
> +            $message .= sprintf(__("<a href='%s'>Click here</a> to go back to the previous page."), $link);
Translations must not contain HTML tags. You have to handle it in a different way.

Also, maybe this link should always be present, even if session has not expired.

2023-07-18 12:57 UTC, cedric-anne requested changes

2023-07-18 13:22 UTC, cedric-anne commented on src/Session.php
> +            isset($_SESSION['glpicsrftokens'][$requestToken])
According to `Session::validateCSRF()`, `$data['_glpi_csrf_token']` may be missing.
```suggestion
        if (
            ($requestToken = $data['_glpi_csrf_token'] ?? null) !== null
            && isset($_SESSION['glpicsrftokens'][$requestToken])
```

2023-07-18 14:44 UTC, cedric-anne approved these changes

2023-07-19 06:41 UTC, orthagh approved these changes

2023-07-19 06:46 UTC, merged