show skip remaining rules only when multiple rules can run
glpi-project/glpi pull request #15253
Opened 2023-07-19 14:16 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #15252

2023-07-20 11:44 UTC, cedric-anne requested changes

2023-07-20 11:44 UTC, cedric-anne commented on src/Rule.php
> +        if (class_exists($collection_class)) {
A rule should always be attached to a collection class. I guess the `getCollectionClassName` method returns inconsistent result for `LevelAgreementLevel`.
As `LevelAgreementLevel` extends `RuleTicket`, the corresponding collection should probably be `RuleTicketCollection`, that uses the default `false` value for its `stop_on_first_match` property, and so the `_stop_rules_processing` should be available.

IMHO, the `getCollectionClassName()` should probably be changed to loop on `get_parent_class()` until it found an existing class that extends `RuleCollection`.

2023-07-24 08:50 UTC, cedric-anne approved these changes

2023-07-25 10:32 UTC, orthagh approved these changes

2023-07-25 10:34 UTC, merged