Prevent last super admin profile from changing interface
glpi-project/glpi pull request #15288
Opened 2023-07-27 07:35 UTC by ccailly

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

It is possible for a user to switch all his "super-admin" profiles to a simplified interface, with the effect of losing the ability to modify the other profiles.
To prevent this, the "Profile's interface" field is set to "read-only" if the profile is the last "super-admin" profile.

2023-07-27 08:50 UTC, AdrienClairembault requested changes
The new code work as expected however I've noticed that the existing function `isLastSuperAdminProfile` is flawed because it does not take the interface into account.

So if a profile has the rights to edit others profiles but is switched to the simplified interface, it still count as a super admin (it shouldn't).

Can you fix this too ?

2023-07-27 13:02 UTC, cedric-anne commented on src/Profile.php
> +            unset($input['interface']);
Maybe a `Session::addMessageAfterRedirect()` call could be added here.

2023-08-01 06:52 UTC, cedric-anne approved these changes

2023-08-01 10:12 UTC, cconard96 approved these changes

2023-08-01 11:21 UTC, merged