Move some Config tabs to Twig (part 1)
glpi-project/glpi pull request #15369
Opened 2023-08-05 14:55 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

2023-08-11 13:31 UTC, cedric-anne approved these changes
Usage of `showXXX` methods to generate HTML outside Twig template and usage of the `call` Twig function should be avoided as possible, but it can be done in future PRs.

2023-08-23 13:43 UTC, orthagh requested changes

2023-08-23 13:43 UTC, orthagh commented on templates/pages/setup/general/api_setup.html.twig
> +      ) }}
```suggestion
      ) }}
      {{ fields.nullField() }}
```
This to add an empty col fields and align url fields (with above paragraph)

2023-08-28 14:39 UTC, cconard96 commented on templates/pages/setup/general/assets_setup.html.twig
> +{% endblock %}
Not related to this PR. That section is missing in the main branch. It was changed to be per-entity settings in #14562.

2023-09-01 08:07 UTC, orthagh commented on templates/pages/setup/general/assets_setup.html.twig
> +{% endblock %}
good point

2023-09-01 08:09 UTC, orthagh approved these changes

2023-09-01 08:14 UTC, orthagh commented
Fix lint please and we can merge

2023-09-02 05:46 UTC, merged