Export printer graph data
glpi-project/glpi pull request #15376
Opened 2023-08-07 14:54 UTC by ccailly

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !28627

Adds the ability to export printer consumption data from the graph. The export is done in CSV format, taking into account the chart parameters: interval and format.

![image](https://github.com/glpi-project/glpi/assets/42278610/cfe7c10c-663d-4146-b571-366126eaafaf)
![image](https://github.com/glpi-project/glpi/assets/42278610/8a57f4e5-c62e-467b-a741-546340eca63e)

2023-08-08 12:17 UTC, AdrienClairembault approved these changes

2023-08-08 12:28 UTC, cedric-anne requested changes

2023-08-08 12:28 UTC, cedric-anne commented on src/Csv/PrinterLogCsvExport.php
> +        return "{$this->printer->fields['name']}.csv";
The `name` field may be empty. A fallback filename, for instance based on printer ID, should be used in this case.

```suggestion
        return !empty($this->printer->fields['name'])
            ? "{$this->printer->fields['name']}.csv"
            : "printer_{$this->printer->getID()}.csv";
```

2023-08-08 12:28 UTC, cedric-anne commented on src/PrinterLog.php
> +            'export_url' => 'printerlogcsv.php?' . Toolbox::append_params([
```suggestion
            'export_url' => '/front/printerlogcsv.php?' . Toolbox::append_params([
```

2023-08-08 12:28 UTC, cedric-anne commented on templates/components/printer_graph_buttons.html.twig
> +    <a href="{{ export_url }}" target="_blank" class="btn btn-sm btn-icon btn-ghost-secondary me-0 me-sm-1 px-2" data-bs-toggle="tooltip" data-bs-placement="bottom" title="{{ __('Export data in CSV')
```suggestion
    <a href="{{ path(export_url) }}" target="_blank" class="btn btn-sm btn-icon btn-ghost-secondary me-0 me-sm-1 px-2" data-bs-toggle="tooltip" data-bs-placement="bottom" title="{{ __('Export data in CSV') }}">
```

2023-08-08 12:54 UTC, cedric-anne approved these changes

2023-08-08 13:55 UTC, trasher approved these changes

2023-08-21 08:56 UTC, orthagh approved these changes

2023-08-22 11:58 UTC, merged