migrate notifications ui to twig
glpi-project/glpi pull request #15375
Opened 2023-08-07 00:36 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

2023-08-24 12:45 UTC, orthagh approved these changes
Seems ok.
Checking each impacted page, everything seems ok and no UI regressions

2023-09-18 08:04 UTC, cedric-anne requested changes

2023-09-18 08:04 UTC, cedric-anne commented on templates/pages/setup/notification/translation_debug.html.twig
> +      {{ fields.dropdownField(
There was a onchange script on this field.

2023-09-18 15:08 UTC, cedric-anne approved these changes

2023-09-18 15:08 UTC, merged