Move some Config tabs to Twig (part 3)
glpi-project/glpi pull request #15372
Opened 2023-08-06 11:24 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

2023-08-24 07:37 UTC, orthagh requested changes

2023-08-24 07:37 UTC, orthagh commented on templates/pages/setup/general/performance.html.twig
Every `<th>` in this page should be `<td>` or if you want to keep the semantic tag, at least we should remove the font-weight on sub rows. It's almost unreadable currently

currently: 
![image](https://github.com/glpi-project/glpi/assets/418844/10ff3901-c153-49d0-a2e2-0e409ca5d367)

If i move all th to td:
![image](https://github.com/glpi-project/glpi/assets/418844/b0b8df51-ce86-4133-9abb-4efaebfadfbf)

2023-08-24 07:37 UTC, orthagh commented on templates/pages/setup/general/performance.html.twig
> +{{ fields.largeTitle(__('Performance'), 'ti ti-dashboard') }}
```suggestion
```

If it's the only main section, it's not required

2023-09-01 08:44 UTC, orthagh requested changes
Some easy wins for performance tab and ok/failed icons:

Enhance readability:
- declare twig macros to display a failed or icon with a message parameter
- maybe one generic can be named like `icon_message()` and two specifics `success_icon_message` and `warning_icon_message` calling the first.

Enhance UX:
- add  `data-bs-toggle="tooltip"` to have a good render of the message on hover
- add bootstrap `.table-active` class to each tr with a section title

2023-09-04 07:31 UTC, orthagh approved these changes

2023-09-18 09:22 UTC, cedric-anne requested changes

2023-09-18 09:22 UTC, cedric-anne commented on templates/pages/setup/general/performance.html.twig
> +         <th class="fw-normal">{{ __('You can use "php bin/console cache:configure" command to configure cache system.') }}</th>
We should prevent translators to be able to alter the command line.
```suggestion
         <th class="fw-normal">{{ __('You can use "%s" command to configure cache system.')|format('php bin/console cache:configure') }}</th>
```

2023-09-18 09:22 UTC, cedric-anne commented on templates/pages/setup/general/logs_setup.html.twig
> +      on_change: 'form_init_all(this.value)'
I do not see where `form_init_all` is declared.

2023-09-18 09:22 UTC, cedric-anne commented on templates/pages/setup/general/logs_setup.html.twig
> +   {{ _self.log_interval_dropdown('purge_restoreitem', __('Add/update relation between items'), config, logs_interval_options) }}
```suggestion
   {{ _self.log_interval_dropdown('purge_restoreitem', __('Restore the item'), config, logs_interval_options) }}
```

2023-09-18 09:22 UTC, cedric-anne commented on templates/pages/setup/general/logs_setup.html.twig
> +   {{ _self.log_interval_dropdown('purge_updateitem', __('Restore the item'), config, logs_interval_options) }}
```suggestion
   {{ _self.log_interval_dropdown('purge_updateitem', __('Update the item'), config, logs_interval_options) }}
```

2023-09-18 15:09 UTC, merged