fix(user): authorization cloning
glpi-project/glpi pull request #15384
Opened 2023-08-09 09:25 UTC by Rom1-B

When cloning a user, the new user's authorization entities did not match the original one.

Original user:
![image](https://github.com/glpi-project/glpi/assets/8530352/bbb09d8b-9c6b-4f8f-adff-f8863ece04f9)

Clone before:
![image](https://github.com/glpi-project/glpi/assets/8530352/2d84834d-c416-4cc3-90c2-9ef6496786b7)

Clone after:
![image](https://github.com/glpi-project/glpi/assets/8530352/878d6af4-5ef5-406f-8d32-9f3eaa06c38f)

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

2023-08-09 09:36 UTC, cedric-anne requested changes

2023-08-09 09:36 UTC, cedric-anne commented on src/Features/Clonable.php
> +            if ($classname !== 'Profile_User') {
It seems that there is a static property for this (used only for `Profile_User`).
```suggestion
            if ($classname::$disableAutoEntityForwarding !== false) {
```

2023-08-09 09:42 UTC, cedric-anne approved these changes

2023-08-09 12:43 UTC, trasher requested changes
Please add a test case

2023-08-09 14:50 UTC, cedric-anne approved these changes

2023-08-10 06:06 UTC, trasher approved these changes

2023-08-10 06:06 UTC, merged