Fix multiple validation with uploaded files
glpi-project/glpi pull request #15386
Opened 2023-08-09 11:20 UTC by AdrienClairembault

When submitting a validation request with an attached file to multiple users, only the first user will receive the file.

![image](https://github.com/glpi-project/glpi/assets/42734840/2c79c475-569a-416e-84a2-71ff6a30520a)

![image](https://github.com/glpi-project/glpi/assets/42734840/30fd1937-9896-4c62-88fc-65af82cbb8bf)

This is due to how we handle files: once an uploaded file is saved it is removed from the tmp file directory, so the first validation request will delete the file after using it and the others validation requests wont be able to find it.

To fix this, I've essentially duplicated the submitted files for each validation request so they can be treated independently from each others.

After fix, the document are handled as expected:

![image](https://github.com/glpi-project/glpi/assets/42734840/387f87c4-9585-4632-bc1c-97be6527a5e6)

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !29064

2023-08-09 11:21 UTC, AdrienClairembault commented
Looking to validate that the proposed solution is acceptable before adding some testing (if possible).

2023-08-09 11:31 UTC, cedric-anne requested changes
As the `CronTask::cronTemp()` automatic action regularly cleans the temp directory, maybe it would be simplier to use `copy` instead of `rename` when a new documents is created from an uploaded file.

2023-08-09 11:31 UTC, cedric-anne commented on src/Toolbox/DuplicatedFileUpload.php
> +                copy(
You should trigger a `E_USER_WARNING` if `copy` returns false.

2023-08-09 11:58 UTC, cedric-anne approved these changes

2023-08-09 12:02 UTC, AdrienClairembault commented
Impact will be one hour of uploaded documents in the tmp dir, could it negatively impact some installations with limited disk space ?

2023-08-09 12:29 UTC, cedric-anne commented
> Impact will be one hour of uploaded documents in the tmp dir, could it negatively impact some installations with limited disk space ?

I do not think it will be a problem, unless there are many many many users that are uploading files very often. Administrator will be able to trigger the cron task every 5 minutes, or to limit uploaded documents size.

2023-08-09 14:04 UTC, trasher approved these changes

2023-08-21 09:12 UTC, orthagh approved these changes

2023-08-25 07:02 UTC, merged