fix(dashboard): tab is displayed without right
glpi-project/glpi pull request #15425
Opened 2023-08-18 12:44 UTC by Rom1-B

On the home page, the dashboard tab could be displayed even if the profile had no rights.

Rights:
![image](https://github.com/glpi-project/glpi/assets/8530352/79ebe8c2-f3ec-4464-b2b5-29a3e7ec0e21)

Before:
![image](https://github.com/glpi-project/glpi/assets/8530352/4651ea49-83b0-4252-bdde-077c308692c1)

After:
![image](https://github.com/glpi-project/glpi/assets/8530352/69184256-d45e-4354-a235-0711c3c4b04e)

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !29195

2023-08-25 08:38 UTC, trasher commented
I have no idea if fix is correct or not :'(

2023-08-31 08:12 UTC, orthagh requested changes
This seems strange as fix indeed.

Within this function, a call of loadAllDashboards function should check for each dashboard if we can view it, and load it in the property.
Also, plugin can add dashboard context also, and limiting to 'core' seems wrong

2023-09-01 08:01 UTC, Rom1-B commented
I'm drafting this because I can no longer reproduce the case, as I did 2 weeks ago when the PR was created.

2023-09-04 07:48 UTC, cedric-anne commented
Maybe this entry is visible when a user that has no "global" access to dashboards can still have access to some dashboards, for instance its own private dashboards, or a dashboard that someone shared to him.

2023-09-15 13:57 UTC, cedric-anne commented
@Rom1-B Is this PR still valid?

2023-09-15 13:58 UTC, closed without merging