feat(reservation): comment display
glpi-project/glpi pull request #15456
Opened 2023-08-25 13:12 UTC by Rom1-B

Display the comment entered here in the booking form:

![image](https://github.com/glpi-project/glpi/assets/8530352/9575c795-278d-4497-b892-71f154a4a662)

![image](https://github.com/glpi-project/glpi/assets/8530352/b528c14f-b637-4a4c-8a41-63786806b98c)

+ richtext activation

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !28083

2023-09-11 12:57 UTC, cedric-anne requested changes
The reservation form is broken. I have error when I try to submit it, and reservation is not created.

```
[2023-09-11 12:54:03] glpiphplog.NOTICE: Dropdown::getDropdownUsers() in /var/www/glpi/src/Dropdown.php line 3999
Unable to decode JSON string! Is this really JSON?  {"user":"2@8add3dfa14a3"} 
[2023-09-11 12:54:05] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "begin" in /var/www/glpi/front/reservation.form.php at line 99
  Backtrace :
  public/index.php:82                                require()
  
[2023-09-11 12:54:05] glpiphplog.NOTICE:   *** PHP Deprecated function (8192): explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/glpi/front/reservation.form.php at line 99
  Backtrace :
  front/reservation.form.php:99                      explode()
  public/index.php:82                                require()
  
[2023-09-11 12:54:05] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key 1 in /var/www/glpi/front/reservation.form.php at line 99
  Backtrace :
  public/index.php:82                                require()
```

2023-09-12 09:53 UTC, Rom1-B commented
I've corrected the errors in the logs.
There's still the purge button that does nothing in the modal, but it works outside.

2023-09-15 13:21 UTC, cedric-anne requested changes

2023-09-15 13:21 UTC, cedric-anne commented on templates/components/form/reservation.html.twig
> +    ) }}
1. On new item creation, value should fallback to current connected user (code was `$uid = (empty($ID) ? Session::getLoginUserID() : $resa->fields['users_id']);`).
2. Field should be readonly in user has no right to update the reservation (there was a condition on `!Session::haveRight("reservation", UPDATE) || !Session::haveAccessToEntity($entities_id)`).

2023-09-15 13:21 UTC, cedric-anne commented on src/ReservationItem.php
> +            $this->initForm($ID, $options);
This page is really hard to find (not your fault).

Display should be reworked. Previous state lacked polish, but it's worse now.

Previous state:
![image](https://github.com/glpi-project/glpi/assets/33253653/64416888-8a40-47d1-b38d-ba1cbd35ae32)

Now:
![image](https://github.com/glpi-project/glpi/assets/33253653/b4f88252-1cce-4793-bc53-0060aab689e3)

2023-09-18 10:13 UTC, cedric-anne approved these changes

2023-10-20 09:12 UTC, merged