fix(translation): richtext
glpi-project/glpi pull request #15477
Opened 2023-08-31 14:10 UTC by Rom1-B

Content translation didn't support richtext.

Before:
![image](https://github.com/glpi-project/glpi/assets/8530352/1d8b1619-8c84-4403-9bea-d58740905ee9)

After:
![image](https://github.com/glpi-project/glpi/assets/8530352/17b33eed-b2d0-4946-b8ec-323bac193128)

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !29299

2023-09-04 07:55 UTC, cedric-anne requested changes

2023-09-04 07:55 UTC, cedric-anne commented on ajax/updateTranslationValue.php
> +if (isset($_POST['field']) && $_POST['field'] == 'content') {
This check should rely on `type => 'tinymce'` declared in `getAdditionalFields()`.

2023-09-04 07:55 UTC, cedric-anne commented on src/DropdownTranslation.php
> +            if ($this->fields['field'] == 'content') {
Same remark here.

2023-09-05 14:14 UTC, cedric-anne approved these changes

2023-09-05 14:17 UTC, orthagh approved these changes

2023-09-05 14:24 UTC, stonebuzz approved these changes

2023-09-05 14:26 UTC, trasher approved these changes

2023-09-05 14:59 UTC, merged