feat(ITILTask): add state icon
glpi-project/glpi pull request #15558
Opened 2023-09-12 07:16 UTC by stonebuzz

Add task state icon

![image](https://github.com/glpi-project/glpi/assets/7335054/37b3199f-6bee-4465-9e13-0d756f98d118)

![image](https://github.com/glpi-project/glpi/assets/7335054/595bc197-7be1-408c-8205-793f0744ca8a)

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !28658

2023-09-12 07:28 UTC, cedric-anne requested changes

2023-09-12 07:28 UTC, cedric-anne commented on src/Planning.php
> +        $label = Planning::getState($status);
To prevent issues if the label contains quotes
```suggestion
        $label = htmlspecialchars(Planning::getState($status), ENT_QUOTES);
```

2023-09-12 08:14 UTC, cedric-anne commented on src/Planning.php
> +        }
```suggestion
        }
        return '';
```

2023-09-12 08:14 UTC, cedric-anne commented on src/Planning.php
> +    public static function getStatusColor($status)
```suggestion
    public static function getStatusColor($status): string
```

2023-09-12 08:15 UTC, cedric-anne approved these changes

2023-09-12 13:25 UTC, orthagh commented on js/common.js
> +var templateTaskStatus = function(option) {
we use this part only one time.
Imo, an inline script is preferable (in `dropdownState` php function)

2023-09-12 14:18 UTC, orthagh approved these changes

2023-09-13 05:56 UTC, trasher approved these changes

2023-09-13 05:56 UTC, merged