fix(notifications): actor replacement
glpi-project/glpi pull request #15623
Opened 2023-09-22 08:43 UTC by Rom1-B

On a ticket, when an assigned group was replaced by another, the notification was sent to the deleted group, and in the message content the old group was displayed as still assigned.

This was because the notification was sent after the new group had been added to the database, but before the old group had been deleted.

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !29660

2023-09-22 09:18 UTC, cedric-anne requested changes
Same proposal was made in #14796, but it has side-effects on status computation (see comments).

2023-10-04 14:18 UTC, cedric-anne submitted a review, later dismissed

2023-10-24 13:05 UTC, orthagh commented
After irl discussion:

- shoult target main branch
- I guess 6 month after release, someone will want the inverse behavior, so:
 provide a new notification for deletion of actors (and copy the same recipients as the former)

2023-11-09 07:12 UTC, Rom1-B commented
If this PR targets `main`, i.e. 10.1.x, it doesn't correct the case on the current version.

In this case, how to fix it on `10.0/bugfixes`?

_I have 2 customers who have reported this problem on 10.0 : !29660 + !30331_

2023-12-29 09:23 UTC, Rom1-B commented
I still think that notifying the deleted actor as if he were still an active actor in the ticket is a bug and should be treated as `bugfixes`.

I would point out that with the 2nd commit, the status doesn't change, it's not temporarily in "in coming".

2025-03-24 08:35 UTC, stonebuzz commented
https://github.com/glpi-project/glpi/pull/15718

2025-04-09 07:59 UTC, cedric-anne requested changes

2025-04-09 07:59 UTC, cedric-anne commented on src/NotificationTargetCommonITILObject.php
> +            'del_assign_user'   => __('Deletion of a user in assignees'),
IMHO, we should add a `remove_xxx` event for all possible actor type (e.g. requester user, requester group, observer user, observer group, assigned user, assigned group and assigned suplier).

If we add this only for assigned users, I am pretty sure that someone will ask for the same feature for another actor type as soon as the feature will be released.

2025-04-09 07:59 UTC, cedric-anne commented on src/CommonITILActor.php
> +                && !isset($this->input['_do_not_compute_status'])
I am not sure this is related to this PR.

2025-04-14 07:24 UTC, Rom1-B commented on src/CommonITILActor.php
> +                && !isset($this->input['_do_not_compute_status'])
This prevents the ticket status from changing temporarily to new during the short period when there are no technicians, between deletion and addition.

2026-08-20 13:51 UTC, cedric-anne approved these changes

2026-08-20 13:51 UTC, merged