fix(ui): fix long content overflox
glpi-project/glpi pull request #15640
Opened 2023-09-27 07:56 UTC by stonebuzz

fix long content overflox

Before : 
![image](https://github.com/glpi-project/glpi/assets/7335054/1248c63d-a3a3-482b-8e6a-cb594dac4478)

After : 
![image](https://github.com/glpi-project/glpi/assets/7335054/d5f13f54-2a5b-4089-a062-346ef8f357dc)

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !29702

2023-09-27 07:59 UTC, cedric-anne approved these changes

2023-09-27 08:01 UTC, orthagh reviewed
I'm not sure I want a vertical scroll in timeline contents.
Can this be managed by a **soft** (no break words) breaking of white spaces

2023-09-27 08:17 UTC, stonebuzz commented
> I'm not sure I want a vertical scroll in timeline contents.
Can this be managed by a soft (no break words) breaking of white spaces

Here, only horizontal scroll is available / enable

![image](https://github.com/glpi-project/glpi/assets/7335054/15126733-3f5d-466e-8af1-5cebb2ef7d11)

2023-09-27 09:08 UTC, stonebuzz commented
![image](https://github.com/glpi-project/glpi/assets/7335054/805c7bf2-2a54-436c-b810-ec339cc17164)

2023-10-02 09:53 UTC, orthagh approved these changes

2023-10-02 10:17 UTC, cedric-anne approved these changes

2023-10-02 10:18 UTC, cedric-anne commented on css/includes/components/_richtext.scss
> +        max-width: 780px;
Maybe this value should be inherited, to be adapted for each context.

2023-10-02 10:18 UTC, cedric-anne requested changes
See last comment.

2023-10-02 12:14 UTC, cedric-anne reviewed
On a Chrome browser, either previous proposal, either the current one are not working, at least on KB element.

HTML content:
```
<p>Test</p>
<p> </p>
<table style="border-collapse: collapse; width: 191.055%; height: 171px;" border="1"><colgroup><col style="width: 0.651448%;"><col style="width: 0.177668%;"><col style="width: 0.177668%;"><col style="width: 0.177668%;"><col style="width: 0.177668%;"><col style="width: 0.177668%;"><col style="width: 0.177668%;"><col style="width: 0.177668%;"><col style="width: 0.177668%;"><col style="width: 0.177668%;"><col style="width: 0.177668%;"><col style="width: 0.177668%;"><col style="width: 0.177668%;"><col style="width: 0.177668%;"><col style="width: 0.177668%;"><col style="width: 0.177668%;"><col style="width: 0.177668%;"><col style="width: 1.12523%;"><col style="width: 1.53979%;"><col style="width: 0.71067%;"><col style="width: 0.651448%;"><col style="width: 0.177668%;"><col style="width: 1.06601%;"><col style="width: 0.177668%;"><col style="width: 1.06601%;"><col style="width: 0.71067%;"><col style="width: 0.651448%;"><col style="width: 0.651448%;"><col style="width: 0.177668%;"><col style="width: 0.651448%;"><col style="width: 0.177668%;"><col style="width: 0.651448%;"><col style="width: 0.94756%;"><col style="width: 1.18445%;"><col style="width: 0.177668%;"><col style="width: 1.53979%;"><col style="width: 0.177668%;"><col style="width: 0.71067%;"><col style="width: 0.651448%;"><col style="width: 1.18445%;"><col style="width: 1.00678%;"><col style="width: 0.177668%;"><col style="width: 0.651448%;"><col style="width: 1.18445%;"><col style="width: 1.00678%;"><col style="width: 0.651448%;"><col style="width: 0.177668%;"><col style="width: 0.47378%;"><col style="width: 0.177668%;"><col style="width: 0.177668%;"><col style="width: 1.00678%;"><col style="width: 0.651448%;"><col style="width: 0.47378%;"><col style="width: 0.177668%;"><col style="width: 0.177668%;"><col style="width: 15.1017%;"><col style="width: 18.2405%;"><col style="width: 18.2405%;"><col style="width: 19.6027%;"><col style="width: 0.71067%;"></colgroup>
<tbody>
<tr>
<td>a</td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td>b</td>
</tr>
<tr>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td>cv</td>
<td>xcv</td>
<td>b</td>
<td>v</td>
<td> </td>
<td>xc</td>
<td> </td>
<td>xc</td>
<td>b</td>
<td>x</td>
<td>v</td>
<td> </td>
<td>v</td>
<td> </td>
<td>v</td>
<td>b </td>
<td>vb</td>
<td> </td>
<td>xcv</td>
<td> </td>
<td>g</td>
<td>h</td>
<td>gh</td>
<td>df</td>
<td> </td>
<td>h</td>
<td>gh</td>
<td>df</td>
<td>h</td>
<td> </td>
<td>f</td>
<td> </td>
<td> </td>
<td>df</td>
<td>h</td>
<td>f</td>
<td> </td>
<td> </td>
<td>dfghdfghn dkfgh dfklghlmd fgjlhhhhhkkkkkkkkkkkkkkkkkkkkkkkkk</td>
<td>kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk</td>
<td>kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk</td>
<td>kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk</td>
<td> </td>
</tr>
</tbody>
</table>
```

![image](https://github.com/glpi-project/glpi/assets/33253653/dccfaa75-31cd-4ceb-9f3e-395c37f1e66b)

2023-10-02 12:17 UTC, cedric-anne commented
> On a Chrome browser, either previous proposal, either the current one are not working, at least on KB element.

Works on a followup.

2023-10-02 12:19 UTC, cedric-anne approved these changes
Fixes the timeline display, but not the KB one. I guess KB display will not be fixable as long as KB page layout in built on tables.

2023-10-02 12:23 UTC, cedric-anne requested changes

2023-10-02 12:23 UTC, cedric-anne commented on css/includes/components/_richtext.scss
> +        max-width: 100%;
See #13038. We should probably preserve the `word-break: normal;` property.
```suggestion
        max-width: 100%;
        word-break: normal;
```

2023-10-02 12:23 UTC, cedric-anne commented on css/includes/components/_richtext.scss
> +    width: 100%;
```suggestion
    width: 100%;

```

2023-10-02 12:53 UTC, stonebuzz commented
> On a Chrome browser, either previous proposal, either the current one are not working, at least on KB element.


I don't know if this has any impact, but your table contains size guidelines. 
with a large table
the rendering seems correct 

![image](https://github.com/glpi-project/glpi/assets/7335054/ac0735e1-d411-40cb-add4-0647c77caf0f)

2023-10-02 13:31 UTC, cedric-anne approved these changes

2023-10-02 13:31 UTC, merged

2023-11-08 10:51 UTC, AdrienClairembault commented
This change affect negatively new followups display:

![image](https://github.com/glpi-project/glpi/assets/42734840/bdc76c14-b87f-4e02-9f0d-9c47250b8672)

The content is too big and does not fit the container, there is now a horizontal scroll bar being displayed.