Update Rule.php
glpi-project/glpi pull request #15654
Opened 2023-09-29 08:57 UTC by Berthe01

Add search option to be able to filter rules by subtype using RestAPI.

I just don't know hopw to choose the ID of this searchOption :/

2023-09-29 09:17 UTC, stonebuzz commented
To determine ID you can you this

```shell
php tools/getsearchoptions.php --type=Rule
Array
(
    [1] => N/A / Nom
    [2] => N/A / ID
    [3] => N/A / Classement
    [4] => N/A / Description
    [5] => N/A / Opérateur logique
    [8] => N/A / Actif
    [16] => N/A / Commentaires
    [19] => N/A / Dernière modification
    [80] => N/A / Entité
    [86] => N/A / Sous-entités
    [121] => N/A / Date de création
)
```
```122``` can be used for this new ```searchoption```

2023-09-29 09:19 UTC, stonebuzz requested changes

2023-09-29 09:19 UTC, stonebuzz commented on src/Rule.php
> +            'id'                 => '1234', //Don't know how to determine this ID
```suggestion
            'id'                 => '122',
```

2023-09-29 09:19 UTC, trasher commented on src/Rule.php
> +            'id'                 => '1234', //Don't know how to determine this ID
```suggestion
            'id'                 => '122',
```

2023-09-29 09:20 UTC, trasher commented
I made the ID change so tests can be run

2023-10-02 09:39 UTC, cedric-anne approved these changes

2023-10-02 09:54 UTC, stonebuzz approved these changes

2023-10-02 12:47 UTC, trasher approved these changes

2023-10-02 12:47 UTC, merged