Fix Task Duration Update Behavior in CommonITILTask
glpi-project/glpi pull request #15852
Opened 2023-10-24 08:38 UTC by ccailly

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #15650

This Pull Request addresses an issue in the `CommonITILTask` class where the manually edited task duration was not replacing the planned duration. 

The changes in this PR ensure that the task duration and the planned duration are bi-directionally linked. This means that if the `actiontime` (task duration) is manually set, it will compute and update the end date accordingly. Conversely, if the `actiontime` is not set, it will compute it based on the difference between the start and end times.

This fix is crucial as it allows the actual time spent on a task to be accurately reflected, even if it differs from the initially planned duration. This behavior aligns with previous versions of the application, where the manually entered task duration would replace the planned duration.

2023-10-25 09:27 UTC, AdrienClairembault requested changes
Looks good to me 👍, work as expected.

Maybe we could move the code added in `prepareInputForUpdate` and `prepareInputForAdd` into a unique function to avoid duplication ?

2023-10-25 10:12 UTC, AdrienClairembault approved these changes

2023-10-30 16:17 UTC, cedric-anne commented on src/CommonITILTask.php
> +    public function handleTaskDuration(&$input, $timestart, $timeend)
If method is used only privately, please declare it as private (it ensure that we can change its signature without affecting plugins).

There is a `$this->callPrivateMethod($instance, $methodName, ...$args)` method that can be used in test suite to test private methods.

```suggestion
    private function handleTaskDuration(array &$input, int $timestart, int $timeend): void
```

2023-10-31 09:42 UTC, cedric-anne approved these changes

2023-10-31 10:06 UTC, orthagh approved these changes

2023-10-31 10:14 UTC, merged