Feat/search ux
glpi-project/glpi pull request #15861
Opened 2023-10-25 14:59 UTC by orthagh

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

![image](https://github.com/glpi-project/glpi/assets/418844/7e5e493a-de00-402e-9e94-31c3ba3ecb59)

2023-11-09 23:57 UTC, cconard96 commented
Here is a commit that fixes some JS conflicts after the search results are refreshed via AJAX and also fixes an issue where the criteria disappears after a search.
https://github.com/glpi-project/glpi/commit/69ab7d5b877ee9b27be9993adac549948688d9bd

2023-11-17 03:54 UTC, cconard96 commented
I made a few fixes on a fork of this PR:
https://github.com/cconard96/glpi/commits/feat/search_ux

The only remaining issue I noticed is when refreshing the results, the `ajax/search.php` endpoint occasionally responds with a JS script tag that would trigger a redirect to the saved search I selected last instead of the results data. This is considered an unexpected response by the Fluid Search JS, so it triggers a full page reload. After the reload, the previously selected saved search is showing in the button label even though I have custom criteria selected.

2023-11-20 14:41 UTC, orthagh commented
TODO:

- [ ] savedsearches split
- [ ] responsive (hide some labels)

2023-11-27 10:45 UTC, AdrienClairembault requested changes
1) The thrash bin toggle is lacking some padding and probably the same rounded borders that are used by the display type toggle:

![image](https://github.com/glpi-project/glpi/assets/42734840/9ee6fddc-577e-41fb-9609-859217f870b8)

2) You can also see in the previous image that the map toggle is missing when inside the thrash bin.

3) Didn't you also wanted to integrate the kanban here ? Maybe delayed to another PR ?

![image](https://github.com/glpi-project/glpi/assets/42734840/b36f3945-ab0b-4c23-8f4b-25d3584495b2)

4) The "filter" dropdown is not highlighted on my side compared to your screen shot.
Maybe it should have some hint of the primary color as it is an important action (more important than sorting IMO) ?

![image](https://github.com/glpi-project/glpi/assets/42734840/73ef3b48-7dd0-441f-9743-67c70c1c9980)

5) When using the map mode, the filter indicate that items are restricted on latitude and longitude but we can't see the associated criteria.

![image](https://github.com/glpi-project/glpi/assets/42734840/d807e3b5-0671-48d6-a2ff-585946144bdb)

Maybe it will confuse some users ? Maybe the lat and long criteria should be shown as readonly ?

6) After using massive actions the items remained checked when the page is reloaded but the "actions" button is not displayed.

![image](https://github.com/glpi-project/glpi/assets/42734840/4d804bb2-7b10-4f8a-bdf5-6d43a0739e18)

----

Otherwise I think it overall looks great, very clean 👍

2023-11-27 14:29 UTC, orthagh commented
- 1, 4 & 6 fixed
- 2 cannot replicate on my side
- 3 later

2023-11-27 15:14 UTC, orthagh commented
2 fixed

2023-11-27 15:15 UTC, AdrienClairembault approved these changes

2023-11-28 14:58 UTC, cconard96 requested changes

2023-11-28 14:58 UTC, cconard96 commented on src/Search.php
> +    public static function showGenericSort($itemtype, array $params)
Not sure these two methods need added here. `Search` only exists still for backwards-compatibility.

2023-11-28 14:58 UTC, cconard96 commented on src/Search.php
> +     * @since 9.4
Wrong version

2023-11-28 15:00 UTC, cconard96 commented on src/Search.php
> +    public static function showGenericSort($itemtype, array $params)
I think the warnings on `Glpi\Search\SearchEngine` and `Search` can be removed/ignored now too.

2023-11-29 07:52 UTC, trasher commented
Search seems OK, I had an issue with sorting. I've selected:
![image](https://github.com/glpi-project/glpi/assets/224733/4ebd866a-bed2-450c-a784-638bd84a3439)

And once I've applied sort, this is shown:
![image](https://github.com/glpi-project/glpi/assets/224733/fd713c7a-a59f-496e-b825-daf93047899c)


I can see following in logs:
```
[2023-11-29 07:51:49] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "" in /var/www/webapps/glpi/src/Search/Output/HTMLSearchOutput.php at line 167
  Backtrace :
  src/Search.php:350                                 Glpi\Search\Output\HTMLSearchOutput::displayData()
  ajax/search.php:90                                 Search::displayData()
  public/index.php:82                                require()
  
[2023-11-29 07:51:49] glpiphplog.WARNING:   *** PHP Warning (2): Trying to access array offset on value of type null in /var/www/webapps/glpi/src/Search/Output/HTMLSearchOutput.php at line 167
  Backtrace :
  src/Search.php:350                                 Glpi\Search\Output\HTMLSearchOutput::displayData()
  ajax/search.php:90                                 Search::displayData()
  public/index.php:82                                require()
```

2023-11-29 07:55 UTC, trasher commented
I guess this happens when I sort on a non displayed column

2023-11-29 08:24 UTC, AdrienClairembault commented
I guess it doesn't make sense to be able to sort multiple time on the same column: 

![image](https://github.com/glpi-project/glpi/assets/42734840/b0064ac9-e1e7-4caf-81b7-7746a7f47c7d)

2023-11-29 08:44 UTC, AdrienClairembault commented on js/modules/Search/Table.js
> +        });
FYI jQuery's `attr` method work on the whole collection, there is no need to iterate on each items.

Something like that would work for example:

```suggestion
        this.getElement().find('thead th').attr({
            'data-sort-num': null,
            'data-sort-order': 'nosort',
        });
```

2023-11-29 09:03 UTC, AdrienClairembault commented
> > I guess it doesn't make sense to be able to sort multiple time on the same column:
> 
> Right, but there's more in fact, I just think about it : but as we defer the sort from the selects to th, any options not present in table header will not be sorted.
> 
> @cconard96 I guess we need to track sorts/orders in a class property and both sources of sorting should alter them rather than forwarding to headers.

A temporary fix would be to allow only the displayed headers to be selectable in the sort list.

2023-11-29 15:43 UTC, orthagh commented
Sort/order issues should be fixed.
More, I added "used" management, adding a new sort row (from card panel), should now take into account previous sorted columns and not presented them

2023-11-29 16:04 UTC, cconard96 approved these changes

2023-11-30 15:13 UTC, trasher approved these changes

2023-12-14 14:48 UTC, cedric-anne approved these changes

2023-12-14 14:49 UTC, merged