Fix Duplicate Notification On Solve
glpi-project/glpi pull request #15878
Opened 2023-10-27 11:59 UTC by tsmr

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

When the user approve (with adding comment or not), 2 notifications are sended : One for Solve ticket : OK but another for adding Followup.

I had _disablenotif on add_close case for fix it

2023-10-27 12:25 UTC, cedric-anne requested changes
This kind of changes was already proposed, and I am not in favor of it.

First, targets may be different for both notifications, for instance, observers may receive only notifications for followps, but not for closing action.

Second, administrators may have configured notifications to have a really short content.
For instance:
 - notification when a followup is added: ``The following comment has been added to the ticket: {$followup_content}.``
 - notification when a ticket is closed: ``The ticket has been closed.``

If you just send the notification related to the ticket closure, people will not have the followup content in their notifications.

2023-10-27 13:52 UTC, tsmr commented
I understand your point of view.
However, in the case where you refuse the response on the resolution notification, and if the requester receives 2 notifications: one where he can respond and not the other, this may not be very confusing for him.

Maybe not notifying the person who approves the solution twice? if this is possible via another means?

2023-12-05 12:31 UTC, cedric-anne commented
> Maybe not notifying the person who approves the solution twice? if this is possible via another means?

I do not think we have a solution for this right now. Anyway, changing this behaviour on a bugfixes version is probably not a good idea. Maybe the slution is to send the notification related to the followup before updating the parent item status. If we do this, the followup notification will be received before the status update notification, and it would probably be better.

@orthagh What do you think of it?

2023-12-05 13:39 UTC, orthagh commented
agree

2024-03-25 10:36 UTC, orthagh commented
staled I guess. If you have time to work again on it (on main), please let us know.

2024-03-25 10:37 UTC, closed without merging