Add Waiting On Send Ticket Validation
glpi-project/glpi pull request #15880
Opened 2023-10-27 12:12 UTC by tsmr

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

Add waiting icon on ticket validation from

![image](https://github.com/glpi-project/glpi/assets/13178158/c31fdf52-bc93-41e2-a42a-c3e776d984aa)

2023-11-06 10:32 UTC, AdrienClairembault requested changes

2023-11-06 10:32 UTC, AdrienClairembault commented on src/CommonITILValidation.php
> +
I think you should be able to reuse what we are already doing for followup and tasks here in this method:

![image](https://github.com/glpi-project/glpi/assets/42734840/b9bc8fab-aa53-4ff5-8df2-35475419aec1)

(Don't forget to add the `use Glpi\Features\ParentStatus;` statement).

And you will also need to handle pending reason edition in the `post_updateItem` function, like this:

![image](https://github.com/glpi-project/glpi/assets/42734840/f69c6a8d-0923-4740-a253-56d735e13ea0)

2023-12-05 12:59 UTC, cedric-anne commented
@tsmr I changed target branch to main. We are trying to limit as much as functionnal changes to GLPI 10.0.

2024-03-25 10:35 UTC, orthagh commented
staled I guess. If you have time to work again on it, please let us know.

2024-03-25 10:35 UTC, closed without merging