fix(ticket): percentage of resolution time
glpi-project/glpi pull request #15948
Opened 2023-11-06 11:00 UTC by Rom1-B

Percentage of resolution time does not exclude waiting time. I think that the pending should freeze this evolution, so its value should be similar just before the pending and just after the exit of pending.

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !30259

2023-11-06 11:06 UTC, Rom1-B commented
As I don't have the rights to modify your PR, I've recreated another one https://github.com/glpi-project/glpi/pull/15948

2023-11-15 10:29 UTC, cedric-anne requested changes

2023-11-15 10:29 UTC, cedric-anne commented on src/Search.php
> +                            $waitingtime = $item->fields['sla_waiting_duration'];
The `$waitingtime` value should be 0 if there is no SLA defined. Also, the `sla_waiting_duration` is only related to the TTR SLA and should not have any impact on TTO and/or OLA. You should define this variable in the previous if/else blocks.
```php
if ($item->isField($slaField) && $item->fields[$slaField] != 0) { // Have SLA
    ...
    $waitingtime = $slaField === 'slas_id_ttr' ? $item->fields['sla_waiting_duration'] : 0;
    ... 
} else {
    ...
    $waitingtime = 0;
    ...
}
```

2023-11-15 10:44 UTC, cedric-anne approved these changes
Seems OK, but I would like to have the customer feedback.

2023-11-24 11:38 UTC, Rom1-B commented
> Seems OK, but I would like to have the customer feedback.

The customer has validated

2023-11-24 11:39 UTC, trasher approved these changes

2023-11-24 11:39 UTC, merged