Fix(Inventory): fix RuleImportAsset for Phone
glpi-project/glpi pull request #16011
Opened 2023-11-17 08:23 UTC by stonebuzz

I don't have a history of the changes made to this part, 
but the rules for importing and linking material that concerning ```Phones``` (which are deactivated by default) don't work at all.
As it stands, it's compulsory to adapt them, otherwise the devices are refused for import.

The default criteria do not seem consistent.

![image](https://github.com/glpi-project/glpi/assets/7335054/eb6a5e64-75df-4c0d-b1cf-595919e1b98b)

This PR corrects the XML resources for creating/resetting XML rules

Because we don't update the rules directly (despite the presence of the ```uuid``` now) -> too complicated

I simply duplicated the rules on the PCs and adapted them to the Phones.

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !30284

2023-11-17 09:13 UTC, trasher approved these changes

2023-11-17 09:48 UTC, Rom1-B commented
"Phone import denied" should be last?

![image](https://github.com/glpi-project/glpi/assets/8530352/b2b7d2b1-cbdf-4153-8c59-5cb04e7fd5bd)

In the "All" tab, the first "Phones" rules are mixed with those for "Computers".

![image](https://github.com/glpi-project/glpi/assets/8530352/8549ac53-b5b2-4717-a730-f8758c3da613)

2023-11-17 10:59 UTC, stonebuzz commented
Last commit fix rule rank and bad copy past

2023-11-17 11:04 UTC, Rom1-B approved these changes

2023-11-27 13:47 UTC, cedric-anne approved these changes

2023-11-27 13:48 UTC, cedric-anne commented
Please rebase to fix conflicts.

2023-11-27 14:22 UTC, cedric-anne requested changes
It seems that you have many duplicated rules in the XML file.

2023-11-27 14:43 UTC, cedric-anne commented on resources/Rules/RuleImportAsset.xml
> +        <ranking>38</ranking>
ranking 38 is after 62, it does not seems logical

2023-11-29 08:35 UTC, Rom1-B approved these changes

2023-11-29 10:51 UTC, cedric-anne approved these changes

2023-11-29 10:51 UTC, merged