Update current user rights during migration
glpi-project/glpi pull request #16031
Opened 2023-11-21 10:32 UTC by AdrienClairembault

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |

2023-11-27 10:24 UTC, cedric-anne commented on src/Migration.php
> +        // Update current user rights so he doesn't have to reload his session
```suggestion
        // Update current user rights so he doesn't have to reload his session.
        // This ensure rights created by plugin install/update migrations are applied immediately.
```

2023-11-27 10:24 UTC, cedric-anne commented on src/Migration.php
> +        if (!isCommandLine()) {
```suggestion
        if (Session::getLoginUserID() !== false) {
```

2023-11-27 10:33 UTC, cedric-anne approved these changes

2023-11-27 10:36 UTC, cedric-anne requested changes
Is it possible to also update the `updateRight` and the `addRightByInterface` methods ?

2023-11-29 10:22 UTC, AdrienClairembault commented
> Is it possible to also update the `updateRight` and the `addRightByInterface` methods ?

If the sessions has to be updated in multiple places, maybe it would be simpler to just reload the current session rights at the end of `Plugin->install()` ?

If I recall correctly, @flegastelois suggested a piece of code like `Session::changeProfile(curent_profile);` in our internal discussion which would do the trick.

2023-12-05 10:18 UTC, cedric-anne commented
> > Is it possible to also update the `updateRight` and the `addRightByInterface` methods ?
> 
> If the sessions has to be updated in multiple places, maybe it would be simpler to just reload the current session rights at the end of `Plugin->install()` ?
> 
> If I recall correctly, @flegastelois suggested a piece of code like `Session::changeProfile(curent_profile);` in our internal discussion which would do the trick.

You could then probably declare a new `Session::reloadCurrentProfile()` method to do this, but it may have an unexpected impact on the currently active entity.

2023-12-05 10:53 UTC, AdrienClairembault commented
Ok for this new method.

If we are unsure of the side effects then it should be moved to main as it is not a priority issue at all and can wait the 10.1 release.

2023-12-11 08:34 UTC, AdrienClairembault commented
Regarding this comment from another PR:

> A simple solution could be to store the date of the last rights changes in the config table and in each user session.
Then if a user load a page and his "date of last rights updates" does not match the one in GLPI's config, we force reload his menu + rights.

This would allow "real time" updates for any already logged in users.
Would this solution be acceptable ?

2023-12-13 13:31 UTC, cedric-anne commented
> Regarding this comment from another PR:
> 
> > A simple solution could be to store the date of the last rights changes in the config table and in each user session.
> > Then if a user load a page and his "date of last rights updates" does not match the one in GLPI's config, we force reload his menu + rights.
> 
> This would allow "real time" updates for any already logged in users. Would this solution be acceptable ?

Adding a date column on the glpi_profiles table would not cost much, and the check/refresh could probably be done in `Session::checkValidSessionId()` https://github.com/glpi-project/glpi/blob/7d5ad9eb12eb0508c3924bd2a2c4d403d43893e7/src/Session.php#L928

The current requests that checks if profile is still attach to user could probably be replaced by a request that check if profile is still attached and/or has change, and then reload rights if it is necessary.

2023-12-13 13:32 UTC, cedric-anne commented
> Would this solution be acceptable ?

See my previous comment.

Anyway, it would not be acceptable on bugfixes branch.

2023-12-14 08:42 UTC, AdrienClairembault commented
> Anyway, it would not be acceptable on bugfixes branch.

Of course.

I'll close this one then since it would no longer be relevant with this new suggested solution.

2023-12-14 08:42 UTC, closed without merging