Fix change status after refused solution
glpi-project/glpi pull request #16044
Opened 2023-11-23 10:00 UTC by Lainow

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #15700

The status Applied for objects of type Change was not defined in the list of statuses allowing the reopening of a CommonITILObject, which prevented GLPI from updating its status, which therefore remained Applied (SOLVED).

2023-11-23 10:32 UTC, trasher commented
please add tests

2023-11-24 07:46 UTC, stonebuzz requested changes

2023-11-24 07:46 UTC, stonebuzz commented on tests/functional/Change.php
> +    public function testValidationStatus()
```suggestion
    public function testStatusWhenSolutionIsRefused()
```

2023-11-24 08:04 UTC, trasher approved these changes

2023-11-27 07:32 UTC, cedric-anne approved these changes

2023-11-27 07:33 UTC, merged