fix(email notification): html entity decode
glpi-project/glpi pull request #16046
Opened 2023-11-23 13:54 UTC by Rom1-B

The `&` in the notification settings was displayed as `&#38;` in received mails.

![image](https://github.com/glpi-project/glpi/assets/8530352/62666069-00e7-4b72-8c93-f135686ef7f1)

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !30570

2023-11-25 14:49 UTC, cconard96 approved these changes

2023-11-27 07:13 UTC, cedric-anne requested changes
When a previously sanitized content must be "unsanitized", it is preferable to use the corresponding `Sanitizer` methods.

2023-11-27 07:13 UTC, cedric-anne commented on src/MailCollector.php
> +        $mmail->SetFrom($CFG_GLPI["admin_email"], html_entity_decode($CFG_GLPI["admin_email_name"]));
```suggestion
        $mmail->SetFrom($CFG_GLPI["admin_email"], Sanitizer::decodeHtmlSpecialChars($CFG_GLPI["admin_email_name"]));
```

2023-11-27 07:13 UTC, cedric-anne commented on src/MailCollector.php
> +                         "\n-- \n" . html_entity_decode($CFG_GLPI["mailing_signature"]);
```suggestion
                         "\n-- \n" . Sanitizer::decodeHtmlSpecialChars($CFG_GLPI["mailing_signature"]);
```

2023-11-27 07:13 UTC, cedric-anne commented on src/NotificationEventMailing.php
> +                $mmail->SetFrom($current->fields['sender'], html_entity_decode($current->fields['sendername']));
```suggestion
                $mmail->SetFrom($current->fields['sender'], Sanitizer::decodeHtmlSpecialChars($current->fields['sendername']));
```

2023-11-27 07:13 UTC, cedric-anne commented on src/NotificationEventMailing.php
> +                    $mmail->AddReplyTo($current->fields['replyto'], html_entity_decode($current->fields['replytoname']));
```suggestion
                    $mmail->AddReplyTo($current->fields['replyto'], Sanitizer::decodeHtmlSpecialChars($current->fields['replytoname']));
```

2023-11-27 07:13 UTC, cedric-anne commented on src/NotificationEventMailing.php
> +                $mmail->AddAddress($recipient, html_entity_decode($current->fields['recipientname']));
```suggestion
                $mmail->AddAddress($recipient, Sanitizer::decodeHtmlSpecialChars($current->fields['recipientname']));
```

2023-11-27 07:13 UTC, cedric-anne commented on src/NotificationMailing.php
> +        $mmail->SetFrom($sender['email'], html_entity_decode($sender['name'] ?? ''), false);
```suggestion
        $mmail->SetFrom($sender['email'], Sanitizer::decodeHtmlSpecialChars($sender['name'] ?? ''), false);
```

2023-11-27 07:13 UTC, cedric-anne commented on src/NotificationMailing.php
> +        $text = __('This is a test email.') . "\n-- \n" . html_entity_decode($CFG_GLPI["mailing_signature"]);
```suggestion
        $text = __('This is a test email.') . "\n-- \n" . Sanitizer::decodeHtmlSpecialChars($CFG_GLPI["mailing_signature"]);
```

2023-11-27 07:13 UTC, cedric-anne commented on src/NotificationMailing.php
> +        $mmail->AddAddress($recipient, html_entity_decode($CFG_GLPI["admin_email_name"]));
```suggestion
        $mmail->AddAddress($recipient, Sanitizer::decodeHtmlSpecialChars($CFG_GLPI["admin_email_name"]));
```

2023-11-27 08:27 UTC, cedric-anne approved these changes

2023-11-27 08:28 UTC, merged