Monaco editors for webhook url and headers
glpi-project/glpi pull request #16061
Opened 2023-11-25 02:06 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

Currently, the URL, custom headers, and payload are all processed as twig templates. However, only the payload editor was actually using Monaco. The custom header value inputs were using a basic autocomplete which didn't make sense if you wanted more than just a single item property on its own. The URL field didn't have any autocomplete, so it wasn't obvious that it could accept twig tags.

This PR adds:
1. A helper function that returns a set of editor options that lets you configure an editor to mimic a `text` input with a single line.
2. A workaround for the global registration of completion items per language which makes having multiple editors a pain. This workaround involves registering a copy of the requested language per-editor which allows each editor to then have its own set of completions.
3. URL and custom header value inputs replaced with single-line Monaco editors. A `formdata` event listener is used in the forms to inject the Monaco editor values into the form data during submission.

This PR also includes a fix for the `wrapper_class` option in the `htmlField` macro.

2023-11-27 09:04 UTC, orthagh requested changes
A few issues I found:
- [Enter] key doesn't validate the completion. In payload it works correctly.
- Style is not correct in dark mode: 
![image](https://github.com/glpi-project/glpi/assets/418844/8d6a031f-bcb9-4f11-800a-24d91cda8a5b)
  Strangely, it's ok in payload editor

2023-11-30 08:07 UTC, orthagh approved these changes

2023-12-05 07:47 UTC, cedric-anne commented on templates/pages/setup/webhook/webhook_headers.html.twig
> +                  //header_value_field.prop('readonly', true);
```suggestion
```

2023-12-05 07:47 UTC, cedric-anne commented on templates/pages/setup/webhook/webhook_headers.html.twig
> +              //const header_value_field = template.find('input[name="header_value[]"]');
```suggestion
```

2023-12-05 08:24 UTC, cedric-anne approved these changes

2023-12-05 08:24 UTC, merged