feat(search-option): add ticket age search option
glpi-project/glpi pull request #16068
Opened 2023-11-27 13:27 UTC by ccailly

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 

## Description

This PR introduces a new 'Age' search option for tickets. This option is not usable for searching but only displayable in the results. The 'Age' is calculated as the time difference between the ticket's date and the current time. If a calendar is associated with the ticket, it calculates the active time between the ticket's date and the current time.

## Changes

- Added 'Age' search option to tickets.
- Updated `getSpecificValueToDisplay` method to handle the new 'Age' field.
- Added `ageSearchOptionDataProvider` method to provide data for testing the 'Age' option.
- Added `testAgeSearchOption` method to test the 'Age' option.

2023-11-29 09:24 UTC, AdrienClairembault requested changes
Looks good, just two remarks that are up for discussion :

1\) "Age" was the name of the label used in the original specific patch of the client but I don't really like it. Maybe something like "Processing time" instead ? 

2\) I am not sure we should display the amount in days:

![image](https://github.com/glpi-project/glpi/assets/42734840/68c2f194-5051-4a11-ab50-24cef49ee688)

Since the time are computed base on a calendar where a day might only be 8 hours, it feels weird to show the total divided by 24 hours days.
I would suggest keeping only hours and minutes.

What are your thoughts on these two points @orthagh ?

2023-11-29 09:45 UTC, orthagh commented
> "Processing time"

"Time since opening"

> amount in days

Since we present the delay with the calendar involved, I guess it's ok like done currently

2023-11-29 12:45 UTC, orthagh approved these changes

2023-12-05 15:24 UTC, AdrienClairembault commented on src/Ticket.php
> +                return sprintf(__('%s days %s hours %s minutes'), floor($time / 86400), floor(($time % 86400) / 3600), floor(($time % 3600) / 60));
I've made the same remark but @orthagh said it was fine with this format.
I agree that I would prefer without the days.

2023-12-05 15:25 UTC, AdrienClairembault requested changes
Can you not display the days from the results (if OK for @orthagh) ?

2023-12-06 07:49 UTC, orthagh commented on src/Ticket.php
> +                return sprintf(__('%s days %s hours %s minutes'), floor($time / 86400), floor(($time % 86400) / 3600), floor(($time % 3600) / 60));
I didn't saw the problem initialy, sorry.
If we want an age for a ticket, computed from the start date, we don't take into account calendars at all, no ?
Or the column title should mention it displays in working days but I guess it's still strange.

2023-12-06 08:09 UTC, AdrienClairembault commented on src/Ticket.php
> +            'additionalfields'   => ['id']
You can add `entities_id` and `date` into this array to fetch all the data you need at once.
You will then no longer need to reload the ticket from the database in the `getSpecificValueToDisplay` function.

2023-12-06 08:11 UTC, AdrienClairembault requested changes
Meant to request change, not approve.

2023-12-19 09:48 UTC, cedric-anne commented on src/Ticket.php
> +                return sprintf(__('%s hours %s minutes ago'), floor($time / 3600), floor(($time % 3600) / 60));
The `ago` does not seems relevant here. Indeed, we are rendering a duration that does not reflect the real time, so we cannot say "16 hours ago" for a ticket created 2 days ago on a calendar that has 8 working hours per day.

2023-12-19 10:40 UTC, cedric-anne approved these changes

2023-12-22 13:06 UTC, trasher approved these changes

2023-12-22 13:06 UTC, merged