fix(IPNetwork): Don't display unicity check result
glpi-project/glpi pull request #16067
Opened 2023-11-27 13:25 UTC by stonebuzz

When an ```IPNetwork``` already exist in GLPI (for the destination entity)

a message is displayed

![image](https://github.com/glpi-project/glpi/assets/7335054/c550c68e-bf16-4369-bd7c-f9807de90803)

From the GLPI interface the message is useful but during the native inventory process, it's rather disturbing to get this error message (especially in red)

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !30610

2023-11-27 13:38 UTC, cedric-anne reviewed
As the result of `IPNetwork::add()` is not even checked from the inventory process, maybe we should probably silent all messages.
In this case, a generic existing key, like `_no_message`, should be used to disable all messages.

2023-11-27 14:17 UTC, stonebuzz commented
> As the result of `IPNetwork::add()` is not even checked from the inventory process, maybe we should probably silent all messages. In this case, a generic existing key, like `_no_message`, should be used to disable all messages.

agree with that

2023-11-27 14:24 UTC, cedric-anne requested changes

2023-11-27 14:24 UTC, cedric-anne commented on src/IPNetwork.php
> +                if (!isset($input['_no_message'])) {
You should not change the result format here, but you should instead update the `if (isset($preparedInput['error'])) {` to `if (isset($preparedInput['error']) && !isset($input['_no_message'])) {`

2023-11-27 14:36 UTC, cedric-anne commented on src/IPNetwork.php
> +        if (isset($preparedInput['error']) && !isset($input['_no_message'])) {
Can also be added on line 482.

2023-11-28 09:47 UTC, stonebuzz commented on src/IPNetwork.php
> +        if (isset($preparedInput['error']) && !isset($input['_no_message'])) {
done (sorry)

2023-11-28 09:48 UTC, cedric-anne approved these changes

2023-11-28 10:44 UTC, trasher approved these changes

2023-11-28 10:44 UTC, merged