Fix satisfaction survey link criteria
glpi-project/glpi pull request #16099
Opened 2023-12-01 10:20 UTC by RomainLvr

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !30498

Different results between the satisfaction survey table in the personal view and the filter assigned to it in the view of tickets awaiting satisfaction survey.

The problem is a mistake between the two queries which are supposed to return the same result.

2023-12-01 10:31 UTC, Rom1-B requested changes

2023-12-01 10:31 UTC, Rom1-B commented on src/Ticket.php
> +                        ];
The IF must remain
```suggestion
                        if (Session::haveRight('ticket', Ticket::SURVEY)) {
                            $options['criteria'][3]['link'] = 'AND';
                            $options['criteria'][3]['criteria'] = [
                                [
                                    'link'        => 'AND',
                                    'field'       => 22, // author
                                    'searchtype'  => 'equals',
                                    'value'       => Session::getLoginUserID(),
                                ],
                                [
                                    'link'        => 'OR',
                                    'field'       => 4, // requester
                                    'searchtype'  => 'equals',
                                    'value'       => Session::getLoginUserID(),
                                ]
                            ];
                        } else {
                            $options['criteria'][3]['field'] = 4; // requester
                            $options['criteria'][3]['searchtype'] = 'equals';
                            $options['criteria'][3]['value'] = Session::getLoginUserID();
                            $options['criteria'][3]['link'] = 'AND';
                        }
```

2023-12-01 13:11 UTC, RomainLvr commented on src/Ticket.php
> +                        ];
Aapplied, thanks :+1:

2023-12-01 13:26 UTC, Rom1-B approved these changes

2023-12-01 14:18 UTC, trasher approved these changes
Seems OK, need customer feedback

2023-12-01 14:25 UTC, RomainLvr commented
> Seems OK, need customer feedback

The customer says he no longer has the error : [Ticket 30498](https://support.teclib.com/front/ticket.form.php?id=30498)

2023-12-04 08:34 UTC, orthagh approved these changes

2023-12-04 08:35 UTC, merged