Interactive local test env
glpi-project/glpi pull request #16151
Opened 2023-12-04 21:14 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

GLPI tests (specifically PHP code tests) can take a very long time to run. My previous answer for that was to manually edit the `test_tests-functional.sh` file locally to restrict tests to a specific directory or file. While that worked, it could be quicker if the docker containers didn't have to get recreated every time `tests/run_tests.sh` is run.

This PR adds a new "interactive" mode to the `run_tests.sh` script which can be activated with the `--interactive` flag. In interactive mode, all containers are started immediately and then it asks the user to enter one of several commands:
- test: Run the currently selected tests. By default, it gets this from the `run_tests.sh` arguments like it did before.
- settest: Change the currently selected test(s)
- setscope: Change the currently selected scope. This is the file or directory to run tests against if the test supports it. Currently, this only affects unit and functional tests. By default, this is "default" which means 
- info: Displays the currently selected tests and scope
- help: Displays the command list
- exit: Stops the containers and exits

After tests are run in interactive mode, regardless of their success, the user is prompted for another command rather than exiting.
If you run tests again and the install was already run, it will not repeat the install tests unless they were explicitly requested.

Also, I tried to fix the LDAP fixture cleanup. When I tried running LDAP tests multiple times, it would fail to add `dc=glpi,dc=org` again and I think it is because the script was only running `ldapdelete` on leaf nodes. I changed it to do recursive deletes instead, but I am not 100% confident it was the best solution.

Examples:
- `tests/run_tests.sh functional`: Run functional tests in non-interactive mode. Same as before.
- `tests/run_tests.sh --interactive functional`: Run in interactive mode and select "functional" tests.
- `settest lint ldap` (inside interactive mode test runner): Select lint and ldap test(s)

2023-12-07 17:18 UTC, AdrienClairembault commented
> setscope: Change the currently selected scope. This is the file or directory to run tests against if the test supports it

Can it also support specifying the method name ? Atoum support it with like this: https://atoum.readthedocs.io/en/latest/running_tests.html#a-class-or-a-method

2023-12-14 18:53 UTC, cconard96 commented
I added support for the `-m` option, but it doesn't work. I don't think it is my poor bash skills though since manually changing the test command line results in it testing nothing and declaring it a success.
```sh
vendor/bin/atoum \
  -p 'php -d memory_limit=512M' \
  --debug \
  --force-terminal \
  --use-dot-report \
  --bootstrap-file tests/bootstrap.php \
  --fail-if-void-methods \
  --fail-if-skipped-methods \
  $ATOUM_ADDITIONNAL_OPTIONS \
  --max-children-number 1 \
  -m tests\\units\\Alert::* \
```
`Success (0 test, 0/0 method, 0 void method, 0 skipped method, 0 assertion)!`

2023-12-26 14:24 UTC, AdrienClairembault commented
I also suffer from poor bash skills but this is how I implemented it on my `gtest` zsh function (code is simplified to only show the important options).

```sh
vendor/bin/atoum -bf tests/bootstrap.php -f $1 -m \*::$2
```

Which could then be used like this:

![image](https://github.com/glpi-project/glpi/assets/42734840/25324ba4-f928-4eb4-8e7d-db39ad0ac293)

The results confirm only one method was executed.

2023-12-26 14:43 UTC, AdrienClairembault requested changes
Regarding the feature itself, I think it is a great addition which would help running tests more efficiently.

However, in my opinion the usability could be improved as it feels a bit too "verbose" to configure your test because you need to run different commands like this:

![image](https://github.com/glpi-project/glpi/assets/42734840/15a2bf7d-1d33-4603-94ff-02299541fefa)

I feel like it may be simpler to use if you could just require a test with a single command like this:

![image](https://github.com/glpi-project/glpi/assets/42734840/d2531fd7-fdbd-46c6-9aa1-9da3e8ae4504)

The `run` prefix could be added if we want to keep support for others distinct commands like "help" or "exit".

It would also need up/back arrow support to reload previous command like a real terminal, which would allow to re-run the previous tests easily.

I realize this may require additional work and perhaps complicated bash code (which I am terrible at and probably can't help with) but I really think it would make the feature more convenient to use.

All of this is subjective so it would be interesting to hear everyone opinions on this (which may differ from mine).

@trasher @orthagh @cedric-anne

2024-01-03 14:08 UTC, orthagh commented
I tested quickly the feature and it's promising.
It's rough for the moment, I needed to think more than 2s :p

Some remarks (I know some apply to the non interactive version present before), just a list a thing I noted:
- `docker compose` runs with `--quiet` option. Not against it, but it's almost the only command in quiet mode.
- Vocabulary: "test" when using the `settest` option may be renamed to "action" (this matches github)
- Scope and test/action may beneficiates from example and also, if possible, completions
- like said by @AdrienClairembault a way to target a specific method (`testsingle xxx/xxx::xxx`) and a up arrow support to run the previous command.
- we may need a test/action "all" selected by default. In comparison, if no scope defined, it considers everything.
- when prompt is waiting "GLPI Tests >", a recall of the `info` option (just before) may be useful.

2024-01-03 15:00 UTC, cconard96 commented
Some changes made so far:
1. `settest`, `setscope`, and `test` commands are now `set action`, `set scope` and `run` respectively.
2. The `run` command now supports arguments for a single action and scope (scope defaults to the selected one if not specified) which affect the single test/action run.
3. `show_info` is run before every prompt for command input to display the currently selected actions and scope.

2024-01-05 13:07 UTC, AdrienClairembault commented
>     2. The `run` command now supports arguments for a single action and scope (scope defaults to the selected one if not specified) which affect the single test/action run.

I understand the action is the tests suite name (`units`, `functional`, ...) but what is the expected value for the scope ?
The full path to the file ?

>     3. `show_info` is run before every prompt for command input to display the currently selected actions and scope.

Does not seems to work on my side.
Sometimes I have some line with the details before my action but most of the time I don't.
Maybe it should always be displayed directly in the prompt ?
Something like `GLPI Tests (action) (scope) >` ?

Also sometimes the wrong action is executed:

![image](https://github.com/glpi-project/glpi/assets/42734840/a22447b7-a439-4933-b413-2b5bb40e3fb9)

2024-01-15 16:03 UTC, cedric-anne commented
I made some modifications to split scope and methods patterns. Indeed, one may want to use both of them at the same time (e.g. all `testPrepare` methods in `tests/functional/Glpi/Inventory` directory).

I fixed some issues with backslashes on test patterns.

Use case using `set` commands:
```
set action functional
set scope tests/functional/Glpi/Agent/Communication/Headers/Common.php
set methods tests\units\Glpi\Agent\Communication\Headers\Common::testHeaders
run
```

Use case using a single command:
```
run functional tests/functional/Glpi/Inventory *::testPrepare
```

2024-01-15 16:04 UTC, cedric-anne approved these changes

2024-01-16 12:58 UTC, AdrienClairembault requested changes
Everything is OK for me expect the lack of up/down arrow support.

It seems it can easily be added like that (I don't fully understand how it works tho...):

```diff
diff --git a/tests/run_tests.sh b/tests/run_tests.sh
index ae7885b794..e4f5c7d453 100755
--- a/tests/run_tests.sh
+++ b/tests/run_tests.sh
@@ -364,7 +364,8 @@ if [[ "$INTERACTIVE" = true ]]; then
     SCOPE=$SELECTED_SCOPE
     METHODS=$SELECTED_METHODS
     show_info
-    read -e -r -p "GLPI Tests > " CHOICE
+    while read -r -e -d $'\n' -p 'GLPI Tests > ' CHOICE; do
+      history -s "$CHOICE"
       if [[ "$CHOICE" = run* ]]; then
         # If actions were specified after the run choice, use them instead of the ones selected
         if [[ "$CHOICE" != "run" ]]; then
@@ -414,6 +415,7 @@ EOF
       fi
       CHOICE=""
     done
+  done
 fi

 cleanup_and_exit
```

2024-01-17 07:20 UTC, cedric-anne requested changes
Since addtition of history, the following usage does not work anymore:
![image](https://github.com/glpi-project/glpi/assets/33253653/3781e868-c9e6-4406-972c-c5b0d138c669)

2024-01-17 13:15 UTC, cconard96 commented
> Since addtition of history, the following usage does not work anymore: ![image](https://private-user-
The commit was reverted. If someone else wants to try adding support, they can. Although, bash seems fairly limited in what we can support with tab-completion and history.

2024-01-17 13:38 UTC, cedric-anne commented
> > Since addtition of history, the following usage does not work anymore:
> 
> The commit was reverted. If someone else wants to try adding support, they can. Although, bash seems fairly limited in what we can support with tab-completion and history.

I guess the issue is due to position of variables declaration/affectation. If the fix is simple to do, it could be done in another PR, but, honestly, I think it is getting a too complex script for our bash skills. If this script is meant to get many enhancements in the future, maybe it should be transformed into a PHP `symfony/console` command.

2024-01-17 13:38 UTC, cedric-anne approved these changes

2024-01-17 13:39 UTC, merged