Skip unneeded LDAP auth checks
glpi-project/glpi pull request #16224
Opened 2023-12-20 01:44 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #15262

When logging in through the API with a user_token instead of a username/password, the authentication code was trying to connect to every active LDAP server even if the user was not from an LDAP. When the user is from an LDAP and has an `auths_id` set, then only that one server is checked. When `auths_id` is 0 or missing, it checks every server. This code should first check the `authtype` before anything else related to LDAP.

2023-12-20 07:32 UTC, cedric-anne approved these changes
Seems OK.

By the way, I recently figured out that I have a LDAP warning (I have a test LDAP that is not always started) when the "remember_me" cookie is used to restore my session after a long time of inactivity.

As far as I understand this piece of code, this issue will be fixed too.

2023-12-20 07:35 UTC, cedric-anne requested changes
Actually, it seems that you have to define manually `$this->user->fields['authtype']` in `Auth::getAlternateAuthSystemsUserLogin()` (the same way it is done for `$this->user->fields['name']`.

Not sure of the side-effects.

2023-12-20 09:21 UTC, orthagh commented
> Actually, it seems that fetching LDAP information is a wanted behaviour for a user that nevers connects before. For instance, if it connects through SSO, we still want to fetch more information from the LDAP.

I confirm this

2024-01-11 10:54 UTC, cedric-anne approved these changes

2024-01-17 08:23 UTC, trasher approved these changes

2024-01-17 08:23 UTC, merged