fix(ticket): watcher ignored on self-service form
glpi-project/glpi pull request #16237
Opened 2023-12-21 13:09 UTC by Rom1-B

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !30913

On the native ticket creation form, in the simplified interface, the watcher was not taken into account.
So even if you filled it in, the created ticket didn't have it.

In the browser console, there was this error:
![image](https://github.com/glpi-project/glpi/assets/8530352/42759bb8-6ebc-4e8f-8f52-fbee8425adc4)

2023-12-26 10:31 UTC, AdrienClairembault requested changes

2023-12-26 10:31 UTC, AdrienClairembault commented on templates/components/itilobject/actors/field.html.twig
> +      setTimeout((function() {
```suggestion
      $(function () {
```
Waiting for the document to be ready should be more reliable than an arbitrary 500ms delay.

2023-12-26 10:31 UTC, AdrienClairembault commented on templates/components/itilobject/actors/field.html.twig
> +      }), 500);
```suggestion
      });
```

2023-12-26 12:54 UTC, AdrienClairembault approved these changes

2024-01-03 11:00 UTC, orthagh approved these changes
Probably since #15957 which was to improve visually the speed of rendering the page.
The new change doesn't seem to impact as much as it was before the previous pr.
So ok for me

2024-01-08 09:09 UTC, merged