Use Monaco for custom css editor
glpi-project/glpi pull request #16288
Opened 2024-01-02 20:31 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

If/when #16287 is merged, the entity Custom UI form will be the last thing in GLPI that uses Codemirror. It doesn't really make sense to have two libraries for code editing/syntax highlighting if it can be avoided. Monaco seems to be the more complete alternative and as noted with the other PR, fulfills our requirements easier (in my opinion). Therefore, I recommend replacing Codemirror with Monaco and then dropping the Codemirror dependency completely.

The Monaco replacement offers code completion as before, as well as these new features:
- Linting. The editor now validates syntax and ensures users are typing valid CSS (not SCSS)
- Inline color preview and selector: Typing a hex color code, rgb function, etc, will put a preview/selector control before the color value. This selector also lets you switch the value between hex, rgb, hsl, etc.
- Inline MDN documentation for CSS properties. Seems bundles with Monaco and doesn't require an Internet connection.
- Information about selector specificity when hovering over selectors
- Contextual suggestions. For example, only the valid options for `flex` will be shown when changing that property's value.

This would require the other PR to be merged first. If testing this PR before the other PR is merged, make sure to check out the commit before the one that actually drops the Codemirror dependencies if you want the debug bar to work.

2024-01-03 08:40 UTC, orthagh approved these changes

2024-01-09 11:30 UTC, cedric-anne commented on templates/pages/admin/entity/custom_ui.html.twig
> +                    e.originalEvent.formData.delete('entities_id');
#16331 should prevent to have to do this.
```suggestion
```

2024-01-10 00:23 UTC, cconard96 commented on inc/define.php
> +    'admin'        => ['clipboard', 'monaco'],
Done. Sector-based loading is only done for the `js/modules/Monaco/MonacoEditor.js` and the relatively small Monaco CSS file. The main Monaco library will only be loaded at the exact time it is needed, much like the Vue code. This is done through stub functions in the MonacoEditor script which wrap the related library use with a dynamic import.

2024-01-10 07:33 UTC, cedric-anne approved these changes

2024-01-10 07:40 UTC, cedric-anne commented on templates/pages/admin/entity/custom_ui.html.twig
> +        <div class="alert alert-info {{ item.fields['enable_custom_css'] == 1 ? 'd-none' : '' }}">{{ __('Custom CSS is disabled') }}</div>
On a sub-entity, this message is displayed when the "Inherits configuration from the parent entity" is selected. This is not corresponding to the effective configuration when the parent entity has custom CSS enabled.
Is it possible to display the inherited value?

2024-01-11 08:27 UTC, cedric-anne requested changes
I rebased to fix conflicts, but my last remark is still valid.

2024-01-15 08:38 UTC, cedric-anne approved these changes

2024-01-15 09:07 UTC, merged