Remove configurable API url
glpi-project/glpi pull request #16297
Opened 2024-01-03 14:14 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | -

Since the documentation and endpoint links were added for the new API, the legacy API URL was made read-only. This PR fully drops the ability to change the legacy API URL. As noted in #14509, user's can accomplish this within their web server configuration instead. Now, the legacy API URL will always be `/api.php/v1`. The old endpoint `/apirest.php` still works. The `api.php` script will simply hand all of the data off to the `apirest.php` script when version 1 is specified.

2024-01-03 14:18 UTC, orthagh approved these changes

2024-01-08 09:12 UTC, trasher approved these changes

2024-01-08 09:12 UTC, trasher commented on src/Migration.php
> +     * @since 9.2
```suggestion
     * @since 10.1.0
```

2024-01-08 09:29 UTC, cedric-anne approved these changes

2024-01-08 09:29 UTC, cedric-anne commented on inc/autoload.function.php
```suggestion
```

2024-01-08 09:33 UTC, cedric-anne requested changes

2024-01-08 09:33 UTC, cedric-anne commented on src/Migration.php
> +    }
This is the exact same as `addConfig`. I am not sure it will work as expected.
A test case on this new method is required.

2024-01-09 14:56 UTC, cedric-anne approved these changes

2024-01-09 14:56 UTC, merged