feat: add pending reason for followup and task templates
glpi-project/glpi pull request #16295
Opened 2024-01-03 10:42 UTC by ccailly

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !30468

This PR adds the ability to define a pending reason in a followup or task template.

2024-01-05 13:57 UTC, AdrienClairembault approved these changes

2024-01-08 10:40 UTC, orthagh approved these changes

2024-01-08 11:01 UTC, cedric-anne requested changes

2024-01-11 07:48 UTC, cedric-anne commented on src/CommonITILTask.php
> +                $pendingReason->getFromDB($template->fields['pendingreasons_id']);
```suggestion
            $pendingReason = new PendingReason();
            if (
                $template->fields['pendingreasons_id'] > 0
                && $pendingReason->getFromDB($template->fields['pendingreasons_id'])
            ) {
```

2024-01-11 07:48 UTC, cedric-anne commented on src/ITILFollowup.php
> +                $pendingReason->getFromDB($template->fields['pendingreasons_id']);
```suggestion
            $pendingReason = new PendingReason();
            if (
                $template->fields['pendingreasons_id'] > 0
                && $pendingReason->getFromDB($template->fields['pendingreasons_id'])
            ) {
```

2024-01-11 07:55 UTC, cedric-anne approved these changes

2024-01-11 08:18 UTC, trasher commented on install/migrations/update_10.0.x_to_10.1.0/itilfollowuptemplates.php
> + * @copyright 2015-2023 Teclib' and contributors.
```suggestion
 * @copyright 2015-2024 Teclib' and contributors.
```

2024-01-11 08:18 UTC, trasher commented on install/migrations/update_10.0.x_to_10.1.0/tasktemplates.php
> + * @copyright 2015-2023 Teclib' and contributors.
```suggestion
 * @copyright 2015-2024 Teclib' and contributors.
```

2024-01-11 08:47 UTC, merged