Fix/maxclosedate nerver updated child
glpi-project/glpi pull request #16313
Opened 2024-01-05 15:52 UTC by Lainow

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #14707

When generating surveys, the max close date of the ticket is stored during a loop, the code updates the parent entity maxdate but never the code never update the current/child entity.

2024-01-08 08:59 UTC, stonebuzz requested changes

2024-01-08 08:59 UTC, stonebuzz commented on src/CommonITILObject.php
> +            'used'                        => self::getAllocableTeamMember(),
This change has no place here

2024-01-08 08:59 UTC, stonebuzz commented on src/CommonITILObject.php
> +
This change has no place here

2024-01-08 08:59 UTC, stonebuzz commented on templates/components/kanban/kanban.html.twig
> +         'used': used,
This change has no place here

2024-01-08 08:59 UTC, stonebuzz commented on src/Ticket.php
> +            // Sauvegarde du max_closedate des enfants pour ne pas tester les m??me tickets 2 fois
```suggestion
            // Save children's max_closedate to avoid testing the same tickets twice
```

2024-01-11 07:45 UTC, cedric-anne commented on src/Ticket.php
> +            $current       = Entity::getUsedConfig('inquest_config', $entity, 'id');
This will not return the current entity ID. I think `$entity` corresponds to the value you are trying to get here.

2024-02-05 11:10 UTC, cedric-anne requested changes
Please try to avoid merge commits inside your PRs as it is a pain to rebase. When you have to synchronize your branches with upstream, try to always use the `rebase` feature (for instance `git pull --rebase origin 10.0/bugfixes`).

Also, please try to avoid changes made on files that have nothing to do with proposed fix/feature. It will pollute the history of these files.

2024-02-05 11:10 UTC, cedric-anne commented on tests/functional/Ticket.php
> +    public function testCronSurveyCreation()
This test will pass even without proposed modifications. It should be rewritten to validates that it fails without any patch and that it is fixed with the proposed patch.

2024-02-13 10:05 UTC, cedric-anne approved these changes

2024-02-13 10:07 UTC, cedric-anne commented
@Lainow I pushed a commit with the correct fix. Your proposal was almost OK, but in fact the initial was related to the fact that the `max_closedate` should be saved on current entity instead on its parent when the configuration is not inherited.

`Entity::getUsedConfig()` is a mess, so the issue was more complicated than I thought.

2024-02-13 11:43 UTC, AdrienClairembault approved these changes
Looks good to me (still suggested some optional changes).

2024-02-13 11:43 UTC, AdrienClairembault commented on tests/functional/Ticket.php
> +        $two_hours_ago    = date("Y-m-d H:i:s", strtotime('-2 hours'));
I guess you could use the new getters methods:

```suggestion
        $root_entity_id    = $this->getTestRootEntity(true);
        $child_1_entity_id = getItemByTypeName('Entity', '_test_child_1', true);
        $child_2_entity_id = getItemByTypeName('Entity', '_test_child_2', true);

        $now              = \Session::getCurrentTime();
        $twelve_hours_ago = date("Y-m-d H:i:s", strtotime('-12 hours'));
        $six_hours_ago    = date("Y-m-d H:i:s", strtotime('-4 hours'));
        $four_hours_ago   = date("Y-m-d H:i:s", strtotime('-4 hours'));
        $two_hours_ago    = date("Y-m-d H:i:s", strtotime('-2 hours'));
```

2024-02-13 11:43 UTC, AdrienClairembault commented on tests/functional/Ticket.php
> +    public function testCronSurveyCreation()
```suggestion
    public function testCronSurveyCreation(): void
```

2024-02-13 12:59 UTC, trasher approved these changes

2024-02-13 13:03 UTC, merged