Add screen capture feature
glpi-project/glpi pull request #16353
Opened 2024-01-11 14:54 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Integration of `screenshot` plugin. Unlike the plugin where the screenshot and recording buttons were separate timeline actions, these buttons now exist within the document item timeline form. That also means users can attach any number of screenshots, recordings, or uploaded files and they all get processed at once. Screenshots and recordings both have previews shown within the form and they can be removed by clicking the "x" on the preview or within the file upload control.

![Selection_211](https://github.com/glpi-project/glpi/assets/17678637/a9d51ff5-b45e-4bd4-b28e-af9076c2cc3c)

This feature only works within "secure contexts". Typically that means you connect over HTTPS or are connecting to `localhost`. If your browser doesn't consider your connection to be a secure context, the screenshot and recording options will be hidden. The browser wouldn't allow access to the required APIs in that case anyways. Further, if GLPI doesn't allow uploading the type of file used by one of the options, that option will not show. It uses PNG for screenshots and WEBM for recordings.

Also, the plugin had restricted screen recordings with a new permission. My reasoning was that the convenience of creating and adding a video, which would be a large file, may not be desired to be accessible to certain users.
**My question is where this permission would fit in. There are no document permissions within simplified interface profiles currently.**

2024-01-15 13:41 UTC, orthagh approved these changes
Finally after a deep clean of my caches, everything work as intended.

about 
> My question is where this permission would fit in. There are no document permissions within simplified interface profiles currently.

Imo, pictures uploading are not problematic at all (and already possible when pasting from clipboard), their size is usually ok.
about webm, as the feature requires enabling the extensions in dropdowns > filetypes, and disabled by default, I guess it's good as it.
I'm not in favor to add dedicated rights for the moment.

2024-01-18 15:17 UTC, cedric-anne commented on js/modules/Screenshot/Screenshot.js
> +class Screenhot {
Multiple methods have no JSDoc. It may help to have it, especially when there are parameters.

2024-02-06 09:08 UTC, cedric-anne requested changes

2024-02-06 09:08 UTC, cedric-anne commented on templates/components/itilobject/timeline/form_document_item.html.twig
> +                <hr class="my-1">
This whole block should probably be skipped when the feature is not available.

When PNG and WebM files are disallowed, or if the `Screenshot.isSupported()` returns `false`, the form title and separator should not be displayed:
![image](https://github.com/glpi-project/glpi/assets/33253653/8cf76ed6-38b2-44f4-a8a1-0ea3b7b474af)

2024-02-06 10:55 UTC, cedric-anne approved these changes

2024-02-06 11:28 UTC, merged