Socket Twig UI
glpi-project/glpi pull request #16365
Opened 2024-01-14 04:55 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Moved Socket-related UI to Twig templates.
Redesigned the form shown on the Sockets tab of Locations. Instead of two forms being shown at the same time, one for adding a single socket and another for adding multiple, there is now only a single form which can switch modes using a slider. For multi-add mode, I also added placeholder text for the two name textboxes to make it clearer to the user how the names are built.

![Selection_213](https://github.com/glpi-project/glpi/assets/17678637/1053eedc-7b1e-4f6b-bb11-e6277f650b23)
![Selection_215](https://github.com/glpi-project/glpi/assets/17678637/ac973a8f-f8d7-4288-9eff-40ee383d5903)

2024-01-15 14:35 UTC, orthagh reviewed
Result is far superior to the previous regarding the design.

I'm still a bit annoyed seeing a lot of content in `renderFromStringTemplate`. This method should help with small twig code. The part in `showForLocation` seems very big for that.
Example, part in `showListForItem` is fine, location one is, I think, too big.

2024-01-17 08:20 UTC, trasher submitted a review, later dismissed
See @orthagh comment

2024-01-17 09:54 UTC, cedric-anne requested changes

2024-01-17 09:54 UTC, cedric-anne commented on src/Socket.php
> +        echo TemplateRenderer::getInstance()->renderFromStringTemplate(<<<TWIG
`TemplateRenderer::renderFromStringTemplate()` should be used only for really small templates. Indeed, templates used this way:
 - are not parsed by `xgettext` and their translations are therefore not recognized,
 - are not parsed by linters.

2024-01-17 09:54 UTC, cedric-anne commented on src/Socket.php
> +            echo TemplateRenderer::getInstance()->renderFromStringTemplate(<<<TWIG
The whole rendering of this method should be moved into a dedicated Twig file that
1. render this small form,
2. includes `components/datatable.html.twig` to render the list.

2024-01-17 09:54 UTC, cedric-anne commented on src/Socket.php
> +            $socket_name = $canedit ? "<a href='{$socket_form_url}?id={$data['id']}'>" . $socket->fields["name"] . "</a>" : $socket->fields["name"];
On main branch, when HTML is build using string concatenation, it is necessary to escape the dynamic data manually:
```suggestion
            $socket_name = $canedit ? "<a href='{$socket_form_url}?id={$data['id']}'>" . htmlspecialchars($socket->fields["name"]) . "</a>" : htmlspecialchars($socket->fields["name"]);
```

Maybe it is necessary to handle the fact that the field could be nullable.

The same remark applies for the whole GLPI codebase on `main` branch.

2024-01-22 13:29 UTC, orthagh approved these changes

2024-01-23 14:59 UTC, cedric-anne approved these changes

2024-01-24 13:30 UTC, merged