Profile assignment twig migration
glpi-project/glpi pull request #16360
Opened 2024-01-12 23:44 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Migrates the forms to assign a profile to a user or a user to a profile to twig.
Migrates the list of profile assignments for a user to the twig datatable template.

Didn't migrate the view of users associated with a profile. I think this is the only case where we have a folder view for sub-items. Do we want to keep it, change it to a datatable, or change it in some other way?
![Selection_212](https://github.com/glpi-project/glpi/assets/17678637/513c19b4-e313-482b-bd2b-cb85b5a4b350)

2024-01-15 10:51 UTC, orthagh requested changes
Wrong pr (removed comment)

2024-01-15 11:12 UTC, orthagh commented
For component we may use list example from tabler : https://preview.tabler.io/lists.html (the top left one)
- mostly .row + .col-6 for layout. Responsive in mind, we may have:
   - single col for mobile device
   - -6 cols for medium size
   - -3 cols for xxl
- I like the fact we display user picture here, and we could enhance ui by doing the same
- we need to find a way to display the checkbox properly on the left, it should be ok I think.

Apart this, maybe review the check all control, it seems off for the moment.

2024-01-22 14:40 UTC, orthagh approved these changes

2024-01-22 15:24 UTC, cedric-anne requested changes

2024-01-22 15:24 UTC, cedric-anne commented on src/Profile_User.php
> +                $link = "<a href='" . $entity_form_url . "?id=" . $data["entities_id"] . "'>" . $link . "</a>";
Special HTML chars must be encoded when HTML is crafted using string concatenation.

```suggestion
                $link = sprintf(
                    '<a href="%s">%s</a>', 
                    htmlspecialchars(Entity::getFormURLWithID($data["entities_id"])),
                    htmlspecialchars($link)
                );
```

2024-01-22 15:24 UTC, cedric-anne commented on src/Profile_User.php
> +                $profile_name = "<a href='{$form_url}?id={$data['id']}'>" . Html::entities_deep($data['name']) . "</a>";
```suggestion
                $form_url = Profile::getFormURLWithID($data['id']);
                $profile_name = sprintf(
                    '<a href="%s">%s</a>', 
                    htmlspecialchars($form_url),
                    htmlspecialchars($data['name'])
                
```

2024-01-22 15:24 UTC, cedric-anne commented on templates/pages/admin/add_profile_authorization.html.twig
> +    <form name="entityuser_form{{ rand }}" id="entityuser_form{{ rand }}" method="post" action="{{ 'Profile_User'|itemtype_form_path }}" data-submit-once>
Not sure this id/name is used anywhere.
```suggestion
    <form method="post" action="{{ 'Profile_User'|itemtype_form_path }}" data-submit-once>
```

2024-01-22 15:24 UTC, cedric-anne commented on src/Profile_User.php
> +                $profile_name = Html::entities_deep($data['name']);
I think it is prefereable to use the native PHP function directly.
```suggestion
                $profile_name = htmlspecialchars($data['name']);
```

2024-01-22 15:25 UTC, cedric-anne commented on src/Profile_User.php
> +        $entity_form_url = Toolbox::getItemTypeFormURL('Entity');
```suggestion
```

2024-01-22 15:31 UTC, cedric-anne commented on src/Profile_User.php
> +
```suggestion
                    htmlspecialchars($data['name'])
                );
```

2024-01-22 16:23 UTC, merged