Review budget and cost UI
glpi-project/glpi pull request #16395
Opened 2024-01-22 03:29 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

- Migrate budget/cost UI to twig
- Refactor SQL queries for items/entities related to a budget
- Budget "Main" tab now shows negative values for "Total remaining in the budget" in parentheses instead of with a negative sign to align with typical accounting practices.
- Added flag to allow hiding the pager in datatables
- Fixed handling of a clearable `date` field.
- Added ability to specify a super-header and footers for datatables
- Some minor code cleanup/PHPDoc fixes

2024-01-22 13:17 UTC, orthagh requested changes
Some errors I found while browsing the "Items" tab on a newly created budget:

```
PHP Warning (2): Undefined variable $item in /var/www/html/glpi/main/src/Budget.php at line 380
PHP Warning (2): Undefined variable $item in /var/www/html/glpi/main/src/Budget.php at line 395
Uncaught Exception Error: Call to a member function maybeDeleted() on null in /var/www/html/glpi/main/src/Budget.php at line 395
```

2024-01-22 15:07 UTC, orthagh approved these changes

2024-01-24 14:21 UTC, cedric-anne requested changes
1) There is a regression in the `Main` tab (generated by `Budget::showValuesByEntity()`). Indeed, we recently adapted this tab (see #15234) to display in a `Other entities` row the total cost of items that are not visible inside the current active entities scope.
![image](https://github.com/glpi-project/glpi/assets/33253653/306cb0e8-bc0f-448c-9768-650465e19eb4)

2) The datatable headers contains a link that seems to be present for sorting purpose, but clicking on it just releods the tab without sorting anything.

2024-02-01 10:11 UTC, cedric-anne reviewed
Please rebase to solve conflicts.

2024-02-01 10:45 UTC, cedric-anne requested changes
With last commit, items that are located outside active entity scope are visible in the `Items` tab of the budget, but they should not (their name / serial number / price may be considered as a sensitive information).

The entity restriction should apply to the `Items` tab, but not to the `Main` tab that shows only grouped information.

2024-02-01 12:46 UTC, cedric-anne commented on src/Budget.php
>          global $DB;
```suggestion
        /** @var \DBmysql $DB */
        global $DB;
```

2024-02-01 12:51 UTC, cedric-anne requested changes

2024-02-01 12:51 UTC, cedric-anne commented on templates/components/form/basic_inputs_macros.html.twig
> +    }) %}
This could probably be done in the default options init code, on line 208.

2024-02-01 12:51 UTC, cedric-anne commented on templates/components/form/basic_inputs_macros.html.twig
> -            {% if options.maybeempty %}
There are some usages of the `maybeempty` option that would be broken.

2024-02-01 13:58 UTC, cedric-anne commented on templates/components/form/basic_inputs_macros.html.twig
> +    {# Do not handle this in the input macro (would show a plain checkbox to clear) #}
```suggestion
```

2024-02-01 14:34 UTC, cedric-anne commented on templates/components/form/basic_inputs_macros.html.twig
>              'input_addclass': options.input_addclass ~ final_expiration_class
```suggestion
            'input_addclass': options.input_addclass ~ final_expiration_class,
```

2024-02-01 14:38 UTC, cedric-anne approved these changes

2024-02-01 15:11 UTC, cedric-anne commented on templates/pages/management/budget.html.twig
> +{% import 'components/form/basic_inputs_macros.html.twig' as inputs %}
```suggestion
```

2024-02-01 15:32 UTC, cedric-anne commented on templates/pages/management/cost.html.twig
> +    {{ fields.textareaField('comment', item.fields['comment'], __('Comment')) }}
```suggestion
    {{ fields.textareaField('comment', item.fields['comment'], _n('Comment', 'Comments', get_plural_number())) }}
```

2024-02-01 16:04 UTC, merged