Add Certificates capacity
glpi-project/glpi pull request #16422
Opened 2024-01-24 14:32 UTC by RomainLvr

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

![image](https://github.com/glpi-project/glpi/assets/102067890/31426405-9af6-4201-8f35-ffa733e93cd6)

2024-01-24 14:35 UTC, AdrienClairembault requested changes

2024-01-24 14:35 UTC, AdrienClairembault commented on src/Asset/Capacity/HasCertificatesCapacity.php
> +        $this->unregisterFromTypeConfig('document_types', $classname);
```suggestion
        $this->unregisterFromTypeConfig('certificate_types', $classname);
```

2024-01-25 11:10 UTC, AdrienClairembault approved these changes

2024-01-25 14:44 UTC, cedric-anne approved these changes

2024-01-25 15:08 UTC, merged