Custom asset templates
glpi-project/glpi pull request #16455
Opened 2024-01-29 00:19 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

2024-01-29 14:53 UTC, cedric-anne requested changes
Unless I miss something, templates are using the clone feature. Indeed, if you create a template that defines, for instance, volumes, they will not be present in any item created from this template unless it is declared in the clone relations.

2024-01-29 14:53 UTC, cedric-anne commented on install/migrations/update_10.0.x_to_10.1.0/assets.php
The following patch should be added to handle developpers that already executed the base migration.
```diff
diff --git a/install/migrations/update_10.0.x_to_10.1.0/assets.php b/install/migrations/update_10.0.x_to_10.1.0/assets.php
index 745807090b..6ce96675ea 100644
--- a/install/migrations/update_10.0.x_to_10.1.0/assets.php
+++ b/install/migrations/update_10.0.x_to_10.1.0/assets.php
@@ -122,6 +122,9 @@ SQL;
     $migration->addKey('glpi_assets_assets', 'assets_assetmodels_id');
     $migration->addField('glpi_assets_assets', 'assets_assettypes_id', 'fkey');
     $migration->addKey('glpi_assets_assets', 'assets_assettypes_id');
+    $migration->addField('glpi_assets_assets', 'is_template', 'bool');
+    $migration->addKey('glpi_assets_assets', 'is_template');
+    $migration->addField('glpi_assets_assets', 'template_name', 'string');
 }
 
 if (!$DB->tableExists('glpi_assets_assetmodels')) {
````

2024-02-07 09:00 UTC, cedric-anne reviewed
Now the cloning feature has been merged, you can rebase and finalize this PR.

2024-02-12 15:24 UTC, cedric-anne approved these changes

2024-02-13 07:19 UTC, trasher approved these changes

2024-02-13 07:20 UTC, merged