Capacity: Has network ports
glpi-project/glpi pull request #16514
Opened 2024-02-05 14:58 UTC by ccailly

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 

Add NetworkPorts capacity

![image](https://github.com/glpi-project/glpi/assets/42278610/d1b02e87-6422-4737-a2a0-bff36c2c5056)

2024-02-06 11:01 UTC, AdrienClairembault approved these changes

2024-02-07 09:41 UTC, AdrienClairembault approved these changes

2024-02-07 13:20 UTC, cedric-anne requested changes
The network ports should probably be cloned when the asset is cloned (they are clone when a computer is cloned).
To do this, you have to declare this method:
```php
    public function getCloneRelations(): array
    {
        return [
            NetworkPort::class,
        ];
    }
```

A test should also be added for this. See #16454 for some inspiration.

2024-02-14 15:54 UTC, cedric-anne approved these changes

2024-02-14 15:54 UTC, merged