Add description for capacities (and muted texts in setup)
glpi-project/glpi pull request #16510
Opened 2024-02-05 13:41 UTC by ccailly

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 

Add a description to each capacity.

![image](https://github.com/glpi-project/glpi/assets/42278610/90a44fcf-87b2-40ae-9898-bb56bca5aec9)

2024-02-05 15:01 UTC, orthagh submitted a review, later dismissed
Regarding design : almost ok, I still think we loose a big space in the middle. I don't want to remove it entirely, but curently there is more space dedicated to emptyness than actual content. Maybe we can inverse space usage.

Another thing, if description is not provided, or empty, the whole block should not be displayed.

Regarding descriptions content, well, they don't inform about anything for the moment 😬 
I mean, yeah, Appliance capacity allows indeed to manage Appliances for the assets.
Don't take this as a personal criticism, but maybe another person, more experienced about the application could take a shot about the content.

2024-02-06 10:27 UTC, AdrienClairembault requested changes

2024-02-06 10:27 UTC, AdrienClairembault commented on src/Asset/Capacity/HasAntivirusCapacity.php
> +    public function getDescription(): string
A general remark here, we merged last week the PHP 8.3 polyfill, which mean we should try to use the `#[Override]` data attribute every time we override a method.

See https://stitcher.io/blog/override-in-php-83

2024-02-07 09:43 UTC, ccailly commented
This is what it looks like with and without description. Regarding the content of the descriptions, I would like help in producing relevant descriptions.
![image](https://github.com/glpi-project/glpi/assets/42278610/bb57e638-f480-42ed-a77b-a6a328f09eb4)

2024-02-07 10:43 UTC, orthagh commented
Seems good ! The design doesn't suffer when a capacity is without description

2024-02-07 10:46 UTC, AdrienClairembault approved these changes

2024-02-13 11:49 UTC, AdrienClairembault commented
What the next step for this ?
Should it be merged as it is and then correct texts can be added later on or do you want to wait for the updates texts before merging ?

2024-02-13 12:28 UTC, cedric-anne commented
IMHO, if only a few capacities are going to have a description, it would probably be more relevant to just have a :grey_question: icon that opens a tooltip. Indeed, descriptions may b far longer than only 2 lines and in this case the current design would probably be not adapted.

2024-02-14 16:02 UTC, AdrienClairembault commented
To move forward, maybe it can be merged as it is for now (as it isn't really a ground breaking feature) ?

Then we can re-evaluate it later on when all capacities are finished and see how many capacities need description and how do we want to display them.

2024-02-19 15:38 UTC, cedric-anne approved these changes

2024-02-19 15:38 UTC, merged