Update inventory lib
glpi-project/glpi pull request #16521
Opened 2024-02-06 13:17 UTC by trasher

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

2024-02-06 13:17 UTC, trasher commented
To include https://github.com/glpi-project/inventory_format/pull/131

2024-02-07 14:47 UTC, cedric-anne requested changes
Tests are failing.

2024-02-07 15:17 UTC, trasher commented
Well, there is indeed something wrong, but it should have failed in lib tests; and it works... :/ Generated JSON for network equipments contains RAM as string, validation should not work.

2024-02-08 14:23 UTC, cedric-anne approved these changes

2024-02-08 14:23 UTC, merged