Fix(RuleRight): Take db groups into account for rights rules on LDAP users
glpi-project/glpi pull request #16548
Opened 2024-02-12 14:17 UTC by stonebuzz

Maybe an alternative to 
https://github.com/glpi-project/glpi/pull/16154

The "groups" criteria for authorizations rules is not processed correctly for LDAP users.

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !31311

2024-02-13 10:15 UTC, cedric-anne commented on tests/LDAP/AuthLdap.php.orig
This file should be removed.

2024-02-13 10:32 UTC, cedric-anne commented on tests/LDAP/AuthLdap.php
> +        $this->array($groups)->hasSize(1);
This is useless, `$this->createItem()` already checkes that teh creation is OK.
```suggestion
```

2024-02-13 10:32 UTC, cedric-anne commented on tests/LDAP/AuthLdap.php
> +
```suggestion
        // Check that the use is not attached to the profile at creation
        $rights = (new Profile_User())->find([
            'users_id' => $users_id,
            'profiles_id' => 4,
        ]);

        $this->array($rights)->hasSize(0);

```

2024-02-13 10:34 UTC, cedric-anne approved these changes
Seems OK, but I wonder if side effects are sufficiently limited to introduce this change in a bugfix version.

2024-02-13 11:18 UTC, AdrienClairembault requested changes
Looks good to me besides some minor requested changes 👍.

No opinion on the main / bugfixes debate (I'd argue that this is a bug even if technically it was just never implemented).

2024-02-13 11:18 UTC, AdrienClairembault commented on tests/LDAP/AuthLdap.php
> +        /**
Indent looks wrong

2024-02-13 11:18 UTC, AdrienClairembault commented on src/User.php
> +        /**
Indent looks wrong.

2024-02-13 11:18 UTC, AdrienClairembault commented on src/User.php
> +     * @param string $user_dn dn of the user
The second parameter is missing from the PHPDoc

2024-02-13 12:12 UTC, cedric-anne commented on src/User.php
> +     */
```suggestion
    /**
     * Retrieve a user from the database using it's dn.
     *
     * @param string $user_dn dn of the user
     *
     * @return bool
     */
```

2024-02-13 12:12 UTC, cedric-anne commented on tests/LDAP/AuthLdap.php
> +     */
```suggestion
    /**
     * Test if rules targeting ldap criteria are working
     *
     * @return void
     */
```

2024-02-13 12:13 UTC, cedric-anne commented on src/User.php
> +    public function getFromDBbyDnAndAuth($user_dn, $auths_id): bool
```suggestion
    public function getFromDBbyDnAndAuth(string $user_dn, int $auths_id): bool
```

2024-02-13 12:13 UTC, cedric-anne commented on src/User.php
> +     * @param string $user_dn dn of the user
```suggestion
     * @param string $user_dn
     * @param int $auths_id
```

2024-02-13 12:44 UTC, trasher commented
I have absolutely no idea if that can cause side effects... But that's something new; therefore it should target main (I guess we can provide a patch to the original reporter).

2024-02-13 13:15 UTC, AdrienClairembault approved these changes

2024-02-14 07:43 UTC, stonebuzz commented
closed in favour of  https://github.com/glpi-project/glpi/pull/16555 (```main```) version

2024-02-14 07:43 UTC, closed without merging