Monaco show basic suggestions for Twig default env
glpi-project/glpi pull request #16569
Opened 2024-02-15 17:09 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Monaco's support for Twig doesn't include any information about the default environment, possibly because it can change (although it doesn't explain why keywords are missing). This PR at least adds some of the more common, available by default, keywords, functions, filters, etc to the list.
Obviously, this is still no replacement for user's reading the Twig documentation, but may give some hints to them that they do indeed have access to a default Twig environment and have some idea of what is available to them.

2024-02-21 09:48 UTC, cedric-anne requested changes
User defined Twig templates should rely on the `Glpi\ContentTemplates\TemplateManager` security policy. Indeed, the rendering environment we use for our application templates is not safe at all, as, for instance, it exposes the `call` function that permit to call any PHP function, including those that can be used to read/write/exec any file accessible on the system.

If we have some user generated templates that are rendered using the `Glpi\Application\View\TemplateRenderer`, it has to be changed.

See the security policy:
https://github.com/glpi-project/glpi/blob/375e81f8ccecb5a16cb0f35b3cf24429fa701546/src/ContentTemplates/TemplateManager.php#L162-L170

2024-02-21 15:05 UTC, cconard96 commented
Nothing I added uses TemplateRenderer, but uses a new, default Twig environment with an array loader that has only the single user-defined template instead. I knew that user's shouldn't have any access to the added extensions we have. The default environment doesn't seem to allow any kind of arbitrary code execution unless we pass objects into the template and then they could access a limited set of data on the items.

The only difference I see between the current implementation and Glpi\ContentTemplates\TemplateManager is it isn't quite as restrictive with the filters/functions they can use (reverse, various array filters, some formatters, encoding filters, etc are not available through TemplateManager) and it doesn't get sanitized by `RichText::getSafeHtml` (not sure this is desired in some cases like webhooks).

2024-02-21 16:13 UTC, cconard96 commented
Should TemplateManager be made less restrictive and have the sanitization part be optional?

2024-02-21 16:33 UTC, cedric-anne commented
> Nothing I added uses TemplateRenderer, but uses a new, default Twig environment with an array loader that has only the single user-defined template instead. I knew that user's shouldn't have any access to the added extensions we have. The default environment doesn't seem to allow any kind of arbitrary code execution unless we pass objects into the template and then they could access a limited set of data on the items.

OK, so it is less a problem.

> Should TemplateManager be made less restrictive

Yes. It can provide more features, as long as it does not provide, for instance, the `include` and the `extends` features that may permit unexpected access to some files.

> and have the sanitization part be optional?

It has been made optional recently.

2024-03-13 14:50 UTC, cedric-anne reviewed
Seems OK.

2024-03-13 14:50 UTC, cedric-anne commented on js/modules/Monaco/MonacoEditor.js
> +            'apply', 'autoescape', 'block', 'for', 'if', 'macro', 'set',
```suggestion
            'apply', 'autoescape', 'block', 'for', 'if', 'elseif', 'macro', 'set',
```

2024-03-13 14:50 UTC, cedric-anne commented on js/modules/Monaco/MonacoEditor.js
> +        const functions = ['min', 'max', 'random', 'range'];
It is available both in filters and functions.
```suggestion
        const functions = ['date', 'min', 'max', 'random', 'range'];
```

2024-03-13 14:50 UTC, cedric-anne commented on js/modules/Monaco/MonacoEditor.js
> +            'abs', 'batch', 'capitalize', 'column', 'default', 'escape', 'filter', 'first', 'format', 'join',
```suggestion
            'abs', 'batch', 'capitalize', 'column', 'date', 'default', 'escape', 'filter', 'first', 'format', 'join',
```

2024-03-14 07:26 UTC, cedric-anne approved these changes

2024-03-14 08:21 UTC, merged

2024-03-14 08:29 UTC, AdrienClairembault approved these changes