Move messages above search to new status area in search controls header
glpi-project/glpi pull request #16621
Opened 2024-02-26 17:21 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | -
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

![Selection_244](https://github.com/glpi-project/glpi/assets/17678637/c283e676-ef50-43dc-a11c-ecde64fdedac)
![Selection_243](https://github.com/glpi-project/glpi/assets/17678637/b56718e3-2c67-43a5-a144-b23bedf8308a)

2024-03-05 15:14 UTC, orthagh commented on templates/components/search/controls.html.twig
> +        <div class="status-area">
Maybe something like that to draw attention:

```suggestion
        <div class="status-area alert alert-danger p-1 m-0">
```

![image](https://github.com/glpi-project/glpi/assets/418844/47df8326-e586-41b4-a072-82d23c8a42da)

2024-03-06 08:23 UTC, orthagh approved these changes

2024-03-06 08:40 UTC, cedric-anne requested changes

2024-03-06 08:40 UTC, cedric-anne commented on src/CronTask.php
> +            $msg = __s('Automatic actions may not be running as expected');
Will be escaped by Twig engine.
```suggestion
            $msg = __('Automatic actions may not be running as expected');
```

2024-03-06 08:40 UTC, cedric-anne commented on src/CronTask.php
> +                'warnings' => '<ul>' . implode('', array_map(static fn ($warning) => "<li>$warning</li>", $warnings)) . '</ul>'
```suggestion
                'warnings' => '<ul>' . implode('', array_map(static fn ($warning) => '<li>' . htmlspecialchars($warning) . '</li>', $warnings)) . '</ul>'
```

2024-03-06 08:40 UTC, cedric-anne commented on src/MailCollector.php
> +                static fn ($v) => '<a class="btn btn-sm btn-ghost-danger align-baseline" href="' . $v['link'] . '">' . htmlentities($v['name']) . '</a>',
```suggestion
                static fn ($v) => '<a class="btn btn-sm btn-ghost-danger align-baseline" href="' . htmlspecialchars($v['link']) . '">' . htmlspecialchars($v['name']) . '</a>',
```

2024-03-06 08:40 UTC, cedric-anne commented on src/MailCollector.php
> -    public function title()
Please add an entry in changelog to indicate that this method was removed.

2024-03-06 14:12 UTC, merged