Forms: floating toolbar
glpi-project/glpi pull request #16629
Opened 2024-02-27 11:19 UTC by AdrienClairembault

Add a "floating toolbar" to the form editor.

![image](https://github.com/glpi-project/glpi/assets/42734840/7525ae9a-893a-42f4-b9e1-be72a88b2fc4)

This toolbar is shown for the active item and allow to insert a new question or section.
Its design and position might change in futures PR as we discuss UX later on.

Others changes:
* Renamed the `data-active-status` attribute to `[data-glpi-form-editor-active-status-indicator]` (to keep things consistant)
* Replaced the `.active` class by a `[data-glpi-form-editor-active]` data attribute (to prevent conflicts as others components may use the same `.active` class, which may impact our selectors)
* Question drag and drop handle is only shown when hovering the question itself (new `[data-glpi-form-editor-question-details]` attribute instead of `[data-glpi-form-editor-question]` which now also contain the toolbar).
* `#handleEditorAction` now received the original event objet to allow specific actions to prevent event propagation.
* The `#addQuestion` and `#addSection` methods now require the current active form element as a parameter, which may be a question, a section or the form itself.
This is needed because these methods behave differently based on the active item (while previously questions and section would always be added at the end of the form, they can now be added anywhere)
* When the last question is deleted, we set the form as active.
This allow the form toolbar to be shown as it will be used to recreate questions if needed.
* Renamed `[data-glpi-form-editor-section-form-container]` to `[data-glpi-form-editor-section-details]` to be consistant with similar selectors for questions and the form itself.
* `#copy_template` accept a new parameter to specify how the data should be copied relative to the destination (after, before, prepend or append).
* Added `#handleItemMove` to centralize tinymce re-initialization process as it can now be triggered from two separate actions (creation a section in the middle of an existing one or moving a question with its handle). The reorder section actions should probably use it too but I didn't want to change it here as it a bit more complicated to handle (TODO later).
* Small bugfix to `#reorderSections` + added a TODO that explain it should no rely on the computeState() data for its behavior.

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |

2024-03-04 14:57 UTC, orthagh reviewed
IRL review:
- remove label for adding question
- when opening a form, the floating bar is on top. A form without any focus should not display the floating bar at all
- After deleting a question, focus the previous.
- If there no question at all, focus the main form.

2024-03-05 13:43 UTC, orthagh approved these changes

2024-03-05 14:42 UTC, cedric-anne requested changes

2024-03-05 14:42 UTC, cedric-anne commented on templates/pages/admin/form/form_editor.html.twig
> +                                        value="{{ item.fields.name }}"
```suggestion
                                        value="{{ item.fields.name|e('html_attr') }}"
```

2024-03-05 14:42 UTC, cedric-anne commented on templates/pages/admin/form/form_question.html.twig
> +                    value="{{ question is not null ? question.fields.name : '' }}"
```suggestion
                    value="{{ question is not null ? question.fields.name|e('html_attr') : '' }}"
```

2024-03-05 15:07 UTC, cedric-anne approved these changes

2024-03-05 15:17 UTC, merged