Fix category metadata in itil kanban cards
glpi-project/glpi pull request #16720
Opened 2024-03-06 22:04 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Partial revert of #16084 to restore the "category" metadata in ITIL Kanban cards to the category ID. This is referenced in SQL queries later. The category name was moved to a new "category_name" metadata property. On the JS side, the filter was changed to refer to the "category_name" if it is set and fallback to "category" like it did before for BC. I don't know if any plugins integrate with the Kanban feature and use this filter.

2024-03-07 07:31 UTC, cedric-anne requested changes

2024-03-07 07:31 UTC, cedric-anne commented on js/modules/Kanban/Kanban.js
> +                    const category = '' + card.data('category_name') !== undefined ? card.data('category_name') : card.data('category');
Just to ensure that the `?` operator is not including the `'' +` part of the operation.
```suggestion
                    const category = '' + (card.data('category_name') !== undefined ? card.data('category_name') : card.data('category'));
```

2024-03-07 07:31 UTC, cedric-anne commented on src/CommonITILObject.php
> +                'category_name' => $category_names[$data['itilcategories_id']] ?? '',
There is a duplicated logic here. On line 9205, the translated category name is fetched (one request for one category) and then, on lines 9349->9411, the translated categories names are fetched again (one request for all categories) to replace categories ids by their name.

Some cleaning should be done. I guess #16084 would not have been necessary if the lines 9349->9411 were working as expected.

2024-03-11 07:44 UTC, cedric-anne approved these changes

2024-03-11 08:02 UTC, trasher approved these changes

2024-03-11 08:05 UTC, merged