Groups UI Twig
glpi-project/glpi pull request #16721
Opened 2024-03-07 01:41 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Move UI relating to items belonging to/managed by groups, users in a group, and groups assigned to a user to twig.

Still need to re-add filter support to the lists. Will require some changes to how filters are handled in the datatables template.

List of users in a group (Before):
![Selection_268](https://github.com/glpi-project/glpi/assets/17678637/3f5a6a78-e9a7-4757-9612-30ca16be2639)

List of users in a group (After):
![Selection_269](https://github.com/glpi-project/glpi/assets/17678637/26d86a0f-cb74-4b92-acc3-21f4bba1656f)

List of groups for a user (Before):
![Selection_266](https://github.com/glpi-project/glpi/assets/17678637/50eaa4c8-0b8c-463c-b98d-5909345c831e)

List of groups for a user (After):
![Selection_267](https://github.com/glpi-project/glpi/assets/17678637/6cc98529-42de-49ed-a844-803f140e729c)

2024-03-07 11:31 UTC, orthagh commented
A few comments:
- having red icons instead nothing seems an UI regression. Red means a warning for the admin where in this case, it's just not having an attribute attached to the user-group relation
- we may also drop the green check and the circle (personal preference) to a simple greyish `ti-check` 
- no pagination is available (i have a 914 group-user)
- can we review the add part also, I think a modal with vertical fields could be better here (the same can be said for Authorizations of user, addition action should be moved to another context)

2024-03-07 11:35 UTC, cconard96 commented
>     * having red icons instead nothing seems an UI regression. Red means a warning for the admin where in this case, it's just not having an attribute attached to the user-group relation

I added them specifically because I noticed the previous checkmark images had no titles and therefore there is no data for screen readers. I'm not sure how well it would be presented in that case with a mix of empty cells and cells containing "Yes". If the UI isn't good, I can remove the icons and only have sr-only "No" spans.

2024-03-07 11:38 UTC, orthagh commented
>  no data for screen readers

Good point

> I can remove the icons and only have sr-only "No" spans.

Good idea !

2024-03-12 11:06 UTC, orthagh commented
> can we review the add part also

I think we're good apart the above point.

2024-03-12 11:35 UTC, cconard96 commented
> > can we review the add part also
> 
> I think we're good apart the above point.

The old UI had an itemtype dropdown above the item list that filtered the list. I need to re-implement that in the datatable filter.

For the form, I thought this could be standardized across all tabs with datatables, at least for short forms like this.
1. The form is initially hidden behind a centered Add button unless it can be fit on a single line (like this case)
2. Clicking the add button shows the form fields, along with an Add and Cancel button. Clicking Add will create the item while Cancel hides the form and shows the original button.
3. Clicking an item in the list will hide the initial Add button and show the form with the selected item's data, along with a Save and Cancel button. This won't effect some items that are intended currently to be deleted and recreated rather than edited link simple links between two other items.
If the form is too long, it would need handled in a modal or a separate page.

2024-03-16 21:00 UTC, cconard96 commented
@AdrienClairembault can you check the display regarding recursive groups?  I'm not sure it was displayed right when you filter the results. Right now, the `clearDuplicatedGroupData` calls are commented out and seem OK for me, but I guess that isn't the desired behavior.

2024-03-18 15:45 UTC, AdrienClairembault commented
Its been a while since the recursive groups dev but I think the goal is to avoid having twice the same group in the list:

![image](https://github.com/glpi-project/glpi/assets/42734840/f2496555-2554-485b-bc85-67824b80c31a)

Case `A` is a group directly assigned to the user, while `B` is a recursive assignation.

If I un-comment `clearDuplicatedGroupData` then there is no duplicated data.

Regarding filtering, maybe it was already broken before (I wasn't aware of this feature).
I've also noticed that sorting does not work (unrelated to whether or not `clearDuplicatedGroupData` is commented).

2024-03-18 15:52 UTC, cconard96 commented
> Its been a while since the recursive groups dev but I think the goal is to avoid having twice the same group in the list:
> 
> Case `A` is a group directly assigned to the user, while `B` is a recursive assignment.
> 
> If I un-comment `clearDuplicatedGroupData` then there is no duplicated data.
> 
> Regarding filtering, maybe it was already broken before (I wasn't aware of this feature). I've also noticed that sorting does not work (unrelated to whether or not `clearDuplicatedGroupData` is commented).

The filters before were just a dropdown to toggle between manager, delegate and nothing, and a yes/no dropdown to show child groups.
With this PR, child groups are always pulled in the data as I wanted to delegate that to the filters in the datatable. IMO, the "duplicates" should always be shown by default. Since there is a column that says which group the association is for, there shouldn't be an issue.
The issue I noticed was that I had a user assigned to a parent group and a child group. In the parent group, none of the flags were set to Yes, while they were in the child group. The parent was made recursive. By default, I saw only their membership in the parent group. When filtering to show managers, the previously shown result for that user disappeared and was replaced with the one in the child group which matched the filter.

2024-03-19 09:35 UTC, AdrienClairembault commented
> IMO, the "duplicates" should always be shown by default. Since there is a column that says which group the association is for, there shouldn't be an issue.

I don't have a strong opinion on this. @orthagh should probably clarify what's best.

Did you see my comment on sorting being broken ? This part must be fixed before it can be merged IMO.

2024-03-19 14:31 UTC, orthagh commented
> For the form, I thought this could be standardized across all tabs with datatables, at least for short forms like this.

OK, that seems fair.
Could you make a bit more spacing between the form and the list (maybe also an hr)


> IMO, the "duplicates" should always be shown by default

I agree

> If time permits, all of the datatables can be iterated on to support more filters, sorting, pagination, etc.

Please note this as a to-do. 
I'm ok to merge as it for the moment. Just we shouldn't forget it

2024-03-19 15:55 UTC, AdrienClairembault approved these changes

2024-03-20 07:44 UTC, cedric-anne commented on src/Group_User.php
> +        }
`$where_filters` are never used.

2024-03-20 10:18 UTC, cedric-anne commented on front/group_user.form.php
> -        );
This should probably stay in the front page. Event logs are mostly made from front files, and, for the moment, we do not have time to think about how we could/should enhance this.

2024-03-28 09:03 UTC, trasher requested changes
Tests are failing, I guess because there is no logged-in user

2024-03-28 21:30 UTC, trasher approved these changes

2024-03-28 21:30 UTC, merged