fix(network port): error message
glpi-project/glpi pull request #16780
Opened 2024-03-14 15:11 UTC by Rom1-B

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !31937

Following https://github.com/glpi-project/glpi/pull/16738, we get an error on ports that have no correspondence in the Fields plugin tables, for example, when the port existed before the fields added by the plugin were created.

```
glpiphplog.NOTICE:   *** PHP Deprecated function (8192): htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/glpi/src/Html.php at line 2502
  Backtrace :
  src/Html.php:2502                                  htmlspecialchars()
  src/NetworkPort.php:1018                           Html::getMassiveActionCheckBox()
  src/NetworkPort.php:905                            NetworkPort->showPort()
  src/NetworkPort.php:1864                           NetworkPort::showForItem()
  src/CommonGLPI.php:694                             NetworkPort::displayTabContentForItem()
  ajax/common.tabs.php:120                           CommonGLPI::displayStandardTab()
  public/index.php:82                                require()
  
glpiphplog.NOTICE:   *** PHP Deprecated function (8192): round(): Passing null to parameter #1 ($num) of type int|float is deprecated in /var/www/glpi/src/NetworkPort.php at line 1054
  Backtrace :
  src/NetworkPort.php:1054                           round()
  src/NetworkPort.php:905                            NetworkPort->showPort()
  src/NetworkPort.php:1864                           NetworkPort::showForItem()
  src/CommonGLPI.php:694                             NetworkPort::displayTabContentForItem()
  ajax/common.tabs.php:120                           CommonGLPI::displayStandardTab()
  public/index.php:82                                require()
```

2024-03-15 16:41 UTC, trasher commented
I have no idea if this is correct or not... Please try to add tests.

2024-03-18 09:47 UTC, Rom1-B commented
> I have no idea if this is correct or not... Please try to add tests.

I don't know how to do this? Because the original problem was that fields from the Fields plugin could be added, but were not visible in the result, because GLPI didn't search for this data.

2024-03-18 10:19 UTC, trasher commented
Well... I have no idea how to test things that are not used neither...

I still have no idea if this fix is correct. Network ports is a nightmare, I skip my turn.

2024-03-19 09:40 UTC, cedric-anne requested changes
At least, please add a test that displays all columns related to native GLPI search options. This would, at least, ensure that the view works as expected without plugins.

2024-03-20 11:02 UTC, cedric-anne commented on tests/functional/NetworkPort.php
> +            if (isset ($column['field'])) {
```suggestion
            if (isset($column['field'])) {
```

2024-03-20 11:02 UTC, cedric-anne commented on tests/functional/NetworkPort.php
> +        foreach ($so as $column) {
```suggestion
        $so_display = [];
        foreach ($so as $column) {
```

2024-03-20 11:04 UTC, cedric-anne approved these changes
As the test validates that it is possible to add all relevant search options and have their content correct regarded the netport data, I am pretty confident.

Let's wait for a couple of days before merging it, so the customer would be able to tell us if everything is OK.

2024-03-26 09:26 UTC, merged