Fix merging of join conditions in search engine
glpi-project/glpi pull request #16793
Opened 2024-03-15 18:33 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

The conversion of request criteria arrays to SQL can only handle a single extra element in the join array for additional criteria. Any extra conditions have to be inside that third element or else they are ignored.

2024-03-19 10:03 UTC, cedric-anne requested changes
Tests are failing.

2024-03-20 07:09 UTC, cedric-anne approved these changes

2024-03-20 08:24 UTC, AdrienClairembault approved these changes

2024-03-20 08:31 UTC, trasher approved these changes

2024-03-20 08:31 UTC, merged