Lock Twig UI
glpi-project/glpi pull request #16797
Opened 2024-03-17 22:40 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Relies on #16796.

- Migrate the lists on an asset's Locks tab to Twig
- New datatable template features
  - Ability to hide regular column headers to accommodate nested datatables (each nested table has its own columns and the parent table only has one column containing the subtables).
  - Ability to toggle massive action checkboxes per-row
  - Ability to change the table class used for styling (table-hover, table-sm, etc)

2024-03-28 09:00 UTC, trasher approved these changes

2024-03-28 09:45 UTC, orthagh requested changes
Another thing, can you try to space a bit the two tables to achieve a visual distinction

2024-03-28 09:45 UTC, orthagh commented on src/Lock.php
> +            <div class="alert alert-primary d-flex align-items-center" role="alert">
```suggestion
            <div class="alert alert-info d-flex align-items-center" role="alert">
```

Not a recent issue, but the style primary for alert is unreadable for light theme (especially with auror theme)

2024-03-29 07:27 UTC, orthagh approved these changes

2024-03-29 07:42 UTC, merged