SLM Twig UI
glpi-project/glpi pull request #16911
Opened 2024-04-09 21:11 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Based on #16910.

- Migrate UI code for SLM/SLA/OLA related code to Twig
- A fair amount of de-duplication of UI code

UX change for escalation levels list. I'm not sure if it changed with a previous Twig PR since it reuses UI code from rules, or was always like this, but the escalation levels list looked too crowded and wasn't easy for me (someone who doesn't use service levels) to understand what was going on.

Before (Without any criteria or actions):
![Selection_291](https://github.com/glpi-project/glpi/assets/17678637/a010bcfa-5bd2-4305-bce7-9e620bcfd16c)

After (With a criteria and action):
![Selection_292](https://github.com/glpi-project/glpi/assets/17678637/23371c11-debe-4c9c-94d7-9173d1fe0ab4)

The change makes the list cleaner but also means that the criteria and actions cannot be added/changed from the escalation level list anymore. You have to click the escalation level link to open its form.

2024-04-11 09:15 UTC, orthagh requested changes
Some issues may be in the main branch directly. I didn't have the time to investigate more.

- form for adding an escalation level seems to lose the relation with the parent SLA/OLA
- I got an incoherence between the number of tickets counted in the tab (32) vs the tab content (no data). 
- general advice: if you find a number dropdown without any special option (like the one for maximum time), replace it with a simple `input[type=number]`

Regarding the UI/UX, nothing to say

2024-04-15 23:10 UTC, cconard96 commented
>     * form for adding an escalation level seems to lose the relation with the parent SLA/OLA

Fixed
 
>     * I got an incoherence between the number of tickets counted in the tab (32) vs the tab content (no data).

Doesn't seem related. This tab also triggers a deprecation warning. It looks like the way this tab is handled was changed a few times in the last year or two.
This tab is still using raw HTML, so I'll probably address the issue it at some point in this project.

2024-04-16 06:56 UTC, orthagh approved these changes

2024-04-16 07:22 UTC, cedric-anne commented on src/LevelAgreement.php
> +     * @return false|Generator
```suggestion
     * @return false|iterable
```

2024-04-16 07:22 UTC, cedric-anne commented on src/LevelAgreementLevel.php
> +    public function showForLA(LevelAgreement $la): void
It is used only by subclasses, and I do not see any reason to permit this method to be overriden. We can make it final and protected.

```suggestion
    final protected function showForLA(LevelAgreement $la): void
```

2024-04-17 06:33 UTC, cedric-anne approved these changes

2024-04-17 07:24 UTC, trasher approved these changes

2024-04-17 07:24 UTC, merged