Clean Software Code
glpi-project/glpi pull request #16912
Opened 2024-04-09 22:45 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Work done before the UI migrations related to Software.

2024-04-10 06:06 UTC, trasher commented on src/Item_SoftwareLicense.php
> +        $order = $_GET['order'] === 'DESC' ? 'DESC' : 'ASC';
undefined case is not handled

2024-04-10 06:09 UTC, trasher commented on src/Item_SoftwareVersion.php
> +     * @param CommonDBTM $item         Computer object
```suggestion
     * @param CommonDBTM $item         Item
```

2024-04-10 06:10 UTC, trasher commented on src/Software.php
> +     * {@inheritdoc}
This whole comment may be removed

2024-04-10 06:13 UTC, trasher commented on src/SoftwareLicense.php
> +        $order = $_GET['order'] === 'DESC' ? 'DESC' : 'ASC';
undefined case not handled

2024-04-10 06:16 UTC, trasher commented
Also, tests are failing :/

2024-04-10 12:30 UTC, trasher approved these changes

2024-04-10 13:40 UTC, cedric-anne requested changes

2024-04-10 13:40 UTC, cedric-anne commented on src/SoftwareLicense.php
> +                        Session::addMessageAfterRedirect(htmlspecialchars(sprintf(
`$message` contains a `<br>` tag for each licence. These `<br>` tags should not be encoded.

2024-04-10 13:40 UTC, cedric-anne commented on src/SoftwareLicense.php
> +        $order = ($_GET['order'] ?? 'DESC') === 'DESC' ? 'DESC' : 'ASC';
```suggestion
        $order = ($_GET['order'] ?? 'ASC') === 'DESC' ? 'DESC' : 'ASC';
```

2024-04-10 13:40 UTC, cedric-anne commented on src/SoftwareLicense.php
> +                case __CLASS__:
We use the `::class` notation everywhre. It seems more logical to use `self::class` here.
```suggestion
                case self::class:
```

2024-04-11 06:06 UTC, cedric-anne approved these changes

2024-04-11 06:43 UTC, merged