fix(contract): expiration date in search
glpi-project/glpi pull request #16935
Opened 2024-04-16 07:47 UTC by Rom1-B

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/glpi-project/glpi/issues/16890

Since https://github.com/glpi-project/glpi/pull/16719, in the search view, the renewal value was not taken into account, and the expiry date of contracts without tacit renewal was wrong.

2024-04-16 07:55 UTC, cedric-anne requested changes
Seems OK, but a test should be added for the `getSpecificValueToDisplay` method, with a data provider that tests, at least, all the renewal types, with, at least, expiration dates in the past and in the future.

2024-04-22 06:50 UTC, cedric-anne commented on tests/functional/Contract.php
> +                'expected' => "2024-07-01"
This test will fail once this date will be passed. I guess the `Infocom::getWarrantyExpir()` must be changed to use the `$_SESSION['glpi_currenttime']` value, in order to be able to force it in this test case.

2024-04-22 07:57 UTC, cedric-anne approved these changes

2024-04-22 08:00 UTC, trasher approved these changes

2024-04-22 08:00 UTC, merged