Planning Twig UI
glpi-project/glpi pull request #16947
Opened 2024-04-19 02:12 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

2024-05-16 10:25 UTC, cedric-anne requested changes
I did not take time to test all the features, but I found some issues.

1) Selecting a start time / duration with the mouse in order to create an event does not work anymore (the preselected values are always the current time and a 1h duration).

2) The external event form in the modal is not displayed correctly (fields are really small).
![image](https://github.com/glpi-project/glpi/assets/33253653/158f44d6-957b-49d3-a39a-88f3d4e33a92)

2024-05-21 11:56 UTC, cedric-anne approved these changes
Seems technically OK, but I did not take time to test all the features.

2024-05-22 09:15 UTC, AdrienClairembault approved these changes

2024-05-24 05:56 UTC, trasher approved these changes

2024-05-24 06:27 UTC, trasher commented
Could you please rebase to solve conflicts?

2024-05-27 07:43 UTC, merged