fix(migration): update template fields
glpi-project/glpi pull request #16966
Opened 2024-04-22 06:34 UTC by Rom1-B

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !32139

Updates the search option number in the `XXXtemplatehiddenfields`, `XXXtemplatemandatoryfields` and `templatepredefinedfields` tables when the itemtype concerned is a CommonITILObject

2024-04-22 13:31 UTC, cedric-anne requested changes

2024-04-22 13:31 UTC, cedric-anne commented on src/Migration.php
> +                        'glpi_' . $itemtype . 'templatepredefinedfields',
```suggestion
                        'glpi_' . strtolower($itemtype) . 'templatehiddenfields',
                        'glpi_' . strtolower($itemtype) . 'templatemandatoryfields',
                        'glpi_' . strtolower($itemtype) . 'templatepredefinedfields',
```

2024-04-22 13:31 UTC, cedric-anne commented on src/Migration.php
> +                    foreach ($tables as $table) {
This method can be used by a plugin migration on a class that extends the CommonITILObject class without implementing the template fields feature (for instance the `PluginReleasesRelease` class).

```suggestion
                    foreach ($tables as $table) {
                        if (!$DB->tableExists($table)) {
                            continue;
                        }
```

2024-04-22 14:21 UTC, trasher approved these changes

2024-04-23 08:24 UTC, cedric-anne commented on src/Migration.php
> +                if ($item instanceof CommonITILObject) {
Will prevent any error if the target itemtype is not a valid class.

```suggestion
                if (is_a($itemtype, 'CommonITILObject', true)) {
```

2024-04-23 08:24 UTC, cedric-anne approved these changes

2024-04-25 14:06 UTC, merged