(Feature) Adding id to user tooltip card
glpi-project/glpi pull request #16974
Opened 2024-04-22 13:47 UTC by Lainow

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !32593

![image](https://github.com/glpi-project/glpi/assets/107540223/4336269a-26e2-4712-9bd0-6d2872d91be8)

2024-04-23 09:04 UTC, stonebuzz requested changes

2024-04-23 09:04 UTC, stonebuzz commented on src/DbUtils.php
> +                        'login'              => $data['name'],
useless, ```login``` is already ahndle after (when we are not in a context of anonymization)
just the display part was missing

2024-04-25 07:27 UTC, cedric-anne approved these changes

2024-04-25 07:27 UTC, cedric-anne commented on src/DbUtils.php
> +                        'user_name'          => $username
When your PR is finished, please, read the diff and remove changes that are useless. This kind of changes will pollute the "blame" view and the history of the file.

```suggestion
                        'user_name'          => $username,
```

2024-04-25 07:27 UTC, cedric-anne commented on templates/components/user/info_card.html.twig
>           <div class="text-muted">
```suggestion

         <div class="text-muted">
```

2024-04-25 08:37 UTC, orthagh commented on templates/components/user/info_card.html.twig
> +                    <i class="fas fa-id-badge"></i>
```suggestion
                    <i class="fa-fw fas fa-id-badge"></i>
```

2024-04-25 09:19 UTC, merged