User inventory rule
glpi-project/glpi pull request #16972
Opened 2024-04-22 13:00 UTC by Lainow

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !32435

Add new options in rules to manage user reconciliation.
![image](https://github.com/glpi-project/glpi/assets/107540223/f47ea9ec-cc59-4ce3-8d9b-97641d2db124)

2024-04-23 17:31 UTC, stonebuzz requested changes

2024-04-23 17:31 UTC, stonebuzz commented on src/RuleAsset.php
> +                                        }
we should not reset the field to 0

If the correct user is not found, leave the field untouched.

2024-04-23 17:31 UTC, stonebuzz commented on src/RuleAsset.php
> +                                        }
we should not reset the field to 0

If the correct user is not found, leave the field untouched.

2024-04-23 17:31 UTC, stonebuzz commented on src/RuleAsset.php
> +                                        }
we should not reset the field to 0

If the correct user is not found, leave the field untouched.

2024-04-24 09:00 UTC, stonebuzz requested changes

2024-04-24 09:00 UTC, stonebuzz commented on tests/functional/Glpi/Inventory/Inventory.php
> +          </USERS>
Can you add another couple of data (```<USER>``` / ```<DOMAIN>```) to test with another criteria like ```Rule::PATTERN_NOT_CONTAIN``` 

```xml
          <USERS>
            <DOMAIN>TECLIB</DOMAIN>
            <LOGIN>" . $xml_fields['name'] . "</LOGIN>
          </USERS>
          <USERS>
            <DOMAIN>TECLIB</DOMAIN>
            <LOGIN>Admin</LOGIN>
          </USERS>
```
Criteria => ```Rule::PATTERN_NOT_CONTAIN``` ```Admin```

2024-04-24 15:01 UTC, stonebuzz commented on src/RuleAsset.php
> +                                    }
```suggestion
                                          $user = User::getFromDBbyEmail($res);
                                        if ($user) {
                                            $output['users_id'] = $user->fields['id'];
                                        }
                                    }
```

2024-05-06 12:42 UTC, stonebuzz approved these changes

2024-05-06 12:46 UTC, orthagh approved these changes

2024-05-06 12:48 UTC, stonebuzz commented
waiting for customer feedback

2024-05-13 09:29 UTC, cedric-anne requested changes

2024-05-13 09:29 UTC, cedric-anne commented on src/RuleAsset.php
> +                                        if (isset($user->fields['id']) && $user->fields['id'] != 0) {
```suggestion
                                        if ($user->getFromDBbyEmail($res)) {
```

2024-05-13 09:29 UTC, cedric-anne commented on src/RuleAsset.php
> +                                break;
Please fix the indentation on these lines.

2024-05-14 13:01 UTC, cedric-anne approved these changes

2024-05-15 06:30 UTC, merged