feat(forms): Adding request type category and related question type
glpi-project/glpi pull request #16984
Opened 2024-04-23 13:03 UTC by ccailly

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 

Added `Request Type` categories and related sub-question type : `Request Type`
![image](https://github.com/glpi-project/glpi/assets/42278610/28aa8782-ccbe-43e6-b33b-2de833bd427d)
![image](https://github.com/glpi-project/glpi/assets/42278610/bff63dc5-3367-4e2c-918f-0f5d1f8f31cf)

2024-05-02 06:51 UTC, AdrienClairembault requested changes

2024-05-02 06:51 UTC, AdrienClairembault commented on src/Form/QuestionType/QuestionTypeRequestType.php
> + */
```suggestion
```

2024-05-02 06:51 UTC, AdrienClairembault commented on src/Form/QuestionType/QuestionTypeRequestType.php
> +            'answers[' ~ question.fields.id ~ ']',
I think this must be replaced by the new format after you rebase the PR to the latest changes

2024-05-07 07:06 UTC, AdrienClairembault approved these changes

2024-05-13 09:01 UTC, cedric-anne approved these changes

2024-05-13 09:01 UTC, merged