(Feature) Adding user tooltip to internal item view
glpi-project/glpi pull request #17006
Opened 2024-04-25 09:33 UTC by Lainow

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !32593

Linked to this Pull request : #16974 
The tooltips were only displayed in the item list and not when we went to the item page. This pull request adds this functionality.

**Ticket page**
![image](https://github.com/glpi-project/glpi/assets/107540223/053488e6-aa4c-49cc-8479-4145deb93fcf)

**Computer page**
![image](https://github.com/glpi-project/glpi/assets/107540223/ed051e80-9882-454c-be87-5d502f24a5dd)

2024-05-06 12:42 UTC, stonebuzz approved these changes

2024-05-06 12:45 UTC, orthagh approved these changes

2024-05-06 12:57 UTC, cedric-anne commented on templates/components/itilobject/selfservice.html.twig
> +                                    {% if session_has_read_right %}
```suggestion
                                    {% if has_profile_right('user',  constant('READ')) %}
```

2024-05-06 12:57 UTC, cedric-anne commented on templates/components/itilobject/timeline/timeline.html.twig
> +                  {% if session_has_read_right %}
```suggestion
                  {% if has_profile_right('user',  constant('READ')) %}
```

2024-05-06 12:57 UTC, cedric-anne commented on templates/components/user/link_with_tooltip.html.twig
> +        {% if session_has_read_right %}
```suggestion
        {% if has_profile_right('user',  constant('READ')) %}
```

2024-05-06 14:36 UTC, AdrienClairembault approved these changes

2024-05-13 06:16 UTC, cedric-anne commented on templates/components/itilobject/selfservice.html.twig
> +                                    {% if has_profile_right('user',  constant('READ')) %}
```suggestion
                                    {% if has_profile_right('user', constant('READ')) %}
```

2024-05-13 06:16 UTC, cedric-anne commented on templates/components/itilobject/timeline/timeline.html.twig
> +                  {% if has_profile_right('user',  constant('READ')) %}
```suggestion
                  {% if has_profile_right('user', constant('READ')) %}
```

2024-05-13 06:16 UTC, cedric-anne commented on templates/components/user/link_with_tooltip.html.twig
> +        {% if has_profile_right('user',  constant('READ')) %}
```suggestion
        {% if has_profile_right('user', constant('READ')) %}
```

2024-05-13 06:16 UTC, stonebuzz requested changes

2024-05-13 06:16 UTC, stonebuzz commented on templates/components/itilobject/selfservice.html.twig
> +                                    {% if has_profile_right('user',  constant('READ')) %}
```suggestion
                                    {% if has_profile_right('user', constant('READ')) %}
```

2024-05-13 06:16 UTC, stonebuzz commented on templates/components/itilobject/timeline/timeline.html.twig
> +                  {% if has_profile_right('user',  constant('READ')) %}
```suggestion
                  {% if has_profile_right('user', constant('READ')) %}
```

2024-05-13 06:16 UTC, stonebuzz commented on templates/components/user/link_with_tooltip.html.twig
> +        {% if has_profile_right('user',  constant('READ')) %}
```suggestion
        {% if has_profile_right('user', constant('READ')) %}
```

2024-05-13 08:05 UTC, merged