refactor(forms): centralize end user input name
glpi-project/glpi pull request #17015
Opened 2024-04-25 13:19 UTC by ccailly

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 

A method has been added to centralize the input names of the question types on the final form interface. The format has also been modified so that the answers to the questions are no longer stored in a single attribute. This is similar to the way FormCreator works, and simplifies the path for the upcoming arrival of the `File` question type.

2024-04-26 09:46 UTC, AdrienClairembault requested changes

2024-04-26 09:46 UTC, AdrienClairembault commented on src/Form/EndUserInputNameProvider.php
> +final class EndUserInputNameProvider
We try to avoid static methods, could you convert the methods to not be `static` ?

2024-04-26 09:46 UTC, AdrienClairembault commented on src/Form/EndUserInputNameProvider.php
> +        return sprintf(static::END_USER_INPUT_NAME, $question->getID());
```suggestion
        return sprintf(self::END_USER_INPUT_NAME, $question->getID());
```

2024-04-26 09:46 UTC, AdrienClairembault commented on src/Form/EndUserInputNameProvider.php
> +    }
When dealing with data from $_POST, it is usually better to use an `array $input` parameter in your function.
For exemple, this is cleaner for tests (no need to generate $_POST values).

2024-04-26 12:32 UTC, AdrienClairembault approved these changes

2024-04-29 11:38 UTC, cedric-anne approved these changes

2024-04-29 11:38 UTC, merged