Network Port Twig UI
glpi-project/glpi pull request #17061
Opened 2024-05-03 01:15 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

2024-05-06 12:37 UTC, orthagh reviewed
Nothing to say, didn't find any flaws

2024-05-06 12:38 UTC, orthagh approved these changes

2024-05-13 12:27 UTC, cedric-anne commented on src/NetworkPort.php
> +                //FIXME This seems prone to false positives. Assume that networkports_id_list is a JSON array. Searching %1% would match 1, 10, 31, 100, etc.
Values are surrounded by quotes, so searching for 1 will be done using `%"1"%` and would not match `"10"` nor `"31"`.
```suggestion
```

2024-05-13 12:57 UTC, cedric-anne requested changes

2024-05-14 06:56 UTC, cedric-anne approved these changes

2024-05-14 06:57 UTC, merged