Use Monaco for legacy API examples
glpi-project/glpi pull request #17060
Opened 2024-05-02 18:49 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Companion PR to #17059. If both PRs are approved, we should have nothing left using PrismJS in the core and it could be removed.
The trade-off in this PR is that Apache and NGINX config examples at the end of the documentation have no language support. In both cases, it is custom syntax.

For the Apache config, everything is commented out anyways so syntax highlighting doesn't really matter. We could trick it into highlighting by choosing any language with a `#` comment character.
For NGINX, the example as written looks mostly good if highlighted as GraphQL, but may look wrong to anyone that actually knows NGINX configs (not me).

Neither of the above workarounds are currently present in this PR.

2024-05-02 18:51 UTC, cconard96 commented
NGINX config rendered with GraphQL language:
![Selection_315](https://github.com/glpi-project/glpi/assets/17678637/54892ef2-330a-4f34-9c9c-639d7768ad73)

2024-05-06 08:22 UTC, orthagh requested changes
On my side, I have bad contrast rendering:
![image](https://github.com/glpi-project/glpi/assets/418844/b4cba637-0123-446a-9af2-77e868fdd70c)

2024-05-06 09:23 UTC, cconard96 commented
> On my side, I have bad contrast rendering

Cache issue? I changed the background color being used by tabler for `pre` elements in this PR.

2024-05-06 10:15 UTC, orthagh commented
You're right, it was cache.

2024-05-06 10:15 UTC, orthagh approved these changes

2024-05-06 10:34 UTC, cedric-anne approved these changes

2024-05-06 10:34 UTC, merged