Handle toast message content better
glpi-project/glpi pull request #17098
Opened 2024-05-11 02:20 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

2024-05-13 12:45 UTC, orthagh approved these changes

2024-05-13 13:20 UTC, cedric-anne requested changes

2024-05-13 13:20 UTC, cedric-anne commented on src/User.php
>          }
These error messages should not be encoded here. Indeed, this method is used in multiple contexts, and it is preferable to encode these error in the caller context, when it is necessary.

2024-05-13 13:26 UTC, cedric-anne commented on src/User.php
>          }
Fixed in latest commit.

2024-05-14 06:23 UTC, trasher approved these changes

2024-05-14 06:23 UTC, merged