greater flexibility for locked tickets
glpi-project/glpi pull request #17099
Opened 2024-05-12 02:18 UTC by oneabrante

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

The current dynamics of blocking tickets becomes somewhat "bureaucratic", laborious and tiring for whoever is managing/forwarding the tickets, whether to another group, technician or being in charge. I am currently experiencing a scenario in which the current ticket blocking configuration has become a separate challenge in terms of bringing more ease and speed to blocked tickets.

Fixed configuration:
- In general configuration > Use blocking: Enabled, List of items to be blocked: Tickets.
- In default values ​​> Auto blocking mode: Disabled, Direct notification: Disabled.

The scenario was this:
When the technician requested writing in the ticket, the standard editing options were enabled, as shown in the image below.

![init_0](https://github.com/glpi-project/glpi/assets/89171200/5a71c0b0-53c5-4c91-b630-3f4e849c6732)

In this case, if for example a page was reloaded, or if a specific group was assigned, as well as the technician himself being in charge of the ticket, the blocking model was provided and thus the editing of the ticket with the standard update fields were no longer enabled.

![ant_1](https://github.com/glpi-project/glpi/assets/89171200/02799749-7379-42a0-a149-64e8b53768a8)

Other than that, to unblock tickets, 2 modes are called requesting confirmation from the technician and to reload the page. I believe that this situation, when we have a lot of assistance throughout the day, where we have a predicted pattern based on ticket blocking, becomes an arduous task.
With this in mind, I implemented a suggestion to bring greater flexibility to allow editing of the ticket by the author of the block, as well as the removal of both modes when unlocking the ticket.

![pos_1](https://github.com/glpi-project/glpi/assets/89171200/2e6802a4-0da1-4a2c-953a-2fe331057218)

2024-05-13 12:40 UTC, orthagh requested changes
I don't want to be rash @oneabrante, but your current PR is unreviewable.
The proposed actual changes (see the relative tab in github UI) are invisible due to a lot of unwanted changes (modifications of copyright header, removal of global comments, moving to majuscules, etc).

Please, restrict the changes to the behavior you want to propose for locks and nothin else.
I'll let a bit of time to make a better proposition, after a few weeks, we'll close.

2024-05-13 12:41 UTC, orthagh commented
And please target `main` branch as `10.0/bugfixes` will not receive any changes of behavior nor features.

2024-05-16 03:04 UTC, oneabrante reviewed
Done

2024-05-27 09:55 UTC, cedric-anne requested changes
The proposed code does not seesm to be compatible with the recent refactoring of the feature made in #16538.

2024-05-27 09:55 UTC, cedric-anne commented on src/Group_User.php
> +            $header_end    .= "</th>";
This change does not seems to be related to the proposed functional change.

2024-05-27 09:55 UTC, cedric-anne commented on src/Html.php
> +               paste_webkit_styles: 'all',
This change does not seems to be related to the proposed functional change.

2024-05-27 09:55 UTC, cedric-anne commented on src/ObjectLock.php
> +    }
These methods are not used anymore since #16538.

2024-05-27 09:55 UTC, cedric-anne commented on src/ObjectLock.php
> +            </a>";
Since #16538, most of the front code has been moved in a dedicated JS files and a dedicated Twig template.

2025-01-16 14:16 UTC, closed without merging

2025-01-16 14:16 UTC, cedric-anne commented
This PR has to many conflicts with the main branch to be reviewed. I am closing it. Feel free to reopen it if you want this enhancement to be integrated in the next major version of GLPI.