feat(forms): Adding dropdown category and related sub question type
glpi-project/glpi pull request #17126
Opened 2024-05-15 13:31 UTC by ccailly

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 

Added `Dropdown` category and related sub-question type : `Dropdown`

Form editor view :
![image](https://github.com/glpi-project/glpi/assets/42278610/5e142b1f-a2e5-4680-9984-a2dea3a41dc3)
![image](https://github.com/glpi-project/glpi/assets/42278610/02174ed3-e50b-4161-b429-eb5344d27db4)

Form end user view :
![image](https://github.com/glpi-project/glpi/assets/42278610/394251b8-db00-470b-88e4-26bff2840ea2)

2024-05-22 07:41 UTC, AdrienClairembault requested changes
Two small bugs I've found:

### 1\) Wrong input name

![image](https://github.com/glpi-project/glpi/assets/42734840/f9b94aea-c81a-4c0f-9ec1-e0fc524b6797)

Should be answers_141 since we switched to the new format.
This mean answers are not taken into account for this question type.

### 2\) Invalid order

![image](https://github.com/glpi-project/glpi/assets/42734840/8774e81b-53ff-4452-bcb8-ccb8ba39a1c2)

![image](https://github.com/glpi-project/glpi/assets/42734840/5e434096-460f-4704-90ad-a5659f41b49c)

It seems the dropdown is not refreshed after options order are modified using drag and drop.

The "old" order is still displayed until we do another action like changing the default value.

2024-05-22 07:41 UTC, AdrienClairembault commented on src/Form/QuestionType/AbstractQuestionTypeSelectable.php
> +                    aria-label="{{ __('Move option') }}"
Translation in inline twig templates are not detected by our extraction tool.
We need to generate them in the PHP code and pass the value to the template.

2024-05-22 07:41 UTC, AdrienClairembault commented on src/Form/QuestionType/AbstractQuestionTypeSelectable.php
> +                    aria-label="{{ __('Default option') }}"
Same here.

2024-05-22 07:41 UTC, AdrienClairembault commented on src/Form/QuestionType/AbstractQuestionTypeSelectable.php
> +                    aria-label="{{ __('Selectable option') }}"
Same here.

2024-05-22 07:41 UTC, AdrienClairembault commented on src/Form/QuestionType/AbstractQuestionTypeSelectable.php
> +                    aria-label="{{ __('Remove option') }}"
Same here.

2024-05-22 13:40 UTC, AdrienClairembault approved these changes

2024-05-22 14:33 UTC, cedric-anne commented on src/Form/QuestionType/QuestionTypeDropdown.php
> +    public function getFooterScript(): string
I think it is not publicly used.
```suggestion
    protected function getFooterScript(): string
```

2024-05-22 14:33 UTC, cedric-anne commented on js/form_question_dropdown.js
> +                this.#updateInputType(this._inputType);
Cahnging the `_inputType` property should be done in the `#updateInputType()` method
```suggestion
                this.#updateInputType(event.target.checked ? 'checkbox' : 'radio');
```

2024-05-22 14:33 UTC, cedric-anne commented on js/form_question_dropdown.js
> +        this._container.closest('[data-glpi-form-editor-question-type-specific]')
```suggestion
        this._inputType = inputType;
        this._container.closest('[data-glpi-form-editor-question-type-specific]')
```

2024-05-22 14:33 UTC, cedric-anne commented on src/Form/QuestionType/AbstractQuestionTypeSelectable.php
> +    public function getFooterScript(): string
```suggestion
    protected function getFooterScript(): string
```

2024-05-22 14:33 UTC, cedric-anne commented on templates/pages/admin/form/form_question.html.twig
> +    aria-label="{{ question is not null ? question.fields.name|e('html_attr') : __('New question') }}"
See #17147
```suggestion
    aria-label="{{ question is not null ? question.fields.name : __('New question') }}"
```

2024-05-22 14:33 UTC, cedric-anne commented on js/form_editor_controller.js
> +                postfix = field.match(/\[([\w-[\]]*)\]$/g);
1. Pattern could be placed in a constant.
2. The `RegExp.test()` method could be used in the `if` condition.
```suggestion
            cons postfix_pattern = new RegExp('\[([\w-\[\]]*)\]$', 'g');
            if (typeof field === 'string' && postfix_pattern.test(field)) {
                postfix = field.match(postfix_pattern);
```

2024-05-22 14:43 UTC, orthagh commented
(opinion based on the provided screenshots)
I feel the design choice when checking multiple flag to switch between radio or checkboxes for options lead to a bad understanding. At least it took a few seconds to understand the options will be displayed in a real dropdown. I almost made a comment about why call it dropdown.

I think in this particular case of dropdown, you should not decorate options at all. More, there is the drag icon, so 2 icons on the left of the options

Ideas for alternative ux:

- select2 tokenisation (may not work without multiple select)
- modal with a [new option] link right to the dropdown
- keep the same design (without decoration), but make options list like it's the dropdown opened (check this [link](https://forum.smartflowsheet.com/support/solutions/articles/5000594816-how-do-i-add-delete-options-in-the-dropdown-picker-list-and-group-parameters-))

2024-05-30 09:48 UTC, ccailly commented
![Capture d’écran du 2024-05-30 11-29-49](https://github.com/glpi-project/glpi/assets/42278610/b95217f3-7c92-4c79-b02a-d64fa5e5da0c)

2024-06-11 08:38 UTC, ccailly commented
![image](https://github.com/glpi-project/glpi/assets/42278610/59262de8-d748-4295-bf46-84c3c7f7a4f6)

2024-06-11 09:07 UTC, cedric-anne commented
@AdrienClairembault @orthagh
Is this OK for you now?

2024-06-11 10:08 UTC, AdrienClairembault requested changes
UI is good now.
Some changes requested for the code.

2024-06-11 10:08 UTC, AdrienClairembault commented on src/Glpi/Form/QuestionType/AbstractQuestionTypeActors.php
> +    public function renderAdministrationTemplate(?Question $question, array $params = []): string
This way the relevant code is only stored in `AbstractQuestionTypeSelectable` and does not impact all questions for something that don't use.

2024-06-24 12:46 UTC, AdrienClairembault approved these changes

2024-07-01 09:21 UTC, cedric-anne reviewed
Seems globally OK, I just made a few minor remarks.

2024-07-01 09:21 UTC, cedric-anne commented on tests/cypress/e2e/form/question_types/dropdown.cy.js
> +        checkOptionLabels(["Option 1", "Option 2", "Option 3"]);
Not a blocker, but, IMHO, when we switch from multiple to single value dropdonw, we should do this:
- if there are multiple values selected, all should be deselected,
- if there is a unique value selected, it should remain selected.

2024-07-01 09:50 UTC, orthagh approved these changes
As discussed together, the current design still has flaws (particularly choosing the default value dropdown, covering the rest of the design, leads to a strange state).
But they may be addressed later, especially with the right panel discussed many times.

Some I agree we're ok for this PR.

2024-07-01 15:01 UTC, cedric-anne approved these changes

2024-07-01 15:01 UTC, merged