Add form tag providers
glpi-project/glpi pull request #17143
Opened 2024-05-17 15:06 UTC by AdrienClairembault

Draft

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |

2024-05-21 13:51 UTC, cedric-anne requested changes

2024-05-21 13:51 UTC, cedric-anne commented on src/Form/Tag/AnswerTagProvider.php
> +                label: "Answer: {$questions->fields['name']}",
It should be translated.
```suggestion
                label: sprintf(__('Answer: %s'), $questions->fields['name']),
```

2024-05-21 14:09 UTC, AdrienClairembault commented on src/Form/Tag/Tag.php
> +            "data-form-tag-provider" => $provider,
I completely missed that, good catch.
I've updated the test, it should now fail if we forget to whitelist any futures attributes.

2024-05-22 06:19 UTC, cedric-anne approved these changes

2024-05-22 07:06 UTC, merged