Fix(Agent): fix CSS and readonly input
glpi-project/glpi pull request #17167
Opened 2024-05-22 14:50 UTC by stonebuzz

Before : 

![image](https://github.com/glpi-project/glpi/assets/7335054/edafa70f-4fe7-4857-9074-304fab9729b9)

After : 

![image](https://github.com/glpi-project/glpi/assets/7335054/572b5c15-3075-4b3f-9c34-6c75659ff98d)

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

2024-05-22 14:51 UTC, orthagh approved these changes

2024-05-23 06:21 UTC, trasher commented on templates/pages/admin/inventory/agent.html.twig
> +                        __('Agent type'),
```suggestion
                        _n('Agent type', 'Agents types', 1),
```

2024-05-23 06:21 UTC, trasher approved these changes

2024-05-23 06:37 UTC, cedric-anne requested changes

2024-05-23 06:37 UTC, cedric-anne commented on templates/pages/admin/inventory/agent.html.twig
> +                        call(item.fields['itemtype'] ~ '::getTypeName', [0]),
There is a Twig filter for this.
```suggestion
                        item.fields['itemtype']|itemtype_name,
```

2024-05-23 06:37 UTC, cedric-anne commented on templates/pages/admin/inventory/agent.html.twig
> +                            <span class="form-help" data-bs-toggle="popover" data-bs-placement="top" data-bs-html="true" data-bs-content="<i> {{ __('When reported by GLPI agent via native inventory')
I think that HTML tags should be escaped inside the attribute value.
```suggestion
                            <span class="form-help" data-bs-toggle="popover" data-bs-placement="top" data-bs-html="true" data-bs-content="{{ '<i>' ~ __('When reported by GLPI agent via native inventory') ~ '</i>' }}">?</span>
```

2024-05-23 06:37 UTC, cedric-anne commented on templates/pages/admin/inventory/agent.html.twig
> +                        call('Dropdown::getDropdownName', ["glpi_agenttypes", item.fields['agenttypes_id']]),
There is a Twig function for this.
```suggestion
                        get_item_name('AgentType', item.fields['agenttypes_id']),
```

2024-05-23 06:37 UTC, cedric-anne commented on templates/pages/admin/inventory/agent.html.twig
> +      {% endif %}
```suggestion
```

2024-05-23 06:37 UTC, cedric-anne commented on templates/pages/admin/inventory/agent.html.twig
> +   {% set item_has_pictures = item.hasItemtypeOrModelPictures() %}
The code related to pictures could be cleaned. Agent has no pictures.
```suggestion
```

2024-05-23 06:37 UTC, cedric-anne commented on templates/pages/admin/inventory/agent.html.twig
> +      <div class="col-12 col-xxl-{{ item_has_pictures ? '9' : '12' }} flex-column">
```suggestion
      <div class="col-12 flex-column">
```

2024-05-23 06:37 UTC, cedric-anne commented on templates/pages/admin/inventory/agent.html.twig
> +   {% endif %}
```suggestion
```

2024-05-23 06:37 UTC, cedric-anne commented on templates/pages/admin/inventory/agent.html.twig
> +   {% endif %}
```suggestion
```

2024-05-23 08:04 UTC, cedric-anne approved these changes

2024-05-23 09:09 UTC, merged