feat(forms): Add cron task to purge old form drafts
glpi-project/glpi pull request #17171
Opened 2024-05-23 09:41 UTC by ccailly

| Q | A
|------------- | --- 
| Bug fix?      | no 
| New feature?  | yes 
| BC breaks?    | no 
| Deprecations? | no 
| Tests pass?   | yes 
| Fixed tickets |

When a user creates a form, the object is directly created in base with the `draft` flag.
If the user doesn't save the form, the object will remain in base but will no longer be accessible.
This task deletes old draft forms.

2024-05-23 09:56 UTC, AdrienClairembault submitted a review, later dismissed
You'll need to delete the old code in `front/from.form.from.php`:

![image](https://github.com/glpi-project/glpi/assets/42734840/4b6e8f8b-25ff-4fc9-a9df-6dbc52ce979a)

2024-05-23 09:56 UTC, AdrienClairembault commented on src/Form/Form.php
> +            'date_mod' => ['<', date('Y-m-d H:i:s', strtotime('-1 day'))],
I would prefer a few more days to be extra safe (original code was 7 days).

```suggestion
            'date_mod' => ['<', date('Y-m-d H:i:s', strtotime('-7 day'))],
```

2024-05-29 06:52 UTC, cedric-anne requested changes
The cron `param` could be used to adjust the retention period of the drafts.

2024-05-29 06:52 UTC, cedric-anne commented on install/empty_data.php
> +                'param' => 30,
```suggestion
                'param' => 7,
```

2024-05-29 06:52 UTC, cedric-anne commented on install/migrations/update_10.0.x_to_11.0.0/form.php
> +    'param'         => 30
```suggestion
    'param'         => 7
```

2024-05-29 06:52 UTC, cedric-anne commented on src/Form/Form.php
> +    public static function cronPurgeDraftForms($task = null)
```suggestion
    public static function cronPurgeDraftForms(CronTask $task): int
```

2024-05-29 06:52 UTC, cedric-anne commented on src/Form/Form.php
> +        ], true);
```suggestion
        $delay = (int) $task->fields['param'];
        $form = new Form();
        $form->deleteByCriteria([
            'is_draft' => 1,
            'date_mod' => ['<', date('Y-m-d H:i:s', strtotime(sprintf('-%d day', $delay)))],
        ], true);
```

2024-05-29 06:52 UTC, cedric-anne commented on src/Form/Form.php
> +        return ['description' => __('Purge old form drafts')];
```suggestion
        return [
            'description' => __('Purge old form drafts'),
            'parameter'   => __('Form drafts retention period (in days)'),
        ];
```

2024-05-29 08:17 UTC, cedric-anne approved these changes

2024-05-29 08:35 UTC, merged