Notification target contract add tags
glpi-project/glpi pull request #17248
Opened 2024-06-04 15:22 UTC by Mirkk

For contract notifications, there is actually only one Tag contract.time that holds either the notice time or the end time.
However it is also sometimes needed to write both dates. This modification adds the contract.noticetime and contract.endtime Tags. The labels used are the ones already in use and thus translated. The tags are shown also on the tags helper page when editing the notification template.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | none

2024-06-11 09:09 UTC, cedric-anne requested changes
Tests are failing.

2025-02-06 09:49 UTC, Mirkk commented
Hello @cedric-anne sorry that I left this here for so long time, but it is still actual for me, and surely also for others that need to write complete notifications for contracts. Would it be possiblle to re-run the checks? There are no more details visible on what has failed in the two checks that were not successful.
Thanks!

2025-02-06 10:00 UTC, trasher commented
You'd better rebase your branch on an up-to-date 10.0/bugfixes; this will trigger tests.

2025-02-07 14:41 UTC, Mirkk commented
Sorry @trasher now I updated to the main branch and all 2000 commits are shown here. 
However, I foud the errors in the tests. Once corrected, I think I will better open a new PR.

2025-02-07 15:38 UTC, trasher commented
> now I updated to the main branch [...]

I've updated target branch on the PR.

2025-02-11 06:34 UTC, trasher approved these changes
lgtm

2025-02-11 07:07 UTC, cedric-anne commented on src/NotificationTargetContract.php
> +            'contract.noticetime'   => __('Contract with notice since the'),
Thsi value will be available even before the contract expiration date, in this case, the contract will not yet be expired.

```suggestion
            'contract.endtime'      => __('Contract expiration date'),
            'contract.noticetime'   => __('Contract notice date'),
```

2025-02-11 07:24 UTC, trasher commented on src/NotificationTargetContract.php
> +            'contract.noticetime'   => __('Contract with notice since the'),
@cedric-anne if we change here, we must change also other existing strings

2025-02-11 07:30 UTC, cedric-anne commented on src/NotificationTargetContract.php
> +            'contract.noticetime'   => __('Contract with notice since the'),
`contract.time` value is only defined when the contract is already expired or the notice period has already been reached.

https://github.com/glpi-project/glpi/blob/f1d7e39171583c89a070c67ec5c6f2aaf3ab450f/src/NotificationTargetContract.php#L103-L116

2025-02-11 08:45 UTC, Mirkk commented on src/NotificationTargetContract.php
> +            'contract.noticetime'   => __('Contract with notice since the'),
Thank you @cedric-anne , "Contract expiration date" and "Contract notice date" are surely better labels. I used the other ones because they were already available & translated.  I commit your suggestion.

2025-02-11 09:09 UTC, cedric-anne approved these changes

2025-02-11 09:28 UTC, trasher approved these changes

2025-02-11 09:41 UTC, merged