Impact - Add Label for Edge
glpi-project/glpi pull request #17335
Opened 2024-06-20 17:37 UTC by tsmr

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

Impact - Add Label for Edges on Cytoscape display

2024-06-20 23:13 UTC, cconard96 commented on js/impact.js
> +                    "text-margin-y": "0px"
Labels may look better with text-margin-y: -10px

2024-06-24 09:28 UTC, orthagh approved these changes
Ok for adding the feature (I didn't review the changes)

2024-06-24 10:32 UTC, cedric-anne requested changes

2024-06-24 10:32 UTC, cedric-anne commented on js/impact.js
> +                tooltipText    : _.unescape(__("Set name for this edge")),
Special chars should be escaped, even on translations.
```suggestion
                content        : '<i class="fas fa-edit me-2"></i>' + _.escape(__("Edge properties...")),
                tooltipText    : _.escape(__("Set name for this edge")),
```

2024-06-24 10:32 UTC, cedric-anne commented on install/migrations/update_10.0.15_to_10.0.16/impactrelations.php
This file should be moved to the 10.0.x->11.0.0 migrations directory.

2024-06-24 11:57 UTC, AdrienClairembault requested changes

2024-06-24 11:57 UTC, AdrienClairembault commented on install/migrations/update_10.0.15_to_10.0.16/impactrelations.php
> +]);
```suggestion
$migration->addField('glpi_impactrelations', 'name', "string", [
    'after'  => 'id',
    'value' => '',
]);
```

We try to use the "official" fields format defined in `migration->fieldFormat()` if possible.
The `string` format would be fine here I think.

2024-06-24 11:57 UTC, AdrienClairembault commented on src/Impact.php
> +        $label
```suggestion
        string $label
```

2024-06-24 11:57 UTC, AdrienClairembault commented on js/impact.js
> +    ACTION_EDIT_EDGE                    : 15,
I think we need to take this new action into account in the `undo` and `redo` functions.

2024-06-26 07:01 UTC, AdrienClairembault approved these changes
Looks good to me.

2024-06-26 14:16 UTC, cedric-anne commented on templates/impact/edit_edge_modal.html.twig
> +                <button type="button" class="btn btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
```suggestion
                <button type="button" class="btn btn-close" data-bs-dismiss="modal" aria-label="{{ _('Close') }}"></button>
```

2024-06-26 14:18 UTC, cedric-anne commented on src/Impact.php
> +    public static function printEditEdgeDialog()
```suggestion
     */
    private static function printEditEdgeDialog(): void
```

2024-06-26 14:19 UTC, cedric-anne approved these changes
Seems OK, but I did not take time to test it.

2024-06-26 19:29 UTC, cedric-anne commented on templates/impact/edit_edge_modal.html.twig
> +                <button type="button" class="btn btn-close" data-bs-dismiss="modal" aria-label="{{ _('Close') }}"></button>
```suggestion
                <button type="button" class="btn btn-close" data-bs-dismiss="modal" aria-label="{{ __('Close') }}"></button>
```

2024-06-26 20:54 UTC, merged