Feat print as pdf
glpi-project/glpi pull request #17354
Opened 2024-06-25 12:14 UTC by Lainow

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 

Ability to export (print) object information in PDF format for example (like a Control + p)

2024-07-05 13:05 UTC, stonebuzz requested changes

2024-07-05 13:05 UTC, stonebuzz commented on src/PrintPreview.php
> +    }
the `history` tab should not be printable (IMHO) (the data is already exportable in the dedicated tab) and with a large volume of data we'll certainly have loading problems

2024-07-05 13:05 UTC, stonebuzz commented on src/PrintPreview.php
> +    public static function showPreview($ID, $options = [])
bad renderer about input file (`Software`)

![image](https://github.com/glpi-project/glpi/assets/7335054/f7f5365e-f6b1-470c-acfd-e87db8d22fbf)

2024-07-05 13:05 UTC, stonebuzz commented on src/PrintPreview.php
> +    public static function showPreview($ID, $options = [])
The portrait format gives me doubts about the display of tables (I don't think there's anything we can do about it).

maybe we should force landscape mode (or manage both)

@orthagh  what do you think?  

![image](https://github.com/glpi-project/glpi/assets/7335054/e007a60e-cbcf-49b3-b162-75b5911dda2e)

2024-07-05 13:19 UTC, Lainow commented on src/PrintPreview.php
> +                ]);
Yes, at the moment the composent tab doesn't work.

2024-07-05 13:22 UTC, orthagh commented on src/PrintPreview.php
> +    public static function showPreview($ID, $options = [])
> I don't think there's anything we can do about it

We already discussed that with @Lainow, you can use responsive design and move the table columns in rows
ex: https://stackoverflow.com/questions/32301206/how-to-fold-table-columns-into-rows-on-mobile-devices

2024-08-23 06:53 UTC, stonebuzz commented
- When debug mode is enable, it's visible in the browser preview (not the generated one)

![image](https://github.com/user-attachments/assets/8f8e3266-40e3-4054-9135-f8f60298fc5b)

- The textarea resize icon is visible

![image](https://github.com/user-attachments/assets/b7e66eb2-1943-4e1e-a2a7-2236d65ad0f4)

- From table (component etc ..) 'Update' should be remove (to gain space)

![image](https://github.com/user-attachments/assets/d3e2293e-c7cc-4c97-aff1-88f66b46bd83)

 - I was thinking of removing the software part, but I think it should be kept (but not active by default).

- Rule import logs should be removed

- As seen together, the 'print preview' tab should be removed (it facilitates dev).

- In general, we need to improve the rendering of tables (reduce space, remove unnecessary columns, etc.).

2024-09-10 13:58 UTC, cconard96 requested changes

2024-09-10 13:58 UTC, cconard96 commented on js/PrintPreview/print_asset.js
> +    var preview = document.querySelector('.preview');
```suggestion
    const preview = document.querySelector('.preview');
```

2024-09-10 13:58 UTC, cconard96 commented on js/PrintPreview/print_asset.js
> +        var tables = preview.querySelectorAll('table, .table');
```suggestion
        const tables = preview.querySelectorAll('table, .table');
```

2024-09-10 13:58 UTC, cconard96 commented on js/PrintPreview/print_asset.js
> +                    var remainingCells = Array.from(row.querySelectorAll('th, td'));
```suggestion
                    const remainingCells = Array.from(row.querySelectorAll('th, td'));
```

2024-09-10 13:58 UTC, cconard96 commented on js/PrintPreview/print_asset.js
> +                    var remainder = 55 % remainingCells.length;
```suggestion
                    const remainder = 55 % remainingCells.length;
```

2024-09-10 13:58 UTC, cconard96 commented on js/PrintPreview/print_asset.js
> +                        var baseColspan = 55;
```suggestion
                        const baseColspan = 55;
```

2024-09-10 13:58 UTC, cconard96 commented on js/PrintPreview/print_asset.js
> +                        var colspan = baseColspan;
```suggestion
                        let colspan = baseColspan;
```

2024-09-10 13:58 UTC, cconard96 commented on js/PrintPreview/print_asset.js
> +            var span = document.createElement('span');
```suggestion
            const span = document.createElement('span');
```

2024-09-10 13:58 UTC, cconard96 commented on js/PrintPreview/print_asset.js
> +            var inlineStyle = input.getAttribute('style');
```suggestion
            const inlineStyle = input.getAttribute('style');
```

2024-09-10 13:58 UTC, cconard96 commented on js/PrintPreview/print_asset.js
> +                var backgroundColorMatch = inlineStyle.match(/background-color:\s*([^;]+);?/);
```suggestion
                const backgroundColorMatch = inlineStyle.match(/background-color:\s*([^;]+);?/);
```

2024-09-10 13:58 UTC, cconard96 commented on js/PrintPreview/print_asset.js
> +                    var colorBox = document.createElement('div');
```suggestion
                    const colorBox = document.createElement('div');
```

2024-09-10 13:58 UTC, cconard96 commented on js/PrintPreview/print_asset.js
> +            var parentSpan = renderedSpan.closest('span.select2-selection.select2-selection--single');
```suggestion
            const parentSpan = renderedSpan.closest('span.select2-selection.select2-selection--single');
```

2024-09-10 13:58 UTC, cconard96 commented on js/PrintPreview/print_asset.js
> +                var newSpan = document.createElement('span');
```suggestion
                const newSpan = document.createElement('span');
```

2024-09-10 13:58 UTC, cconard96 commented on js/PrintPreview/print_asset.js
> +            var onchangeAttr = select.getAttribute('onchange');
```suggestion
            const onchangeAttr = select.getAttribute('onchange');
```

2024-09-10 13:58 UTC, cconard96 commented on js/PrintPreview/print_asset.js
> +                var parentDiv = select.closest('div');
```suggestion
                const parentDiv = select.closest('div');
```

2024-09-10 13:58 UTC, cconard96 commented on js/PrintPreview/print_asset.js
> +            var modal = form.querySelector('.modal-dialog');
```suggestion
            const modal = form.querySelector('.modal-dialog');
```

2024-09-10 13:58 UTC, cconard96 commented on js/PrintPreview/print_asset.js
> +        var form = document.querySelector('form[name^="massaction"]');
```suggestion
        const form = document.querySelector('form[name^="massaction"]');
```

2024-09-10 13:58 UTC, cconard96 commented on js/PrintPreview/print_monitor.js
> +$(function() {
For all "var" uses, they should be replaced with const or let.

2024-09-10 13:58 UTC, cconard96 commented on js/PrintPreview/print_software.js
> +
For all "var" uses, they should be replaced with const or let.

2024-09-10 13:58 UTC, cconard96 commented on js/PrintPreview/print_software.js
> +                spanElement.textContent = helpdeskCheckbox.checked ? 'Yes' : 'No';
Should be translated?

2024-09-10 13:58 UTC, cconard96 commented on js/PrintPreview/print_software.js
> +                    spanElement.textContent = 'Yes from';
Should be translated?

2024-09-10 13:58 UTC, cconard96 commented on src/CommonDBRelation.php
> +            return static::$itemtype_1::getIcon();
This seems wrong to return the icon.
Also not sure relation classes should automatically use the name of one of the linked types by default.

2024-10-08 10:45 UTC, cconard96 requested changes

2024-10-08 10:45 UTC, cconard96 commented on js/PrintPreview/print_monitor.js
> +$(function() {
This is still relevant

2024-10-08 10:45 UTC, cconard96 commented on js/PrintPreview/print_software.js
> +
This is still relevant

2024-10-08 10:45 UTC, cconard96 commented on src/PrintPreview.php
> +            $actions[$action_prefix . 'print_preview'] = '<i class="' . self::getIcon() . '"></i>' . __('Display to a printable view');
```suggestion
            $actions[$action_prefix . 'print_preview'] = '<i class="' . self::getIcon() . '"></i>' . __s('Display to a printable view');
```

2024-10-08 10:45 UTC, cconard96 commented on src/PrintPreview.php
> +            $label = '<span><i class="' . $itemtype::getIcon() . ' me-2"></i>' . $itemtype::getTypeName(0) . '</span>';
```suggestion
            $label = '<span><i class="' . $itemtype::getIcon() . ' me-2"></i>' . htmlspecialchars($itemtype::getTypeName(Session::getPluralNumber())) . '</span>';
```

2024-10-08 10:45 UTC, cconard96 commented on templates/components/form/fields_macros.html.twig
> +        {{ _self.htmlField(name, value, label, options) }}
Not sure this should be changed specifically for text fields. If the issue is the border in the print, it could be solved with CSS.

2024-10-08 10:45 UTC, cconard96 commented on templates/components/printpreview/asset_print_preview.html.twig
> +                        <i class="{{ call(key ~ '::getIcon') }}"></i> &nbsp {{ key == 'Item_Devices' ? 'Components' : call(key ~ '::getTypeName') }}
```suggestion
                        <i class="{{ key|itemtype_icon }}"></i>{{ key == 'Item_Devices' ? 'CommonDevice'|itemtype_name : key|itemtype_name }}
```

2024-10-08 10:45 UTC, cconard96 commented on templates/components/printpreview/asset_print_preview.html.twig
> +    console.log(jsFile);
```suggestion
```

2024-10-08 10:45 UTC, cconard96 commented on templates/components/printpreview/itil_print_preview.html.twig
> +                        <i class="{{ call(key ~ '::getIcon') }}"></i> &nbsp {{ key }}
```suggestion
                        <i class="{{ key|itemtype_icon }}"></i>{{ key|itemtype_name }}
```

2024-10-08 10:45 UTC, cconard96 commented on templates/components/printpreview/print_preview.html.twig
> +                console.log(modalDialogs);
```suggestion
```

2024-10-08 10:45 UTC, cconard96 commented on templates/components/printpreview/print_preview.html.twig
> +                    <i class="{{ call(item.getType() ~ '::getIcon') }}"></i> &nbsp {{ call(item.getType() ~ '::getTypeName') }}
```suggestion
                    <i class="{{ call(item.getIcon()) }}"></i>{{ item.getTypeName()) }}
```

2024-10-08 14:43 UTC, cconard96 requested changes

2024-10-08 14:43 UTC, cconard96 commented on js/PrintPreview/print_software.js
> +    var preview = document.querySelector('.preview');
```suggestion
    const preview = document.querySelector('.preview');
```

2024-10-08 14:43 UTC, cconard96 commented on js/PrintPreview/print_software.js
> +        var mainform = preview.querySelector('#main-form');
```suggestion
        const mainform = preview.querySelector('#main-form');
```

2024-10-08 14:43 UTC, cconard96 commented on js/PrintPreview/print_software.js
> +            var helpdeskCheckbox = mainform.querySelector('input[name="is_helpdesk_visible"]');
```suggestion
            const helpdeskCheckbox = mainform.querySelector('input[name="is_helpdesk_visible"]');
```

2024-10-08 14:43 UTC, cconard96 commented on js/PrintPreview/print_software.js
> +                var spanElement = document.createElement('span');
```suggestion
                const spanElement = document.createElement('span');
```

2024-10-08 14:43 UTC, cconard96 commented on js/PrintPreview/print_software.js
> +            var updateCheckbox = mainform.querySelector('input[name="is_update"][type="checkbox"]');
```suggestion
            const updateCheckbox = mainform.querySelector('input[name="is_update"][type="checkbox"]');
```

2024-10-08 14:43 UTC, cconard96 commented on js/PrintPreview/print_software.js
> +                    var spanElement2 = document.createElement('span');
```suggestion
                    const spanElement2 = document.createElement('span');
```

2024-10-08 14:43 UTC, cconard96 commented on js/PrintPreview/print_software.js
> +                    var nextSibling = spanElement2.nextSibling;
```suggestion
                    const nextSibling = spanElement2.nextSibling;
```

2024-10-08 14:43 UTC, cconard96 commented on js/PrintPreview/print_software.js
> +                    var parentDiv = updateCheckbox.closest('div');
```suggestion
                    const parentDiv = updateCheckbox.closest('div');
```

2024-10-14 10:42 UTC, cconard96 approved these changes

2025-03-17 09:23 UTC, Lainow commented
Not the right way to do it, you have to rethink the thing to find a better way to do it.

2025-03-17 09:23 UTC, closed without merging