Form destination auto config
glpi-project/glpi pull request #17367
Opened 2024-06-26 13:02 UTC by AdrienClairembault

Draft, waiting for dependencies to be merged (#17352 ).
Reviews can be done but only on the `Form destination auto config` commit.

---

Introduce the "auto config" feature on form destinations:

![image](https://github.com/glpi-project/glpi/assets/42734840/c73758a0-3d8d-4f1c-acc4-5ef8106cf8fa)

When a destination is created, all its fields are set as "auto configurated".
This mean that GLPI will pick the best value for each fields without the need for the user to manually edit them.

The goal here is that 95% of users will never need to change anything on this tab and thus can use forms destinations with little efforts.
The 5% remaining "power users" can still override the auto value and set their own values for super complex forms.

Right now we only have two fields but there will be a lot more in the final version (ticket category, location, urgency, linked items, ...).

---

To compare with formcreator, this feature did not exist which meant heavy configuration was needed for all forms.
For exemple if you added an "Urgency" question to your form, it would not be used in the created ticket unless you specified manually that the urgency must be set from the answer to a given question.

On native forms the auto config will do that by itself (once we have the urgency setting as it does not exist yet as mentioned before) .

This will be the same for every "not yet implemented" configuration fields that you can think of (ticket category, location, linked items, ...).

---

Another benefit is related to the `Content` field which can be "incrementally edited".

On formcreator you had a special `##fullform##` tag which was an "all or nothing" solution: either you rely on `fullform` to generate your ticket description or you had to write the whole description from zero.

On native forms you can see exactly the generated content with the questions and answers, which mean you can directly edit it to make some small changes like hiding a special question or adding a different formatting for a given answer.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |

2024-07-01 08:31 UTC, cedric-anne reviewed
Seems technically OK.

2024-07-01 08:31 UTC, cedric-anne commented on js/form_destination_auto_config_controller.js
> +            if (is_blacklisted) {
```suggestion
            const is_excluded = input.data('glpi-itildestination-toggle-do-not-disable') !== undefined;
            if (is_excluded) {
```

2024-07-01 08:31 UTC, cedric-anne commented on js/form_destination_auto_config_controller.js
> +            }
Can be simplified.
```suggestion
            input.prop('disabled', is_auto_config_enabled);
```

2024-07-01 08:31 UTC, cedric-anne commented on tests/cypress/e2e/form/form_destination.cy.js
> +                .should('have.text', "") // Empty because the form doens't have any questions
```suggestion
                .should('have.text', "") // Empty because the form doesn't have any questions
```

2024-07-01 09:26 UTC, orthagh requested changes
As discussed together, the current implementation slightly overloads UI for addressing advanced features (fullform improvement, default values for questions)
Suggestion to make a global auto-config toggle or limit it to only the content field.

Whatever the choice made, a form helper should explain how the automated choice is made

2024-07-03 09:03 UTC, AdrienClairembault commented
The new changes simplify the configuration even more by relying directly on default values when possible.
Complex fields like the ticket's content still allow an auto configuration.

![image](https://github.com/glpi-project/glpi/assets/42734840/cda13a4c-c9e9-4181-9c0a-1377749b55a2)

2024-07-03 09:04 UTC, orthagh approved these changes

2024-07-03 09:35 UTC, cedric-anne approved these changes
OK, but tests are failing.

2024-07-03 10:19 UTC, AdrienClairembault commented
I forgot to update another test that rely on the number of checkboxes being displayed on the page.
I'll use this occasion to improve the test to make it a bit less brittle.

2024-07-04 06:41 UTC, merged