Add AdditionalTargets For SoftwareLicense Alert
glpi-project/glpi pull request #17365
Opened 2024-06-26 10:28 UTC by tsmr

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

Add AdditionalTargets For SoftwareLicense Alert

2024-06-26 11:35 UTC, orthagh approved these changes

2024-06-26 11:52 UTC, cedric-anne reviewed
IMHO, it will not work as expected. Indeed, this alert may be related to multiple licences, and I am not sure that the notification logic will be able to find the tech/group in charge with the provided data.

2024-06-26 11:52 UTC, trasher approved these changes

2024-06-26 11:53 UTC, cedric-anne requested changes
It will indeed not work. See discussions in #13774 and #13789.

2024-06-26 15:01 UTC, tsmr commented
I understand. Like certificates, recipients of the alert will receive all expired certificates and not just those for which they are responsible?

2024-06-26 21:01 UTC, cedric-anne commented
My point is that this code will not work. Indeed, the notification is created by `NotificationEvent::raiseEvent('alert', new self(), $options)`, meaning that the `$target_object` of the `NotificationTarget` will be an empty `SoftwareLicense` item. The id of the tech/group in charge is fetched from this `$target_object`, so this id will always be unset/0.

2025-01-16 14:07 UTC, cedric-anne commented
This PR seems stale, I close it.

2025-01-16 14:07 UTC, closed without merging