(Enhancement) Antivirus item twig update
glpi-project/glpi pull request #17409
Opened 2024-07-02 13:03 UTC by Lainow

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 

I need it for the print preview functionality because some tables are in twig and others are not, which makes the preview display complicated to modify effectively.

**Before**
![image](https://github.com/glpi-project/glpi/assets/107540223/513df9d2-4853-48e2-b3d9-4e06e9b13176)

**After**
![image](https://github.com/glpi-project/glpi/assets/107540223/f09e945a-b8eb-4072-8cc3-9f2f6a96ffc2)

2024-07-02 13:08 UTC, cconard96 approved these changes

2024-07-02 13:08 UTC, cconard96 commented on templates/components/form/item_antivirus_item.html.twig
> +    <div class='center firstbloc'>
```suggestion
    <div class='text-center mb-3'>
```
Should use standard bootstrap/tabler classes instead of the old GLPI-specific ones.

2024-07-02 13:08 UTC, cconard96 commented on src/ItemAntivirus.php
> +                'manufacturers_id' => 'raw_html',
`date_expiration` should use the `date` formatter (or `datetime` if it includes time).

2024-07-02 13:08 UTC, cconard96 commented on src/ItemAntivirus.php
> +                'date_expiration' => Html::convDate($data['date_expiration']),
Date formatting should be done in Twig via the `date` or `datetime` formatter for the datatable template.

2024-07-02 13:09 UTC, cconard96 requested changes
See previous comments. Accidentally approved instead of requesting changes.

2024-07-02 14:43 UTC, orthagh approved these changes

2024-07-03 05:47 UTC, trasher approved these changes

2024-07-03 06:19 UTC, cedric-anne approved these changes

2024-07-03 06:19 UTC, merged