(enhancement) ItemVirtualMachine twig update
glpi-project/glpi pull request #17405
Opened 2024-07-01 14:49 UTC by Lainow

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 

I need it for the print preview functionality because some tables are in twig and others are not, which makes the preview display complicated to modify effectively.

**Before**
![image](https://github.com/glpi-project/glpi/assets/107540223/f12f8553-cd12-4e19-b386-2fe12f1d1083)

**After**
![image](https://github.com/glpi-project/glpi/assets/107540223/558ff92e-6b6a-4864-9245-6ea315ae88ec)

2024-07-01 15:01 UTC, cconard96 requested changes

2024-07-01 15:01 UTC, cconard96 commented on templates/components/form/item_virtualmachine.html.twig
> +            <a class='btn btn-primary' href='{{ vmformurl }}'>
Typically, I've been changing the list UI to show forms like this directly in the page with the list if they don't have a ton of fields.
If this remains as an anchor tag though, it needs `role="button"`.

2024-07-01 15:01 UTC, cconard96 commented on templates/components/form/item_virtualmachine.html.twig
> +        <div class='alert alert-info'>
Should use the macro from `templates/components/alerts_macros.html.twig` to standardize the display of alerts.

2024-07-02 09:44 UTC, cconard96 commented on templates/components/form/item_virtualmachine.html.twig
> +            <a class='btn btn-primary' href='{{ vmformurl }}' >
Adding `role="button"` is still relevant for accessibility.

2024-07-02 12:06 UTC, cconard96 approved these changes

2024-07-02 13:26 UTC, cconard96 approved these changes

2024-07-03 06:23 UTC, cedric-anne requested changes

2024-07-03 06:23 UTC, cedric-anne commented on src/ItemVirtualMachine.php
>                      }
I guess `$computer->can($host['items_id'], READ)` may return a different result for each row. In this case, you will have a mix of entries with 4 columns and entries with 2 columns. Also, `$columns` is redefined on each loop iteration.

IMHO, `$columns` should be defined once, and then every entries should contain the 4 columns (with empty values if they should ot be readable).

2024-07-03 06:56 UTC, AdrienClairembault approved these changes
Ok for me with suggested changes from @cedric-anne.

2024-07-03 10:32 UTC, cedric-anne requested changes
Should `NOT_AVAILABLE` be displayed instead of empty values ?

2024-07-03 10:32 UTC, cedric-anne commented on src/ItemVirtualMachine.php
> +                ]);
This is not mandatory to use the template rendering machine to render a single line. Also, your template corresponds to 2 distincts cases that have no parameters in common. This kind of cases should be handled by 2 distinc template files.

```suggestion
                echo '<h3 class="text-start">' . __s('List of hosts') . '</h3>';
```

2024-07-03 10:32 UTC, cedric-anne commented on src/ItemVirtualMachine.php
> +                            'name' => $computer->fields['name'],
Should be espaced here due to the usage of the `raw_html` formatter.
```suggestion
                            'name' => htmlspecialchars($computer->fields['name']),
```

2024-07-03 10:32 UTC, cedric-anne commented on src/ItemVirtualMachine.php
>                  $vm->getFromDB($virtualmachine['id']);
```suggestion
                if (!$vm->getFromDB($virtualmachine['id'])) {
                    continue:
                }
```

2024-07-03 10:32 UTC, cedric-anne commented on src/ItemVirtualMachine.php
> +                    'comment'                   => $virtualmachine['comment'] ?? NOT_AVAILABLE,
There is no reason to have null/undefined values here.
```suggestion
                    'name'                      => $vm->getLink(),
                    'comment'                   => $virtualmachine['comment'],
```

2024-07-03 10:32 UTC, cedric-anne commented on src/ItemVirtualMachine.php
> +                    'ram'                       => $virtualmachine['ram'] ?? NOT_AVAILABLE,
```suggestion
                    'uuid'                      => $virtualmachine['uuid'],
                    'vcpu'                      => $virtualmachine['vcpu'],
                    'ram'                       => $virtualmachine['ram'],
```

2024-07-03 10:39 UTC, cconard96 commented
> Should `NOT_AVAILABLE` be displayed instead of empty values ?

Maybe that needs clarified/standardized. In some cases, we leave empty values and other times use N/A. I'm not really sure what would be best. Maybe empty when the type of value is a number/string/etc but N/A when it is a link to another item/object?

2024-07-03 11:54 UTC, cedric-anne requested changes

2024-07-03 11:54 UTC, cedric-anne commented on src/ItemVirtualMachine.php
> +                    continue:
```suggestion
                    continue;
```

2024-07-03 11:54 UTC, cedric-anne commented on templates/components/form/item_virtualmachine.html.twig
> +{% else %}
This case is not needed anymore.

2024-07-03 14:55 UTC, cedric-anne commented on templates/components/form/item_virtualmachine.html.twig
> +{% endif %}
```suggestion
<h3 class='text-start mt-5'>{{ __('List of virtualized environments') }}</h3>
{% if canedit %}
    <div class='text-center mb-3'>
        <a class='btn btn-primary' href='{{ vmformurl }}' role="button">
            {{ __('Add a virtual machine') }}
        </a>
    </div>
{% endif %}

{% if not has_vm %}
    {{ alerts.alert_info(
        __('No virtualized environment associated with the item')
    ) }}
{% endif %}
```

2024-07-04 07:42 UTC, cedric-anne approved these changes

2024-07-04 07:42 UTC, merged