feat(rules): update reset rules modal and restrict button display
glpi-project/glpi pull request #17416
Opened 2024-07-03 07:53 UTC by ccailly

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !33542

Rules reset button changed to danger style.
Original neutral modal replaced by danger modal.
Button displayed only if user is on root entity and has configuration modification rights.

![image](https://github.com/glpi-project/glpi/assets/42278610/92339004-1a6a-4fe9-85fd-941db927ffaa)

2024-07-03 09:30 UTC, cedric-anne commented on src/Plugin.php
> +                                $plugin->getField('name')
`content` will not be escaped anymore due to the usage of the `|raw` filter
```suggestion
                                __s('By uninstalling the "%s" plugin you will lose all the data of the plugin.'),
                                htmlspecialchars($plugin->getField('name'))
```

2024-07-03 09:30 UTC, cedric-anne commented on src/Glpi/Marketplace/View.php
> +                    $plugin_inst->getField('name')
`content` will not be escaped anymore due to the usage of the `|raw` filter
```suggestion
                                __s('By uninstalling the "%s" plugin you will lose all the data of the plugin.'),
                                htmlspecialchars($plugin_inst->getField('name'))
```

2024-07-03 09:40 UTC, AdrienClairembault reviewed
I feel like the component except too much html rendered content as parameters, which is not ideal as it make it difficult to configure it.

Here are my suggestions to simplify it:
`open_btn` -> This value is displayed directly as "raw" content before the modal container.
Wouldn't it make more sense to display it manually before calling the component ?

`content` -> In the two implementation we use simple strings without HTML tags. I guess it could be a simple string variable ?

`confirm_btn` => I guess we have to keep this one as HTML for now. Ideally it should just be a simple label but with the design of GLPI the button is used as either a link or a form so we can't really change it :/

2024-07-03 09:41 UTC, trasher approved these changes

2024-07-03 12:41 UTC, cedric-anne commented on src/Glpi/Marketplace/View.php
> +            HTML;
```suggestion
HTML;
```

2024-07-03 12:42 UTC, cedric-anne commented on src/Plugin.php
> +                        TWIG;
```suggestion
TWIG;
```

2024-07-04 06:55 UTC, AdrienClairembault requested changes

2024-07-04 06:55 UTC, AdrienClairembault commented on src/RuleCollection.php
> +                        'open_btn': open_btn,
```suggestion
```

I think this param is no longer used.

2024-07-04 07:38 UTC, AdrienClairembault approved these changes

2024-07-08 09:26 UTC, cedric-anne approved these changes

2024-07-08 09:26 UTC, merged