Check if MAC address exists before assume it's an Unmanaged device
glpi-project/glpi pull request #17506
Opened 2024-07-12 15:19 UTC by eduardomozart

A MAC address should be unique. When running a NetDiscovery task, it may create a new Unmanaged asset with a MAC address that already exists on GLPI, which can lead to duplicate MAC addresses on NetworkPort DB table, so before assuming it's an Unmanaged device, check if there's any item on DB that matches this MAC address.

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | https://github.com/glpi-project/glpi-inventory-plugin/issues/530

2024-08-02 05:25 UTC, trasher commented
Please fix tests and CI. Also, this probably need a specific test case

2024-09-16 07:14 UTC, trasher commented
Hi, are you going to work again on this one or should we close?

Also, no new feature will be accepted on 10.0/bugfixes branch, it must target main.

2024-09-16 12:52 UTC, eduardomozart commented
Yes, I will, but I'm not being paid for this like TecLib does, so it's a third party contribution project that I've work with. Any help to fix bugs on your commercial product would be helpful, since it's a bug and not an intended behavior from GLPI Agent and GLPI core itself.

2024-09-16 13:18 UTC, trasher commented
I'm not convinced this is a bug, and since that can change existing inventory behavior; it should still target main branch.

Anyway, community issues  are handled on a on a voluntary basis. 

Finally, just for you to know I do not like your remarks.

Best regards.

2024-09-16 15:39 UTC, eduardomozart commented
Yes, it's a voluntary project, but TecLib hire employees to provide commercial support and there's about ~$2M income per year that TechLib does, so there should be interest on TechLib to fix bugs on a product it receives money for instead of expecting voluntaries to do so. TechLib also benefits from works of their volunters, so when you guys ask for tests and do not provide any help to develop them and troubleshoot the issues we report, instead of expecting us to do all the hard work, would be appreciable.

Of course this is a bug and it's simply reproduciable: Do a Network Discovery task, inventory discovered devices using Network Inventory task, and do a Network Discovery task again: you'll see that devices that was already inventories by an Network Inventory task will be shown on "Unmanaged devices" again, overriding the info collected by Network Inventory task. MAC address should be treated as unique and information be merged with the current device instead of simply overriding it all with useless information from Network Discovery task as it does today, and my fix attempts to fix that.

2024-09-17 07:37 UTC, stonebuzz commented
hi @eduardomozart 

`NetDiscovery` and `NetInventory` are not designed for `ESX` inventory, but only for `SNMP-capable `devices. 

If the `ESX` comes up as `Unamanged`, it's because the agent hasn't been able to find the type from its OIDs (cf https://glpi-agent.readthedocs.io/en/latest/database.html | https://github.com/glpi-project/sysobject.ids/).

Logical, since it doesn't respond to `SNMP`

That's the real problem! Using `SNMP` `inventory`/`discovery` on non-compatible equipment.

So your fix, as it stands, looks more like a band-aid to help you deal with this particular case, which is the result of bad practice.

Of course, it's always possible to improve this reconciliation, so here are a few comments on this `PR`

- It's the `Unmanaged` (`src/Inventory/asset/Unmanaged`) class that needs to be improved (it already contains code for reconciliation (cf. `rulepassed` function)) not `MainAsset`.
- Must be done on `main` branch (as it would be an `improvement` of the reconciliation method)
- `Unit tests` must be added, it can often seem demanding, but clearly mandatory . We have over `150,000` lines of code running tests (`25,000` just for inventory!) , guaranteeing increased robustness and optimum process reliability.

To conclude

it's important to remember the foundation of our project: it's open source AND community-based. Although we have an in-house team working on the product, collaboration with the community is at the heart of our vision. 

We firmly believe that this synergy betweenTECLIB and volunteer contributors is the strength and richness of our product.



Best regards

2024-09-17 11:45 UTC, eduardomozart commented
> hi @eduardomozart
> 
> `NetDiscovery` and `NetInventory` are not designed for `ESX` inventory, but only for `SNMP-capable `devices.
> 
> If the `ESX` comes up as `Unamanged`, it's because the agent hasn't been able to find the type from its OIDs (cf https://glpi-agent.readthedocs.io/en/latest/database.html | https://github.com/glpi-project/sysobject.ids/).
> 
> Logical, since it doesn't respond to `SNMP`
> 
> That's the real problem! Using `SNMP` `inventory`/`discovery` on non-compatible equipment.
> 
> So your fix, as it stands, looks more like a band-aid to help you deal with this particular case, which is the result of bad practice.
> 
> Of course, it's always possible to improve this reconciliation, so here are a few comments on this `PR`
> 
> * It's the `Unmanaged` (`src/Inventory/asset/Unmanaged`) class that needs to be improved (it already contains code for reconciliation (cf. `rulepassed` function)) not `MainAsset`.
> * Must be done on `main` branch (as it would be an `improvement` of the reconciliation method)
> * `Unit tests` must be added, it can often seem demanding, but clearly mandatory . We have over `150,000` lines of code running tests (`25,000` just for inventory!) , guaranteeing increased robustness and optimum process reliability.
> 
> To conclude
> 
> it's important to remember the foundation of our project: it's open source AND community-based. Although we have an in-house team working on the product, collaboration with the community is at the heart of our vision.
> 
> We firmly believe that this synergy betweenTECLIB and volunteer contributors is the strength and richness of our product.
> 
> Best regards

Hello, thank you for your reply. 
About the community vision of GLPI, I believe it can be improved. As a volunteer, I provided a lot of contributions reporting bugs and fixing them when possible for years now. But recently with GLPI 10, I’m not sure if the code guidelines changed or something like that, but every bug is treated like “it’s intended behavior” and if we want to fix it, we have to do it ourselves, with little to none support of GLPI team, and when we provide a fix, it isn’t accept if there’s a missing indent somewhere, something easy to fix that GLPI team could simply add the missing indent and commit the code. It seems to me a lot of ill will when us volunteers take hours digging and fixing known bugs that could be explored further with GLPI team help.

About the Unmanaged device instance, it seems to happen with ESXi hosts and also IP phones. I know there’s no reason to do a Network Discovery for a device that was already discovered, but when I report a bug, I always report it as an average user do so, so this bug doesn’t affect me directly, but the average user would expect to input its internal IP range and GLPI discover new devices automagically while keeping the current one as it is. There’s other places where this fix could work from, e.g before adding an Unmanaged device from Net Discovery, check if that MAC address exists on GLPI and do not add them as such if it is.

Commentaries like yours really help us to understand GLPI internals and how it was intended to work, instead of simply letting us on our own luck. I would expend hours doing unit tests (which I have difficulties to do because I am not a developer, just someone who wants to contribute and make the GLPI even better) for a fix that would not be approved at all. I will see what I can do to provide a functional code to fix this on Unmanaged asset portion of the code. Thank you.

2025-01-16 13:22 UTC, cedric-anne requested changes
I do not know this part, so I cannot tell if it is a bug or not, and therefore what branch should be targetted. Anyway, this requires a PHPUnit test to validate that it works as expected.

@trasher @stonebuzz @orthagh Is this a bug or a new feature?

2025-01-16 13:36 UTC, stonebuzz commented
Hi @eduardomozart 

can you provider inventory from this tw assets `server02` and `Esxi01`

![image](https://github.com/user-attachments/assets/a25eea3d-5f6f-4b31-85e9-fba6ef591e95)

As far as I'm concerned, the PR is not going in the right direction - the problem must lie elsewhere.

2025-01-20 13:51 UTC, closed without merging