Add user category search option (Requester, Observer, Technician)
glpi-project/glpi pull request #17515
Opened 2024-07-15 14:41 UTC by RomainLvr

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !33234

## Dev request

The customer wants to sort the "Support > Tickets" view by user category

![image](https://github.com/user-attachments/assets/d462e268-c992-4ffa-81a1-3fb36231ab56)

### Result : 
![image](https://github.com/user-attachments/assets/4075ba0b-5f12-406f-9e2b-aa55687583a2)

2024-07-16 06:40 UTC, Rom1-B commented
Wouldn't that be possible via a `global rule`, like here?

![image](https://github.com/user-attachments/assets/48587bc2-e22f-464d-9405-2024f3f370e0)

2024-07-16 09:33 UTC, RomainLvr commented
> Wouldn't that be possible via a `global rule`, like here?
> 
> ![image](https://private-user-images.githubusercontent.com/8530352/348968817-48587bc2-e22f-464d-9405-2024f3f370e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMTcxOTAsIm5iZiI6MTcyMTExNjg5MCwicGF0aCI6Ii84NTMwMzUyLzM0ODk2ODgxNy00ODU4N2JjMi1lMjJmLTQ2NGQtOTQwNS0yMDI0ZjNmMzcwZTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTZUMDgwMTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWNmZGMwNDgyMmMwZGRhNDNiYTRmMWE0MDA3M2VhNTZlZjE4OWQ0ODJkZjA2ZGFkN2U4ZjQ1ODg3ZWNlMmRjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fxbVLHFbDj_ByLuImKfeSlyjFGX2JAtEjdl3cTVgSZ8)

After a few checks and tests, I've deduced that it's not possible to use the global rules because you'd have to add an itemtype pointing to the ticket actors (`Ticket_User`) in the profile configuration:

![image](https://github.com/user-attachments/assets/a97e21bf-6820-4b19-acc6-1d005da78fdb)

However, this class is not compatible with the operation of global rules. Using the `User` class doesn't work either because in tickets, the relationship is made through `CommonITILActors`. If you have an idea of how to make the link, I'd love to hear from you.

2024-07-23 08:33 UTC, AdrienClairembault requested changes
A small PHP unit test demonstrating the feature would be nice :)

2024-07-31 09:23 UTC, cedric-anne approved these changes

2024-07-31 09:23 UTC, cedric-anne commented on src/CommonITILObject.php
> +        $tab[]= [
```suggestion
        $tab[] = [
```

2024-07-31 09:23 UTC, cedric-anne commented on src/CommonITILObject.php
> +        $tab[]= [
```suggestion
        $tab[] = [
```

2024-07-31 10:14 UTC, AdrienClairembault approved these changes
Ok for the requested changes (but still not tested)

2024-08-13 09:41 UTC, Rom1-B requested changes
Seems OK, but I agree with @AdrienClairembault that tests would be welcome.

2024-08-22 14:19 UTC, merged