Fix(LifeCycle): ticket must be closed after the follow-up has been added
glpi-project/glpi pull request #17543
Opened 2024-07-18 12:20 UTC by stonebuzz

When the requester validates the solution, the comment is added as a follow-up.

But the parent (Ticket) is closed before this action.

This can be seen in the ticket history

![image](https://github.com/user-attachments/assets/586da20f-52ce-439e-b714-3fa1dd814905)

This PR reverses the action order

![image](https://github.com/user-attachments/assets/6927ec8b-0097-44be-86de-22f84adad197)

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !33833

2024-07-18 12:29 UTC, cedric-anne approved these changes
Seems OK.

2024-07-18 13:11 UTC, orthagh approved these changes

2024-07-18 13:12 UTC, AdrienClairembault approved these changes

2024-07-18 13:43 UTC, cedric-anne requested changes
It seems that it breaks an existing test. Could you check?

2024-07-22 08:30 UTC, cedric-anne approved these changes

2024-07-22 09:15 UTC, AdrienClairembault approved these changes

2024-07-22 09:16 UTC, merged