Feature : targeted private saved searches
glpi-project/glpi pull request #17587
Opened 2024-07-24 08:48 UTC by ArthurMinfotel

| Q             | A
| ------------- | ---
| Bug fix?      |  no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 

Add option to choose targets for private saved searches. 
Modify CommonDBVisible to make it possible to restrict the types of target available, and to choose the right used to determine the availability of user type targets.
For a saved search, a target can either be a user or a group. 
User and group dropdown take into account entity of the item when loading available targets.

The class used for the user target might need to be changed (SavedSearch_User is already used so I couldn't follow the naming convention set by the other CommonDBVisible items, so I created SavedSearch_UserTarget for now).
Also the new method getVisibilityRight could be used to dynamically get the right for the itemtype associated with the saved search (to only be able to targets users with the read right on the itemtype).

Example : 
Target tab for SavedSearch :
![image](https://github.com/user-attachments/assets/cb009220-fe71-4abc-8f30-a8656a42d3af)
Corresponding record in DB : 
![image](https://github.com/user-attachments/assets/74dcedbd-23d2-448a-8f3e-ca4e41f22a50)
Available saved searches for the itemtype for users 2 without any target set :
![image](https://github.com/user-attachments/assets/19e89a5b-a5ea-43c3-969b-dd65d38e2975)
User 2 added as a target : 
![image](https://github.com/user-attachments/assets/dd3c8625-9202-4d7e-9663-d886f92f2907)
Available saved searches on the itemtype for user 2 after being added added as a target : 
![image](https://github.com/user-attachments/assets/af50c271-4a17-4603-b9a1-846952037bbd)

Type of targets available set through the static variable $types : 
![image](https://github.com/user-attachments/assets/f3d93a4b-8cc2-4542-ac8e-095b10c23de4)

Restrictions on groups available as targets based on the item's entity (for the example entity set as 1 instead of root) : 
List of entities : 
![image](https://github.com/user-attachments/assets/91bb39e4-4baa-4f42-95ac-351289850fc1)
List of groups with entity restrictions : 
![image](https://github.com/user-attachments/assets/9f2cd874-f13b-4c02-9e96-c20496d2b0e6)
Visibility for groups : 
![image](https://github.com/user-attachments/assets/6627c57b-e3b4-4595-b9f0-7a52dc7ef0f8)
Subvisibility : 
![image](https://github.com/user-attachments/assets/830976dc-01cf-4453-8cf8-d42e29378305)

2024-07-24 08:51 UTC, cedric-anne commented
@ArthurMinfotel 

Could you add some screenshots to your PR description?

2024-07-24 15:15 UTC, ArthurMinfotel commented
> @ArthurMinfotel
> 
> Could you add some screenshots to your PR description?

I've edited it to add several screenshoots, showing an example and the added functionnalities.

2024-08-01 15:13 UTC, ArthurMinfotel commented
> We discussed about it with @orthagh and we think that the `is_private` flag should be removed from the database. Indeed, having both a public/private management + a entity/groups/users visibility management is redundant and can be a bit complex to handle for the end user.
> 
> At creation, if the saved search is created as public, then it a visibility on the root entity + recursive should be automatically created. If it is created as private, the lack of visibility filters should be sufficient to make it private.
> 
> It would require to add a migration to add a new visibility filter to all existing public searches.

The current behavior of the public searches is to have them available for all users within it's entity (and child entities if it is recursive), so shouldn't I rather make it so that it automaticaly create a link with its entity rather the root entity if it is meant to be a public search ?

2024-08-01 16:18 UTC, cedric-anne commented
> > We discussed about it with @orthagh and we think that the `is_private` flag should be removed from the database. Indeed, having both a public/private management + a entity/groups/users visibility management is redundant and can be a bit complex to handle for the end user.
> > At creation, if the saved search is created as public, then it a visibility on the root entity + recursive should be automatically created. If it is created as private, the lack of visibility filters should be sufficient to make it private.
> > It would require to add a migration to add a new visibility filter to all existing public searches.
> 
> The current behavior of the public searches is to have them available for all users within it's entity (and child entities if it is recursive), so shouldn't I rather make it so that it automaticaly create a link with the active entity rather than the root entity if it is meant to be a public search ?

As we add visibility specs to saved searches, the idea was to consider that a saved search with no visibility is private. In this case, the `is_private` flag is no more useful.

2024-08-02 14:33 UTC, ArthurMinfotel commented
@cedric-anne Could you tell me if what I've added for the creation of public search matches what you talked about ? Same for the migration. Thanks in advance.

2024-09-05 06:47 UTC, cedric-anne commented
> @cedric-anne Could you tell me if what I've added for the creation of public search matches what you talked about ? Same for the migration. Thanks in advance.

It seems to match our functional request, but I do not have time right now to do a complete review.

2024-09-05 12:26 UTC, AdrienClairembault requested changes
I have a fatal error when trying to access the saved searches page:

```
[2024-09-05 12:20:25] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "LEFT JOIN" 
in /glpi/main/src/Glpi/Search/Provider/SQLProvider.php at line 2231
  Backtrace :
  src/Search.php:679                                 Glpi\Search\Provider\SQLProvider::getDefaultJoinCriteria()
  src/Glpi/Search/Provider/SQLProvider.php:3804      Search::addDefaultJoin()
  src/Glpi/Search/SearchEngine.php:641               Glpi\Search\Provider\SQLProvider::constructSQL()
  src/Glpi/Search/SearchEngine.php:657               Glpi\Search\SearchEngine::getData()
  src/Glpi/Search/SearchEngine.php:614               Glpi\Search\SearchEngine::showOutput()
  src/Search.php:165                                 Glpi\Search\SearchEngine::show()
  front/savedsearch.php:55                           Search::show()
  ...Glpi/Controller/LegacyFileLoadController.php:57 require()
  vendor/symfony/http-kernel/HttpKernel.php:101      Glpi\Controller\LegacyFileLoadController->Glpi\Controller\{closure}()
  ...ymfony/http-foundation/StreamedResponse.php:106 Symfony\Component\HttpKernel\HttpKernel::Symfony\Component\HttpKernel\{closure}()
  vendor/symfony/http-foundation/Response.php:423    Symfony\Component\HttpFoundation\StreamedResponse->sendContent()
  public/index.php:58                                Symfony\Component\HttpFoundation\Response->send()
  
[2024-09-05 12:20:25] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: array_key_exists(): Argument #2 ($array) must be
of type array, null given in /glpi/main/src/Glpi/Search/Provider/SQLProvider.php at line 2232
  Backtrace :
  src/Glpi/Search/Provider/SQLProvider.php:2232      array_key_exists()
  src/Search.php:679                                 Glpi\Search\Provider\SQLProvider::getDefaultJoinCriteria()
  src/Glpi/Search/Provider/SQLProvider.php:3804      Search::addDefaultJoin()
  src/Glpi/Search/SearchEngine.php:641               Glpi\Search\Provider\SQLProvider::constructSQL()
  src/Glpi/Search/SearchEngine.php:657               Glpi\Search\SearchEngine::getData()
  src/Glpi/Search/SearchEngine.php:614               Glpi\Search\SearchEngine::showOutput()
  src/Search.php:165                                 Glpi\Search\SearchEngine::show()
  front/savedsearch.php:55                           Search::show()
  ...Glpi/Controller/LegacyFileLoadController.php:57 require()
  vendor/symfony/http-kernel/HttpKernel.php:101      Glpi\Controller\LegacyFileLoadController->Glpi\Controller\{closure}()
  ...ymfony/http-foundation/StreamedResponse.php:106 Symfony\Component\HttpKernel\HttpKernel::Symfony\Component\HttpKernel\{closure}()
  vendor/symfony/http-foundation/Response.php:423    Symfony\Component\HttpFoundation\StreamedResponse->sendContent()
  public/index.php:58                                Symfony\Component\HttpFoundation\Response->send()

```

I also have some errors related to a missing `is_private` field when accessing a singular saved search

```
[2024-09-05 12:21:45] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key
"is_private" in /glpi/main/src/SavedSearch.php at line 176
  Backtrace :
  src/CommonDBTM.php:2957                            SavedSearch->canViewItem()
  src/CommonDBTM.php:1413                            CommonDBTM->can()
  src/CommonDBTM.php:1484                            CommonDBTM->getLink()
  src/CommonDBTM.php:1324                            CommonDBTM->addMessageOnAddAction()
  front/savedsearch.form.php:50                      CommonDBTM->add()
  ...Glpi/Controller/LegacyFileLoadController.php:57 require()
  vendor/symfony/http-kernel/HttpKernel.php:101      Glpi\Controller\LegacyFileLoadController->Glpi\Controller\{closure}()
  ...ymfony/http-foundation/StreamedResponse.php:106 Symfony\Component\HttpKernel\HttpKernel::Symfony\Component\HttpKernel\{closure}()
  vendor/symfony/http-foundation/Response.php:423    Symfony\Component\HttpFoundation\StreamedResponse->sendContent()
  public/index.php:58                                Symfony\Component\HttpFoundation\Response->send()
  
[2024-09-05 12:21:46] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key
"is_private" in /glpi/main/src/SavedSearch.php at line 176
  Backtrace :
  src/CommonDBTM.php:2957                            SavedSearch->canViewItem()
  src/CommonDBTM.php:6521                            CommonDBTM->can()
  front/savedsearch.form.php:111                     CommonDBTM::displayFullPageForItem()
  ...Glpi/Controller/LegacyFileLoadController.php:57 require()
  vendor/symfony/http-kernel/HttpKernel.php:101      Glpi\Controller\LegacyFileLoadController->Glpi\Controller\{closure}()
  ...ymfony/http-foundation/StreamedResponse.php:106 Symfony\Component\HttpKernel\HttpKernel::Symfony\Component\HttpKernel\{closure}()
  vendor/symfony/http-foundation/Response.php:423    Symfony\Component\HttpFoundation\StreamedResponse->sendContent()
  public/index.php:58                                Symfony\Component\HttpFoundation\Response->send()
  
[2024-09-05 12:21:46] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key
"is_private" in /glpi/main/src/SavedSearch.php at line 167
  Backtrace :
  src/CommonDBTM.php:2997                            SavedSearch->canCreateItem()
  src/CommonDBTM.php:2491                            CommonDBTM->can()
  .../twig/twig/src/Extension/CoreExtension.php:1629 CommonDBTM->canEdit()
  ...tes/ac/ac4e6f347f3439630bec9c113c2e2d08.php:131 Twig\Extension\CoreExtension::getAttribute()
  vendor/twig/twig/src/Template.php:360              __TwigTemplate_57914519ef8b5fd53f2488a6f974814c->doDisplay()
  vendor/twig/twig/src/Template.php:335              Twig\Template->yield()
  vendor/twig/twig/src/TemplateWrapper.php:38        Twig\Template->render()
  src/Glpi/Application/View/TemplateRenderer.php:164 Twig\TemplateWrapper->render()
  src/CommonGLPI.php:1117                            Glpi\Application\View\TemplateRenderer->render()
  src/CommonGLPI.php:1235                            CommonGLPI->showNavigationHeader()
  src/CommonDBTM.php:6546                            CommonGLPI->display()
  front/savedsearch.form.php:111                     CommonDBTM::displayFullPageForItem()
  ...Glpi/Controller/LegacyFileLoadController.php:57 require()
  vendor/symfony/http-kernel/HttpKernel.php:101      Glpi\Controller\LegacyFileLoadController->Glpi\Controller\{closure}()
  ...ymfony/http-foundation/StreamedResponse.php:106 Symfony\Component\HttpKernel\HttpKernel::Symfony\Component\HttpKernel\{closure}()
  vendor/symfony/http-foundation/Response.php:423    Symfony\Component\HttpFoundation\StreamedResponse->sendContent()
  public/index.php:58                                Symfony\Component\HttpFoundation\Response->send()
  
[2024-09-05 12:21:47] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key
"is_private" in /glpi/main/src/SavedSearch.php at line 176
  Backtrace :
  src/CommonDBTM.php:2957                            SavedSearch->canViewItem()
  ajax/common.tabs.php:86                            CommonDBTM->can()
  ...Glpi/Controller/LegacyFileLoadController.php:57 require()
  vendor/symfony/http-kernel/HttpKernel.php:101      Glpi\Controller\LegacyFileLoadController->Glpi\Controller\{closure}()
  ...ymfony/http-foundation/StreamedResponse.php:106 Symfony\Component\HttpKernel\HttpKernel::Symfony\Component\HttpKernel\{closure}()
  vendor/symfony/http-foundation/Response.php:423    Symfony\Component\HttpFoundation\StreamedResponse->sendContent()
  public/index.php:58                                Symfony\Component\HttpFoundation\Response->send()
  
[2024-09-05 12:21:47] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key
"is_private" in /glpi/main/src/SavedSearch.php at line 167
  Backtrace :
  src/CommonDBTM.php:2997                            SavedSearch->canCreateItem()
  src/CommonDBTM.php:2491                            CommonDBTM->can()
  .../twig/twig/src/Extension/CoreExtension.php:162 [...]

2024-11-12 10:36 UTC, AdrienClairembault requested changes
I can't add a target:

![add_user](https://github.com/user-attachments/assets/269fbaf4-7542-49de-b8e6-cd9693c13b2e)

It fails for all possible choices (user, group and entity).

2024-11-14 10:44 UTC, ArthurMinfotel commented
Made some changes to take the deletion of savedsearch.form.php into account (what was causing issue when I last requested a review, didn't notice the deletion when I merged from main and didn't do any functionnal tests for the minor changes I did after).

I created a new controller to include the action needed for items extending CommonDBVisible : it extends GenericFormController and deal with the 'addvisibility' action.

There are some right issues when loading a saved search with a profile which doesn't have the read right on bookmark_public, which I temporarely fixed by overriding the canView method in SavedSearch to always return true. But I also add to override getMenuContent because of that (which only stop the link from appearing in the menu, the list can still be accessed).

2024-12-18 14:01 UTC, AdrienClairembault requested changes

2025-01-30 14:22 UTC, ArthurMinfotel commented
If everything is OK from a pratical point of view, I will start working on updating the current test functions and adding a new one for the targets.

2025-02-05 13:48 UTC, ArthurMinfotel commented
Tests are updated.
Things that are tested are :

1. Automatically adding the saved search's entity as target if input contains is_private with a falsy value.
2. For each type of target, visibility of a saved search to a user other than the creator when using SavedSearch::getMine().

2025-02-10 11:07 UTC, ArthurMinfotel commented
I've updated the controller to fix the issue with the class instance.

For the lint, I believe those are not fixable : 
![image](https://github.com/user-attachments/assets/abce732c-32a8-40f9-99ee-46009c0c721f)
The first and second are called in `getTabNameForItem` and `displayTabContentForItem`, and so lint doesn't recognise the method from the class `CommonDBVisible` since its parameter $item is typed as `CommonGLPI`.
As the third one, it's a right check, so I don't even know what the cause might be.

2025-02-11 08:41 UTC, AdrienClairembault commented on src/SavedSearch.php
> +            switch ($item->getType()) {
```suggestion
            switch ($item::class) {
```

2025-02-11 08:41 UTC, AdrienClairembault commented on src/SavedSearch.php
> +            case 'SavedSearch':
```suggestion
        switch ($item::class) {
            case SavedSearch::class:
```

2025-02-11 08:43 UTC, AdrienClairembault commented
I've added suggestions that should fix the typing issues.

For the "always true" issue, this is because the condition exist twice:

![image](https://github.com/user-attachments/assets/de036906-c805-4916-9e90-45d96a8a45cc)

So when you reach the second condition, it will always be true because if the first one was false then the function would have returned a value already.

I'll let you review to see which one you need to keep.

2025-02-11 08:46 UTC, AdrienClairembault commented on install/migrations/update_10.0.x_to_11.0.0/group_savedsearch.php
> +        `is_recursive` tinyint(1) NOT NULL DEFAULT '0',
This should fix the tests.

```suggestion
        `is_recursive` tinyint NOT NULL DEFAULT '0',
```

2025-02-11 09:33 UTC, ArthurMinfotel commented
I added the suggested fix. I will remember those for future developments.

2025-02-11 15:30 UTC, AdrienClairembault reviewed
Ok for me besides the right check.

2025-02-11 15:30 UTC, AdrienClairembault commented on src/Glpi/Controller/VisibilityController.php
> +        $class = $request->attributes->get('class');
We probably need to check here that the user is allowed to update the visibility of the item.

2025-02-12 08:18 UTC, AdrienClairembault approved these changes

2025-04-15 14:59 UTC, cedric-anne commented
I rebased the branch to fix conflicts and revert some whitespace changes to reduce the diff. If @orthagh approves the feature, I will do a last technical review and merge it.

2025-04-23 15:15 UTC, flegastelois commented
I tested the feature:
- with the "glpi" user, I created a savedsearch on the Tickets
- shared it to a "normal" target user
- logged in with the "normal" user
- attempting to access the savedsearch from the Tickets results in a fatal error

By the way, the left menu points to the "Tools" section, instead of remaining in the Tickets section.

Note that if I add the "READ" (Saved Searches) permission for the "normal" user profile (Observer by default), it doesn't change anything.

![image](https://github.com/user-attachments/assets/b0107e52-075d-4686-a901-394d96874c49)

```
User can not access the SavedSearch 1
In ./front/savedsearch.php(53)
#0 ./src/Glpi/Controller/LegacyFileLoadController.php(59): require()
#1 ./vendor/symfony/http-kernel/HttpKernel.php(101): Glpi\Controller\LegacyFileLoadController->Glpi\Controller\{closure}()
#2 ./vendor/symfony/http-foundation/StreamedResponse.php(106): Symfony\Component\HttpKernel\HttpKernel::Symfony\Component\HttpKernel\{closure}()
#3 ./vendor/symfony/http-foundation/Response.php(423): Symfony\Component\HttpFoundation\StreamedResponse->sendContent()
#4 ./src/Glpi/Kernel/Kernel.php(266): Symfony\Component\HttpFoundation\Response->send()
#5 ./public/index.php(58): Glpi\Kernel\Kernel->sendResponse()
#6 {main}
```

2025-07-09 12:17 UTC, cedric-anne commented
Replaced by #20247

2025-07-09 12:17 UTC, closed without merging