feat(forms): Transform "title" field into a rich text in form destination
glpi-project/glpi pull request #17590
Opened 2024-07-24 12:39 UTC by ccailly

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed 

Support for tags in the title field. The field is now a tinyMCE field with toolbar and status bar disabled.
HTML tags and line breaks are not allowed.

![image](https://github.com/user-attachments/assets/775f0f2c-b996-4b0b-9fdd-27cbe44bb013)

2024-07-25 08:48 UTC, AdrienClairembault requested changes
Can you remove the auto config support ?
The tag should just be the default value.

Sorry if my screenshot in the backlog lead you to believe we wanted an auto config here, it was from an older version and we have since removed the auto config on the title.

The idea is to only use auto config when the default value can't be "good enough" to cover what we want. 
In this case a tag with the form name is perfect for a default value.

2024-07-26 10:02 UTC, AdrienClairembault approved these changes
Perfect 👍

2024-07-30 08:03 UTC, cedric-anne requested changes

2024-07-30 08:03 UTC, cedric-anne commented on src/Html.php
> +        bool $toolbar = true,
Please move this new parameter after existing ones, to prevent BC-break on calls that are not using named parameters.

2024-07-30 12:40 UTC, cedric-anne approved these changes

2024-07-31 07:17 UTC, merged