Fix dropdown fields label when name contains `[]` chars
glpi-project/glpi pull request #17616
Opened 2024-07-31 13:29 UTC by cedric-anne

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

Found while testing #17462.

The `for` attribute of the label was incorrect (e.g. `dropdown_myprop[]1246579875`) and different from the `<select>` id (e.g. `dropdown_myprop__1246579875`) that is generated by:
https://github.com/glpi-project/glpi/blob/6edfb3d336b824d1d6005b44c53b68e9dc51ebe0/src/Dropdown.php#L227

2024-07-31 13:34 UTC, AdrienClairembault requested changes
I've let a TODO for this in the dropdownArrayField macro:

![image](https://github.com/user-attachments/assets/fe5cec2d-ae4a-4f81-9a9e-a19056708db1)

Can you delete it ?

Also maybe we need a proper filter/function/macro to avoid repeating this logic in multiple places.

2024-07-31 13:42 UTC, trasher approved these changes

2024-07-31 13:43 UTC, cedric-anne commented
> I've let a TODO for this in the dropdownArrayField macro:
> 
> ![image](https://private-user-images.githubusercontent.com/42734840/353850888-fe5cec2d-ae4a-4f81-9a9e-a19056708db1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MzM2ODAsIm5iZiI6MTcyMjQzMzM4MCwicGF0aCI6Ii80MjczNDg0MC8zNTM4NTA4ODgtZmU1Y2VjMmQtYWU0YS00ZjgxLTlhOWUtYTE5MDU2NzA4ZGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDEzNDMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhODI5NjMwOWQ5ZmFkNGVmYjRiZTcxNGFlMTNkOWUzNzM1MmM5NzRmNDNlODU5ZGY1NGYyYTUzNjQ0YTVmNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mS3HA1iX0RNWMcxI2-pGLSm7SQsHQHvuOadQscJOW_E)
> 
> Can you delete it ?
> 
> Also maybe we need a proper filter/function/macro to avoid repeating this logic in multiple places.

The main problem is that we cannot force the id in the `Dropdown::show*()` methods, but I do not have time to do better for now.

2024-07-31 16:22 UTC, cconard96 approved these changes

2024-07-31 16:25 UTC, cconard96 commented
How compatible is this change with the one I made in #17323 for "Automatically generated IDs from names may break labels because the name wasn't slugified"?

https://github.com/glpi-project/glpi/pull/17323/files#diff-12e218694082593986b5e9b3dc90adf6ae346b28027f7944ec6c8ca99354fbe5R747

2024-08-01 06:45 UTC, cedric-anne commented
> How compatible is this change with the one I made in #17323 for "Automatically generated IDs from names may break labels because the name wasn't slugified"?
> 
> https://github.com/glpi-project/glpi/pull/17323/files#diff-12e218694082593986b5e9b3dc90adf6ae346b28027f7944ec6c8ca99354fbe5R747

I think there should not be compatibility issues with this change.

2024-08-01 06:46 UTC, merged