Forms destinations: config urgency
glpi-project/glpi pull request #17638
Opened 2024-08-01 13:52 UTC by AdrienClairembault

Credit to @ccailly, we both ended up working on this feature by accident so I've merged both work into one (there was good things to keep on both sides).

![image](https://github.com/user-attachments/assets/8e69def9-12f2-41ba-9ae9-1265c197f1d2)

Note that I've noticed this does not take into account that urgency levels can be disabled in the general config (the urgency question type also missed this "feature").
I've added it to the backlog and will fix it in another PR (I'll probably add a proper Urgency backed enum because we don't even have constants for urgency values right now).

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |

2024-08-22 12:52 UTC, AdrienClairembault commented
Rebased to latest main.

2024-08-26 12:36 UTC, ccailly requested changes

2024-08-26 12:36 UTC, ccailly commented on src/Glpi/Form/Destination/CommonITILField/UrgencyFieldConfig.php
> +            // $strategy = UrgencyFieldStrategy::LAST_VALID_ANSWER;
```suggestion
            $strategy = UrgencyFieldStrategy::LAST_VALID_ANSWER;
```

2024-08-26 12:40 UTC, ccailly approved these changes

2024-09-04 12:25 UTC, AdrienClairembault commented
Rebased to latest main (PHPStan level 4 was checked)

2024-09-09 09:36 UTC, cedric-anne approved these changes

2024-09-09 09:38 UTC, merged