feat(forms): Add ITILCategory field configuration for form destination
glpi-project/glpi pull request #17652
Opened 2024-08-06 13:00 UTC by ccailly

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

![image](https://github.com/user-attachments/assets/ebbc4bc2-0295-442e-bee9-8882870fa5ac)

Possible configurations :
![image](https://github.com/user-attachments/assets/7a999bb6-2e3e-42db-bfd7-20a52c9760e8)

"Specific ITIL Category" display a secondary select to let the user pick the chosen template :
![image](https://github.com/user-attachments/assets/24c6d481-0f4a-4a75-8953-5125b66105c0)

"Answer from a specific question" display a secondary select to let the user pick the chosen question :
![image](https://github.com/user-attachments/assets/b92ccb0f-d21e-4935-aae3-464ac40400fa)

2024-09-10 14:02 UTC, AdrienClairembault requested changes

2024-09-10 14:42 UTC, AdrienClairembault requested changes

2024-09-10 14:42 UTC, AdrienClairembault commented on tests/cypress/support/commands.js
> +Cypress.Commands.add('checkAndCloseAlert', (text) => {
Can you add the definition to command.d.ts ?
Vscode doesn't want to autocomplete the new commands without it.

2024-09-11 12:21 UTC, AdrienClairembault approved these changes

2024-09-18 14:28 UTC, cedric-anne approved these changes

2024-09-18 14:28 UTC, merged