Service catalog minimal implementation
glpi-project/glpi pull request #17661
Opened 2024-08-08 13:01 UTC by AdrienClairembault

Minimal implementation of the new service catalog.

![image](https://github.com/user-attachments/assets/7bd9734d-1345-4a0c-80b8-47f89d16144a)

---

Below are the tasks I plan to add to the backlog.
This list is based on the specifications discussed here: https://outline.teclib.com/doc/catalogue-de-service-interface-self-service-7OGd1p5dVx
Changes to ticket validation will be discussed in separate specifications and are not included in the list.

Tasks:
* Filter forms according to access policies
* Limit the number of forms that can be displayed (pagination)
* Add search bar
* Add form icons
* Add form descriptions (currently we display form header instead, which is not meant to be used for this)
* Add forms accent colors
* Add categories
* Add "pinned" forms 
* Replace "Tickets" menu entry by multiple entries ("Ongoing tickets", "Closed tickets", ...).
* Add unread messages counters to menus
* Final service catalog UI/UX review
* Force creation of at least one ticket per form
* Add "auto close" option to this mandatory ticket

Let me know if you thing something is missing from this list.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |

2024-08-08 13:02 UTC, AdrienClairembault commented
Draft as some ongoing PR must be merged first.

2024-08-22 14:33 UTC, AdrienClairembault commented on front/helpdesk.public.php
Diff is much easier to review with white space changes disabled.

2024-09-09 13:51 UTC, cedric-anne requested changes

2024-09-09 13:51 UTC, cedric-anne commented on templates/layout/page_skeleton.html.twig
> +{% set interface = call("Session::getCurrentInterface") %}
1. There is a Twig function for it.
2. We should avoid to use the `call` function in new features. It has been made to ease the transition to Twig but its usages have to be replaced by some cleaner code later.
```suggestion
{% set interface = get_current_interface() %}
```

2024-09-09 13:51 UTC, cedric-anne commented on templates/pages/self-service/service_catalog.html.twig
> +                        <div class="text-secondary">{{ form.fields.header|raw }}</div>
Rich text provided by end user must be rendered using the `|safe_html` filter that will clean any unsafe code.
```suggestion
                        <div class="text-secondary">{{ form.fields.header|safe_html }}</div>
```

2024-09-09 14:16 UTC, cedric-anne approved these changes

2024-09-09 14:47 UTC, merged