Custom Asset Default Display Preferences
glpi-project/glpi pull request #17675
Opened 2024-08-12 20:28 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

2024-08-19 07:23 UTC, cedric-anne requested changes
Tests are failing.

2024-08-19 07:23 UTC, cedric-anne commented on src/Glpi/Asset/AssetDefinition.php
> +            $DB->insert(
I think it should be done using the `DisplayPreference::add()` method. I know most of operations in `DisplayPreference` class are done directly with low level DB methods, but IMHO, it is an issue as it prevent plugins to be able to use hooks on these operations.

2024-08-22 14:25 UTC, cedric-anne commented on src/Glpi/Asset/AssetDefinition.php
> +        $prefs = [31, 23, 5, 4, 40, 3, 19];
I just reorder preferences to match the default computer preferences.

```suggestion
        $prefs = [
            4, // Name
            40, // Model
            5, // Serial
            23, // Manufacturer
            31, // Status
            3, // Location
            19, // Last Update
        ];
```

2024-08-22 14:25 UTC, cedric-anne approved these changes

2024-08-22 14:26 UTC, cedric-anne commented on src/Glpi/Asset/AssetDefinition.php
> +
```suggestion
```

2024-08-23 06:23 UTC, trasher approved these changes

2024-08-23 07:47 UTC, orthagh approved these changes

2024-08-23 07:48 UTC, merged