Soft-deprecate ancient type system leftovers
glpi-project/glpi pull request #17748
Opened 2024-08-31 11:34 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes (not strict at all)
| Tests pass?   | yes
| Fixed tickets | -

Maybe too late to hard-deprecate or remove this for GLPI 11, but the usage can at least be discouraged.
This PR only adds PHPDoc deprecations, changelog entries, and a PHPStan return type hint for `getType`.
Both the property and function seem to have origins when "types" were integers (0.7 versions and earlier) instead of class names and before late-static bindings were added to PHP (PHP 5.3 in 2009).

The `$type` property appears to be used by the GLPI Inventory plugin more than just changing the default value of the property.
`getType` is obviously widely used throughout the core and plugin code although the core code has been slowly moving towards using things like `static::class` and `$item::class` directly.

If we have to remove uses of `getType` in the core before adding the PHPDoc, it wouldn't be a difficult change to make; Just a lot of replacements.

2024-09-02 06:00 UTC, trasher submitted a review, later dismissed

2024-09-02 06:44 UTC, trasher requested changes
Please fix CI

2024-09-02 06:46 UTC, cedric-anne requested changes
We use a PHPStan extension to trigger errors when it detects usage of a deprecated piece of code. If we want to deprecate this usage, then we have to remove all its usages in our code.

I am not against this deprecation, but we have to focus on the features development. If it requires to much work, it could be postponed.

Also, using `::class` will not be a problem in most of existing cases, but the best way to check types is tu use `$var instanceof Class` checks. Indeed, some plugins may want to have some of their classes to use the same behaviour as the extended class. It would probably be limited to edge cases, but making it possible could still be useful for plugin developers. Anyway, `::class` could be used in a first step, and we could evaluate later the complexity of using `instanceof` checks in the whole codebase.

2024-09-02 23:24 UTC, cconard96 commented
> Also, using `::class` will not be a problem in most of existing cases, but the best way to check types is tu use `$var instanceof Class` checks. Indeed, some plugins may want to have some of their classes to use the same behaviour as the extended class. It would probably be limited to edge cases, but making it possible could still be useful for plugin developers. Anyway, `::class` could be used in a first step, and we could evaluate later the complexity of using `instanceof` checks in the whole codebase.

I wasn't even considering changing behaviors. Also, at least one plugin extends GLPI classes for weird purposes (datainjection; not quite sure why it does) that replacing every class check with instanceof or is_subclass could lead to unintended behavior. This seems like something that can be addressed as needed.

2024-09-03 08:16 UTC, cedric-anne commented
> > Also, using `::class` will not be a problem in most of existing cases, but the best way to check types is tu use `$var instanceof Class` checks. Indeed, some plugins may want to have some of their classes to use the same behaviour as the extended class. It would probably be limited to edge cases, but making it possible could still be useful for plugin developers. Anyway, `::class` could be used in a first step, and we could evaluate later the complexity of using `instanceof` checks in the whole codebase.
> 
> I wasn't even considering changing behaviors. Also, at least one plugin extends GLPI classes for weird purposes (datainjection; not quite sure why it does) that replacing every class check with instanceof or is_subclass could lead to unintended behavior. This seems like something that can be addressed as needed.

Using `instanceof` checks is indeed something that must be documented if in a migration guide if it is done everywhere, and is something that we should not do in GLPI 11.0 as we do not have time for it.

Changing `getType()` occurences by `::class` is a valid change for GLPI 11.0, but if we do it, plugins that are checking their code with PHPStan will have to handle this deprecation too.

2024-09-18 13:55 UTC, cedric-anne commented
I added an entry in the backlog to remove the usage of `getType()` in the GLPI codebase. IMHO, it will be hard to do it in GLPI 11.0 as it will probably have a huge impact in GLPI and all the plugins, and we may not have the time to handle it.

Anyway, we cannot deprecate `CommonDBTM::getType()` if we do not remove all the usages in GLPI itself.

I close this PR, but feel free to reopen it if you find time to do all the require replacements.

2024-09-18 13:55 UTC, closed without merging