Fix wrong join in DB delete call for QueuedWebhook
glpi-project/glpi pull request #17769
Opened 2024-09-02 08:54 UTC by RomainLvr

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !34177

When executing the `queuedwebhookclean` automatic action, an error occurs : 

`Uncaught Exception LogicException: Invalid JOIN type `glpi_webhooks`. in /var/www/html/glpi/src/DBmysqlIterator.php at line 660`

2024-09-02 08:59 UTC, trasher commented
LGTM, maybe a tests case is missing here.

2024-09-02 09:09 UTC, cedric-anne approved these changes

2024-09-02 09:49 UTC, trasher commented
For new tests, please use directly PHPUnit (in `phpunit` dir for now).

2024-09-02 10:39 UTC, cedric-anne commented on phpunit/functional/QueuedWebhook.php
> + * @copyright 2003-2014 by the INDEPNET Development Team.
```suggestion
```

2024-09-02 10:40 UTC, cedric-anne requested changes

2024-09-02 10:40 UTC, cedric-anne commented on phpunit/functional/QueuedWebhook.php
> +class QueuedWebhook extends DbTestCase
It should be renamed to `QueuedWebhookTest`, and the file should be renamed too.

```suggestion
class QueuedWebhookTest extends DbTestCase
```

2024-09-02 10:45 UTC, cedric-anne requested changes
Maybe you can add multiple `QueuedWebhook` enties with different `send_time` / `sent_try` and check that only the expired entries were cleaned by the `cronQueuedWebhookClean` method.

Also, you should probably call the method directly in your test, instead of testing the `CronTask::launch()` result.

2024-09-04 05:58 UTC, cedric-anne approved these changes

2024-09-04 05:59 UTC, merged