Fix unreachable code reported by PHPstan
glpi-project/glpi pull request #17809
Opened 2024-09-06 14:59 UTC by AdrienClairembault

## Checklist before requesting a review

*Please delete options that are not relevant.*

- [ ] I have performed a self-review of my code.

## Description

Investigate unreachable code reported by PHPstan.
I've fixed the easy cases and left some comment for special cases that will need more investigation.

In some places, I've added exception to keep some unreachable code as a safety mechanism in some switches, let me know if you prefer not to (phpcs is already supposed to detect involuntary switch fall-through so this might be overkill).

One of the cases will be fixed by #17806, I'll rebase once merged.

2024-09-06 14:59 UTC, AdrienClairembault commented on src/Webhook.php
Please disable white-space changes to better review this file.

2024-09-09 06:19 UTC, trasher commented
Tests are failing

2024-09-09 07:09 UTC, cedric-anne requested changes

2024-09-09 07:09 UTC, cedric-anne commented on src/Notification_NotificationTemplate.php
>          }
This change is not correct. `Notification_NotificationTemplate::getModeClass('mailing')` is a valid call, and the expected returned class is `NotificationMailing`.

2024-09-09 07:34 UTC, AdrienClairembault commented
Rebased to main + fixed getModeClass issues.

2024-09-09 07:36 UTC, cedric-anne approved these changes

2024-09-09 07:39 UTC, trasher approved these changes

2024-09-09 08:14 UTC, merged