Fix - RGB format for dashboard widget colours
glpi-project/glpi pull request #17820
Opened 2024-09-10 08:31 UTC by RomainLvr

## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes !34379
- In the dashboard, the widget colours could not be in RGB format

## Screenshots (if appropriate):
![image](https://github.com/user-attachments/assets/2e77ab3f-7b5a-45b6-85f0-cfc7872a44e5)

![image](https://github.com/user-attachments/assets/e45f9be7-9491-4053-8ed0-1dfec3a9184b)

2024-09-10 08:34 UTC, trasher commented on src/Toolbox.php
> +                if (preg_match('/rgba?\((\d+),\s*(\d+),\s*(\d+),?\s*([\d\.]+)?\)/', $color, $matches)) {
I guess the `preg_match` should be enough, no need for 2 checks.

2024-09-10 08:43 UTC, cconard96 commented
Dashboard cards were supposed to support transparency. Having a card at half transparency for example is a good way to make the cards look OK in both light and dark themes.

2024-09-11 09:05 UTC, trasher reviewed
Should not the alpha value be handled? This would need a test case I guess.

Appart of that, it seems correct from a code point of view, but I do not know for thun functional part. 
Also, did you see Curtis comment?

2024-09-11 09:33 UTC, cedric-anne approved these changes

2024-09-11 09:35 UTC, cedric-anne requested changes
My bad, if there is transparency set, then it should probably be handled. The lib we use to convert colors does not support it, but it should not be a pain to do it manually (the code to convert a number to its hex value is quiet simple).

2024-09-18 12:51 UTC, cedric-anne approved these changes

2024-09-18 12:51 UTC, merged