Can see private task assign to me or my group
glpi-project/glpi pull request #17918
Opened 2024-09-24 09:40 UTC by Lainow

## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes !34489

I can see a private spot that has been assigned to me even though I don't have the right to see private spots.
Added the right to view my group's tasks.

## Screenshots (if appropriate):

2024-09-25 13:08 UTC, Rom1-B requested changes

2024-09-25 13:08 UTC, Rom1-B commented on src/CommonITILObject.php
> +                        'users_id_tech' => Session::getCurrentInterface() === "central" ? (int)Session::getLoginUserID() : 0,
Can you please add some tests ?

2024-09-26 11:14 UTC, Rom1-B requested changes

2024-09-26 11:14 UTC, Rom1-B commented on phpunit/functional/TicketTest.php
> +        ]);
I'm not sure the clone is essential?
```suggestion
        $this->createItem('User', [
            'name' => 'new_user',
            'login' => 'new_user',
            'password' => 'new_user',
            'password2' => 'new_user',
            '_profiles_id' => $new_tech,
            '_entities_id' => getItemByTypeName('Entity', '_test_root_entity', true),
        ]);
```

2024-09-26 11:14 UTC, Rom1-B commented on phpunit/functional/TicketTest.php
> +        ]);
You should create the profile directly without cloning, with only the rights you need.

2024-09-27 05:53 UTC, Rom1-B requested changes

2024-09-27 05:53 UTC, Rom1-B commented on phpunit/functional/TicketTest.php
> +
It creates the profile twice and none of them seem to be used
```suggestion
```

2024-09-27 08:02 UTC, Rom1-B commented on phpunit/functional/TicketTest.php
> +                'content'       => 'private task of only see his task user',
```suggestion
                'content'       => 'private task assigned to normal user',
```

2024-09-27 08:02 UTC, Rom1-B commented on phpunit/functional/TicketTest.php
> +                'private task of only see his task user',
```suggestion
                'private task assigned to normal user',
```

2024-09-27 08:02 UTC, Rom1-B commented on phpunit/functional/TicketTest.php
> +                'private task of only see his task user',
```suggestion
                'private task assigned to normal user',
```

2024-09-27 08:02 UTC, Rom1-B commented on phpunit/functional/TicketTest.php
> +                    'private task of only see his task user',
```suggestion
                    'private task assigned to normal user',
```

2024-09-27 08:56 UTC, Rom1-B approved these changes

2024-09-27 12:07 UTC, trasher approved these changes

2024-09-27 13:28 UTC, AdrienClairembault approved these changes

2024-09-30 12:04 UTC, cedric-anne approved these changes

2024-09-30 12:04 UTC, merged

2024-10-11 06:10 UTC, alisher372 commented
whats about assigned group to the private task