Create default forms on installation or update
glpi-project/glpi pull request #17942
Opened 2024-09-26 09:53 UTC by AdrienClairembault

## Checklist before requesting a review

*Please delete options that are not relevant.*

- [X] I have performed a self-review of my code.
- [X] I have added tests that prove my fix is effective or that my feature works.

## Description

Add two default forms when installing GLPI or updating to GLPI 11.
The goal is to copy the "old" helpdesk form:

![image](https://github.com/user-attachments/assets/30745fb5-589e-4e81-ac5e-888b4b15a535)

It is split into two Incident/Request forms which are almost identical.
Note that the "associated elements" question is missing because it isn't possible to implement it right now (we will work on that later) and that the picked "watchers" are also not applied into the ticket (not possible yet too).

The default forms themselves are subject to change later as we make the final adjustments before GLPI 11.
Right now, the goal is just to offer the same feature that in GLPI 10 but with two "real" forms.

2024-09-26 14:04 UTC, AdrienClairembault commented
Update tests fail with MariaDB, probably because it doesn't compare json correctly (as JSON is only a real type in MySQL).
We probably need to use the dedicated json_equals somewhere if we are on MariaDB but I am not sure if we want to waste time working on that (for a false positive).

![image](https://github.com/user-attachments/assets/1c3b1002-377f-4fd7-93ec-616330a2c74c)

Suggestions are welcome.

2024-09-27 07:47 UTC, AdrienClairembault commented
Nvm it is actually MySQL that fails the comparison 🤷 
I'm tempted to just ignore these two json fields in the update tests, ok for you @cedric-anne ?

2024-09-27 08:42 UTC, trasher commented
> I'm tempted to just ignore these two json fields in the update tests

I guess the problem is the tests suite is not ready for that kind of data; and therefore should be fixed; not ignored. Anyway, I do not know well that part, I've no proposition so far.

2024-09-30 12:17 UTC, AdrienClairembault commented
> I guess the problem is the tests suite is not ready for that kind of data; and therefore should be fixed; not ignored. Anyway, I do not know well that part, I've no proposition so far.

I agree but we have to pick our priorities at this time and this specific false positive case is very low in my TODO list.
If anyone else has more free time, feel free to correct it.

2024-09-30 13:46 UTC, cedric-anne requested changes

2024-09-30 13:46 UTC, cedric-anne commented on src/Glpi/Form/DefaultFormsManager.php
> +        );
This piece of code is not really resilient to default form data changes. It could probably be improved.

2024-10-01 11:32 UTC, cedric-anne approved these changes

2024-10-01 13:37 UTC, orthagh approved these changes
A few remark after I tested the current pr:

- the first one is already noted:
   > Note that the "associated elements" question is missing

   We should not ship 11.0 without that.

- Reset forms on an existing instance (update case). I found it worked when I removed all my existing forms. Maybe we can do better here? A cli command, a button in debug mode ?

- The current render of the form (by previewing it): it's bad; especially in comparison of the current hard-coded form. On my QHD screen, it's not displayed entirely without scrolling. Do we need to have one container with bug margins/paddings for each question/inputs?

2024-10-01 14:20 UTC, AdrienClairembault commented
> The current render of the form (by previewing it): it's bad;

This is known and will be worked on soon, don't worry ;)

2024-10-03 08:06 UTC, merged