Home page: use our own illustrations
glpi-project/glpi pull request #17958
Opened 2024-09-30 10:05 UTC by AdrienClairembault

## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [X] I have added tests that prove my fix is effective or that my feature works.

## Description

- Remove undraw
- Add our own illustrations into `/pics/illustrations`
- Add a new twig function to easily use the illustrations: `{{ render_illustration("my_icon.svg", 100) }}`
- The illustrations are adapted to the current user theme, this is done by injecting css variables into the SVG before it is rendered.

## Screenshots (if appropriate):

Note: icon are still being worked on and will keep being improved in further iterations.

![image](https://github.com/user-attachments/assets/b265d0c4-826e-484b-a17c-4f25083e60e0)

2024-09-30 13:29 UTC, cedric-anne requested changes

2024-09-30 13:29 UTC, cedric-anne commented on src/Glpi/UI/IllustrationManager.php
> +
`file_get_contents` will anyway trigger a warning if the file content cannot be fetched.

```suggestion
```

2024-09-30 13:29 UTC, cedric-anne commented on src/Glpi/UI/IllustrationManager.php
> +        $svg_content = $this->setSize($svg_content, $size);
This method is not really a getter.
```suggestion
        $svg_content = $this->adjustSize($svg_content, $size);
```

2024-09-30 14:10 UTC, orthagh approved these changes

2024-09-30 14:19 UTC, AdrienClairembault commented
Converted to draft as I've just received a new iteration of some icons.
I'll update it quickly.

2024-10-02 13:07 UTC, cedric-anne approved these changes
Seems OK, but you have conflicts to resolve.

2024-10-02 15:13 UTC, merged