feat(forms): Add a new step to the import process to solve requirements issues
glpi-project/glpi pull request #17996
Opened 2024-10-02 14:38 UTC by ccailly

## Checklist before requesting a review

*Please delete options that are not relevant.*

- [X] I have read the CONTRIBUTING document.
- [X] I have performed a self-review of my code.
- [X] I have added tests that prove my fix is effective or that my feature works.

## Description

- Add a new step when importing a form to reconcile objects not available on the GLPI where the form will be imported.
- Add an action to remove a form from the import list.

![image](https://github.com/user-attachments/assets/6f49b24e-a333-4c5c-9232-7453ed1e17ba)
![image](https://github.com/user-attachments/assets/8c838c3a-1578-4f8c-8754-ab205844b807)
![image](https://github.com/user-attachments/assets/be13e4b7-c559-4540-8de6-153e49a9d566)

2024-10-09 08:07 UTC, AdrienClairembault requested changes
The UI looks great but I have some request on the technical side.

The idea (which I should have worded directly in the specifications, my bad) was to use the existing DatabaseMapper object to add the replacements items without having to modify the code of the serializer itself.

Something like that:
```php
        $serializer = new FormSerializer();
        $mapper = new DatabaseMapper(Session::getActiveEntities());

+       $replacements = $request->request->all()["replacements"] ?? [];
+       foreach ($replacements as $replacement) {
+           $mapper->addMappedItem(...);
+       }

        return $this->render("pages/admin/form/import/step4_execute.html.twig", [
            'title'   => __("Import results"),
            'menu'    => ['admin', Form::getType()],
            'results' => $serializer->importFormsFromJson($json, $mapper),
        ]);
```

Unless there are some technical difficulties that I am missing, this solution would avoid needing to modify the serializer methods as we reuse the data mapper parameter that was made for this use case (I hope there are no tricky edge case that would make it impossible).

If this kind of solution can work, it will make the code much simpler :)

2024-10-16 09:57 UTC, AdrienClairembault reviewed
Regarding the removal of a form, there are two issues:
- We are searching on the form name
- We are editing the JSON

Searching on the form name may be dangerous as it is not guaranteed to be unique.
Maybe we should include some kind of unique ID for each forms into the export instead ?
Then we can exclude form using this id instead of the name.

I'd also like to avoid editing the JSON if possible.
An hidden input with the ids of the ignored forms would be simpler IMO.

Then the serializer can know that the form is ignored and we can display it on the report if you see what I mean ?

2024-10-21 09:23 UTC, AdrienClairembault requested changes

2024-10-21 09:23 UTC, AdrienClairembault commented on src/Glpi/Form/Export/Serializer/FormSerializer.php
> +
This is not longer used.

```suggestion
```

2024-10-21 09:23 UTC, AdrienClairembault commented on src/Glpi/Form/Export/Serializer/FormSerializer.php
> +    public function resolveIssues(
Can you rename this method ?
The current name seems to imply that it solve issues when it seems to be listing issues instead.

2024-10-21 09:23 UTC, AdrienClairembault commented on phpunit/functional/Glpi/Form/Export/FormSerializerTest.php
Can you add a new test case here to show that the skipped form parameter is taken into account ?

2024-10-21 09:23 UTC, AdrienClairembault commented on src/Glpi/Form/Export/Serializer/FormSerializer.php
> +        array $skipped_forms,
I think it make sense that the import can be run without ignoring any form, thus maybe this parameter should be optional (move it to last + add `[]` default value) ?

2024-10-21 09:23 UTC, AdrienClairembault commented on src/Glpi/Form/Export/Serializer/FormSerializer.php
> +        array $skipped_forms,
Same here regarding args order.

2024-10-21 09:23 UTC, AdrienClairembault commented on src/Glpi/Form/Export/Serializer/FormSerializer.php
> +
I think you forgot to switch to IDs here ;).
(It also mean the test suite is incomplete as it should catch this error).

2024-10-21 13:34 UTC, AdrienClairembault approved these changes

2024-10-23 14:02 UTC, cedric-anne requested changes

2024-10-23 14:02 UTC, cedric-anne commented on templates/pages/admin/form/import/step3_resolve_issues.html.twig
> +	<form method="POST" action="{{ path('Form/Import/Preview') }}">
This file is indented using tabs.

2024-10-28 14:12 UTC, cedric-anne approved these changes

2024-10-28 14:12 UTC, merged