Drop MysIsam support
glpi-project/glpi pull request #18017
Opened 2024-10-07 09:41 UTC by AdrienClairembault

## Checklist before requesting a review

*Please delete options that are not relevant.*

- [X] I have performed a self-review of my code.
- [X] I have added tests that prove my fix is effective or that my feature works.

## Description

Drop MysIsam support.

2024-10-07 14:25 UTC, AdrienClairembault commented
Test failure is unrelated, I'll rebase once main is fixed.

2024-10-08 07:21 UTC, cedric-anne requested changes

2024-10-08 07:21 UTC, cedric-anne commented on src/DBConnection.php
> -        bool $allow_myisam = true,
Please add a changelog entry:
```
`DBConnection::createMainConfig()` signature changed. The `$allow_myisam` parameter has been removed.
```

2024-10-08 07:21 UTC, cedric-anne commented on src/DBConnection.php
> -        bool $allow_myisam = true,
Same here.

2024-10-08 07:21 UTC, cedric-anne commented on src/DBmysql.php
> -    public $allow_myisam = true;
Please add a changelog entry for this removal.

2024-10-08 07:21 UTC, cedric-anne commented on src/Glpi/System/Requirement/TablesEngine.php
> + * @since 9.5.0
```suggestion
 * @since 11.0.0
```

2024-10-08 07:21 UTC, cedric-anne commented on src/Glpi/System/Requirement/TablesEngine.php
> +final class TablesEngine extends AbstractRequirement
```suggestion
final class DatabaseTablesEngine extends AbstractRequirement
```

2024-10-08 07:21 UTC, cedric-anne commented on src/Glpi/System/Requirement/TablesEngine.php
> +            __('DB tables engine')
```suggestion
            __('Database tables engine')
```

2024-10-08 07:21 UTC, cedric-anne commented on src/Glpi/System/Requirement/TablesEngine.php
> +        }
We should not list all the tables. Someone that has not yet run the migration would have a list of 300+ tables displayed.
Also, the `Please run the command` part should probably be added after the explaination of the validation failure.

I propose the following message:
> The database contains %d tables using the unsupported MyISAM engine. Please run the "%s" command to migrate them to the InnoDB engine.

2024-10-08 07:21 UTC, cedric-anne commented on src/Glpi/System/RequirementsManager.php
> +            $requirements[] = new DbEngine($db);
It should not be moved here. The display order in the UI correspond to the declaration order here.

2024-10-08 08:41 UTC, cedric-anne approved these changes

2024-10-08 08:48 UTC, orthagh approved these changes

2024-10-08 09:27 UTC, trasher approved these changes

2024-10-08 11:49 UTC, trasher commented
Please fix tests

2024-10-09 20:04 UTC, cedric-anne commented
Thinking about it again, I realize that completely blocking the creation of MyISAM tables is going to be painful to manage in the plugins. This PR was proposed to fix an issue on a GLPI table, I guess the `DatabaseTableEngine` requirement could only check GLPI core tables (the `DBmysql::getMyIsamTables()` have a boolean parameter to exclude plugins tables), and we could keep the previous behaviour (warning when a MyISAM table is created + warnings on the central page).

Anyway, I have no solution that could permit to prevent changes on the old migrations in GLPI itself.

2024-10-10 09:20 UTC, AdrienClairembault commented
Is it really that bad for plugins ? This can be fixed at once by a simple search and replace.
It feels like a minor issues compared to the whole auto escaping changes that will require a million times more more work for plugins maintainers.

2024-10-10 09:39 UTC, trasher commented
Fixing auto escaping is absolutely not comparable.

Are you arguing there already are breaking changes to introduce another one?
We have to think about how we can do the best to ease migration; and force changes only when it's really not possible (this is totally acceptable anyway).

2024-10-10 09:53 UTC, AdrienClairembault commented
> Are you arguing there already are breaking changes to introduce another one?

I am arguing that it takes 5 second to fix and that it wont be the painful part of migrating plugins to GLPI 11.

Forcing people to remove references to an engine that's been outdated for almost 15 years doesn't seem unreasonable to me.

2024-10-17 14:33 UTC, AdrienClairembault commented
Rebased to fix conflicts, only "Revert warning" commit was added.

2024-10-17 15:25 UTC, cedric-anne approved these changes

2024-10-17 15:26 UTC, merged