Fix tinymce on-demand loading
glpi-project/glpi pull request #18105
Opened 2024-10-20 17:03 UTC by cconard96

## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.

## Description

TinyMCE is currently loaded in two ways:
- Sector-based inclusion
- On-demand just before initializing the editor on a textarea

Neither of these cases are very good.

The first case technically works, but there can be some cases where the library is loaded for no reason. For example, it was included for the `central` page but its only ever actually used if you click on an event in the planning widget which loads the Reminder/Event form in a modal. If you don't actually initialize an editor, you have a 680kb script (non-minified size) being loaded for nothing.

The second case makes more sense, except that it doesn't actually load the library if initialized any time after `includeHeader` is called because `initEditorSystem` calls `requireJs`. Instead, it adds the library to the session property and would have it automatically load the next time `includeHeader` is called (page refresh). This is how you end up with bugs like #3663. The solution for the referenced issue was to just load the library for the entire `central` sector which is more of a workaround than addressing the actual issue.

You *could* directly import the required scripts by adding `script` tags with the `src` attribute set inside `initEditorSystem`, but that would load them multiple times if there are multiple editors.

The solution here is to move the initialization into its own script which imports the extra JS files and then use dynamic imports to ensure the module is only loaded once but still allows initializing multiple editors.

2024-10-28 15:18 UTC, AdrienClairembault commented on src/Html.php
> -
The underlying TODO has not been fixed, tinymce placeholder are still invisible without this code.

![image](https://github.com/user-attachments/assets/931b6929-660e-4d3d-b22a-31aaeb97983f)

2024-10-30 07:27 UTC, trasher requested changes
See @AdrienClairembault comment

2024-12-10 16:10 UTC, AdrienClairembault reviewed
Placeholder styles seems to not be fully loaded.

On main:
![image](https://github.com/user-attachments/assets/7125a3e4-e810-4ee4-84af-32c838c0a243)

With your changes:
![image](https://github.com/user-attachments/assets/23daec31-412e-4c76-bf77-3f0aa8eb699a)

There are a lot of extra padding and the text color isn't right.

edit: the cursor seems also wrong, it not longer have the `text` appearance.

2024-12-10 22:11 UTC, cconard96 commented
Positioning is the same for me regardless of if using the custom skin or oxide.

2024-12-11 09:23 UTC, AdrienClairembault reviewed
It seems to now work for some placeholders but not all:

![image](https://github.com/user-attachments/assets/b4de624f-7241-45a3-8a78-e610563ed585)

In this example the second one doesn't have the correct color.

Padding issues seems to be mostly resolved, there is still some additional left padding that seems to be applied when compared to `main` but I can live with it.

Nevertheless, maybe it mean the styles are not fully charged so it might be worth investigating because there might be other issues that we may miss here.

2025-01-14 23:29 UTC, cconard96 commented
I've reverted back to the oxide skin to unblock this PR. I'll work on fixing it in a different PR.

2025-01-16 10:00 UTC, cedric-anne commented on src/Html.php
>                  $_SESSION['glpi_js_toload'][$name][] = 'js/RichText/ContentTemplatesParameters.js';
There are many plugins that are using `Html::requireJs('tinymce')` in their script for the pages that contains a TinyMCE editor initialized by either `Html::textarea()` or the `textareaField()` Twig macro.

As far as I understand, this is no longer necessary, and the manual loading of the `lib/tinymce.js` lib is mandatory only if the initialization of the corresponding editor instance is made differently by the plugin. There is at least 2 plugins that do it. I am not sure it corresponds to legitimate cases, but keeping this way of loading TinyMCE lib is not an issue.

1. I think we should add a changelog entry to explain that it is no longer necessary to manually load TinyMCE in the most common cases.
2. We should probably only load the `lib/tinymce.js` script here. If a plugin has its own TinyMCE init logic, it is probable that it does not use the form tags / user mentions / content templates features.

2025-01-20 14:33 UTC, cedric-anne requested changes
Tests are still failing.

2025-03-19 13:25 UTC, orthagh approved these changes
Seems operational for me.
The move to a module is clearly welcomed.

I checked the form editor, unless I'm wrong, the previously mentioned issues are fixed.
Could you quickly check @AdrienClairembault ?

2025-03-19 14:17 UTC, AdrienClairembault reviewed
I am not sure about this because it slow down the loading of tinymce.

This issue with that is that until tinymce is loaded, the "raw" textarea is displayed instead of tinymce container.

This lead to a visual "stutter" where the UI update awkwardly when the page is loaded.

See:
![module_tiny](https://github.com/user-attachments/assets/36b4f1f6-4bab-4282-bd93-769789c2189e)

Compared to main:
![main_tiny](https://github.com/user-attachments/assets/15065b85-f76a-4313-832e-4fcae7f8f5a1)

It is more noticeable on some page than others.

2025-03-19 14:36 UTC, cconard96 commented
TinyMCE was already slow to initialize but I didn't notice it slowing down more. In general, it's far from lightweight. Preferably we wouldn't wait for an instance to be needed to load the library but it is not wanted by others to globally load TinyMCE JS.

2025-03-24 12:48 UTC, AdrienClairembault requested changes
I can clearly see the difference on my side (maybe other people can confirm).
It should be fixed before merging this IMO.

2025-03-24 16:18 UTC, cconard96 commented
> I can clearly see the difference on my side (maybe other people can confirm). It should be fixed before merging this IMO.

Feel free to offer suggestions, but even in debug mode and with browser cache disabled, a TinyMCE editor loads and is ready to use in about a second from the page requested for me which is about standard even before this PR. Tested with the "Text in the login box" field in general setup, Forms, and a new ticket. Changing *how* the JS is imported should have little effect especially in production when it will be cached anyways and it seems like the TinyMCE code is delayed until the DOM is ready anyways.

For the description for a new ticket, it takes 450ms from the start of the `TinyMCEEditor` constructor until the `tinymce.init` promise resolves. TinyMCE plugins account for a bit of this, but even without plugins it is still around 380-400ms.

2025-03-25 08:09 UTC, AdrienClairembault commented
@orthagh suggested loading the module in the main page instead (the issue here is that the script is executed after the tab itself is being fetched).

2025-07-21 14:40 UTC, cedric-anne commented
What should we do with this PR?

@cconard96 @orthagh

2025-07-21 14:51 UTC, cconard96 commented
> What should we do with this PR?
> 
> @cconard96 @orthagh

I'm going to refrain from having a strong opinion other than *something* needs done to fix TinyMCE loading.
Another option @trasher suggested in #20020 was to always load the TinyMCE library.

2025-09-03 13:15 UTC, cconard96 commented
The issue was fixed by always loading TinyMCE in https://github.com/glpi-project/glpi/pull/20380. I don't think this PR needs to remain open even if we decide to switch back to on-demand loading later.

2025-09-03 13:15 UTC, closed without merging