Add pending reason notification events
glpi-project/glpi pull request #18162
Opened 2024-10-30 10:03 UTC by cconard96

Fixes !34694

Add ITIL notification events for:
- Adding pending reason to ITIL item
- Removing pending reason from ITIL item
- ITIL item closed automatically from pending reason

The following event already existed:
- Automatic reminder

2024-10-30 10:17 UTC, trasher approved these changes

2024-10-30 10:22 UTC, cedric-anne approved these changes

2024-10-30 10:33 UTC, AdrienClairembault requested changes
Can this be tested ?

2024-10-30 10:39 UTC, cconard96 commented
Well its broken anyways. Not that I've ever had notifications set up and working properly.

2025-01-16 12:35 UTC, cedric-anne approved these changes

2025-01-16 14:06 UTC, AdrienClairembault approved these changes

2025-01-16 14:06 UTC, merged