fix(inventory): is_recursive
glpi-project/glpi pull request #18227
Opened 2024-11-05 13:17 UTC by Rom1-B

## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes !34858
- During an inventory, it was not possible to create a monitor (for example) recursively. The main computer can be created recursively through rules, but this does not apply to related items.

## Screenshots (if appropriate):

2024-11-05 13:20 UTC, trasher commented on src/Inventory/Asset/MainAsset.php
> +                    $this->is_recursive = $input['is_recursive'] = $dataEntity['is_recursive'];
I'm not sure I understand what will  happen here.

2024-11-05 14:17 UTC, trasher commented on src/Inventory/Asset/InventoryAsset.php
> +    public function setEntityID($id, $is_recursive = 0): InventoryAsset
Maybe add a new new `setEntityRecursive` method or rename to `setEntity` (and change phpdoc).

2024-11-05 14:17 UTC, trasher reviewed
Looks correct, please add a test.

2024-11-05 15:00 UTC, trasher commented on src/Inventory/Asset/MainAsset.php
> +                    $this->is_recursive    = $dataEntity['is_recursive'];
```suggestion
                    $this->setEntityRecursive($dataEntity['is_recursive']);
```

2024-11-06 08:31 UTC, stonebuzz commented
make sure that for all objects managed by the native inventory as : 

![image](https://github.com/user-attachments/assets/f2eb1712-f76a-42d7-a23e-4222b80a241a)

If the corresponding table contains `is_recursive` , the native inventory must forward the value of the main asset to the linked element. 

Except for objects inherited from `CommonDBChild`  and declared in 

```php
    protected static $forward_entity_to = ['Item_Disk','ItemVirtualMachine',
        'Item_SoftwareVersion', 'Infocom',
        'NetworkPort', 'ReservationItem',
        'Item_OperatingSystem'
    ];
```

Because GLPI core already handles entity/recursivity tracking

2024-11-06 08:33 UTC, stonebuzz commented
MainAsset should be 

- Computer
- Printer
- NetworkEquipement
- Phone

(be careful of `Unamanged` which can be created from a `NetworkPort` on a `NetworkEquipement`)

2024-11-08 10:27 UTC, stonebuzz requested changes

2024-11-08 10:27 UTC, stonebuzz commented on phpunit/functional/Glpi/Inventory/InventoryTest.php
> +                        // && !($asset instanceof \Glpi\Inventory\Asset\Software)
it looks like we're testing the Softawre part (I can't remember if we decided not to touch it, as the destination entity management is different from classic management).

2024-11-13 08:19 UTC, stonebuzz approved these changes

2024-11-13 09:05 UTC, trasher approved these changes

2024-11-13 09:06 UTC, merged