Search for forms and faq articles on home page
glpi-project/glpi pull request #18239
Opened 2024-11-06 11:08 UTC by AdrienClairembault

## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [X] I have added tests that prove my fix is effective or that my feature works.

## Description

Allow user to search for forms and faq articles on home page.

## Screenshots (if appropriate):

![image](https://github.com/user-attachments/assets/6dbe56ec-dd09-4675-ac19-1b3917fc012c)

2024-11-21 09:15 UTC, cedric-anne requested changes

2024-11-21 09:15 UTC, cedric-anne commented on templates/pages/helpdesk/search.html.twig
> +                            {{ faq.answer|raw }}
```suggestion
                            {{ faq.answer|safe_html }}
```

2024-11-21 09:15 UTC, cedric-anne approved these changes

2024-11-21 09:37 UTC, orthagh commented
A question also, how behave the description if (very) long ?

2024-11-25 08:00 UTC, AdrienClairembault commented
> What will happen if there is 50 FAQ entries and 10 forms matching the searched term ?

I want to add some kind of infinite scroll (or similar solutions) later.
For now we can put an hardcoded limit to 20.

2024-11-25 08:04 UTC, AdrienClairembault commented
> A question also, how behave the description if (very) long ?

There is an ellipsis:

![image](https://github.com/user-attachments/assets/fa6a4b37-d495-495b-b04a-304e3976b088)

2024-11-25 08:17 UTC, orthagh approved these changes
Please add the limit, yes. Anyway OK for me.

2024-11-25 11:18 UTC, cedric-anne approved these changes

2024-11-25 11:19 UTC, merged