Add option to set default state for planned task
glpi-project/glpi pull request #18264
Opened 2024-11-07 14:41 UTC by ArthurMinfotel

## Checklist before requesting a review

- [ x ] I have read the CONTRIBUTING document.
- [ x ] I have performed a self-review of my code.

## Description

- Add a configuration option to set the default state of planned task separately from regular tasks.

## Screenshots :

General setup : 
![image](https://github.com/user-attachments/assets/aeccca31-b1b9-4faf-b6b6-bf574ad33269)

User preferences : 
![image](https://github.com/user-attachments/assets/239935ee-512b-4c91-9dc5-00486b5ff30b)

Opening a task form : 
![image](https://github.com/user-attachments/assets/fe07a882-4339-4267-bc48-5ddde78d7b96)

After clicking the button to open the planned task part : 
![image](https://github.com/user-attachments/assets/63dcb067-9b86-4e31-858c-b83c85b76d8e)

2025-01-15 10:30 UTC, cedric-anne requested changes
@ArthurMinfotel Please fix tests.

2025-01-16 13:20 UTC, orthagh approved these changes

2025-01-16 13:39 UTC, trasher requested changes
This branch must be rebased, and tests must be fixed

2025-01-29 13:29 UTC, cedric-anne requested changes

2025-01-29 13:29 UTC, cedric-anne commented on install/migrations/update_10.0.x_to_11.0.0/configs.php
> +);
Please add this new field in the `glpi-empty.sql` file.

2025-01-29 13:41 UTC, cedric-anne commented on install/migrations/update_10.0.x_to_11.0.0/configs.php
> +    'int',
```suggestion
    'int DEFAULT NULL',
```

2025-01-29 14:24 UTC, trasher approved these changes

2025-02-18 08:47 UTC, cedric-anne requested changes

2025-02-18 08:47 UTC, cedric-anne commented on install/migrations/update_10.0.x_to_11.0.0/configs.php
> +    'planned_task_state' => Planning::TODO,
It is preferable to use only raw values in the migration code. This prevents the migration behaviour to change if the corresponding constant value changes.

```suggestion
    'planned_task_state' => '1',
```

2025-02-18 08:47 UTC, cedric-anne commented on install/migrations/update_10.0.x_to_11.0.0/configs.php
> +    ['value' => Planning::TODO]
`value` is for the default value (and it is alrready defined by `DEFAULT NULL`).
```suggestion
    ['update' => 1]
```

2025-02-18 08:48 UTC, cedric-anne approved these changes

2025-02-18 09:29 UTC, cedric-anne commented on install/migrations/update_10.0.x_to_11.0.0/configs.php
> +    ['update' => 1]
In fact the value should remain `NULL` for existing users, to be sure that the default config is applied.
```suggestion
    'int DEFAULT NULL'
```

2025-02-18 09:30 UTC, AdrienClairembault approved these changes

2025-02-18 10:18 UTC, merged