Add VM OS and IP Inventory
glpi-project/glpi pull request #18265
Opened 2024-11-07 14:48 UTC by Lainow

*Please delete options that are not relevant.*

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes !34616 and !32800
- Here is a brief description of what this PR does

Addition of the operating system and ip in the information retrieved from the vCenter API by the agent

## Screenshots (if appropriate):

2024-11-07 15:47 UTC, stonebuzz commented
@Lainow 

can you add test for OS (Even if the implementation was already OK on the inventory side)

2024-11-08 10:26 UTC, stonebuzz requested changes

2024-11-08 10:26 UTC, stonebuzz commented on phpunit/functional/Glpi/Inventory/Assets/VirtualMachineTest.php
> +          ]));
can you check IPAddress value

2024-11-08 10:26 UTC, stonebuzz commented on phpunit/functional/Glpi/Inventory/Assets/VirtualMachineTest.php
> +          ]));
can you check OS value

2024-11-13 08:19 UTC, stonebuzz approved these changes

2024-11-13 08:48 UTC, cedric-anne commented
@Lainow 

Please rebase your PR to ensure that test suite is executed on an up-to-date branch.

2024-11-13 09:36 UTC, merged