Add the port ID connected to the requested port
glpi-project/glpi pull request #18298
Opened 2024-11-13 14:04 UTC by RomainLvr

## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes !35017
- Here is a brief description of what this PR does

Retrieve the network ports of connected devices. Previously, the API only provided information about the main device's network ports, not its connections. The added code uses `NetworkPort::getContact` to retrieve the connected port ID `netport_oppositecontactID`, allowing users to identify connected devices directly in the API response. This addition is visible when the `with_networkports` option is enabled in the request.

2024-11-13 14:33 UTC, cedric-anne requested changes

2024-11-13 14:33 UTC, cedric-anne commented on src/Api/API.php
> +                            $data['netport_oppositecontactID'] = $oppositecontactID ;
`networkports_id_opposite` would be preferable to match naming conventions.

```suggestion
                            $data['networkports_id_opposite'] = $oppositecontactID ;
```

2024-11-13 14:33 UTC, cedric-anne commented on src/Api/API.php
> +                        }
It is preferable to have similar keys in all JSON responses from a same endpoint.

```suggestion
                        } else {
                            $data['networkports_id_opposite'] = null;
                        }
```

2024-11-14 10:30 UTC, AdrienClairembault approved these changes

2024-11-14 13:12 UTC, trasher commented
Please add tests.

2024-11-20 07:20 UTC, trasher approved these changes
LGTM, but need someone else that know the API should review this one.

2024-11-20 09:52 UTC, cedric-anne reviewed
It is OK for me, but I think we should integrate it only in the main branch. Indeed, some API client libraries providing automatic conversion from response to object may be really strict and may be broken by the addition of a property unknown to them.

2024-11-20 09:58 UTC, cedric-anne approved these changes
I changed the target branch to main and rebased your changes.

2024-11-20 14:57 UTC, merged