Permit to authenticate to the HL API doc using the session cookie
glpi-project/glpi pull request #18301
Opened 2024-11-13 15:29 UTC by cedric-anne

## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.

## Description

Instead of using the `remember_me` cookie, I p^ropose to use directly the session cookie for the HL API doc authentication. It fixes #18299.

2024-11-13 16:04 UTC, cconard96 approved these changes

2024-11-14 06:55 UTC, trasher requested changes
Tests are broken

2024-11-14 07:45 UTC, cedric-anne commented
As said in the failing test comment it should be rewriten: https://github.com/glpi-project/glpi/blob/484a265d49e0aefd4edebfbb2917706b5e9ebcbe/tests/functional/Glpi/Api/HL/Controller/CoreController.php#L329-L331

I do not have time to do it right now, so I put back this PR status to draft

2025-03-26 16:04 UTC, cedric-anne commented
I do not have time right now to finish this.

2025-03-26 16:04 UTC, closed without merging