Add User itemtype to Licenses & Contracts linked items
glpi-project/glpi pull request #18335
Opened 2024-11-18 13:35 UTC by RomainLvr

## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes !34567
- Here is a brief description of what this PR does

## Screenshots (if appropriate):

Adding the relationship of Licenses and Contracts to Users

Licenses : 

![image](https://github.com/user-attachments/assets/b0812af1-e8b0-43ea-8ec1-0311354ccc16)

Contracts : 
![image](https://github.com/user-attachments/assets/f862c3bf-f7c7-4824-8e09-e4deaf87ce08)

2024-11-18 13:52 UTC, AdrienClairembault commented
The discussion in #13294 seems to to indicate that this feature was refused last time.

I've also found this on our gitlab: https://gitlab.teclib.com/editions/projects/features-request/-/issues/133

2024-11-18 14:14 UTC, cconard96 commented
AFAIK this still hasn't been planned out and there is so much related to license management that people have been asking for for years that just isn't possible yet. It only really makes sense to me to do a complete rework.

2024-11-25 14:43 UTC, orthagh commented
I don't remember at all the reason why #13294 was refused.
After checking, the important point is the summary tab and the countdown of used licenses and this seems to work correctly.

Maybe there are issues (I didn't check) with linking entities of users, which are managed differently than in other objects.
Also, if we start adding more objects to licenses, we need a dedicated CFG_GLPI constant.

As Curtis says, we still should rework licenses and at least **decouple them from software itemtype**, but regarding assignments to users, I don't see UX issues. As said above, there may exist technical problems.

2024-12-06 07:59 UTC, stonebuzz approved these changes

2024-12-09 13:09 UTC, cedric-anne requested changes
You should add a `SoftwareLicense_User` tab in the `User` form.

2024-12-09 13:09 UTC, cedric-anne commented on front/item_softwarelicense.form.php
> +    $_POST['users_id'] = $_POST['items_id'];
```suggestion
    $_POST['users_id'] = $_POST['items_id'];
    unset($_POST['itemtype'], $_POST['items_id']);
```

2024-12-09 13:09 UTC, cedric-anne commented on install/migrations/update_10.0.x_to_11.0.0/software_license.php
> +if ($DB->fieldExists(SoftwareLicense::getTable(), 'softwares_id')) {
Migrations should always use hardcoded names. Same remark for other occurrences in this file.

```suggestion
if ($DB->fieldExists('glpi_softwarelicenses', 'softwares_id')) {
```

2024-12-09 13:09 UTC, cedric-anne commented on install/migrations/update_10.0.x_to_11.0.0/software_license.php
> + * @copyright 2003-2014 by the INDEPNET Development Team.
No need to have this copyright line on new files.

```suggestion
```

2024-12-09 13:09 UTC, cedric-anne commented on install/mysql/glpi-empty.sql
> +) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;
Please move this before `SET FOREIGN_KEY_CHECKS=1;`.

2024-12-09 13:09 UTC, cedric-anne commented on src/Item_SoftwareLicense.php
> +        // Add LicensSoftwareLicense_Usere_User
```suggestion
        // Add SoftwareLicense_User
```

2024-12-09 13:09 UTC, cedric-anne commented on src/Item_SoftwareLicense.php
> +                new QueryExpression($DB::quoteValue(1), 'is_dynamic'),
```suggestion
                new QueryExpression($DB::quoteValue(0), 'is_dynamic'),
```

2024-12-12 09:02 UTC, cedric-anne approved these changes

2024-12-12 10:50 UTC, trasher approved these changes

2024-12-12 10:51 UTC, merged