Stream only specific responses
glpi-project/glpi pull request #18348
Opened 2024-11-19 10:52 UTC by cedric-anne

## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.

## Description

The proposed changes should permit to limit the usage of streamed responses to the endpoints that actually really require it.

These changes will also permit:
 - to detect unexpected `flush()`/`ob_flush()`/`ob_clean()`/`ob_end_clean()` operations (I added a warning for this);
 - to add the Symfony profiler in all GLPI pages, unless an `exit()`/`die()` instruction is used.

Whitespace changes should be ignored for the review. Many changes are just related to encapsulation of some scripts in a streamed response object.

2024-11-19 10:56 UTC, trasher approved these changes

2024-11-19 10:58 UTC, AdrienClairembault approved these changes

2024-11-19 11:01 UTC, cconard96 requested changes
This would break the handling of debug error messages by the new API.
See DebugResponseMiddleware.php.

This handling would have to be adjusted.

2024-11-19 11:20 UTC, cedric-anne commented
> This would break the handling of debug error messages by the new API. See DebugResponseMiddleware.php.
> 
> This handling would have to be adjusted.

I reverted the changes made on the HLAPI. It will not be impacted by the current changes because it has its own controller.

2024-11-19 11:21 UTC, cconard96 approved these changes

2024-11-19 11:38 UTC, flegastelois requested changes
Blank page (without errors): /front/ruledictionnarysoftware.php?replay_rule=replay_rule

2024-11-19 14:26 UTC, cedric-anne commented
I put this PR back to draft.

In GLPI 11.0, the progress bar display is broken. I am not able to understand what is the issue behind this. Anyway, using `flush()` not always work as expected. For instance, if there is a proxy between the client and the PHP server, then the proxy may wait for the full response to be received before sending it to the client. The webserver itself may act like this.

With #18296, we will add a new progress bar system that we will have to use in replacement of the current system. Once it will be done, the current PR will be ready to be merged.

I tested the `/front/cron.php` beahaviour (by putting `sleep(5); Toolbox::logDebug('OK');` after the `flush()` instruction), and it is OK on my machine, the browser consider the response as fully received after 50ms, and the execution continues on the PHP server.

2025-04-17 14:08 UTC, AdrienClairembault approved these changes

2025-04-18 08:42 UTC, Pierstoval requested changes

2025-04-18 08:42 UTC, Pierstoval commented on src/Glpi/Controller/LegacyFileLoadController.php
> +                sprintf('Unexpected output detected in `%s`.', $target_file),
```suggestion
                sprintf('Sending headers in scripts is deprecated. Occurred in `%s`.', $target_file),
```

Makes it clearer that it's about headers

2025-04-18 08:42 UTC, Pierstoval commented on src/Glpi/Controller/LegacyFileLoadController.php
> +                    sprintf('Unexpected output detected in `%s`.', $target_file),
```suggestion
                    sprintf('Sending output (via "echo", raw HTML or other methods) is deprecated in scripts, you should return an instance of "%s" instead. Occurred in `%s`.', Response::class, $target_file),
```

2025-04-18 12:51 UTC, trasher approved these changes
LGTM, not sure I have tested all possible cases, but I did not see any flagrant issues so far.

2025-04-22 07:27 UTC, cedric-anne commented on src/Glpi/Controller/LegacyFileLoadController.php
> +                    sprintf('Unexpected output detected in `%s`.', $target_file),
Sending output via `echo` or any other method is not deprecated yet. The issue here is that a script returns a `Response` instance and, at the same time, outputs something.

2025-04-22 07:28 UTC, cedric-anne commented on src/Glpi/Controller/LegacyFileLoadController.php
> +                sprintf('Unexpected output detected in `%s`.', $target_file),
Headers will be sent only if something forces the output to be flushed. Otherwise, it will be buffered.

2025-04-22 07:29 UTC, merged