feat(forms): Horizontal layout
glpi-project/glpi pull request #18354
Opened 2024-11-20 13:32 UTC by ccailly

## Checklist before requesting a review

*Please delete options that are not relevant.*

- [X] I have read the CONTRIBUTING document.
- [X] I have performed a self-review of my code.
- [X] I have added tests that prove my fix is effective or that my feature works.
- [X] This change requires a documentation update.

## Description

Added the possibility of grouping up to 4 questions (or comments) in a horizontal layout.

## Screenshots (if appropriate):

[Capture vidéo du 20-11-2024 14:15:52.webm](https://github.com/user-attachments/assets/74f3ce68-6b0a-4926-96a8-bf5641ebe614)

2024-11-20 15:27 UTC, ccailly commented
Horizontal layout behavior on form rendering.

[Capture vidéo du 20-11-2024 16:24:18.webm](https://github.com/user-attachments/assets/e46d0fad-b0d4-49e2-8322-e840b565d619)

2024-11-22 14:26 UTC, AdrienClairembault commented
When dragging a question from a horizontal row, it can't be added next to a a question that is not on a row:

![image](https://github.com/user-attachments/assets/89845e1a-35b1-4bad-8a49-73b4950e37f5)

It only work with questions that are not from a row (you can see the extra space that allow the question to be inserted):

![image](https://github.com/user-attachments/assets/d63b5013-6479-42f2-939a-74eb7ef54252)

2024-12-11 10:07 UTC, AdrienClairembault requested changes
Some UI suggestions, pinging @orthagh to confirm if he agrees with it.

![form-split1](https://github.com/user-attachments/assets/8d6f7cb6-fd77-4024-a2f3-cbeaae6c1f94)

1) I think the actions should be displayed when you hover on the empty blocks (rather than having to click inside of them to see the actions).

2) Not sure about the button styling, it feels a bit strange with the "straight" border radius.
IMO, just using a `cursor:pointer` for the active state would be enough and we wouldn't need to use the active button styling.

3) The buttons are displayed in a muted style when inactive. It make them feel "disabled", I think displaying them at the normal opacity would be clearer.

![form-split2](https://github.com/user-attachments/assets/d2062ee1-6990-4ca3-acb4-9a850994d176)

I can't move my question into the open slots, not sure if it is on purpose ?
Also each time I drop it, a slot disappears.

![form-split3](https://github.com/user-attachments/assets/a7f31a3b-e163-439a-bd38-6dad6e7b5ef8)

Shouldn't deleting the second slot transform my field into a single row item since there is only one slot left ? The split row controls are still displayed here, it seems impossible to remove them.

![form-split4](https://github.com/user-attachments/assets/4bff6934-892b-4401-b8d8-54c159e53eeb)

It seems questions are always moved to the first slot, even when inserted into a specific slot.

2024-12-11 10:40 UTC, orthagh commented
> I think the actions should be displayed when you hover on the empty blocks (rather than having to click inside of them to see the actions).

Yes, but take into account a way to display them in responsive mode. We may have an active state in addition of hover.
Or just make behavior differ on both displays, hover on a big screen, active on mobile.

> Shouldn't deleting the second slot transform my field into a single row item since there is only one slot left ? The split row controls are still displayed here, it seems impossible to remove them.

Agree

2024-12-30 10:12 UTC, AdrienClairembault commented
Sometimes the drag and drop become very small (seems to happens randomly):

![image](https://github.com/user-attachments/assets/6ba7aac3-ad2a-43a7-9fa9-1bed21b427b0)

2024-12-30 10:12 UTC, AdrienClairembault commented
I think you already known this one but the "vertical" styles are not applied sometimes:

![image](https://github.com/user-attachments/assets/9c257d40-8f5a-4f5b-9239-ff74c2d1bba2)

2025-01-02 13:07 UTC, ccailly commented
> Sometimes the drag and drop become very small (seems to happens randomly):
> 
> ![image](https://private-user-images.githubusercontent.com/42734840/399269233-6ba7aac3-ad2a-43a7-9fa9-1bed21b427b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4MjM0NDUsIm5iZiI6MTczNTgyMzE0NSwicGF0aCI6Ii80MjczNDg0MC8zOTkyNjkyMzMtNmJhN2FhYzMtYWQyYS00M2E3LTlmYTktMWJlZDIxYjQyN2IwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAyVDEzMDU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMzU0YWY1MzRiNWE3ZDA3YmZlOTYxNzU4YWRhNGMxMGMxN2YzZGQ4NGYxZWUyY2QyYmNmZjY5ZmQyNmExMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.44bfNsYw_iXDWh3YiU3iuPud5c5ubtGu7L7O5_mN5Dg)

I haven't been able to reproduce this bug, I've tried a lot of things but I never get this all-crushed display.

2025-01-06 09:46 UTC, AdrienClairembault commented
Maybe we should force the height to be identical for a single row ?

![image](https://github.com/user-attachments/assets/33ae0273-3396-4cec-8cf4-c017be8fc0f6)

2025-01-07 09:05 UTC, AdrienClairembault reviewed
It feels very nice and easy to use. I think we are good overall and can merge once the tests go green.
Do you want to do a final review on your side @orthagh ?

Note that there are probably a few minors issues that can still be found, but we can fix them later to avoid keeping this PR open too long.

2025-01-07 13:02 UTC, orthagh commented
I may want to make a final check yes.
Will try to do that this afternoon.

2025-01-08 10:42 UTC, orthagh approved these changes

2025-01-13 13:23 UTC, trasher commented
Please review sonar issues

2025-01-13 13:30 UTC, ccailly commented
> Please review sonar issues

The issues reported by SonarQube don't seem to be related to my changes.
I've made changes to the `Html.php` file, but not to the method that's causing the problem.
I can look into it, but probably in another PR to avoid complicating this one.

2025-01-14 06:54 UTC, trasher commented
Sonar issues are indeed now fixed (after you rebase). But now, database update is failing.

2025-01-16 11:39 UTC, cedric-anne approved these changes

2025-01-16 14:36 UTC, AdrienClairembault approved these changes

2025-01-16 14:42 UTC, merged