Fix tickets users added after webhook filter check
glpi-project/glpi pull request #18391
Opened 2024-11-27 09:30 UTC by RomainLvr

## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes !35208
- Here is a brief description of what this PR does

In the webhook filters, when targeting ticket creations (e.g., "Technician assigned is Jon Doe"), the webhook is not triggered for a ticket that meets the valid conditions.
The issue lies in the fact that post_add elements (such as adding a user to the ticket) are processed only after the filtering criteria are evaluated to determine whether the webhook should be triggered.

## Screenshots (if appropriate):
![image](https://github.com/user-attachments/assets/d76911b8-f3d3-47f7-94cb-2f8593bb95ec)

2024-11-27 09:47 UTC, cconard96 approved these changes

2024-11-27 09:57 UTC, Rom1-B requested changes

2024-11-27 09:57 UTC, Rom1-B commented on src/CommonDBTM.php
>                      Plugin::doHook(Hooks::ITEM_ADD, $this);
Why before the hook and not after?
```suggestion
                    Plugin::doHook(Hooks::ITEM_ADD, $this);
                    Webhook::raise('new', $this);
```

2024-12-02 09:29 UTC, cedric-anne approved these changes

2024-12-03 09:11 UTC, cedric-anne approved these changes

2024-12-03 10:53 UTC, AdrienClairembault approved these changes

2024-12-03 11:02 UTC, Rom1-B approved these changes

2024-12-03 13:22 UTC, merged