Fix: Preserve Redirection Links for Images in Emails
glpi-project/glpi pull request #18397
Opened 2024-11-27 16:04 UTC by MyvTsv

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [ ] I have added tests that prove my fix is effective or that my feature works.

## Description

It fixes !35308 and !36506

When an image is sent by email, it is possible to link it in order to redirect the user to another page. SharePoint uses this system which links to images. The problem is that if the user sends an image containing a redirect link, GLPI displays the image in the DOM but does not redirect the user to the associated link.

2024-11-28 13:13 UTC, stonebuzz commented
Maybe a new test should be added (instead of update it) to test the regex format (permissive now) 

To test that it accepts any type of content before or after `<img>`, including HTML tags.

```html
<a href="example.com">
  <span>Balise imbriquée</span>
  <img src="image.jpg" alt="Image" class="tag-class" />
</a>
```

```html
<a href="example.com">
  Une image simple
  <img src="image.jpg" alt="Image" class="tag-class" />
  Plus de texte ici
</a>
```

```html
<a href="example.com">
  <div>
    Contenu complexe
    <img src="image.jpg" class="tag-class" />
  </div>
</a>
```

2024-12-02 09:32 UTC, cedric-anne requested changes
The previous test case should be preserved.

2024-12-06 07:23 UTC, stonebuzz requested changes
Other format should be test too

2024-12-06 07:23 UTC, stonebuzz commented on phpunit/functional/ToolboxTest.php
> +            then a second image surrounded by links <a href="http://www.example.org/">link1</a> <img alt="{$img_2_tag}" width="10" src="{$image_2_src}" /> <a href="http://www.example.org/2">link2</a>
```suggestion
            then a second image surrounded by links <a href="http://www.example.org/">link1</a> <a href="{$image_2_src}" target="_blank" ><img alt="{$img_2_tag}" width="10" src="{$image_2_src}" /></a> <a href="http://www.example.org/2">link2</a>
```

2025-02-04 14:09 UTC, Rom1-B requested changes
You need to add these test cases without modifying the originals

2025-02-05 15:30 UTC, Rom1-B requested changes
Please add tests case

2025-02-26 11:09 UTC, stonebuzz approved these changes

2025-02-26 12:09 UTC, trasher approved these changes

2025-02-26 12:49 UTC, cedric-anne commented on src/Toolbox.php
> +                                $pattern = '/<a[^>]*>(?![^<]*<a)(?:(?!<\/a>)[\s\S])*?<img[^>]*' . preg_quote($image['tag'], '/') . '[^>]*>[\s\S]*?<\/a>/s';
Could you please add a comment in the code that explain all parts of this pattern ?

2025-02-26 13:13 UTC, cedric-anne commented on src/Toolbox.php
> +                                $pattern = '/<a[^>]*>(?![^<]*<a)(?:(?!<\/a>)[\s\S])*?<img[^>]*' . preg_quote($image['tag'], '/') . '[^>]*>[\s\S]*?<\/a>/s';
Maybe this pattern would be easier to understand:
```php
// Try to detect any unclosed `<a>` tag that preced the `<img>` tag
$pattern = '/<a[^>]*>(?:(?!<\/a>).)*<img[^>]* . preg_quote($image['tag'], '/') . '/s';
```

It will detect any unclosed `<a>` tag that precede the `<img>` tag. IMHO, there is no need to try to detect the closing `</a>` placed after the `<img>` tag.

2025-02-27 11:31 UTC, cedric-anne approved these changes

2025-02-27 11:32 UTC, merged