fix: add hook display_login in login error page
glpi-project/glpi pull request #18413
Opened 2024-11-29 07:53 UTC by MyvTsv

- [ ] I have read the CONTRIBUTING document.
- [ ] I have performed a self-review of my code.

## Description

- It fixes !35394
Added a display_login hook in login_error.html.twig which allows to change the logo thanks to the branding plugin

## Screenshots (if appropriate):

![Capture d’écran du 2024-11-29 08-52-09](https://github.com/user-attachments/assets/f5f9c0c2-414a-4dc1-9034-abfbb9fa3ae0)

2024-11-29 08:23 UTC, stonebuzz approved these changes

2024-11-29 08:25 UTC, stonebuzz requested changes

2024-11-29 08:25 UTC, stonebuzz commented on templates/pages/login_error.html.twig
> +            {{ call_plugin_hook(constant('Glpi\\Plugin\\Hooks::DISPLAY_LOGIN')) }}
Maybe a new hook `DISPLAY_LOGIN_ERROR` should be created to differentiate between the login page and the login error page 

If I take the example of the news plugin (which lets you add information to the home page), this change will also display the information on the error page

2024-12-02 09:03 UTC, cedric-anne requested changes
This will not fix some specific pages, like the password recovery pages. The best solution,  IMHO, is to add 3 new hooks, `add_css_notlogged`, `add_javascript_notlogged` and `add_header_tag_notlogged`, and use them in the `/templates/layout/page_card_notlogged.html.twig` context. This will provide a generic and flexible solution that could be used more widely than hooks dedicated to precise pages.

2024-12-03 09:26 UTC, cedric-anne requested changes
1. The logic could be moved in the `FrontEndAssetsExtension`. Indeed, you could declare Twig function like `get_plugins_js_files(bool $is_anonymous_page)` that would do the same as your `Html::add_css_file_plugin()` method. Then it could be used in the `templates/layout/parts/head.html.twig` and the `templates/layout/parts/page_footer.html.twig` files like this: `{% set js_file = js_file|merge(get_plugins_js_files(is_anonymous_page|default(false))) %}`. You would just then have to remove this logic from the `Html::footer()` and from the `Html::includeHeader()` methods.

2. Maybe replacing the `_notlogged` suffix by `_anonymous` or even `_anonymous_page` would be less ambiguous for plugin developers.

3. The same logic should also be applied to the `add_javascript_module` hook. I did not see it previously because the corresponding constant is not declared. The constant should be added in the `Hooks` class.

2024-12-04 20:15 UTC, cedric-anne approved these changes
@MyvTsv I made a few changes, you can check them commit by commit.

I tested it manually and it is OK for me. However, I would prefer to have a feedback from the customer before merging this.

Also, could you please add an example usage for all these new hooks in the [example plugin](https://github.com/pluginsGLPI/example) ?

2024-12-06 07:20 UTC, stonebuzz approved these changes
Ok for me, 

You also need to add the new Hook `ADD_*_ANONYMOUS_*` to the GLPI doc.

https://github.com/glpi-project/docdev

2024-12-06 08:01 UTC, Rom1-B approved these changes

2024-12-20 07:08 UTC, trasher approved these changes
OK for me, still need to be documented.

2024-12-20 07:09 UTC, merged

2024-12-20 08:06 UTC, stonebuzz commented
> OK for me, still need to be documented.

@MyvTsv -> here -> https://github.com/glpi-project/doc (with new `PR`)

2024-12-20 08:33 UTC, trasher commented
> > OK for me, still need to be documented.
> 
> @MyvTsv -> here -> https://github.com/glpi-project/doc (with new `PR`)

Open against master branch since it's a 10.0 change.