fix(user): can not update is_active field via massive action
glpi-project/glpi pull request #18491
Opened 2024-12-06 08:22 UTC by Rom1-B

## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes !35356
- Here is a brief description of what this PR does

Following https://github.com/glpi-project/glpi/pull/18441, the `is_active` field can still be modified by massive actions, a success message is displayed saying that the user has been modified, but the field was not modified in base. This PR is designed to display an error message while maintaining this security control.

## Screenshots (if appropriate):

2024-12-06 09:29 UTC, trasher commented
Please a dedicated test

2024-12-06 12:17 UTC, Rom1-B commented
> Please a dedicated test

There's already a test dedicated to Sensitive Fields, which I've updated, is that enough?

2024-12-06 14:06 UTC, trasher commented
> > Please a dedicated test
> 
> There's already a test dedicated to Sensitive Fields, which I've updated, is that enough?

Seems good, yes :)

2024-12-06 14:06 UTC, trasher approved these changes

2024-12-06 15:02 UTC, AdrienClairembault commented
If I recall correctly, the field can only be updated for users that have less rights than you ?

In this case, maybe the error message should indicate the names of the users, so it is clear which user have been modified and which have not.

2024-12-06 15:07 UTC, Rom1-B commented
It's already listed (_31688 is the user name I can't change_).

![image](https://github.com/user-attachments/assets/265608e4-777a-437f-a3cb-7c99fdfb3587)

2024-12-09 08:40 UTC, cedric-anne requested changes

2024-12-09 08:40 UTC, cedric-anne commented on src/User.php
> +                        && $input_key != '_useremails' // Always in $input
All virtual fields should be excluded from this comparison.

```suggestion
                        && !str_starts_with($input_key, '_') // virtual field
```

2024-12-09 09:08 UTC, merged