Remove Laminas JSON library
glpi-project/glpi pull request #18501
Opened 2024-12-07 19:35 UTC by cconard96

## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.

## Description

Fixes #18412

This library is abandoned and wasn't strictly needed.

2024-12-09 09:02 UTC, cedric-anne approved these changes
Seems technically OK, not tested manually.

2024-12-09 09:30 UTC, AdrienClairembault approved these changes

2024-12-09 10:03 UTC, orthagh requested changes
Just after checking out this PR, some things are broken:

- labels of horizontal tabs widget  show Nan or nothing
- Point markers of line/area charts are not displayed anymore when you enable the option
- edit an option of any cards, remove the controls of the cards after saving:
![image](https://github.com/user-attachments/assets/9f69ffca-9b1a-4791-81f3-fa045cf4293b)

Not related to this PR:
- There is a "Show legend" option that doesn't seem to be working anymore

2024-12-09 11:14 UTC, cconard96 commented
>     * edit an option of any cards, remove the controls of the cards after saving:

Also an issue on main

2024-12-09 11:43 UTC, cedric-anne commented on src/Glpi/Dashboard/Widget.php
> +                        serie['symbol'] = (param) => param > 0 ? 'circle': 'none';
Variable name was `value` in the previous code. I guess it matches the component documentation.
```suggestion
                        serie['symbol'] = (value) => value > 0 ? 'circle': 'none';
```

2024-12-09 13:06 UTC, orthagh commented
In Current state, a line/area graph (ex "ticket status by month") give me a js error: "Uncaught TypeError: serie.label is undefined"

2024-12-13 10:13 UTC, orthagh approved these changes
I don't see so far any issues related to the pr itself.

I found one valid on main also:

- legend option -> doesn't work anymore
- some options of a card are not saved (some are working like gradient, chart type, etc):
  - palette
  - labels
  - legend

I'll create an issue for that

2024-12-13 11:02 UTC, trasher commented
Could you please rebase to solve conflicts?

2024-12-13 14:01 UTC, merged