Make CommonDBRelations purgeable with the delete right
glpi-project/glpi pull request #18547
Opened 2024-12-13 14:07 UTC by RomainLvr

## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] This change requires a documentation update.

## Description

- It fixes !35411
- Here is a brief description of what this PR does

## Screenshots (if appropriate):

To remove a relationship between two items (e.g., `Domain` -> `Computer`), the system currently requires purge rights on the source item (`Domain` in this case). This behavior is problematic because granting purge rights not only allows the removal of relationships but also permits the deletion of items themselves. This creates a security concern when the intent is solely to manage relationships without affecting the items involved.

![image](https://github.com/user-attachments/assets/bc8f1ced-4599-456d-a134-4a9d22ad0092)

![image](https://github.com/user-attachments/assets/bc214a4e-f0c0-4325-836a-e7dabe656b6d)

2024-12-13 14:40 UTC, stonebuzz requested changes

2024-12-13 14:40 UTC, stonebuzz commented on src/MassiveAction.php
> +                }
Purging with only the deletion right would set a precedent in GLPI.

If I take the example of `Item_OperatingSystem` which is also a `CommonDBRelation`, the difference (in the code) is that `Item_OperatingSystem` does not depend on the` $rightname = "operatingsystem"`. 

It even specifies to `CommonDBRelation` not to check the rights on the `OperatingSystem` item.

`public static $checkItem_2_Rights = self::DONT_CHECK_ITEM_RIGHTS;`

This simple patch should be sufficient.

```patch
diff --git a/src/Domain_Item.php b/src/Domain_Item.php
index e349b077b6..c1ae17bcf1 100644
--- a/src/Domain_Item.php
+++ b/src/Domain_Item.php
@@ -42,7 +42,7 @@ class Domain_Item extends CommonDBRelation
     public static $itemtype_2 = 'itemtype';
     public static $items_id_2 = 'items_id';
 
-    public static $rightname = 'domain';
+    public static $checkItem_1_Rights = self::DONT_CHECK_ITEM_RIGHTS;
 
     public static function getTypeName($nb = 0)
     {
```

This allows the `purge` of the relation without granting the purge right on `Domain`.

`CommonDBRelation` will verify that the user has the right to `update` the main element, in this case, `Computer`, to allow the purge of the relation.

2024-12-13 14:43 UTC, cconard96 commented
I'm not sure this makes sense. In fact, it may only require delete permissions for Domains because `Domain_Item` specifies that as its rightname. In general, deleting a relationship only requires UPDATE rights for both of the associated items (Domain and Asset in this case).

2024-12-13 14:52 UTC, stonebuzz commented
> I'm not sure this makes sense. In fact, it may only require delete permissions for Domains because `Domain_Item` specifies that as its rightname. In general, deleting a relationship only requires UPDATE rights for both of the associated items (Domain and Asset in this case).

So only this should enought

```patch
diff --git a/src/Domain_Item.php b/src/Domain_Item.php
index e349b077b6..9be6dcc3ae 100644
--- a/src/Domain_Item.php
+++ b/src/Domain_Item.php
@@ -42,8 +42,6 @@ class Domain_Item extends CommonDBRelation
     public static $itemtype_2 = 'itemtype';
     public static $items_id_2 = 'items_id';
 
-    public static $rightname = 'domain';
-
     public static function getTypeName($nb = 0)
     {
         return _n('Domain item', 'Domain items', $nb);

```
In this way, `CommonDBRelation` check the `update` permissions on both sides.

(and it works)

2024-12-16 07:58 UTC, cedric-anne reviewed
Fix seems OK. Should it target the 10.0 branch?

2024-12-16 08:36 UTC, RomainLvr commented
> Fix seems OK. Should it target the 10.0 branch?

This fix does not work in 10.0

2024-12-16 08:59 UTC, trasher commented
Please fix tests

2024-12-16 09:24 UTC, cedric-anne commented on templates/generic_show_form.html.twig
> +                        {{ fields.textareaField('sysdescr', item.fields['sysdescr'], __('Sysdescr'), field_options) }}
The related commit should not be present in the current PR.

2024-12-16 10:00 UTC, closed without merging

2024-12-16 10:06 UTC, RomainLvr commented
PR redone here  https://github.com/glpi-project/glpi/pull/18553