fix: remote connections removal and display of deleted dynamic connec…
glpi-project/glpi pull request #18546
Opened 2024-12-13 12:40 UTC by MyvTsv

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [ ] I have added tests that prove my fix is effective or that my feature works.

## Description

- It fixes !35523
- This PR fixes a bug that prevented the removal of dynamic remote connections from a computer. Deleted dynamic connections are now displayed in blocked objects.

## Screenshots (if appropriate):

![Image PR](https://github.com/user-attachments/assets/46517c4d-3266-4d80-ac52-b8931b84cfea)

2024-12-13 13:11 UTC, stonebuzz requested changes

2024-12-13 13:11 UTC, stonebuzz commented on src/Lock.php
> +                echo "<td class='left'>" . Dropdown::getYesNo($remote_management->fields['is_dynamic']) . "</td>";
Can you add remote management type  (teamviewer / anydesk etc ...) column

2024-12-13 14:09 UTC, trasher commented on src/Lock.php
> +            foreach ($DB->request($remote_management->getTable(), $params) as $line) {
(`$iterator may not be the best name, I did not check if it's already used in the method)

2024-12-16 07:20 UTC, stonebuzz approved these changes

2024-12-16 07:31 UTC, trasher approved these changes

2024-12-16 07:58 UTC, Rom1-B approved these changes

2024-12-16 08:27 UTC, cedric-anne approved these changes

2024-12-16 08:27 UTC, merged