Allow validating only unsolved ITIL
glpi-project/glpi pull request #18604
Opened 2024-12-23 22:50 UTC by cconard96

## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [ ] I have added tests that prove my fix is effective or that my feature works.

## Description

While working on #17215, I noticed one place where the search result link for tickets waiting for approval filtered to unsolved tickets only. Some of the issue reported in the bug report was fixed in #18380 but there was still an inconsistency. Instead of hiding the ability to validate closed tickets only, it seems like it makes sense to also block validating solved tickets and changes. Once something is solved, all actions should be considered finished so approvals are expected to happen before that. Once solved, it is just waiting for user validation that the fix worked or validation from technicians in the case of an Observed change.

2025-01-02 13:31 UTC, Lainow commented
Once a ticket has been resolved, requests can no longer be modified, but once it has been closed, they can be edited again.
![image](https://github.com/user-attachments/assets/325a6013-82a1-435d-8344-4c48e65f8481)

2025-01-02 13:32 UTC, Lainow requested changes
See my previous comment

2025-01-15 13:16 UTC, Lainow requested changes
![image](https://github.com/user-attachments/assets/62256720-4c7d-4d2c-bd8f-b5987850ace3)
When I switch my ticket to Resolu, the approval request form is always at the bottom of my timeline.

When the ticket is closed, everything works perfectly.

2025-01-15 17:21 UTC, cconard96 commented
I cannot recreate that. I added an approval to myself while the ticket was unsolved and the answer form was shown. I solved the ticket and the answer form disappeared. I closed the ticket and the answer form remained gone.

2025-01-16 13:37 UTC, trasher commented
Should not this one targets 10.0 branch?

2025-01-16 13:48 UTC, cconard96 commented
> Should not this one targets 10.0 branch?

I didn't think so. Less of a bug and more changing a long-standing behavior. I felt better not introducing a behavior change, especially a restriction, in 10.0.

2025-01-16 13:50 UTC, trasher commented
> > Should not this one targets 10.0 branch?
> 
> I didn't think so. Less of a bug and more changing a long-standing behavior. I felt better not introducing a behavior change, especially a restriction, in 10.0.

OK for me

2025-01-16 13:50 UTC, trasher approved these changes

2025-01-16 14:05 UTC, cedric-anne approved these changes
Technically OK, but I would prefer to have a functional validation from @orthagh before merging this one.

2025-01-16 14:21 UTC, AdrienClairembault commented
Seems OK for me, at first I thought I had the same issue as shown in @Lainow's comment but in fact it this the solution approval form which is being displayed in this case, not the validation one.

![image](https://github.com/user-attachments/assets/e2ec0d58-a1b9-46fb-b2e0-911a053b25fa)

Unrelated but display of the solution is a bit weird tho (I'll open an issue)

2025-01-16 14:30 UTC, merged