Apply some defaults to Ticket from other items on initial load only
glpi-project/glpi pull request #18611
Opened 2024-12-27 13:09 UTC by cconard96

## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [ ] I have added tests that prove my fix is effective or that my feature works.

## Description

Fixes #17351

2025-01-06 11:53 UTC, cedric-anne requested changes

2025-01-06 11:53 UTC, cedric-anne commented on src/Ticket.php
> +        if (!$ID && !array_key_exists('_glpi_csrf_token', $options['_saved'])) {
Checking the `_glpi_csrf_token` token may not work as expected in some edge cases. Indeed, we could imagine a feature that would introduce pre-selection steps that result in calling the `Ticket::showForm()` method with some predefined options based on a submitted form.

Code would be most resilient with the introduction of a `CommonDBTM::hasSavedInput()` method, that would return the result of `isset($_SESSION['saveInput'][$this->getType()])`.

2025-01-08 15:24 UTC, cedric-anne approved these changes

2025-01-08 15:25 UTC, AdrienClairembault approved these changes

2025-01-09 06:59 UTC, trasher approved these changes

2025-01-09 06:59 UTC, merged