Fix dashboard class undefined
glpi-project/glpi pull request #18617
Opened 2024-12-28 21:48 UTC by cconard96

## Checklist before requesting a review

- [x] I have read the CONTRIBUTING document.
- [x] I have performed a self-review of my code.
- [ ] I have added tests that prove my fix is effective or that my feature works.

## Description

On `main`, sometimes dashboards are not loading and the `GLPIDashboard` JS global is undefined at the time the constructor tries being called. Added bare-minimum E2E test to check that dashboards are loading on each of the 4 included dashboard locations.

2024-12-30 10:19 UTC, AdrienClairembault commented
Seems like it causes the `search/display_preferences.cy.js` test to fail, even after multiple tries it does not go green.

2024-12-30 10:53 UTC, cconard96 commented
> Seems like it causes the `search/display_preferences.cy.js` test to fail, even after multiple tries it does not go green.

I noticed, even if I don't understand how they are related at all. This test seems to fail a lot even if it manages to pass after a few tries in other PRs. In this run:
1. Failed because it couldn't find `#tabspanel-select`
2. No failure noted. Should have been a pass?
3. Couldn't find Pending reason option (probably because it was already in the shown items list)
4. Same as failure 3

For the first failure, it is probably a matter of waiting for a network request using `waitForNetworkIdle`. For the last 2, I don't see the relation with this PR.

2025-01-06 11:39 UTC, cedric-anne approved these changes
Seems OK.

2025-01-06 11:39 UTC, cedric-anne commented on tests/cypress/e2e/dashboards.cy.js
> +describe('Entities selector', () => {
```suggestion
describe('Dashboard', () => {
```

2025-01-06 11:39 UTC, cedric-anne commented on tests/cypress/e2e/dashboards.cy.js
> + * @copyright 2015-2024 Teclib' and contributors.
```suggestion
 * @copyright 2015-2025 Teclib' and contributors.
```

2025-01-07 08:43 UTC, cedric-anne requested changes
E2E tests are failing.

2025-01-08 15:12 UTC, cconard96 commented
> E2E tests are failing.

I don't see how it is related. Both failed tests are related to the Pending Reason search option being shown. Nothing in my PR touches any related code.

2025-01-09 14:41 UTC, AdrienClairembault commented
Tests still seems flaky but only on the CI, it's very hard to fix it when there is no way to reproduce it properly locally.

2025-01-09 14:41 UTC, AdrienClairembault approved these changes

2025-01-09 14:55 UTC, cedric-anne approved these changes

2025-01-09 14:55 UTC, merged