fix upgrade
glpi-project/glpi pull request #2348
Opened 2017-06-22 12:22 UTC by yllen

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #2328 #2347

*Please update this template with something that matches your PR*

2017-06-22 12:24 UTC, remicollet commented
+1 for DBIterator part

2017-06-22 12:31 UTC, btry commented on inc/dbmysql.class.php
> +                        trigger_error("BAD JOIN, value sould be [ table => criteria ]", E_USER_ERROR);
Hi
There is a typo : sould => should

2017-06-22 13:42 UTC, remicollet commented on inc/dbmysql.class.php
> +                        trigger_error("BAD JOIN, value sould be [ table => criteria ]", E_USER_ERROR);
Even "sould" => "must" ;)

2017-06-22 14:06 UTC, remicollet commented on install/update_91_92.php
I think there is a big misunderstanding here... :(

Digging in the code, and old migration scripts, it seems only "new table" have to be backup...  but still not clear

2017-06-22 14:08 UTC, remicollet commented on install/update_91_92.php
> +      // yllen: you backup an inexisting table. If backup existing table it's done at the beginning
Totally agree here, this seems wrong.
Once the table is rename from "glpi_bookmarks", "glpi_savedsearches", you MUST keep it.
How can both exists ?

2017-06-22 14:11 UTC, trasher commented on install/update_91_92.php
Yes, only tables created in the update script should be in the array; they'll be renamed as backup on further runs.

2017-06-22 14:15 UTC, trasher commented on install/update_91_92.php
> +      // yllen: you backup an inexisting table. If backup existing table it's done at the beginning
Indeed, that can be dropped

2017-06-22 14:16 UTC, trasher commented on install/update_91_92.php
> +      $migration->migrationOneTable("glpi_savedsearches");
Why the `migrationOneTable`? `addPostQuery` will be executed after the migration, so, this should not be needed.

2017-06-22 14:18 UTC, trasher commented on inc/dbmysql.class.php
> +                  case 'JOIN' : // deprecated
Maybe add an output in the log when the deprecated case is used

2017-06-22 14:21 UTC, trasher commented on tests/units/DBmysqlIterator.php
> +   public function testInnerJoin() {
The error case should be tested as well

2017-06-22 14:35 UTC, trasher commented on install/update_91_92.php
> +   // Yllen: must be done at the beginning for all tables to forget change place of the message if new table added in list
I guess this should stay at the bottom, this is probably more "visible" for the users.

Anyways, I propose not to keep that kind of global message here, the Migration object can be in charge.

As example:
```diff
diff --git a/inc/migration.class.php b/inc/migration.class.php
index a8278f2..e2e74f2 100644
--- a/inc/migration.class.php
+++ b/inc/migration.class.php
@@ -51,6 +51,7 @@ class Migration {
       'pre'    => [],
       'post'   => []
    ];
+   private $has_backups;
 
    const PRE_QUERY = 'pre';
    const POST_QUERY = 'post';
@@ -647,6 +648,13 @@ class Migration {
          $DB->queryOrDie($query['query'], $query['message']);
       }
 
+      if ($this->has_backups) {
+         $migration->displayWarning(
+            __("You can delete backup tables if you have no need of them."),
+            true
+         );
+      }
+
       // end of global message
       $this->displayMessage(__('Task completed.'));
    }
@@ -854,7 +862,7 @@ class Migration {
     * @return boolean
     */
    public function backupTables($tables) {
-      $backup_tables = false;
+      $this->has_backups = false;
       foreach ($tables as $table) {
          // rename new tables if exists ?
          if (TableExists($table)) {
@@ -866,10 +874,10 @@ class Migration {
                   "backup_$table"
                )
             );
-            $backup_tables = true;
+            $this->has_backups = true;
             $this->renameTable("$table", "backup_$table");
          }
       }
-      return $backup_tables;
+      return $this->has_backups;
    }
 }
diff --git a/install/update_91_92.php b/install/update_91_92.php
index 299da48..0f49234 100644
--- a/install/update_91_92.php
+++ b/install/update_91_92.php
@@ -800,11 +800,6 @@ Regards,',
       $DB->queryOrDie($query, "9.2 add saved searches alerts notification translation");
    }
 
-   if ($has_backups) {
-      $migration->displayWarning("You can delete backup tables if you have no need of them.",
-                                 true);
-   }
-
    if (TableExists('glpi_queuedmails')) {
       $migration->renameTable("glpi_queuedmails", "glpi_queuednotifications");
       $migration->addPostQuery("UPDATE glpi_crontasks SET itemtype='QueuedNotification' WHERE itemtype='QueuedMail'");
```

2017-06-26 11:01 UTC, yllen commented on install/update_91_92.php
> +      $migration->migrationOneTable("glpi_savedsearches");
it's for adding fields before adding keys

2017-06-26 11:25 UTC, yllen commented on install/update_91_92.php
> +   // Yllen: must be done at the beginning for all tables to forget change place of the message if new table added in list
It's more logical for me to add this message in backupTable function

2017-06-27 10:11 UTC, trasher commented on install/update_91_92.php
> +      $migration->migrationOneTable("glpi_savedsearches");
This is already the case; I've just tested an upgrade from a 9.1 database against current master; all three keys have been created

2017-06-27 10:18 UTC, trasher commented
For further PR, please do not make so much "CS changes" as this make real changes difficult to see :/
Either regroup all that kind of changes into one specific commit, or on another PR to keeps things "simple" ;)

2017-06-27 10:19 UTC, trasher requested changes
Globaly OK, remaining points:
* test error cases,
* add a warning on deprecated case (or leave it not deprecated)

2017-06-27 11:32 UTC, trasher commented
> test error cases

==> done. i've also moved DBMysqlIterator to its own class; and factorized a bit join conditions ('INNER' was mainly a copy/paste from 'LEFT')

2017-06-27 12:32 UTC, trasher approved these changes

2017-06-28 07:39 UTC, orthagh approved these changes

2017-06-28 08:19 UTC, merged

2017-06-28 08:27 UTC, yllen commented on install/update_91_92.php
> +      $migration->migrationOneTable("glpi_savedsearches");
i've tested from master only this table and keys were not added.
addPostQuery is done after migration so after addKeys.

The better way to do is to put the addField "do_count" at the end and add the array update in it.