Massive Action: link multiple tickets to a problem
glpi-project/glpi pull request #7394
Opened 2020-06-10 14:19 UTC by AdrienClairembault

Internal ref: 18423, 19662.

New massive action to link multiple tickets to a problem.
![image](https://user-images.githubusercontent.com/42734840/84391403-3dc8d600-abf9-11ea-8627-530598c00f72.png)

New massive action to resolve multiple tickets.
![image](https://user-images.githubusercontent.com/42734840/84391376-35709b00-abf9-11ea-9f01-ae1964e22fd4.png)

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

2020-06-11 06:25 UTC, trasher commented on inc/ticket.class.php
> +            echo Html::submit(_('Link'), [
```suggestion
            echo Html::submit(__('Link'), [
```

2020-08-20 07:38 UTC, AdrienClairembault commented
Are you still expecting changes or is this good to merge ?

2020-09-16 06:17 UTC, trasher requested changes

2020-09-16 06:17 UTC, trasher commented on inc/ticket.class.php
> +            $label = _n('Solution template', 'Solution templates', 1);
```suggestion
            $label = SolutionTemplate::getTypeName(1);
```

2020-09-16 06:17 UTC, trasher commented on inc/ticket.class.php
> +            $label = __('Solution type');
Will cause gettext warnings.
```suggestion
            $label = SolutionType::getTypeName(1);
```

2020-09-16 06:18 UTC, trasher commented
Please rebase on up to date master branch, to get new tests (especially those on gettext).

2020-10-09 13:04 UTC, AdrienClairembault commented
Rebased again to fix conflict, should be good to merge.

2020-10-09 13:12 UTC, trasher approved these changes

2020-10-09 13:17 UTC, merged