Fix itilcategory dropdown in tickets/changes/problems
glpi-project/glpi pull request #7996
Opened 2020-09-23 15:28 UTC by AdrienClairembault

Internal ref: 20757.

Given the following ITIL categories in multiple entities:
![image](https://user-images.githubusercontent.com/42734840/94034134-f3432200-fdc1-11ea-8a2c-7c9673f65ee3.png)

---

Before (categories in child entities are ignored):
![image](https://user-images.githubusercontent.com/42734840/94034149-f9d19980-fdc1-11ea-8a96-7285a2e64a59.png)

---

After:
![image](https://user-images.githubusercontent.com/42734840/94034168-fe964d80-fdc1-11ea-804c-39a9f9dfceba.png)

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

2020-09-24 05:47 UTC, trasher approved these changes

2020-09-25 13:21 UTC, orthagh commented on inc/session.class.php
> +      return $_SESSION['glpiactiveentities'];
```suggestion
      return $_SESSION['glpiactiveentities'] ?? [];
```

2020-09-29 06:21 UTC, trasher approved these changes

2020-09-29 06:34 UTC, cedric-anne commented
It means that you can create a ticket in entity A1 with a category of AA2. If you display the ticket from entity A1 without "tree structure", it will be linked to a category that you cannot access. Is it intended ?

2020-10-01 14:16 UTC, AdrienClairembault commented
> It means that you can create a ticket in entity A1 with a category of AA2. If you display the ticket from entity A1 without "tree structure", it will be linked to a category that you cannot access. Is it intended ?

It doesn't seems to be a problem for me, in this case you can see the category but not interact with it so it should be fine ?

2020-10-06 12:36 UTC, orthagh requested changes
As seen together, i disagree strongly with this change.

This is not desirable to get the entity/is_recursive couple from current session when retrieving foreign key data.
We may have bugs in rules/notifications due to this

2020-10-06 12:47 UTC, closed without merging