PHPDoc: Fix some param and return types
glpi-project/glpi pull request #8065
Opened 2020-10-06 00:45 UTC by cconard96

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -

2020-10-06 06:00 UTC, orthagh approved these changes

2020-10-06 06:03 UTC, trasher approved these changes
Well, approved; but I've not reviewed; that would take too much time

2020-10-06 06:15 UTC, cedric-anne approved these changes

2020-10-06 06:17 UTC, cedric-anne requested changes

2020-10-06 06:17 UTC, cedric-anne commented on inc/authldap.class.php
> +    * @param null    $sync          Sync field
```suggestion
    * @param string|null    $sync          Sync field
```

2020-10-06 06:17 UTC, cedric-anne commented on inc/computervirtualmachine.class.php
> +    * @param array fields  Array of virtualmachine fields
```suggestion
    * @param array $fields  Array of virtualmachine fields
```

2020-10-06 06:25 UTC, cedric-anne requested changes

2020-10-06 06:25 UTC, cedric-anne commented on inc/dbconnection.class.php
> +    * @param boolean Enable or disable cron task (true by default)
```suggestion
    * @param boolean $enable Enable or disable cron task (true by default)
```

2020-10-06 06:25 UTC, cedric-anne commented on inc/mailcollector.class.php
> +    * @param \Laminas\Mail\Storage\Part $subpart  Message part (for recursive ones)
```suggestion
    * @param string                     $subpart  Subpart index (used in document filenames)
```

2020-10-06 06:27 UTC, cedric-anne commented
Errors I found detected by Scutinizer: https://scrutinizer-ci.com/g/glpi-project/glpi/inspections/f5487ea7-b2db-4f6d-95fa-527becd6b3e5

On this kind of PR, checking Scrutinizer results is usefull.

2020-10-08 08:56 UTC, cedric-anne approved these changes

2020-10-08 09:10 UTC, merged