Added add_default_join plugin hook
glpi-project/glpi pull request #8452
Opened 2020-12-24 19:03 UTC by edgardmessias

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | none

2021-01-05 12:14 UTC, cedric-anne requested changes
Can you explain how you want to use this hook, and maybe give an example of code ?

2021-01-05 12:14 UTC, cedric-anne commented on inc/search.class.php
> +            $out = Reminder::addVisibilityJoins();
```suggestion
            $out = Reminder::addVisibilityJoins();
            break;
```

2021-01-05 12:14 UTC, cedric-anne commented on inc/search.class.php
> +            $out = RSSFeed::addVisibilityJoins();
```suggestion
            $out = RSSFeed::addVisibilityJoins();
            break;
```

2021-01-05 12:14 UTC, cedric-anne commented on inc/search.class.php
> +                                      break;
```suggestion
            break;
```

2021-01-05 12:14 UTC, cedric-anne commented on inc/search.class.php
> +      /* Hook to restrict user right on current itemtype */
```suggestion
```

2021-01-05 12:15 UTC, cedric-anne commented
I changed target branch to master, as 9.5/bugfixes branch is only for bug fixes.

2021-01-05 12:46 UTC, edgardmessias commented
> Can you explain how you want to use this hook, and maybe give an example of code ?

Sometimes when I am developing a internal plugin, I see the necessity of change the default  filter behavior, and using only `add_default_where` it's a performance nightmare

2021-01-11 07:25 UTC, cedric-anne approved these changes

2021-01-11 07:33 UTC, cedric-anne commented
Hi,

Can you add this in documentation (https://github.com/glpi-project/docdev/blob/master/source/plugins/hooks.rst) and also add a short example of usage in example plugin (https://github.com/pluginsGLPI/example) ?

Regards

2021-01-11 07:55 UTC, trasher approved these changes

2021-01-11 08:10 UTC, orthagh approved these changes

2021-01-20 06:45 UTC, merged