make notification email/name from entity inheritables
glpi-project/glpi pull request #8559
Opened 2021-01-21 09:27 UTC by orthagh

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | maybe #6944, and internal ref !21352

The purpose of this pr is to make easier configuration from large entity tree
All fields in the notification tabs of entities are inheritable except mails and names (ex prefix or signatures are inheritable despite no inline documentation).

I took the opportunity to extends inline documentation for inheritance on missing fields (and remove <font> balise deprecated in 1999 😬 )

I still have a concern by the way, we may change existing malformed setup in existing instances.
And some may have emails changes (before if no value defined in the direct entity, the system took the global configuration).
It's difficult to say if it's a big impact but i dont' have solution to ease this transiftion, any ideas ?

![image](https://user-images.githubusercontent.com/418844/105330978-3330df00-5bd3-11eb-8da7-09bbf0d0c2eb.png)

2021-01-21 11:05 UTC, orthagh commented
slight rework of the design

![image](https://user-images.githubusercontent.com/418844/105342629-e2c07e00-5be0-11eb-8cd4-0d99d7cc5443.png)

2021-01-21 11:20 UTC, trasher approved these changes

2021-01-21 15:07 UTC, trasher approved these changes

2021-01-21 15:07 UTC, trasher commented on tests/bootstrap.php
> +         ], [
You should bump the `_version` if you change bootstrap data

2021-01-22 09:00 UTC, cedric-anne requested changes

2021-01-22 10:42 UTC, orthagh commented on inc/entity.class.php
> +      if (strlen($entity->fields['admin_email']) == 0) {
same

2021-01-22 10:43 UTC, orthagh commented on inc/notificationtarget.class.php
> +      $admin_reply      = trim(Entity::getUsedConfig('admin_replyl', $this->getEntity(), '', ''));
good catch, a functional test is missing here also

2021-01-22 10:44 UTC, cedric-anne commented on inc/entity.class.php
> +      if (strlen($entity->fields['admin_reply']) == 0) {
So maybe you shiould add a comment in the code.

2021-01-22 10:47 UTC, cedric-anne approved these changes

2021-01-22 11:05 UTC, orthagh commented on inc/entity.class.php
> +      if (strlen($entity->fields['admin_reply']) == 0) {
done

2021-01-22 12:14 UTC, merged