Fixed custom css entity with quotes
glpi-project/glpi pull request #8576
Opened 2021-01-25 23:08 UTC by edgardmessias

Currenty, the caracters `quote`, `greater than (>)` and `less than (<)` are converted to `&quote;`, `&gt;` and `&lt;`

This PR decode it to back

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |

2021-01-26 11:32 UTC, cedric-anne requested changes
Hi,

This solution is not acceptable as it will result in possible XSS. You can test by inserting `</style><script>alert(1);</script>` in this field.

Handling these chars can be a good enhancement, but solution have to be secure.

Regards

2021-01-26 12:13 UTC, edgardmessias commented
@cedric-anne , I agree with you, I am looking the `htmLawed` function to solve it

2021-01-26 12:20 UTC, cedric-anne commented
> @cedric-anne , I agree with you, I am looking the `htmLawed` function to solve it

Maybe `strip_tags` would do the job.

2021-01-27 12:43 UTC, edgardmessias commented
@cedric-anne done using `Html::clean`

2021-01-27 13:31 UTC, trasher commented
Sounds much more correct to me :) I wonder if #8587 should be fixed the "same" way?

2021-01-27 13:34 UTC, edgardmessias commented
> Sounds much more correct to me :) I wonder if #8587 should be fixed the "same" way?

Yes, because the `Html:clean`  call `Html::entity_decode_deep` internalyy

2021-01-27 14:47 UTC, cedric-anne commented
Hi @edgardmessias ,

#8589 is an alternative proposal.

Both differences :
 - I do not use `Html::clean`, that is a complex method and requires to still decode specific chars to have a correct rendering;
 - In the entity form, the raw input is displayed (with entities encoding to prevent security issues).

Can you take a look and tell me if you agree with my proposal ?

Regards

2021-01-27 14:56 UTC, edgardmessias commented
Hi @cedric-anne .

The problem with your PR is about existent content that has encoded caracteres (&gt; and &quot;)

I guess if add a `html_entity_decode` before `strip_tags` solve the problem

2021-01-27 15:03 UTC, cedric-anne commented
> Hi @cedric-anne .
> 
> The problem with your PR is about existent content that has encoded caracteres (> and ")
> 
> I guess if add a `html_entity_decode` before `strip_tags` solve the problem

This existing contents is already not working, and I guess people who tried to use it had either found another solution, either deactivate usage of the buggy custom CSS. In both case, it will require a manual operation to put it back.
Trying to decode content that was handled as HTML before beiing stored in database could introduce other kind of bugs.

2021-01-27 15:06 UTC, trasher commented
I'm closing this one; fix is in the other PR.

For existing data, maybe it can be done from an upgrade script?

2021-01-27 15:06 UTC, closed without merging

2021-01-27 15:08 UTC, trasher commented
> For existing data, maybe it can be done from an upgrade script?

Talking about that with @cedric-anne; indeed, this was not working before, so existing data is probably not to fix.