fix(core): use CommonDBTM instead of CommonDropdown
glpi-project/glpi pull request #8643
Opened 2021-02-10 06:21 UTC by stonebuzz

Original problem :

When creating a line with location, the line takes the entity of the location unlike certificates, for example

The inheritance of the class "line" has changed from ````CommonDBTM``` to ````CommonDropDown``` (I don't know why)

This PR revert commit https://github.com/glpi-project/glpi/commit/8052033582dc58eb6f90b256db4c436d3104f4e7#diff-7d3f7c2f1bdbb4c5a110fffc4d89bd93fd223c1cdad4d0b9698aae74344cda83R41

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | internal 21479

2021-02-10 06:42 UTC, btry commented
Hi

I validate this change.

Le 10 février 2021 07:22:11 GMT+01:00, Stanislas <notifications@github.com> a écrit :
>Original problem :
>
>When creating a line with location, the line takes the entity of the
>location unlike certificates, for example
>
>The inheritance of the class &quot;line&quot; has changed from
>````CommonDBTM``` to ````CommonDropDown``` (I don&#39;t know why)
>
>
>This PR revert commit
>https://github.com/glpi-project/glpi/commit/8052033582dc58eb6f90b256db4c436d3104f4e7#diff-7d3f7c2f1bdbb4c5a110fffc4d89bd93fd223c1cdad4d0b9698aae74344cda83R41
>
>| Q             | A
>| ------------- | ---
>| Bug fix?      | yes
>| New feature?  | no
>| BC breaks?    | no
>| Deprecations? | no
>| Tests pass?   | yes
>| Fixed tickets | internal 21479
>
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/glpi-project/glpi/pull/8643
>
>-- Commit Summary --
>
>  * fix(core): use CommonDBTM instead of CommonDropdown
>
>-- File Changes --
>
>    M inc/line.class.php (2)
>
>-- Patch Links --
>
>https://github.com/glpi-project/glpi/pull/8643.patch
>https://github.com/glpi-project/glpi/pull/8643.diff
>
>-- 
>You are receiving this because your review was requested.
>Reply to this email directly or view it on GitHub:
>https://github.com/glpi-project/glpi/pull/8643

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

2021-02-10 08:15 UTC, trasher approved these changes

2021-02-10 08:48 UTC, cedric-anne requested changes
Mentionned commit was also removing some search options that are defined in `CommonDropdown` but are not in `CommonDBTM`, they should be put back again.

2021-02-10 08:55 UTC, stonebuzz commented
> Mentionned commit was also removing some search options that are defined in `CommonDropdown` but are not in `CommonDBTM`, they should be put back again.

done

2021-02-10 08:56 UTC, cedric-anne approved these changes

2021-02-11 07:24 UTC, orthagh approved these changes

2021-02-11 08:04 UTC, merged