Add location from user and default group from user for rule asset
glpi-project/glpi pull request #8655
Opened 2021-02-11 10:22 UTC by ales-infotel

This is a new feature for assets rules. It adds  new criterias User location and user in a group. And a action to copy location from user and a action to copy group default from user.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

2021-02-11 10:38 UTC, ales-infotel commented
I don't understand why my PR generates an error that is not related to the files I modified and the other files come from the master branch.
see test failure :
> There is 1 failure:
=> tests\units\Glpi\Csv\LogCsvExport::testGetFileName():
In file /var/glpi/tests/units/Glpi/Csv/LogCsvExport.php on line 0, string() failed for data set [0] of data provider csvTestProvider: strings are not equal
-Expected
+Actual
@@ -1 +1 @@
-string(29) "testexporttocsv-520210211.csv"
+string(32) "testexporttocsv-5_2021_02_11.csv"

2021-02-12 13:37 UTC, cedric-anne commented
> I don't understand why my PR generates an error that is not related to the files I modified and the other files come from the master branch.
> see test failure :
> 
> > There is 1 failure:
> > => tests\units\Glpi\Csv\LogCsvExport::testGetFileName():
> > In file /var/glpi/tests/units/Glpi/Csv/LogCsvExport.php on line 0, string() failed for data set [0] of data provider csvTestProvider: strings are not equal
> > -Expected
> > +Actual
> > @@ -1 +1 @@
> > -string(29) "testexporttocsv-520210211.csv"
> > +string(32) "testexporttocsv-5_2021_02_11.csv"

Hi,

This has been fixed on master. Please rebase on last commit to be sure that other tests are passing.

Regards

2021-02-12 15:36 UTC, ales-infotel commented
ok thank, now the tests are good

2021-02-15 14:49 UTC, cedric-anne reviewed
It seems correct.

Please add some unit tests to validate this behaviour.

2021-02-16 07:37 UTC, trasher commented
Looks good to me, waiting for tests to validate

2021-02-16 09:55 UTC, ales-infotel commented
i have add somes tests

2021-02-17 07:13 UTC, trasher approved these changes

2021-02-17 09:19 UTC, cedric-anne requested changes

2021-02-17 09:19 UTC, cedric-anne commented on inc/commondbtm.class.php
> +            }
```suggestion
            $input['_groups_id_of_user'] = [];
            foreach ($groups_user as $group) {
               $input['_groups_id_of_user'][] = $group['groups_id'];
            }
```

2021-02-17 09:19 UTC, cedric-anne commented on inc/ruleasset.class.php
> +                     $output['groups_id'] = $input['_groups_id_of_user'];
```suggestion
                     $output['groups_id'] = reset($input['_groups_id_of_user']);
```

2021-02-17 09:19 UTC, cedric-anne commented on tests/units/RuleAsset.php
> +      $computer_em->getFromDB($computer_id);
```suggestion
      $this->integer($computer_id)->isGreaterThan(0);
      $this->boolean($computer_em->getFromDB($computer_id))->isTrue();
```

2021-02-17 09:19 UTC, cedric-anne commented on tests/units/RuleAsset.php
> +      $computer_em->getFromDB($computer_id);
```suggestion
      $this->boolean($computer_em->getFromDB($computer_id))->isTrue();
```

2021-02-17 09:19 UTC, cedric-anne commented on tests/units/RuleAsset.php
> +      $computer_em->getFromDB($computer_id);
```suggestion
      $update = $computer_em->update([
                              'id'       => $computer_id,
                              'users_id' => $users_id,
                           ]);
      $this->boolean($update)->isTrue();
      $this->boolean($computer_em->getFromDB($computer_id))->isTrue();
```

2021-02-17 09:19 UTC, cedric-anne commented on tests/units/RuleAsset.php
> +      $user->getFromDB(getItemByTypeName('User', 'tech', true));
```suggestion
      $user = getItemByTypeName('User', 'tech');
```

2021-02-17 09:19 UTC, cedric-anne commented on tests/units/RuleAsset.php
> +      $computer->getFromDB($computers_id);
```suggestion
      $this->integer($computers_id)->isGreaterThan(0);
      $this->boolean($computer->getFromDB($computers_id))->isTrue();
```

2021-02-17 09:19 UTC, cedric-anne commented on tests/units/RuleAsset.php
> +      $user->getFromDB(getItemByTypeName('User', 'tech', true));
```suggestion
      $user = getItemByTypeName('User', 'tech');
```

2021-02-17 09:19 UTC, cedric-anne commented on tests/units/RuleAsset.php
> +      $computer->getFromDB($computers_id);
```suggestion
      $this->integer($computers_id)->isGreaterThan(0);
      $this->boolean($computer->getFromDB($computers_id))->isTrue();
```

2021-02-18 08:11 UTC, cedric-anne approved these changes

2021-02-18 08:26 UTC, merged