Newlines are removed in preformatted text
glpi-project/glpi pull request #8826
Opened 2021-03-12 10:10 UTC by falco2001

I did the following tests with a signature of 15 lines! :

- ticket creation by mail tool -> the signature is displayed as a block, it's ok all the same
- follow-up by email -> ok now signature ok follow-up with the follow-up before that is displayed

2021-03-12 10:29 UTC, trasher commented
Hi, thank you for your contribution.

If your PR is related to an existing ticket, please refer to it in your commit message; it'll be closed automatically if the PR is merged.

Also, tests are currently broken, they must be fixed; and we may need an new test case for that change.

2021-03-22 10:14 UTC, cedric-anne requested changes
This fix does not seems correct to me. With the current state of code, all newlines should be handled the same way.
If there is a rendering issue on notifications, the then fix has to be applied on the rendering part.
If the rendering part cannot be patched, the the fix has to be more global, in order to fix all places where this is rendered.

2021-04-20 08:35 UTC, trasher commented
Ne feedback from a while; I close

2021-04-20 08:35 UTC, closed without merging

2021-04-20 11:15 UTC, falco2001 commented
Hello,
with that part of the code. This has been working for 1 month without too much problem. Of course, the old tickets have imperfections, but the new ones with 10 lines signature everything is ok whether it is in email, in webmail, in creation of closed ticker and in response

```

Ligne 1243 de  mailcollector.class.php 
 // Replace plain text line breaks to marker if content is not html
 // and rich text mode is enabled (otherwise remove them)
      
      $string = str_replace(
        // Avant  ["\r\n", "\n", "\r"],
         ["\r\n", "\n\n", "\r"], //YD
         $this->body_is_html ? ' ' : $br_marker,
         $string
      );
      $string = str_replace(["\n"],$br_marker,$string); //YD


```