Fix/inventory
glpi-project/glpi pull request #9340
Opened 2021-07-28 09:41 UTC by trasher

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

2021-07-28 13:51 UTC, orthagh approved these changes

2021-07-28 14:40 UTC, g-bougard requested changes

2021-07-28 14:40 UTC, g-bougard commented on inc/agent/communication/abstractrequest.class.php
> +               '|\$ref\[file~2///var/www/html/private/glpi/vendor/glpi-project/inventory_format/inventory.schema.json\]|',
Using a hard-coded path here is wrong.
```suggestion
               '|\$ref\[file~2//.*/vendor/glpi-project/inventory_format/inventory.schema.json\]|',
```

2021-07-28 16:12 UTC, trasher commented on composer.json
> +        "glpi-project/inventory_format": "dev-feature/update-devices",
Yes, until there is a new lib release (once this pr will be ok).

2021-07-30 08:25 UTC, g-bougard approved these changes

2021-07-30 08:28 UTC, g-bougard commented
This PR closes #9316.

2021-07-30 08:34 UTC, merged