fix(inventory): fix remote inventory / status
glpi-project/glpi pull request #9398
Opened 2021-08-05 13:45 UTC by stonebuzz

Actually, GLPI try to get all addresses from computer to request a remote inventory / status

from a standard inventory GLPI return three addresses (```NetworkPortLocal``` are excluded)
```https://192.168.1.24:62354/status``` (by ipv4)
```https://2a01:e0a:87c:4ea0:f178:597:e709:8aea:62354/status``` (by ipv6)
```https://Desktop:62354/status``` (by name)

Only IPV4 work

This PR Restrict addresses to get only IPV4 compliant

Perhaps we could save the IP used by the agent during the ```PROLOG``` (into ```Agent``` object)

| Q             | A
| ------------- | ---
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #number

2021-08-06 08:04 UTC, stonebuzz commented
As discuss with @g-bougard 

When agent contact GLPI save into ```glpi_agents``` table three new informations

- IP ```$_SERVER['REMOTE_ADDR']``` use by agent to contact GLPI (store as binary with ```inet_pton```)
- IP version
- Protocol : ```http``` by default , ```https``` if plugin ```ssl``` is active agent side 

When user request ```/status```, ```/now``` (or other from plugins)
GLPI use this IP and make only one call.

2021-08-10 07:52 UTC, g-bougard requested changes

2021-08-10 07:52 UTC, g-bougard commented on inc/agent.class.php
> +      }
I don't see any usage of `ip_version` in your PR but there to just set it in database. I think you can just get rid of it.

2021-08-10 07:52 UTC, g-bougard commented on inc/agent.class.php
> +
As discussed privately, you also will be able to set the port and you have to check set ports for ssl httpd-plugin before telling we should use `https`.
```suggestion
      if (!isset($metadata['httpd-port'])) {
         $input['port'] = $metadata['httpd-port'];
      }

      $input['ip_protocol'] = 'http';
      if (isset($metadata['httpd-plugins']['ssl']['ports'])) {
         $ssl_ports[] = $metadata['httpd-plugins']['ssl']['ports'];
         if (in_array("0", $ssl_ports) || (isset($metadata['httpd-port']) && in_array($metadata['httpd-port'], $ssl_ports))) {
            $input['ip_protocol'] = 'https';
         }
      }

```
The right logic is there but this is a suggestion and I didn't test it, so try it and fix it before merging.

This code is also following glpi agent commit: https://github.com/glpi-project/glpi-agent/commit/209f730be0f98797ce7bb5fa10ea63ee2da6339b
Here is an example of what you can obtain from [glpi-agent](https://github.com/glpi-project/glpi-agent) during CONTACT request:
```
{
   "action": "contact",
   "deviceid": "asus-2021-01-26-17-04-22",
   "enabled-tasks": [
      "inventory"
   ],
   "httpd-plugins": {
      "inventory": "disabled",
      "proxy": {
         "disabled": "no",
         "glpi_protocol": "yes",
         "local_store": "/srv/glpi-agent/proxy",
         "max_pass_through": 5,
         "max_proxy_threads": 10,
         "maxrate": 30,
         "maxrate_period": 3600,
         "no_category": "",
         "only_local_store": 0,
         "port": "8081",
         "prolog_freq": 24,
         "url_path": "/proxy"
      },
      "secondaryproxy": "disabled",
      "ssl": {
         "disabled": "no",
         "ports": [
            "0",
            "8081"
         ],
         "ssl_cert_file": "cert.pem",
         "ssl_key_file": "key.pem"
      },
      "test": "disabled",
      "toolbox": "disabled"
   },
   "httpd-port": "62354",
   "installed-tasks": [
      "collect",
      "deploy",
      "esx",
      "inventory",
      "netdiscovery",
      "netinventory",
      "wakeonlan"
   ],
   "name": "GLPI-Agent",
   "version": "1.0-dev"
}
```

2021-08-10 07:52 UTC, g-bougard commented on inc/agent.class.php
> +         return inet_ntop($values[$field]);
You should probably handle the case `inet_ntop()` returns `false` in case of error.

2021-08-10 07:52 UTC, g-bougard commented on inc/agent.class.php
> +         $input['ip_binary'] = inet_pton($_SERVER['REMOTE_ADDR']);
You should probably handle the case `inet_pton()` returns `false` even if this should not happen.

2021-08-10 08:20 UTC, g-bougard commented on inc/agent.class.php
> +   public function requestAgent($endpoint): Response {
This update comes first from #9395.

2021-09-07 06:28 UTC, stonebuzz commented
I have a question about local imports 
With this feature the IP registered will be the IP of the computer injecting the XML file and not the IP of the inventory

2021-09-07 06:49 UTC, g-bougard commented
In that case, this generally means we can't contact remote agent, so in that case, we should probably not set any remote status url.

Then we can also think about the proxy agent case. In that case, the targeted agent UUID should be set in GLPI-Agent-ID HTTP header so the proxy can do the job.

2021-12-14 16:04 UTC, stonebuzz commented
close this PR
see -> https://github.com/glpi-project/glpi/pull/10115

2021-12-14 16:04 UTC, closed without merging