retro compatibility
glpi-project/glpi pull request #9422
Opened 2021-08-18 17:01 UTC by delcroip

$itemtype is used only in case of stat, all the other cases don't need params, without default it create a compatibility issue with reports plugin (and I guess other piece of code)

| Q             | A
| ------------- | ---
| Bug fix?      | yes (but on master)
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | NA

2021-08-18 17:05 UTC, cconard96 approved these changes

2021-08-18 23:53 UTC, cconard96 requested changes

2021-08-18 23:53 UTC, cconard96 commented on inc/dropdown.class.php
> +   static function showOutputFormat($itemtype = NULL) {
```suggestion
   static function showOutputFormat($itemtype = null) {
```

2021-08-19 06:21 UTC, cedric-anne approved these changes

2021-08-23 07:17 UTC, trasher approved these changes

2021-08-23 07:17 UTC, merged