FEAT: create KB from followup or task
glpi-project/glpi pull request #9593
Opened 2021-09-23 08:00 UTC by Rom1-B

Allows to create a kb from followup or task, as it already exists in solution.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !22387

2021-09-24 08:45 UTC, trasher commented
This should target master

2021-09-24 13:06 UTC, trasher reviewed
Maybe all the logic inside front files maybe moved in class

2021-09-24 13:06 UTC, trasher commented on front/change.form.php
> +               'title'         => __('Save solution to the knowledge base'),
As far as I understand, there are 3 possible cases; title here is OK for one only

2021-09-27 08:01 UTC, cedric-anne commented on inc/knowbaseitem.class.php
> +               } else if (isset($options['task_id'])) {
```suggestion
               } else if (isset($options['tasks_id'])) {
```

2021-09-27 08:01 UTC, cedric-anne commented on inc/knowbaseitem.class.php
> +               if (isset($options['fw_id'])) {
```suggestion
               if (isset($options['itilfollowups_id'])) {
```

2021-09-27 08:01 UTC, cedric-anne commented on inc/knowbaseitem.class.php
> +                  $task->getFromDB($options['task_id']);
```suggestion
                  $task->getFromDB($options['tasks_id']);
```

2021-09-30 09:09 UTC, orthagh requested changes

2021-09-30 09:09 UTC, orthagh commented on front/itilfollowup.form.php
> +Html::displayErrorAndDie('Lost');
```suggestion
Html::displayErrorAndDie('Lost');

```

2021-09-30 09:12 UTC, orthagh commented
An aditionnal PR need to be done to redo the UI part in modern-UI

2021-09-30 13:40 UTC, orthagh approved these changes

2021-10-01 07:39 UTC, cedric-anne approved these changes

2021-10-01 07:41 UTC, cedric-anne commented
Replaced by #9620

2021-10-01 07:45 UTC, closed without merging